1.2.0

diff --git a/examples/test/pt2pt/Makefile.in b/examples/test/pt2pt/Makefile.in
--- a/examples/test/pt2pt/Makefile.in
+++ b/examples/test/pt2pt/Makefile.in
@@ -1,28 +1,34 @@
 ALL: default
 ##### User configurable options #####
 
-MPIR_HOME   = @MPIR_HOME@
-CC          = @MPICC@
-CLINKER     = @MPICC@
-CCC         = @MPICPLUSPLUS@
-CCLINKER    = $(CCC)
-F77         = @MPIF77@
-FLINKER     = @MPIF77@
-OPTFLAGS    = @OPTFLAGS@
-MPIFDEP     = @MPIFDEP@
-
+MPIR_HOME    = @MPIR_HOME@
+CC           = @MPICC@
+CLINKER      = @MPICC@
+CCC          = @MPICPLUSPLUS@
+CCLINKER     = $(CCC)
+F77          = @MPIF77@
+F90BASE	     = @MPIF90BASE@
+F90          = @MPIF90@
+FLINKER      = @MPIF77@
+OPTFLAGS     = @OPTFLAGS@
+MPIFDEP      = @MPIFDEP@
+F77_OPTFLAGS = @F77_EXTRA_FLAG@
 ### End User configurable options ###
 
 SHELL = /bin/sh
+prefix     = @prefix@
+top_srcdir = @top_srcdir@
+srcdir     = @srcdir@
+@VPATH@
 
 PROFLIB =
-CFLAGS  = $(OPTFLAGS) 
+CFLAGS  = @CFLAGS@ @DEFS@ $(OPTFLAGS) 
 CCFLAGS = $(CFLAGS)
 FFLAGS = $(OPTFLAGS)
 # Use LIBS to add any special libraries for C programs
-LIBS = 
+LIBS = @LIB_PATH@ @LIB_LIST@
 # Use FLIBS to add any special libraries for Fortran programs
-FLIBS = 
+FLIBS = @FLIB_PATH@ @LIB_LIST@
 EXECS = overtake sendrecv isndrcv third fourth fifth sixth hvectest \
 	hvectest2 hvec probe probe1 testtest1 ssendtest ssendtest2 typetest\
 	dtypelife issendtest issend2 issendinit relrank nullproc trunc \
@@ -31,7 +37,8 @@ EXECS = overtake sendrecv isndrcv third fourth fifth sixth hvectest \
 	pack bsendtest typebase irsend irsendinit longmsgs waitall waitall2 \
 	testsome getelm testall sndrcv nbtest nblock sendmany order hindexed \
 	commit cancel persist typecreate reqcreate sndrcvrep flood flood2 \
-	persist2 dataalign dtyperecv reqfree sndrcvrpl2 cancel2
+	persist2 dataalign dtyperecv reqfree sndrcvrpl2 cancel2 cancel3 \
+	cancelmessages cancelibm sendorder exittest
 OTHEREXECS = testtypes secondf allpair systest send1 \
 		systest1 allpair2 bsendtest structf typebasef 
 default: $(EXECS)
@@ -41,13 +48,31 @@ default: $(EXECS)
 testing: 
 	  -./runtests $(TESTARGS)
 
-linktest: overtake secondf clean
+# We want the link tests to be noisier about problems
+linktest: 
+	-$(MAKE) overtake
+	@if [ ! -x overtake ] ; then \
+	    echo "Could not link a C program with MPI libraries" ; \
+	    exit 1 ; fi
+	-$(MAKE) secondf
+	@if [ ! -x secondf ] ; then \
+	    echo "Could not link a Fortran program with MPI libraries" ; \
+	    exit 1 ; fi
+	$(MAKE) clean
 
-linktest1: overtake clean
+linktest1: 
+	-$(MAKE) overtake
+	@if [ ! -x overtake ] ; then \
+	    echo "Could not link a C program with MPI libraries" ; \
+	    exit 1 ; fi
+	$(MAKE) clean
 
 all: testing
 
 fortran_tests: secondf allpair allpair2 structf typebasef send1 pingpong
+
+#f90_tests: secondf90 allpair90 allpair290 structf90 typebasef90 send190 \
+#	pingpong90
 
 overtake: overtake.o test.o
 	$(CLINKER) $(OPTFLAGS) -o overtake overtake.o test.o $(LIBS)
@@ -253,49 +278,55 @@ cancel: cancel.o
 cancel2: cancel2.o
 	$(CLINKER) $(OPTFLAGS) -o cancel2 cancel2.o $(LIBS)
 
+cancel3: cancel3.o
+	$(CLINKER) $(OPTFLAGS) -o cancel3 cancel3.o $(LIBS)
+
+cancelmessages: cancelmessages.o
+	$(CLINKER) $(OPTFLAGS) -o cancelmessages cancelmessages.o $(LIBS)
+
+cancelibm: cancelibm.o
+	$(CLINKER) $(OPTFLAGS) -o cancelibm cancelibm.o $(LIBS)
+
+sendorder: sendorder.o
+	$(CLINKER) $(OPTFLAGS) -o sendorder sendorder.o $(LIBS)
+
+exittest: exittest.o
+	$(CLINKER) $(OPTFLAGS) -o exittest exittest.o $(LIBS)
+
 # This has a test for HAS_FORTRAN so that the link test target will work
 # even when -nof77 is selected.
 secondf: $(MPIFDEP) secondf.o
 	if test "@HAS_FORTRAN@" = 1 ; then \
-	$(FLINKER) $(OPTFLAGS) -o secondf secondf.o $(FLIBS) ; fi
+	$(FLINKER) $(OPTFLAGS) -o ./secondf secondf.o $(FLIBS) ; fi
 
 allpair: $(MPIFDEP) allpair.o 
-	$(FLINKER) $(OPTFLAGS) -o allpair allpair.o $(FLIBS)
+	$(FLINKER) $(OPTFLAGS) -o ./allpair allpair.o $(FLIBS)
 
 allpair2: $(MPIFDEP) allpair2.o
-	$(FLINKER) $(OPTFLAGS) -o allpair2 allpair2.o $(FLIBS)
+	$(FLINKER) $(OPTFLAGS) -o ./allpair2 allpair2.o $(FLIBS)
 
 structf: $(MPIFDEP) structf.o
-	$(FLINKER) $(OPTFLAGS) -o structf structf.o $(FLIBS)
+	$(FLINKER) $(OPTFLAGS) -o ./structf structf.o $(FLIBS)
 
 send1: $(MPIFDEP) send1.o
-	$(FLINKER) $(OPTFLAGS) -o send1 send1.o $(FLIBS)
+	$(FLINKER) $(OPTFLAGS) -o ./send1 send1.o $(FLIBS)
 
 pingpong: $(MPIFDEP) pingpong.o
-	$(FLINKER) $(OPTFLAGS) -o pingpong pingpong.o $(FLIBS)
+	$(FLINKER) $(OPTFLAGS) -o ./pingpong pingpong.o $(FLIBS)
 
 typebasef: $(MPIFDEP) typebasef.o
-	$(FLINKER) $(OPTFLAGS) -o typebasef typebasef.o $(FLIBS)
-
-#
-# Some systems have no test for a symbolic link and return false for
-# a link that exists
-#mpif.h: $(MPIR_HOME)/include/mpif.h
-#	if test \! -r mpif.h ; then \
-#	    /bin/rm -f mpif.h ; \
-#	    ln -s $(MPIR_HOME)/include/mpif.h . ; \
-#	fi
+	$(FLINKER) $(OPTFLAGS) -o ./typebasef typebasef.o $(FLIBS)
 
 #
 # Make sure that we remove executables for specific architectures
 clean:
 	@-/bin/rm -f *.o *~ PI* $(EXECS) *.out core pt2pt.diff $(OTHEREXECS) \
-		*.trace rdb.* startup.* 
+		*.trace rdb.* startup.* mpif.h ${srcdir}/*.o
 	@-for file in $(EXECS) Makefile ; do \
 	   /bin/rm -f $$file.sun4 $$file.alpha $$file.IRIX $$file.freebsd ;\
 	done
 
 .c.o:
-	$(CC) $(CFLAGS) -c $*.c
+	$(CC) $(CFLAGS) -c $<
 .f.o:
-	$(F77) $(FFLAGS) -c $*.f
+	$(F77) $(FFLAGS) $(F77_OPTFLAGS) -c $<
diff --git a/jumpshot/configure b/jumpshot/configure
--- a/jumpshot/configure
+++ b/jumpshot/configure
@@ -14,15 +14,17 @@ ac_default_prefix=/usr/local
 ac_help="$ac_help
 --enable-echo                      - Turn on strong echoing.  The default is enable=no. "
 ac_help="$ac_help
---with-bindir=GEN_BINDIR           - This is the directory where jumpshot's executable will be located.  Without this directory, you can not configure jumpshot. "
+--enable-debug                     -- This option turns on the debugging flags, -g, and uses jdb to run the code.  The default is enable=on"
 ac_help="$ac_help
---with-arch_bindir=ARCH_BINDIR     - This is an optional directory (in addition to the bindir directory) where jumpshot's executable will be located.  For example, when configuring with MPICH, this will be the build/ARCH/DEVICE/bin directory. "
+--with-bindir=GEN_BINDIR           - This is a bin directory where jumpshot's executable will be located.  If not specified, then jumpshot's executable will be placed in jumpshot/bin only."
 ac_help="$ac_help
 --with-jumpshot_home=JUMP_HOME - This is the path of the top-level directory where jumpshot is located.  Without this directory, you can not configure jumpshot."
 ac_help="$ac_help
 --with-java=JAVA_HOME              - The path of JAVA's top-level directory.  If this option is not given, then configure will try to locate java for you.  "
 ac_help="$ac_help
 --with-java_version=VERSION         - The version of JAVA that you will be using.  If this option is not given, then configure will try to locate the version for you "
+ac_help="$ac_help
+--with-jflags=JFLAGS          -- supply java compiler flags, e.g. optimization flags, -O, to the java compiler"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -525,6 +527,7 @@ fi
 
 TEMP_VERSION=""
 JUMPSCRIPT=""
+GEN_BINDIR=""
 #
 # Check whether --enable-echo or --disable-echo was given.
 if test "${enable_echo+set}" = set; then
@@ -533,21 +536,19 @@ if test "${enable_echo+set}" = set; then
 fi
 
 #
+# Check whether --enable-debug or --disable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval="$enable_debug"
+  :
+else
+  enable_debug=no
+fi
+
+#
 # Check whether --with-bindir or --without-bindir was given.
 if test "${with_bindir+set}" = set; then
   withval="$with_bindir"
   GEN_BINDIR=$withval
-else
-  echo "You need to specify a directory where jumpshot's executable will be copied to!" ; exit 1
-fi
-
-#
-# Check whether --with-arch_bindir or --without-arch_bindir was given.
-if test "${with_arch_bindir+set}" = set; then
-  withval="$with_arch_bindir"
-  ARCH_BINDIR=$withval
-else
-  ARCH_BINDIR=""
 fi
 
 #
@@ -561,6 +562,16 @@ fi
 
 #
 if test ! -d "$JUMPSHOT_HOME" ; then
+    if test -s src/code/jumpshot.java ; then 
+        JUMPSHOT_HOME=`pwd`
+    fi
+fi
+#
+if test -z "$JUMPSHOT_HOME" ; then 
+    { echo "configure: error: "You need to specify the top-level directory where jumpshot is located!"" 1>&2; exit 1; }
+fi
+#
+if test ! -d "$JUMPSHOT_HOME" ; then
     { echo "configure: error: "***$JUMPSHOT_HOME is not a valid directory - cannot continue"" 1>&2; exit 1; }
 fi
 #
@@ -572,7 +583,7 @@ else
   JAVA_HOME=""
 fi
 
-#
+# 
 # Check whether --with-java_version or --without-java_version was given.
 if test "${with_java_version+set}" = set; then
   withval="$with_java_version"
@@ -582,14 +593,22 @@ else
 fi
 
 #
-if test ! -d "$GEN_BINDIR" ; then
-    # We really shouldn't depend on -p (not all systems have it)
-    mkdir -p "$GEN_BINDIR"
+# Check whether --with-jflags or --without-jflags was given.
+if test "${with_jflags+set}" = set; then
+  withval="$with_jflags"
+  JFLAGS="$withval"
+fi
+
+#
+# Append "-g" to JFLAGS if enable_debug=yes
+if test $enable_debug = "yes"; then
+    if test -z "`echo $JFLAGS | grep "\-g"`"; then
+        JFLAGS="-g $JFLAGS"
+    fi
 fi
 #
-if test -n "$ARCH_BINDIR" -a ! -d "$ARCH_BINDIR" ; then
-    # We really shouldn't depend on -p (not all systems have it)
-    mkdir -p "$ARCH_BINDIR"
+if test ! -d $JUMPSHOT_HOME/bin ; then
+    mkdir $JUMPSHOT_HOME/bin
 fi
 #
 subdir=""
@@ -619,7 +638,7 @@ else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:623: checking host system type" >&5
+echo "configure:642: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -679,11 +698,13 @@ case "$host" in
 	    subdir="freebsd"
 	fi
 esac
+
 if test -z "$subdir" ; then
     if test -d "/software/common" ; then
         subdir="common"
     fi
 fi
+
 if test -z "$JAVA_HOME" ; then
 for dir in $PATH \
     /usr \
@@ -719,61 +740,236 @@ for dir in $PATH \
         if test -n "$java_type1"; then
 	    if test -d "$dir/JDK/bin" ; then
 	        if test -x "$dir/JDK/bin/java" -a "$dir/JDK/bin/jre" ; then
-	            JAVA_HOME="$dir/JDK"
-	            break
+		    # try running with -version
+		    if $dir/JDK/bin/java -version >/dev/null 2>&1 ; then
+   	                JAVA_HOME="$dir/JDK"
+	                break
+		    fi
 	        fi
 	    fi
         elif test -n "$java_type2" -o "$java_type3" ; then
 	    if test -x "$dir/bin/java" -a "$dir/bin/jre" ; then
-	        JAVA_HOME="$dir"
-	        break
+	        if $dir/bin/java -version >/dev/null 2>&1 ; then 
+  	            JAVA_HOME="$dir"
+	            break
+		fi
 	    fi
 	fi
     fi
 done
 fi
+
+# CHECK if SWING library is there
+if test -z "$SWING_LIBS"; then
+    SWING_LIBS="$JUMPSHOT_HOME/swing/swing.jar"
+fi
+
+SWING_LIBRARIES=`echo $SWING_LIBS | sed 's/:/ /g'`
+for library in $SWING_LIBRARIES ; do
+    if test ! -f "$library"; then
+        echo "**** $library in \$SWING_LIBS does NOT exist!"
+        echo "     hence CLASSPATH cannot be set"
+        exit 1
+    fi
+done
+
 if test -z "$JAVA_HOME" ; then
     echo "configure: warning: "Cannot find JAVA!"" 1>&2
     { echo "configure: error: "Please put JAVA in your path and reconfigure"" 1>&2; exit 1; }
 fi
+
+# CHECK the version of Java used
 if test -z "$VERSION" ; then
-    VERSION=`$JAVA_HOME/bin/java -version 2>&1 | grep 1.1`
-    if test -z "$VERSION" ; then
-        VERSION=`$JAVA_HOME/bin/java -version 2>&1 | grep 1.2`
-        if test -z "$VERSION" ; then
-            echo "Cannot determine version of java"
-            echo "Using the build/unix/bin/jumpshot script to execute JUMPSHOT"
-            echo "This may cause problems if you are using version 1.2 or higher"
-            JUMPSCRIPT="build/unix/bin/jumpshot"	
-        else
-	    echo "Java Version is $VERSION"
-	    JUMPSCRIPT="build/unix/bin/jumpshot12"
+    VERSION=`$JAVA_HOME/bin/java -version 2>&1`
+    if test -z "$VERSION" ; then 
+        echo "Cannot determine version of java"
+        echo "Using the bin/jumpshot script to execute JUMPSHOT"
+        echo "Jumpshot-2 is designed to be used with Java 1.1"
+    else 
+        echo "Java is $VERSION"
+        echo "Checking Java"
+        IsJava10=`echo $VERSION | grep 1.0`
+        IsJava11=`echo $VERSION | grep 1.1`
+        IsJava12=`echo $VERSION | grep 1.2`
+        IsJava13=`echo $VERSION | grep 1.3`
+# if it is not Java 1.1, exit!  
+        if test -z "$IsJava11" ; then
+            if test -n "$IsJava12" -o -n "$IsJava13" ; then
+               echo "**** Java $VERSION is incompatible with Jumpshot-2 !"
+               echo "     Jumpshot-2 is designed to be used with Java 1.1"
+            elif test -n "$IsJava10" ; then
+               echo "**** Java $VERSION is too old to be used with Jumpshot-2 !"
+               echo "     Jumpshot-2 is designed to be used with Java 1.1"
+            fi
+            exit 1
         fi
+    fi
+    JUMPSCRIPT="build/unix/bin/jumpshot"	
+fi
+
+if test -f "$JAVA_HOME/lib/classes.zip" ; then
+    JAVA_LIBS="$JAVA_HOME/lib/rt.jar:$JAVA_HOME/lib/classes.zip:$JAVA_HOME/classes"
+else
+    echo "**** $JAVA_HOME/lib/classes.zip does NOT exist"
+    echo "     JAVA_LIBS cannot be set, neither can CLASSPATH !"
+    exit 1
+fi
+
+JC="$JAVA_HOME/bin/javac"
+JAR="$JAVA_HOME/bin/jar"
+if test $enable_debug = "yes"; then
+    JVM="$JAVA_HOME/bin/jdb"
+else
+    JVM="$JAVA_HOME/bin/java"
+fi
+
+for exe in "$JC" "$JAR" "$JVM" ; do
+    if test ! -x "$exe" ; then
+        echo "**** $exe does NOT exist, check JAVA_HOME = $JAVA_HOME"
+        exit 1
+    fi
+done
+
+
+
+
+
+
+
+
+
+
+# Fixup for make
+MAKE=${MAKE:-make}
+
+echo $ac_n "checking gnumake""... $ac_c" 1>&6
+echo "configure:847: checking gnumake" >&5
+/bin/rm -f conftest
+cat > conftest <<.
+SHELL=/bin/sh
+ALL:
+	@(dir=`pwd` ; cd .. ; \$(MAKE) -f \$\$dir/conftest SUB)
+SUB:
+	@echo "success"
+.
+str=`$MAKE -f conftest 2>&1`
+if test "$str" != "success" ; then
+    str=`$MAKE --no-print-directory -f conftest 2>&1`
+    if test "$str" = "success" ; then
+        MAKE="$MAKE --no-print-directory"
+	echo "$ac_t""yes using --no-print-directory" 1>&6
     else
-        echo "Java Version is $VERSION"
-        JUMPSCRIPT="build/unix/bin/jumpshot"
+	echo "$ac_t""no" 1>&6
     fi
 else
-    TEMP_VERSION=`echo $VERSION | grep 1.1`
-    if test -z "$TEMP_VERSION" ; then
-        TEMP_VERSION=`echo $VERSION | grep 1.2`
-	if test -z "$TEMP_VERSION" ; then
-            echo "Cannot determine if you are using version 1.1.* or 1.2.*"
-            echo "Using the build/unix/bin/jumpshot script to execute JUMPSHOT"
-            echo "This may cause problems if you are using version 1.2 or higher"
-            JUMPSCRIPT="build/unix/bin/jumpshot"
-        else
-            echo "Java Version is $VERSION"
-	    JUMPSCRIPT="build/unix/bin/jumpshot12"
-	fi				
+    echo "$ac_t""no" 1>&6
+fi
+/bin/rm -f conftest
+str=""
+
+
+echo $ac_n "checking BSD 4.4 make""... $ac_c" 1>&6
+echo "configure:873: checking BSD 4.4 make" >&5
+/bin/rm -f conftest
+cat > conftest <<.
+ALL:
+	@echo "success"
+.
+cat > conftest1 <<.
+include conftest
+.
+str=`$MAKE -f conftest1 2>&1`
+/bin/rm -f conftest conftest1
+if test "$str" != "success" ; then
+    echo "$ac_t""Found BSD 4.4 so-called make" 1>&6
+    echo "The BSD 4.4 make is INCOMPATIBLE with all other makes."
+    echo "Using this so-called make may cause problems when building programs."
+    echo "You should consider using gnumake instead."
+    
+else
+    echo "$ac_t""no - whew" 1>&6
+fi
+str=""
+
+
+echo $ac_n "checking OSF V3 make""... $ac_c" 1>&6
+echo "configure:897: checking OSF V3 make" >&5
+/bin/rm -f conftest
+cat > conftest <<.
+SHELL=/bin/sh
+ALL:
+	@# This is a valid comment!
+	@echo "success"
+.
+str=`$MAKE -f conftest 2>&1`
+/bin/rm -f conftest 
+if test "$str" != "success" ; then
+    echo "$ac_t""Found OSF V3 make" 1>&6
+    echo "The OSF V3 make does not allow comments in target code."
+    echo "Using this make may cause problems when building programs."
+    echo "You should consider using gnumake instead."
+    
+else
+    echo "$ac_t""no" 1>&6
+fi
+str=""
+
+
+
+echo $ac_n "checking for virtual path format""... $ac_c" 1>&6
+echo "configure:921: checking for virtual path format" >&5
+rm -rf conftest*
+mkdir conftestdir
+cat >conftestdir/a.c <<EOF
+A sample file
+EOF
+cat > conftest <<EOF
+all: a.o
+VPATH=.:conftestdir
+.c.o:
+	@echo \$<
+EOF
+ac_out=`$MAKE -f conftest 2>&1 | grep 'conftestdir/a.c'`
+if test -n "$ac_out" ; then 
+    echo "$ac_t""VPATH" 1>&6
+    VPATH='VPATH=.:$(srcdir)'
+else
+    rm -f conftest
+    cat > conftest <<EOF
+all: a.o
+.PATH: . conftestdir
+.c.o:
+	@echo \$<
+EOF
+    ac_out=`$MAKE -f conftest 2>&1 | grep 'conftestdir/a.c'`
+    if test -n "$ac_out" ; then 
+        echo "$ac_t"".PATH" 1>&6
+        VPATH='.PATH: . $(srcdir)'
     else
-        echo "Java Version is $VERSION"
-        JUMPSCRIPT="build/unix/bin/jumpshot"
+	echo "$ac_t""neither VPATH nor .PATH works" 1>&6
     fi
 fi
-#
+rm -rf conftest*
 
 
+
+#echo "JAVA_HOME  = |$JAVA_HOME|"
+#echo "JAVA_LIBS  = |$JAVA_LIBS|"
+#echo "JFLAGS     = |$JFLAGS|"
+#echo "JC         = |$JC|"
+#echo "JAR        = |$JAR|"
+#echo "JVM        = |$JVM|"
+#echo "SWING_LIBS = |$SWING_LIBS|"
+#echo "JUMP_HOME  = |$JUMPSHOT_HOME|"
+#echo "JUMPSCRIPT = |$JUMPSCRIPT|"
+
+# In case of a VPATH build, we need to create the src directory before
+# invoking ac_OUTPUT
+if test ! -d src ; then mkdir src ; fi
+# JUMPSCRIPT is more difficult.  Try to create the default directories 
+# for it, at least
+if test ! -d build ; then mkdir build ; fi
+if test ! -d build/unix ; then mkdir build/unix ; fi
 trap '' 1 2 15
 
 trap 'rm -fr conftest* confdefs* core core.* *.core $ac_clean_files; exit 1' 1 2 15
@@ -840,7 +1036,7 @@ done
 
 ac_given_srcdir=$srcdir
 
-trap 'rm -fr `echo "$JUMPSCRIPT" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "Makefile src/code/Makefile $JUMPSCRIPT" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -876,7 +1072,15 @@ s%@host_cpu@%$host_cpu%g
 s%@host_vendor@%$host_vendor%g
 s%@host_os@%$host_os%g
 s%@JAVA_HOME@%$JAVA_HOME%g
+s%@JAVA_LIBS@%$JAVA_LIBS%g
+s%@JFLAGS@%$JFLAGS%g
+s%@JC@%$JC%g
+s%@JAR@%$JAR%g
+s%@JVM@%$JVM%g
+s%@SWING_LIBS@%$SWING_LIBS%g
 s%@JUMPSHOT_HOME@%$JUMPSHOT_HOME%g
+s%@VPATH@%$VPATH%g
+s%@MAKE@%$MAKE%g
 
 CEOF
 EOF
@@ -918,7 +1122,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"$JUMPSCRIPT"}
+CONFIG_FILES=\${CONFIG_FILES-"Makefile src/code/Makefile $JUMPSCRIPT"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
@@ -991,26 +1195,24 @@ else
     { echo "configure: error: "***$JUMPSCRIPT is not a valid file - Make sure you have"" 1>&2; exit 1; }
     { echo "configure: error: "   configured with a valid JUMPSHOT home directory"" 1>&2; exit 1; }
 fi
-#    
-if test -z "$ARCH_BINDIR" ; then
-    if test -f $GEN_BINDIR/jumpshot ; then
-        /bin/rm -f $GEN_BINDIR/jumpshot
+#
+if test -z "$GEN_BINDIR" ; then
+    if test -f $JUMPSHOT_HOME/bin/jumpshot ; then
+        /bin/rm -f $JUMPSHOT_HOME/bin/jumpshot
     fi
-    echo "Jumpshot's executable will be located in $GEN_BINDIR"
+    echo "Jumpshot's executable will be located in $JUMPSHOT_HOME/bin"
     echo "Make sure you set your path to include this directory!"
-    cp $JUMPSCRIPT $GEN_BINDIR
+    cp $JUMPSCRIPT $JUMPSHOT_HOME/bin
 else
     if test -f $GEN_BINDIR/jumpshot ; then
         /bin/rm -f $GEN_BINDIR/jumpshot
     fi
-    if test -f $ARCH_BINDIR/jumpshot ; then
-        /bin/rm -f $ARCH_BINDIR/jumpshot
+    if test -f $JUMPSHOT_HOME/bin/jumpshot ; then
+        /bin/rm -f $JUMPSHOT_HOME/bin/jumpshot
     fi
     echo "Jumpshot's executable will be located in $GEN_BINDIR"
-    echo "and $ARCH_BINDIR"
+    echo "and $JUMPSHOT_HOME/bin"
     echo "Make sure you set your path to include at least one of these directories!"
     cp $JUMPSCRIPT $GEN_BINDIR
-    cp $JUMPSCRIPT $ARCH_BINDIR
+    cp $JUMPSCRIPT $JUMPSHOT_HOME/bin
 fi
-
-
diff --git a/jumpshot/configure.in b/jumpshot/configure.in
--- a/jumpshot/configure.in
+++ b/jumpshot/configure.in
@@ -11,31 +11,45 @@ dnl
 AC_INIT()
 TEMP_VERSION=""
 JUMPSCRIPT=""
+GEN_BINDIR=""
 #
 AC_ARG_ENABLE(echo, [--enable-echo                      - Turn on strong echoing.  The default is enable=no.] ,set -x)
 #
-AC_ARG_WITH(bindir, [--with-bindir=GEN_BINDIR           - This is the directory where jumpshot's executable will be located.  Without this directory, you can not configure jumpshot. ], GEN_BINDIR=$withval, echo "You need to specify a directory where jumpshot's executable will be copied to!" ; exit 1)
+AC_ARG_ENABLE(debug, [--enable-debug                     -- This option turns on the debugging flags, -g, and uses jdb to run the code.  The default is enable=on], ,enable_debug=no)
 #
-AC_ARG_WITH(arch_bindir, [--with-arch_bindir=ARCH_BINDIR     - This is an optional directory (in addition to the bindir directory) where jumpshot's executable will be located.  For example, when configuring with MPICH, this will be the build/ARCH/DEVICE/bin directory. ], ARCH_BINDIR=$withval, ARCH_BINDIR="")
+AC_ARG_WITH(bindir, [--with-bindir=GEN_BINDIR           - This is a bin directory where jumpshot's executable will be located.  If not specified, then jumpshot's executable will be placed in jumpshot/bin only.], GEN_BINDIR=$withval)
 #
 AC_ARG_WITH(jumpshot_home,   [--with-jumpshot_home=JUMP_HOME - This is the path of the top-level directory where jumpshot is located.  Without this directory, you can not configure jumpshot.], JUMPSHOT_HOME=$withval, echo "You need to specify the top-level directory where jumpshot is located!" ; exit 1)
+#
+if test ! -d "$JUMPSHOT_HOME" ; then
+    if test -s src/code/jumpshot.java ; then 
+        JUMPSHOT_HOME=`pwd`
+    fi
+fi
+#
+if test -z "$JUMPSHOT_HOME" ; then 
+    AC_MSG_ERROR("You need to specify the top-level directory where jumpshot is located!")
+fi
 #
 if test ! -d "$JUMPSHOT_HOME" ; then
     AC_MSG_ERROR("***$JUMPSHOT_HOME is not a valid directory - cannot continue")
 fi
 #
 AC_ARG_WITH(java, [--with-java=JAVA_HOME              - The path of JAVA's top-level directory.  If this option is not given, then configure will try to locate java for you.  ], JAVA_HOME=$withval, JAVA_HOME="")
-#
+# 
 AC_ARG_WITH(java_version, [--with-java_version=VERSION         - The version of JAVA that you will be using.  If this option is not given, then configure will try to locate the version for you ], VERSION=$withval, VERSION="")
 #
-if test ! -d "$GEN_BINDIR" ; then
-    # We really shouldn't depend on -p (not all systems have it)
-    mkdir -p "$GEN_BINDIR"
+AC_ARG_WITH(jflags, [--with-jflags=JFLAGS          -- supply java compiler flags, e.g. optimization flags, -O, to the java compiler], JFLAGS="$withval")
+#
+# Append "-g" to JFLAGS if enable_debug=yes
+if test $enable_debug = "yes"; then
+    if test -z "`echo $JFLAGS | grep "\-g"`"; then
+        JFLAGS="-g $JFLAGS"
+    fi
 fi
 #
-if test -n "$ARCH_BINDIR" -a ! -d "$ARCH_BINDIR" ; then
-    # We really shouldn't depend on -p (not all systems have it)
-    mkdir -p "$ARCH_BINDIR"
+if test ! -d $JUMPSHOT_HOME/bin ; then
+    mkdir $JUMPSHOT_HOME/bin
 fi
 #
 subdir=""
@@ -80,11 +94,13 @@ case "$host" in
 	    subdir="freebsd"
 	fi
 esac
+
 if test -z "$subdir" ; then
     if test -d "/software/common" ; then
         subdir="common"
     fi
 fi
+
 if test -z "$JAVA_HOME" ; then
 for dir in $PATH \
     /usr \
@@ -120,62 +136,131 @@ for dir in $PATH \
         if test -n "$java_type1"; then
 	    if test -d "$dir/JDK/bin" ; then
 	        if test -x "$dir/JDK/bin/java" -a "$dir/JDK/bin/jre" ; then
-	            JAVA_HOME="$dir/JDK"
-	            break
+		    # try running with -version
+		    if $dir/JDK/bin/java -version >/dev/null 2>&1 ; then
+   	                JAVA_HOME="$dir/JDK"
+	                break
+		    fi
 	        fi
 	    fi
         elif test -n "$java_type2" -o "$java_type3" ; then
 	    if test -x "$dir/bin/java" -a "$dir/bin/jre" ; then
-	        JAVA_HOME="$dir"
-	        break
+	        if $dir/bin/java -version >/dev/null 2>&1 ; then 
+  	            JAVA_HOME="$dir"
+	            break
+		fi
 	    fi
 	fi
     fi
 done
 fi
+
+# CHECK if SWING library is there
+if test -z "$SWING_LIBS"; then
+    SWING_LIBS="$JUMPSHOT_HOME/swing/swing.jar"
+fi
+
+SWING_LIBRARIES=`echo $SWING_LIBS | sed 's/:/ /g'`
+for library in $SWING_LIBRARIES ; do
+    if test ! -f "$library"; then
+        echo "**** $library in \$SWING_LIBS does NOT exist!"
+        echo "     hence CLASSPATH cannot be set"
+        exit 1
+    fi
+done
+
 if test -z "$JAVA_HOME" ; then
     AC_MSG_WARN("Cannot find JAVA!")
     AC_MSG_ERROR("Please put JAVA in your path and reconfigure")
 fi
+
+# CHECK the version of Java used
 if test -z "$VERSION" ; then
-    VERSION=`$JAVA_HOME/bin/java -version 2>&1 | grep 1.1`
-    if test -z "$VERSION" ; then
-        VERSION=`$JAVA_HOME/bin/java -version 2>&1 | grep 1.2`
-        if test -z "$VERSION" ; then
-            echo "Cannot determine version of java"
-            echo "Using the build/unix/bin/jumpshot script to execute JUMPSHOT"
-            echo "This may cause problems if you are using version 1.2 or higher"
-            JUMPSCRIPT="build/unix/bin/jumpshot"	
-        else
-	    echo "Java Version is $VERSION"
-	    JUMPSCRIPT="build/unix/bin/jumpshot12"
+    VERSION=`$JAVA_HOME/bin/java -version 2>&1`
+    if test -z "$VERSION" ; then 
+        echo "Cannot determine version of java"
+        echo "Using the bin/jumpshot script to execute JUMPSHOT"
+        echo "Jumpshot-2 is designed to be used with Java 1.1"
+    else 
+        echo "Java is $VERSION"
+        echo "Checking Java"
+        IsJava10=`echo $VERSION | grep 1.0`
+        IsJava11=`echo $VERSION | grep 1.1`
+        IsJava12=`echo $VERSION | grep 1.2`
+        IsJava13=`echo $VERSION | grep 1.3`
+# if it is not Java 1.1, exit!  
+        if test -z "$IsJava11" ; then
+            if test -n "$IsJava12" -o -n "$IsJava13" ; then
+               echo "**** Java $VERSION is incompatible with Jumpshot-2 !"
+               echo "     Jumpshot-2 is designed to be used with Java 1.1"
+            elif test -n "$IsJava10" ; then
+               echo "**** Java $VERSION is too old to be used with Jumpshot-2 !"
+               echo "     Jumpshot-2 is designed to be used with Java 1.1"
+            fi
+            exit 1
         fi
-    else
-        echo "Java Version is $VERSION"
-        JUMPSCRIPT="build/unix/bin/jumpshot"
     fi
-else
-    TEMP_VERSION=`echo $VERSION | grep 1.1`
-    if test -z "$TEMP_VERSION" ; then
-        TEMP_VERSION=`echo $VERSION | grep 1.2`
-	if test -z "$TEMP_VERSION" ; then
-            echo "Cannot determine if you are using version 1.1.* or 1.2.*"
-            echo "Using the build/unix/bin/jumpshot script to execute JUMPSHOT"
-            echo "This may cause problems if you are using version 1.2 or higher"
-            JUMPSCRIPT="build/unix/bin/jumpshot"
-        else
-            echo "Java Version is $VERSION"
-	    JUMPSCRIPT="build/unix/bin/jumpshot12"
-	fi				
-    else
-        echo "Java Version is $VERSION"
-        JUMPSCRIPT="build/unix/bin/jumpshot"
-    fi
+    JUMPSCRIPT="build/unix/bin/jumpshot"	
 fi
-#
+
+if test -f "$JAVA_HOME/lib/classes.zip" ; then
+    JAVA_LIBS="$JAVA_HOME/lib/rt.jar:$JAVA_HOME/lib/classes.zip:$JAVA_HOME/classes"
+else
+    echo "**** $JAVA_HOME/lib/classes.zip does NOT exist"
+    echo "     JAVA_LIBS cannot be set, neither can CLASSPATH !"
+    exit 1
+fi
+
+JC="$JAVA_HOME/bin/javac"
+JAR="$JAVA_HOME/bin/jar"
+if test $enable_debug = "yes"; then
+    JVM="$JAVA_HOME/bin/jdb"
+else
+    JVM="$JAVA_HOME/bin/java"
+fi
+
+for exe in "$JC" "$JAR" "$JVM" ; do
+    if test ! -x "$exe" ; then
+        echo "**** $exe does NOT exist, check JAVA_HOME = $JAVA_HOME"
+        exit 1
+    fi
+done
+
 AC_SUBST(JAVA_HOME)
+AC_SUBST(JAVA_LIBS)
+AC_SUBST(JFLAGS)
+AC_SUBST(JC)
+AC_SUBST(JAR)
+AC_SUBST(JVM)
+AC_SUBST(SWING_LIBS)
 AC_SUBST(JUMPSHOT_HOME)
-AC_OUTPUT($JUMPSCRIPT)
+
+# Fixup for make
+MAKE=${MAKE:-make}
+PAC_MAKE_IS_GNUMAKE
+PAC_MAKE_IS_BSD44
+PAC_MAKE_IS_OSF
+PAC_MAKE_VPATH
+AC_SUBST(MAKE)
+
+#echo "JAVA_HOME  = |$JAVA_HOME|"
+#echo "JAVA_LIBS  = |$JAVA_LIBS|"
+#echo "JFLAGS     = |$JFLAGS|"
+#echo "JC         = |$JC|"
+#echo "JAR        = |$JAR|"
+#echo "JVM        = |$JVM|"
+#echo "SWING_LIBS = |$SWING_LIBS|"
+#echo "JUMP_HOME  = |$JUMPSHOT_HOME|"
+#echo "JUMPSCRIPT = |$JUMPSCRIPT|"
+
+# In case of a VPATH build, we need to create the src directory before
+# invoking ac_OUTPUT
+if test ! -d src ; then mkdir src ; fi
+# JUMPSCRIPT is more difficult.  Try to create the default directories 
+# for it, at least
+if test ! -d build ; then mkdir build ; fi
+if test ! -d build/unix ; then mkdir build/unix ; fi
+AC_OUTPUT(Makefile src/code/Makefile $JUMPSCRIPT)
 
 if test -f "$JUMPSCRIPT" ; then
     chmod a+x $JUMPSCRIPT
@@ -183,26 +268,24 @@ else
     AC_MSG_ERROR("***$JUMPSCRIPT is not a valid file - Make sure you have")
     AC_MSG_ERROR("   configured with a valid JUMPSHOT home directory")
 fi
-#    
-if test -z "$ARCH_BINDIR" ; then
-    if test -f $GEN_BINDIR/jumpshot ; then
-        /bin/rm -f $GEN_BINDIR/jumpshot
+#
+if test -z "$GEN_BINDIR" ; then
+    if test -f $JUMPSHOT_HOME/bin/jumpshot ; then
+        /bin/rm -f $JUMPSHOT_HOME/bin/jumpshot
     fi
-    echo "Jumpshot's executable will be located in $GEN_BINDIR"
+    echo "Jumpshot's executable will be located in $JUMPSHOT_HOME/bin"
     echo "Make sure you set your path to include this directory!"
-    cp $JUMPSCRIPT $GEN_BINDIR
+    cp $JUMPSCRIPT $JUMPSHOT_HOME/bin
 else
     if test -f $GEN_BINDIR/jumpshot ; then
         /bin/rm -f $GEN_BINDIR/jumpshot
     fi
-    if test -f $ARCH_BINDIR/jumpshot ; then
-        /bin/rm -f $ARCH_BINDIR/jumpshot
+    if test -f $JUMPSHOT_HOME/bin/jumpshot ; then
+        /bin/rm -f $JUMPSHOT_HOME/bin/jumpshot
     fi
     echo "Jumpshot's executable will be located in $GEN_BINDIR"
-    echo "and $ARCH_BINDIR"
+    echo "and $JUMPSHOT_HOME/bin"
     echo "Make sure you set your path to include at least one of these directories!"
     cp $JUMPSCRIPT $GEN_BINDIR
-    cp $JUMPSCRIPT $ARCH_BINDIR
+    cp $JUMPSCRIPT $JUMPSHOT_HOME/bin
 fi
-
-
diff --git a/mpid/ch_p4/p4/configure.in b/mpid/ch_p4/p4/configure.in
--- a/mpid/ch_p4/p4/configure.in
+++ b/mpid/ch_p4/p4/configure.in
@@ -37,7 +37,7 @@ Usage: ${progname} -p4arch=ARCH_TYPE [-alog={on,off}] [-dprintfl={on,off}]
                    [-p4comm=shared]  [-listener_pathname="\<pathname\>"]
                    [-rsh=command] [-rshnol] [-cflags=flags] 
                    [-threaded_listener] [-nothreaded_listener]
-                   [-dlast] [-listenersig=name] [--enable-nonblockread]
+                   [-dlast] [-listenersig=name] [--disable-nonblockread]
 "
 RSHCOMMAND=
 MDEP_LIBS=
@@ -52,15 +52,28 @@ FC=${FC:-f77}
 threaded_listener=0
 userSet_threaded_listener=0
 listener_sig=""
-use_nonblock_read=0
+# use modern socket code (EOF on socket can be distinquished from no-data)
+# unless the test below fails.  This can be turned off with
+# --disable-nonblockread
+use_nonblock_read=1
 #
 for arg
 do
 case $arg in
+  -srcdir=* | --srcdir=* | --srcdi=* | --srcd=* | --src=* | --sr=* | --s=*)
+	srcdir=`echo $arg | sed 's/[-a-z_]*=//'` ;;
+  -exec-prefix=* | --exec_prefix=* | --exec-prefix=* | --exec-prefi=* | --exec-pref=* | --exec-pre=* | --exec-pr=* | --exec-p=* | --exec-=* | --exec=* | --exe=* | --ex=* | --e=*)
+	exec_prefix=`echo $arg | sed 's/[-a-z_]*=//'` ;;
+  -libbuild_dir=*) libbuild_dir=`echo A$arg | sed 's/A[-a-z_]*=//'` ;;
   -p4arch=*)
      p4arch=`echo $arg|sed 's/-p4arch=//'`
      eval "p4arch_`echo $p4arch`=1"
      echo Setting p4arch to $p4arch
+     ;;
+  -p4device=*)
+     p4device=`echo $arg|sed 's/-p4device=//'`
+     eval "p4device_`echo $p4device`=1"
+     echo Setting p4device to $p4device
      ;;
   -p4echo=*)
      p4echo=`echo $arg|sed 's/-p4echo=//'`
@@ -166,11 +179,45 @@ DEFINE_VENDOR_IPC="#undef VENDOR_IPC"
 DEFINE_P4_DPRINTFL="#define P4_DPRINTFL"
 LISTENER_PATHNAME=""
 ]
+
+# It is important to remove the p4_config.h file if we are performing
+# a VPATH build
+rm -f config.log p4_config.h
 AC_PREPARE()
+
+# Standard directories
+if test -z "$top_srcdir" -o "$top_srcdir" = "." ; then 
+    top_srcdir=$srcdir
+fi
+# Remove the config file from the srcdir if this is a VPATH build.
+rm -f $top_srcdir/p4_config.h
+
+AC_SUBST(top_srcdir)
+if test -z "$exec_prefix" ; then 
+    exec_prefix="${top_srcdir}"
+fi
+AC_SUBST(exec_prefix)
+if test -z "$libdir" ; then libdir="$exec_prefix/lib" ; fi
+AC_SUBST(libdir)
+
+# libbuild_dir is used to build the libraries in before they are installed.
+if test -z "$libbuild_dir" ; then 
+    libbuild_dir=`pwd`/lib
+fi
+if test ! -d $libbuild_dir ; then
+    if mkdir $libbuild_dir ; then 
+	:
+    else
+        print_error "Could not create directory $libbuild_dir"
+        exit 1
+    fi
+fi
+AC_SUBST(libbuild_dir)
+
 AC_PROG_RANLIB()
 # check for valid architecture
 # Check for an EXACT match, since that's what the defines require
-egrep "^    $p4arch\$" MACHINES > /dev/null 2>&1
+egrep "^    $p4arch\$" $srcdir/MACHINES > /dev/null 2>&1
 if test $? != 0 ; then
     echo Invalid arch $p4arch
     exit 1
@@ -180,6 +227,10 @@ if test -n "$p4make"; then
     MAKE=$p4make
 fi
 #
+if test -z "$VPATH" ; then 
+    PAC_MAKE_VPATH
+fi
+
 if test -n "$p4arch_SUN"; then
     P4ARCH=SUN
     if test -n "$p4comm_shared"; then
@@ -200,13 +251,22 @@ if test -n "$p4arch_NETBSD"; then
       DEFINE_SYSV_IPC="#define SYSV_IPC"
     fi
 fi
-#						486 running Linux
+#						x86 running Linux
 if test -n "$p4arch_LINUX"; then
     P4ARCH=LINUX
     if test -n "$p4comm_shared"; then
       DEFINE_SYSV_IPC="#define SYSV_IPC"
     fi
 fi
+
+#                                                Alpha running Linux
+if test -n "$p4arch_LINUX_ALPHA"; then
+    P4ARCH=LINUX
+    if test -n "$p4comm_shared"; then
+      DEFINE_SYSV_IPC="#define SYSV_IPC"
+    fi
+fi
+
 #                                             KSR
 if test -n "$p4arch_KSR"; then
     P4ARCH=KSR
@@ -230,8 +290,14 @@ if test -n "$p4arch_SUN_SOLARIS"; then
     fi
     AC_HAVE_LIBRARY(socket)
     AC_HAVE_LIBRARY(nsl)
+    AC_MSG_CHECKING(for how many arguments gettimeofday takes)
+    AC_TEST_PROGRAM([#include <sys/time.h>
+main() {struct timeval tp;
+gettimeofday(&tp);return 0;}],
+MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_WIERDGETTIMEOFDAY"
+AC_MSG_RESULT(one!),AC_MSG_RESULT(two - whew))
 
-    PAC_IS_GETTIMEOFDAY_OK(,MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_WIERDGETTIMEOFDAY")
+dnl    PAC_IS_GETTIMEOFDAY_OK(,MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_WIERDGETTIMEOFDAY")
 
     dnl #MDEP_LIBS = /usr/ucblib/libucb.a -lsocket -lnsl  # for fortran
 fi
@@ -368,7 +434,11 @@ fi
 if test -n "$p4arch_SGI"; then
     P4ARCH=SGI
     RANLIB=true
-    AC_HAVE_LIBRARY(sun)
+    # Look for getpwnam.  If not found, try to find it in -lsun
+    AC_FUNC_CHECK(getpwnam,has_getpwnam=1,has_getpwnam=0)
+    if test $has_getpwnam = 0 ; then
+        AC_HAVE_LIBRARY(sun)
+    fi
     dnl    MDEP_CFLAGS=-cckr
     if test -n "$p4comm_shared"; then
       DEFINE_VENDOR_IPC="#define VENDOR_IPC"
@@ -379,7 +449,10 @@ fi
 if test -n "$p4arch_SGI5"; then
     P4ARCH=SGI
     RANLIB=true
-    AC_HAVE_LIBRARY(sun)
+    AC_FUNC_CHECK(getpwnam,has_getpwnam=1,has_getpwnam=0)
+    if test $has_getpwnam = 0 ; then
+        AC_HAVE_LIBRARY(sun)
+    fi
     dnl    MDEP_CFLAGS=-cckr
     if test -n "$p4comm_shared"; then
       DEFINE_VENDOR_IPC="#define VENDOR_IPC"
@@ -390,7 +463,10 @@ fi
 if test -n "$p4arch_SGI32"; then
     P4ARCH=SGI
     RANLIB=true
-    AC_HAVE_LIBRARY(sun)
+    AC_FUNC_CHECK(getpwnam,has_getpwnam=1,has_getpwnam=0)
+    if test $has_getpwnam = 0 ; then
+        AC_HAVE_LIBRARY(sun)
+    fi
     # This choice of flags is for the SGI compilers.  If the user chose
     # gcc, they won't work.
     PAC_CHECK_COMPILER_OPTION(-32,MDEP_CFLAGS="-32";MDEP_LFLAGS="-32")
@@ -406,7 +482,10 @@ fi
 if test -n "$p4arch_SGIN32"; then
     P4ARCH=SGI
     RANLIB=true
-    AC_HAVE_LIBRARY(sun)
+    AC_FUNC_CHECK(getpwnam,has_getpwnam=1,has_getpwnam=0)
+    if test $has_getpwnam = 0 ; then
+        AC_HAVE_LIBRARY(sun)
+    fi
     # This choice of flags is for the SGI compilers.  If the user chose
     # gcc, they won't work.
     PAC_CHECK_COMPILER_OPTION(-n32,MDEP_CFLAGS="-n32";MDEP_LFLAGS="-n32")
@@ -421,7 +500,10 @@ fi
 if test -n "$p4arch_SGI6"; then
     P4ARCH=SGI
     RANLIB=true
-    AC_HAVE_LIBRARY(sun)
+    AC_FUNC_CHECK(getpwnam,has_getpwnam=1,has_getpwnam=0)
+    if test $has_getpwnam = 0 ; then
+        AC_HAVE_LIBRARY(sun)
+    fi
     dnl MDEP_CFLAGS="-cckr -woff 1552,1174"
     dnl MDEP_FFLAGS="-cckr -woff 1552,1174"
     PAC_CHECK_COMPILER_OPTION([-woff 1552,1174],
@@ -438,7 +520,10 @@ fi
 if test -n "$p4arch_SGI_MP"; then
     P4ARCH=SGI_MP
     RANLIB=true
-    AC_HAVE_LIBRARY(sun)
+    AC_FUNC_CHECK(getpwnam,has_getpwnam=1,has_getpwnam=0)
+    if test $has_getpwnam = 0 ; then
+        AC_HAVE_LIBRARY(sun)
+    fi
     AC_HAVE_FUNCS(setsid)
     AC_HAVE_FUNCS(isatty)
     dnl MDEP_CFLAGS=-cckr
@@ -537,7 +622,7 @@ fi
 # dump copy of MDEP_CFLAGS into file for other system to pick up
 /bin/rm -f mpdepcflags
 echo $MDEP_CFLAGS > mdepcflags
-# evaluate variables for lib/p4_config.h
+# evaluate variables for p4_config.h
 if test "$p4alog" = "on"; then
     DEFINE_ALOG="#define ALOG_TRACE"
 fi
@@ -552,7 +637,10 @@ fi
 AC_CROSS_CHECK()
 #
 # Look for netinet/in.h and sys/socketvar.h
-PAC_CHECK_HEADERS(netinet/in.h)
+has_rpc_rpc=0
+PAC_CHECK_HEADERS(rpc/rpc.h,has_rpc_rpc=1)
+has_netinet_in=0
+PAC_CHECK_HEADERS(netinet/in.h,has_netinet_in=1)
 PAC_CHECK_HEADERS(arpa/inet.h)
 PAC_CHECK_HEADERS(sys/socketvar.h)
 PAC_CHECK_HEADERS(stdlib.h)
@@ -572,6 +660,42 @@ main() {return 0;}],
 AC_MSG_RESULT(yes)
 AC_DEFINE(BOTH_STRING_INCS),AC_MSG_RESULT(no))
 #
+if test "$has_rpc_rpc" = 1 ; then
+    # does it really?
+    # (gcc on Solaris 5.6 sometimes fails, particularly when OS was upgraded
+    # from 5.5 to 5.6 but gcc was not reinstalled).
+    AC_COMPILE_CHECK([correct headers with rpc/rpc.h],[
+#include <sys/types.h>
+#include <rpc/rpc.h>]
+,,,cc_broken=1)
+    if test "$cc_broken" = 1; then
+        echo "Your C compiler $CC fails to compile the program"
+        echo "#include <sys/types.h>"
+        echo "#include <rpc/rpc.h>"
+	echo "If you are using gcc, make sure that the system include"
+        echo "files and the gcc include files are consistent.  If "
+        echo "you have upgraded the OS, you may need to reinstall gcc"
+        exit 1
+    fi
+fi
+if test "$has_netinet_in" = 1 ; then
+    # does it really?
+    # (gcc on Solaris 5.6 sometimes fails, particularly when OS was upgraded
+    # from 5.5 to 5.6 but gcc was not reinstalled).
+    AC_COMPILE_CHECK([correct headers with netinet/in.h],[
+#include <sys/types.h>
+#include <netinet/in.h>]
+,,,cc_broken=1)
+    if test "$cc_broken" = 1; then
+        echo "Your C compiler $CC fails to compile the program"
+        echo "#include <sys/types.h>"
+        echo "#include <netinet/in.h>"
+	echo "If you are using gcc, make sure that the system include"
+        echo "files and the gcc include files are consistent.  If "
+        echo "you have upgraded the OS, you may need to reinstall gcc"
+        exit 1
+    fi
+fi
 #
 # It isn't enough to check for stdarg.  Even gcc doesn't get it right;
 # on some systems, the gcc version of stdio.h loads stdarg.h WITH THE WRONG
@@ -579,11 +703,6 @@ AC_DEFINE(BOTH_STRING_INCS),AC_MSG_RESULT(no))
 #
 if test -n "$havestdarg" ; then
     PAC_COMPILE_CHECK_FUNC(stdarg is correct,[
-/* DEC Alpha compiler by default does NOT define __STDC__ but DOES
-   accept prototypes */
-#if !defined(__STDC__)
-'bad text'
-#endif
 #include <stdio.h>
 #include <stdarg.h>
 int func( int a, ... ){
@@ -599,10 +718,17 @@ return 0;
 int main() { func( 1, 2 ); return 0;}],AC_DEFINE(USE_STDARG))
 fi
 #
+AC_HAVE_FUNCS(sigsetmask)
+AC_HAVE_FUNCS(sigblock)
 # Look for sigaction routine (instead of signal)
 AC_HAVE_FUNCS(sigaction)
 AC_COMPILE_CHECK(for struct sigaction,[#include <signal.h>],[
 struct sigaction act; sigaddset( &act.sa_mask, SIGINT );],sigaction_ok="yes",sigaction_ok="no")
+# XOPEN mandates that union semun NOT be defined(!)
+AC_COMPILE_CHECK(for union semun,[#include <sys/types.h>
+#include <sys/ipc.h>
+#include <sys/sem.h>],[
+union semun arg;arg.val=0;],,AC_DEFINE(SEMUN_UNDEFINED))
 # strerror is prefered over extern char *sys_errlist[];
 AC_HAVE_FUNCS(strerror)
 AC_HAVE_LIBRARY(crypt,CRYPT_LIBS=-lcrypt)
@@ -610,16 +736,20 @@ AC_HAVE_LIBRARY(crypt,CRYPT_LIBS=-lcrypt)
 AC_HAVE_FUNCS(vprintf)
 
 #
-# Check that nonblocking read works
-if test -s readblock.c ; then
+# Check that nonblocking read works:
+# Early SYSV (R2) had a design problem with nonblocking sockets:
+# there was no way to distinquish between EOF and no data on socket.
+# This code tests for this case; if an EOF on the socket gives the
+# correct value (-1), we note this.  If it fails, there is code in
+# p4 to work around this design bug, but it can introduce performance
+# penalties.  
+if test -s $top_srcdir/readblock.c -a $use_nonblock_read = 1 ; then
     AC_MSG_CHECKING([that read O_NDELAY works])
     readworks=0
-    AC_TEST_PROGRAM([`cat readblock.c`],readworks=1)
+    AC_TEST_PROGRAM([`cat $top_srcdir/readblock.c`],readworks=1)
     if test $readworks = 1 ; then
         AC_MSG_RESULT(yes)
-	if test $use_nonblock_read = 1 ; then
-            AC_DEFINE(NONBLOCKING_READ_WORKS)
-	fi
+        AC_DEFINE(NONBLOCKING_READ_WORKS)
     else
 	AC_MSG_RESULT(no)
     fi
@@ -648,6 +778,57 @@ if test -n "$RSHNOL" ; then
     AC_DEFINE(RSH_HAS_NO_L)
 fi
 #
+#
+# The following are necessary for AIX in particular because in 64 bit mode,
+# some of the socket functions use size_t (unsigned long, 64 bits) instead of
+# int (signed int, 32 bits) as a return value.  Getting the wrong type
+# causes all sorts of chaos.  Unfortunately, there isn't any consensus on what
+# the arguments *should* be.
+found_sockopt_type=0
+AC_COMPILE_CHECK([if getsockopt wants socklen_t],[#include <sys/types.h>
+#include <sys/socket.h>],[socklen_t dummy; int rc, skt; void *ssz;
+rc = getsockopt(skt,SOL_SOCKET,SO_SNDBUF,ssz,&dummy);],found_sockopt_type=1)
+if test $found_sockopt_type = 1 ; then
+    MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_SOCKLEN_T"
+fi
+if test $found_sockopt_type = 0 ; then
+    # This case is harder.  size_t is a valid type, but it may not be the 
+    # one that getsockopt etc wants.
+    AC_MSG_CHECKING([if getsockopt wants size_t])
+    PAC_TRY_COMPILE_CLEAN([#include <sys/types.h>
+#include <sys/socket.h>],[int try(void){size_t dummy; int rc, skt; void *ssz;
+rc = getsockopt(skt,SOL_SOCKET,SO_SNDBUF,ssz,&dummy);
+return rc;}],found_sockopt_type)
+    case $found_sockopt_type in 
+	0) AC_MSG_RESULT(yes)
+           MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_SIZE_T_FOR_SOCKLEN_T"
+	;;
+	1) AC_MSG_RESULT([no (warnings from compiler)])
+	;;
+	2) AC_MSG_RESULT(no)
+	;;
+    esac
+fi
+
+#
+# Check whether u_int should be used for xdr_array 
+use_u_int=0
+AC_MSG_CHECKING([if xdr_array wants u_int])
+PAC_TRY_COMPILE_CLEAN([#include <rpc/xdr.h>
+],[int try(void){
+u_int l, ms, el; xdrproc_t elproc; XDR *xdrs; int rc; char **arrp;
+rc = xdr_array(xdrs,arrp,&l,ms,el,elproc);
+return rc;}],use_u_int)
+case $use_u_int in 
+    0) AC_MSG_RESULT(yes)
+       MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_U_INT_FOR_XDR"
+       ;;
+    1) AC_MSG_RESULT([no (compiler warnings)])
+       ;;
+    2) AC_MSG_RESULT(no)
+       ;;
+esac
+
 if test $threaded_listener = 1 ; then
     # Try to find a thread package
     has_pthread=0
@@ -721,5 +902,7 @@ AC_SUBST(RSHCOMMAND)dnl
 AC_OUTPUT(Makefile lib/Makefile alog/Makefile usc/Makefile usc/usctest/Makefile messages/Makefile include/Makefile lib_f/Makefile contrib/Makefile contrib_f/Makefile bin/Makefile doc/Makefile messages_f/Makefile misc/Makefile monitors/Makefile servers/Makefile)
 dnl 
 dnl This code removes that stupid first line placed by ac_output
-PAC_OUTPUT_EXEC(lib/p4_config.h)
+dnl p4_config.h needs to be in the top-level directory so that VPATH will 
+dnl work correctly
+PAC_OUTPUT_EXEC(p4_config.h)
 
diff --git a/romio/Makefile.in b/romio/Makefile.in
--- a/romio/Makefile.in
+++ b/romio/Makefile.in
@@ -16,6 +16,8 @@ MPIO_DIRS   = mpi-io
 ALL_DIRS    = mpi-io mpi-io/fortran mpi2-other/info mpi2-other/info/fortran mpi2-other/array mpi2-other/array/fortran adio/common adio/ad_pfs adio/ad_piofs adio/ad_nfs adio/ad_ufs adio/ad_xfs adio/ad_hfs adio/ad_sfs test
 SHELL       = /bin/sh
 
+@VPATH@
+
 all: mpio
 
 mpio:
@@ -24,7 +26,7 @@ mpio:
 	$(MAKE) clean
 	@if test "$(NOPROFILE)" = 0 ; then\
             $(MAKE) profile; \
-        fi;
+        fi;\
 	$(MAKE) clean
 	$(RANLIB) $(LIBNAME)
 	@if test "$(FROM_MPICH)" = 0 ; then \
@@ -108,32 +110,34 @@ mpiolib:
          done
 
 profile: 
-	@dirs=`echo "$(MPIO_DIRS)"`; \
-        if test "$(BUILD_MPI_INFO)" = 1 ; then \
-            dirs=`echo "$$dirs" mpi2-other/info` ;\
-            if test "$(NOF77)" = 0 ; then\
-                dirs=`echo "$$dirs" mpi2-other/info/fortran` ;\
-            fi;\
-        fi; \
-        if test "$(BUILD_MPI_ARRAY)" = 1 ; then \
-            dirs=`echo "$$dirs" mpi2-other/array` ;\
-            if test "$(NOF77)" = 0 ; then\
-                dirs=`echo "$$dirs" mpi2-other/array/fortran` ;\
-            fi;\
-        fi; \
-        if test "$(NOF77)" = 0 ; then\
-            dirs=`echo "$$dirs" mpi-io/fortran` ;\
-        fi;\
-        for dir in $$dirs ;\
-         do \
-            echo " " ;\
-            echo building profiling interface in directory $$dir ;\
-            (cd $$dir; \
-             $(MAKE) profile MPIOPROFILE="-D__MPIO_BUILD_PROFILING";) ;\
-             if [ $$? != 0 ] ; then \
-                 echo "Make failed in directory $$dir" ; exit 1 ;\
-             fi ;\
-         done
+	@if [ "@HAS_WEAK_SYMBOLS@" = 0 ] ; then \
+           dirs=`echo "$(MPIO_DIRS)"`; \
+           if test "$(BUILD_MPI_INFO)" = 1 ; then \
+               dirs=`echo "$$dirs" mpi2-other/info` ;\
+               if test "$(NOF77)" = 0 ; then\
+                   dirs=`echo "$$dirs" mpi2-other/info/fortran` ;\
+               fi;\
+           fi; \
+           if test "$(BUILD_MPI_ARRAY)" = 1 ; then \
+               dirs=`echo "$$dirs" mpi2-other/array` ;\
+               if test "$(NOF77)" = 0 ; then\
+                   dirs=`echo "$$dirs" mpi2-other/array/fortran` ;\
+               fi;\
+           fi; \
+           if test "$(NOF77)" = 0 ; then\
+               dirs=`echo "$$dirs" mpi-io/fortran` ;\
+           fi;\
+           for dir in $$dirs ;\
+            do \
+               echo " " ;\
+               echo building profiling interface in directory $$dir ;\
+               (cd $$dir; \
+                $(MAKE) profile MPIOPROFILE="-D__MPIO_BUILD_PROFILING";) ;\
+                if [ $$? != 0 ] ; then \
+                    echo "Make failed in directory $$dir" ; exit 1 ;\
+                fi ;\
+            done \
+	fi
 
 cleanall:
 	@dirs=`echo "$(ALL_DIRS)"`; \
diff --git a/src/env/Makefile.in b/src/env/Makefile.in
--- a/src/env/Makefile.in
+++ b/src/env/Makefile.in
@@ -2,147 +2,206 @@
 #      All rights reserved.  See COPYRIGHT in top-level directory.
 #
 
-##### User configurable options #####
-
-ARCH        = @ARCH@
-DEVICE      = @DEVICE@
-MPIR_HOME   = @MPIR_HOME@
-PREFIX      = @PREFIX@
 CC          = @CC@
 F77         = @F77@
+F90         = @F90@
 AR          = @AR@
 RANLIB      = @RANLIB@
-INCLUDE_DIR = @INCLUDE_PATH@ -I../../mpid/$(DEVICE) -I../../include
-DEVICE      = @DEVICE@
 OPTFLAGS    = @OPTFLAGS@
+OPTFLAGSC   = @OPTFLAGSC@
+prefix      = @prefix@
+top_srcdir  = @top_srcdir@
+srcdir      = @srcdir@
+libbuild_dir = @libbuild_dir@
 
-### End User configurable options ###
+DEFS        = @DEFS@ ${MPIPROFILE} -I. -I${srcdir} @mpich_includes@
+CFLAGS      = @CFLAGS@ 
 
-SHELL = /bin/sh
+SHELL       = /bin/sh
 
-MPI_INCLUDE    = ../../include/mpi.h
-DEVICE_LIB = 
-CFLAGS = @CFLAGS@ $(OPTFLAGS) @OPTFLAGSC@ $(INCLUDE_DIR) -DMPI_$(ARCH) \
-	$(MPIPROFILE)
-FFLAGS = @FFLAGS@ $(OPTFLAGS) @OPTFLAGSF@
-LIBS = ../../build/$(ARCH)/$(DEVICE)/lib/lib@MPILIBNAME@.a $(DEVICE_LIB)
+@VPATH@
+
+.SUFFIXES:
+.SUFFIXES: .o .c .f
+
+LIBS = ${libbuild_dir}/lib@MPILIBNAME@.a
+
+FFLAGS = @FFLAGS@ ${OPTFLAGS} @OPTFLAGSF@
+
 MPI_FOBJECTS = farg.o initfcmn.o initfdte.o
-MPI_COBJECTS = abort.o debugutil.o init.o initutil.o finalize.o initialize.o \
+MPI_COBJECTS = abort.o debugutil.o init.o initthread.o initutil.o \
+	finalize.o initialize.o \
 	errorstring.o fstrutils.o initdte.o \
 	getpname.o errcreate.o errset.o errget.o errfree.o errclass.o \
-	wtime.o wtick.o errmsg.o getversion.o msgqdllloc.o
+	wtime.o wtick.o nerrmsg.o getversion.o msgqdllloc.o
 MPI_FSOURCES = farg.f initfcmn.f initfdte.f
-MPI_CSOURCES = abort.c debugutil.c init.c initutil.c \
+MPI_CSOURCES = abort.c debugutil.c init.c initthread.c initutil.c \
 	finalize.c fstrutils.c initialize.c errorstring.c initdte.c \
 	getpname.c errcreate.c errset.c errget.c errfree.c errclass.c \
-	wtime.c wtick.c errmsg.c getversion.c msgqdllloc.c
+	wtime.c wtick.c nerrmsg.c getversion.c msgqdllloc.c
 MPI_TSOURCES = errclass.c 
 MPI_WSOURCES = abortf.c finalizef.c errclassf.c
 MPI_WOBJECTS = initializef.o abortf.o initf.o finalizef.o errorstringf.o \
 	getpnamef.o errcreatef.o errsetf.o errgetf.o errfreef.o errclassf.o \
 	wtimef.o wtickf.o getversionf.o
 
-MPI_SOURCES = $(MPI_CSOURCES) $(MPI_WSOURCES)
-MPI_OBJECTS = $(MPI_COBJECTS) $(MPI_WOBJECTS)
+MPI_SOURCES = ${MPI_CSOURCES} ${MPI_WSOURCES}
+MPI_OBJECTS = ${MPI_COBJECTS} ${MPI_WOBJECTS}
 
-default: setlinks ../../build/$(ARCH)/$(DEVICE)/lib/lib@MPILIBNAME@.a
+default: ${libbuild_dir}/lib@MPILIBNAME@.a
+	if [ -n "@MPI_FOBJECTS@" ] ; then \
+	@MAKE@ ${libbuild_dir}/lib@MPILIBNAME@f.a ; fi
 
-profile: ../../build/$(ARCH)/$(DEVICE)/lib/libp@MPILIBNAME@.a
 
-wrapperlib: $(MPI_WOBJECTS)
-	$(AR) ../../build/$(ARCH)/$(DEVICE)/lib/libf@MPILIBNAME@.a $?	
+profile: ${libbuild_dir}/libp@MPILIBNAME@.a
+
+wrapperlib: ${MPI_WOBJECTS}
+	${AR} ${libbuild_dir}/libf@MPILIBNAME@.a $?	
 
 # default_all is the same as default, but without the RANLIB.  This
 # can speed up the build (ranlibs can take a LONG time).  profile_all 
 # is the same, but for the profile library
-default_all: setlinks default_objs
-default_objs: $(MPI_OBJECTS) @MPI_FOBJECTS@ @MPE_MPI_EXT_O@
-	$(AR) ../../build/$(ARCH)/$(DEVICE)/lib/lib@MPILIBNAME@.a $?
-profile_all: $(MPI_OBJECTS) @MPI_FOBJECTS@
-	$(AR) ../../build/$(ARCH)/$(DEVICE)/lib/libp@MPILIBNAME@.a $?
+default_all: default_objs
+default_objs: ${MPI_OBJECTS} @MPI_FOBJECTS@ 
+	${AR} ${libbuild_dir}/lib@MPILIBNAME@.a $?
+	if [ -n "@MPI_FOBJECTS@" ] ; then \
+	@MAKE@ ${libbuild_dir}/lib@MPILIBNAME@f.a ; fi
+profile_all: ${MPI_OBJECTS} @MPI_FOBJECTS@
+	${AR} ${libbuild_dir}/libp@MPILIBNAME@.a $?
 
-$(MPI_OBJECTS) :  $(MPI_INCLUDE)
-$(MPI_FOBJECTS) :  $(MPI_INCLUDE)
+${MPI_OBJECTS} :  ${MPI_INCLUDE}
+${MPI_FOBJECTS} :  ${MPI_INCLUDE}
+
+mpe_debug_objs: @MPE_MPI_EXT_O@
+	${AR} ${libbuild_dir}/lib@MPILIBNAME@.a @MPE_MPI_EXT_O@
+	${RANLIB} ${libbuild_dir}/lib@MPILIBNAME@.a
 
 # 
 # This is needed for initutil.c
-setlinks:
-	if [ ! -s ../../include/mpeexten.h ] ; then \
-	    (cd ../../include ; ln -s ../mpe/mpeexten.h mpeexten.h ) ; fi
-	if [ ! -s mpehname.c ] ; then \
-	    ln -s ../../mpe/mpehname.c mpehname.c ; fi
-#	if [ ! -s dbxerr.c ] ; then \
-#	    ln -s ../../mpe/dbxerr.c dbxerr.c ; fi
-#wrappers:
-#	-/bin/rm -f $(MPI_WSOURCES)
-#	../../util/bfort -ferr -mpi -mnative -mapptr -ptrprefix MPIR_ \
-#		-anyname -I pubinc $(MPI_TSOURCES)	
+#setlinks:
+#	if [ ! -s ${top_srcdir}/include/mpeexten.h ] ; then \
+#	    (cd ${top_srcdir}/include ; \
+#		ln -s ${top_srcdir}/mpe/mpeexten.h mpeexten.h ) ; fi
 
 source_names:
-	@echo $(MPI_CSOURCES)
+	@echo ${MPI_CSOURCES}
 
 #
 # This gives -mpiversion the ability to echo the configuration arguments.
-initutil.o: initutil.c
-	$(CC) $(CFLAGS) -c -DCONFIGURE_ARGS_CLEAN='"@CONFIGURE_ARGS_CLEAN@"' \
-	-DMPIRUN_MACHINE='"@DEFAULT_MACHINE@"' \
-	-DMPIRUN_DEVICE='"@DEVICE@"' \
-	initutil.c
+#initutil.o: ${srcdir}/initutil.c
+#	${CC} ${DEFS} ${INCLUDES} ${CFLAGS} -c \
+#	-DCONFIGURE_ARGS_CLEAN='"@CONFIGURE_ARGS_CLEAN@"' \
+#	-DMPIRUN_MACHINE='"@DEFAULT_MACHINE@"' \
+#	-DMPIRUN_DEVICE='"@DEVICE@"' \
+#	${srcdir}/initutil.c
+
+mpich.En_US.cat: ${srcdir}/mpich.En_US.msg
+	@GENCAT@ mpich.En_US.cat ${srcdir}/mpich.En_US.msg
+
+# Create the message catalog files.  This will add ALL files, including the
+# US English one
+# The .m files are requires on IRIX and perhaps other platforms
+# The files are put into the libbuild directory when building.  When
+# installing, they are put into messagecat_dir.
+message_cat: mpich.En_US.cat
+	for file in ${srcdir}/mpich.*.msg ; do \
+	fileroot=`basename $file .msg` ; \
+	/bin/rm -f $fileroot.cat $fileroot.cat.m ; \
+	@GENCAT@ $fileroot.cat $file > /dev/null 2>&1 ; \
+	if test -s $fileroot.cat ; then \
+	    /bin/rm -f ${libbuild_dir}/$fileroot.cat ; \
+	    cp $fileroot.cat ${libbuild_dir} ; \
+	fi ; \
+	if test -s $fileroot.cat.m ; then \
+	    /bin/rm -f ${libbuild_dir}/$fileroot.cat.m ; \
+	    cp $fileroot.cat.m ${libbuild_dir} ; \
+	fi ; \
+	done )
+	if test -s mpich.En_US.cat ; then \
+	    if test ! -s ${libbuild_dir}/mpich.cat ; then \
+	       (cd ${libbuild_dir} ; ln -s mpich.En_US.cat mpich.cat ) \
+	    fi \
+	else \
+	    echo "Could not create catalog. US English messages will be used" ; \
+	fi
+
 #
 # We should really put this entire directory AFTER src/infoexport; then we
 # can test on the existance of the library.  
 # We use PREFIX instead of MPIR_HOME so that the result of installing
 # the MPI libraries will work
-msgqdllloc.o: msgqdllloc.c
+msgqdllloc.o: ${top_srcdir}/src/env/msgqdllloc.c
 	if test -n "@SHAREDKIND_FOR_TV@" -a "@SHAREDKIND_FOR_TV@" != "ignore" ; then \
 	  if test -n "@PREFIX@" ; then \
-	      $(CC) $(CFLAGS) @CC_SHARED_OPT_FOR_TV@ -c \
-	  -DMPICH_INFODLL_LOC='"@PREFIX@/build/$(ARCH)/$(DEVICE)/lib/libtvmpich.so"' \
-		  msgqdllloc.c ; \
+	      ${CC} ${DEFS} ${CFLAGS} @CC_SHARED_OPT_FOR_TV@ -c \
+	  -DMPICH_INFODLL_LOC='"@PREFIX@/build/${ARCH}/${DEVICE}/lib/libtvmpich.so"' \
+		  ${top_srcdir}/src/env/msgqdllloc.c ; \
 	  else \
-	      $(CC) $(CFLAGS) -c @CC_SHARED_OPT_FOR_TV@ \
-	  -DMPICH_INFODLL_LOC='"@MPIR_HOME@/build/$(ARCH)/$(DEVICE)/lib/libtvmpich.so"' \
-		  msgqdllloc.c ; \
+	      ${CC} ${DEFS} ${CFLAGS} -c @CC_SHARED_OPT_FOR_TV@ \
+	  -DMPICH_INFODLL_LOC='"@MPIR_HOME@/build/${ARCH}/${DEVICE}/lib/libtvmpich.so"' \
+		  ${top_srcdir}/src/env/msgqdllloc.c ; \
 	  fi \
 	else \
-	    $(CC) $(CFLAGS) -c msgqdllloc.c ; \
+	    ${CC} ${DEFS} ${CFLAGS} -c ${top_srcdir}/src/env/msgqdllloc.c ; \
 	fi
 .c.o:
-	$(CC) $(CFLAGS) -c $*.c
+	${CC} ${DEFS} ${INCLUDES} ${CFLAGS} ${OPTFLAGSC} ${OPTFLAGS} -c $<
+# For VPATH builds, some Fortran compilers use the directory of the file 
+# rather than the directory of the build.
 .f.o:
-	$(F77) $(FFLAGS) -c $*.f
+	if [ -n "@FINCARG@" ] ; then \
+	    ${F77} @FINCARG@. ${FFLAGS} -c $< ; \
+	else \
+	    if [ ! -s $*.f ] ; then cp $< . ; fi ; \
+	    ${F77} ${FFLAGS} -c $*.f ; \
+	fi
 
 # Always compile this with -g
 # Warning: some systems might not support -g.  We'll deal with that when
 # we have to.  We use the part of CFLAGS that does not include the
 # optimization switches.
-debugutil.o: debugutil.c
-	$(CC) -g @CFLAGS@ $(INCLUDE_DIR) -DMPI_$(ARCH) $(MPIPROFILE) -c \
-		debugutil.c
+debugutil.o: ${srcdir}/debugutil.c
+	${CC} -g ${DEFS} ${INCLUDES} @CFLAGS@ ${INCLUDE_DIR} ${MPIPROFILE} -c \
+		${srcdir}/debugutil.c
 
 # GETNAME_DEFS are needed by mpehname.c; these need mpe includes
-mpehname.o: mpehname.c
-	$(CC) $(CFLAGS) @GETNAME_DEFS@ -c -I../../mpe mpehname.c 
+mpehname.o: ${top_srcdir}/mpe/mpehname.c
+	${CC} ${DEFS} ${CFLAGS} @GETNAME_DEFS@ -c -I${top_srcdir}/mpe \
+		${top_srcdir}/mpe/mpehname.c 
 # Note that we remove the link after we use it.
-#dbxerr.o: dbxerr.c
-#	$(CC) $(CFLAGS) @GETNAME_DEFS@ -c -I../../mpe dbxerr.c 
-#	rm -f dbxerr.c
+dbxerr.o: ${top_srcdir}/mpe/dbxerr.c
+	${CC} ${DEFS} ${CFLAGS} @GETNAME_DEFS@ -c -I${top_srcdir}/mpe \
+		${top_srcdir}/mpe/dbxerr.c 
+	rm -f dbxerr.c
 # errmsg needs to know about NLS definitions.
-errmsg.o: errmsg.c
-	$(CC) $(CFLAGS) @NLS_DEFS@ -c errmsg.c
+nerrmsg.o: ${srcdir}/nerrmsg.c mpierrstrings.h
+	${CC} ${DEFS} ${CFLAGS} @NLS_DEFS@ -c ${srcdir}/nerrmsg.c
 
-../../build/$(ARCH)/$(DEVICE)/lib/lib@MPILIBNAME@.a: \
-		$(MPI_OBJECTS) @MPI_FOBJECTS@ @MPE_MPI_EXT_O@
-	$(AR) $@ $?
-	$(RANLIB) $@
+farg90.o: ${srcdir}/farg90.f
+	@if [ -n "$(F90)" ] ; then \
+	  $(F90) -c ${FFLAGS} ${srcdir}/farg90.f ; \
+	  cp farg90.o ${libbuild_dir} ; \
+	fi
 
-../../build/$(ARCH)/$(DEVICE)/lib/libp@MPILIBNAME@.a: $(MPI_OBJECTS) @MPI_FOBJECTS@
-	$(AR) $@ $?
-	$(RANLIB) $@
+${libbuild_dir}/lib@MPILIBNAME@.a: \
+		${MPI_OBJECTS} @MPI_FOBJECTS@ 
+	${AR} $@ $?
+	${RANLIB} $@
+
+${libbuild_dir}/libp@MPILIBNAME@.a: ${MPI_OBJECTS} @MPI_FOBJECTS@
+	${AR} $@ $?
+	${RANLIB} $@
+# This library is created to contain ONLY the Fortran MPI_Init and
+# called routines.  This is needed for shared library support.
+${libbuild_dir}/lib@MPILIBNAME@f.a: initf.o farg.o
+	${AR} $@ initf.o farg.o
+	${RANLIB} $@
 tstmsg:
-	$(CC) $(CFLAGS) -DTEST_MSGS @NSL_DEFS@ -c errmsg.c
-	@CLINKER@ -o errmsg errmsg.o \
-		../../build/$(ARCH)/$(DEVICE)/lib/lib@MPILIBNAME@.a
-	/bin/rm -f errmsg.o
+	${CC} ${CFLAGS} -DTEST_MSGS @NLS_DEFS@ -c nerrmsg.c
+	@CLINKER@ -o nerrmsg nerrmsg.o ${libbuild_dir}/lib@MPILIBNAME@.a
+	/bin/rm -f nerrmsg.o
+
+# We need to clean the srcdir of any .o files because they can confuse the
+# VPATH build process
 clean:
-	/bin/rm -f *.o *~ errmsg
+	/bin/rm -f *.o *~ ${srcdir}/*.o
diff --git a/util/mpireconfig.in b/util/mpireconfig.in
--- a/util/mpireconfig.in
+++ b/util/mpireconfig.in
@@ -1,5 +1,21 @@
 #! /bin/sh
-CONFIG_FILES="$*"
+#
+# For "inplace" usage of config.status, we need srcdir to be "."
+# Hmmmm
+CONFIG_FILES=""
+destpair=""
+for arg 
+do
+    if [ -s $arg.in ] ; then 
+        CONFIG_FILES="$CONFIG_FILES $arg" 
+    elif [ -s #top_srcdir#/$arg.in ] ; then
+        CONFIG_FILES="$CONFIG_FILES #top_srcdir#/$arg" 
+	destpair="$destpair #top_srcdir#/$arg::$arg"
+    else
+        echo "Cannot find file $arg"
+	exit 1
+    fi
+done
 export CONFIG_FILES
 PREFIX="#PREFIX#"
 #
@@ -13,7 +29,22 @@ PREFIX="#PREFIX#"
 # but I've lost the example that made me suggest this.
 # 
 # First, try the device/architecture specific config.status
-if [ -s #MPIR_HOME#/build/#ARCH#/#DEVICE#/bin/config.status ] ; then 
+# Our first try is for the mpireconfig.dat in the same directory as this script
+# came from if it is specifically set.
+mydir=`echo $0 | sed 's%/[^/][^/]*$%%'`
+if [ -x $mydir/mpireconfig.dat ] ; then
+    CONFIG_HEADERS=""
+    export CONFIG_HEADERS
+    $mydir/mpireconfig.dat 
+elif [ -x #bindir#/mpireconfig.dat ] ; then
+    CONFIG_HEADERS=""
+    export CONFIG_HEADERS
+    #bindir#/mpireconfig.dat 
+elif [ -x #binbuild_dir#/mpireconfig.dat ] ; then
+    CONFIG_HEADERS=""
+    export CONFIG_HEADERS
+    #binbuild_dir#/mpireconfig.dat 
+elif [ -x #MPIR_HOME#/build/#ARCH#/#DEVICE#/bin/config.status ] ; then 
     # Export the location of mpichconf.h.in
     #CONFIG_HEADERS="#MPIR_HOME#/build/#ARCH#/#DEVICE#/include/mpichconf.h"
     # In fact, we DO NOT want to recreate mpichconf.h  We must
@@ -21,14 +52,20 @@ if [ -s #MPIR_HOME#/build/#ARCH#/#DEVICE#/bin/config.status ] ; then
     CONFIG_HEADERS=""
     export CONFIG_HEADERS
     #MPIR_HOME#/build/#ARCH#/#DEVICE#/bin/config.status
-elif [ -s #MPIR_HOME#/config.status ] ; then
+elif [ -x #MPIR_HOME#/config.status ] ; then
     # Export the location of mpichconf.h.in
     #CONFIG_HEADERS="#MPIR_HOME#/mpichconf.h"
     CONFIG_HEADERS=""
     export CONFIG_HEADERS
     #MPIR_HOME#/config.status
 else
-    echo "A config.status file is needed to perform a reconfig of a file"
+    echo "An mpireconfig.dat file is needed to perform a reconfig of a file"
     exit 1
 fi
-
+if [ -n "$destpair" ] ; then
+    # Move created files to their final places
+    for pair in $destpair ; do
+	stmt=`echo "$pair" | sed 's/::/ /'`
+        eval mv $stmt
+    done
+fi
