1.2.1

diff --git a/examples/test/pt2pt/Makefile.in b/examples/test/pt2pt/Makefile.in
--- a/examples/test/pt2pt/Makefile.in
+++ b/examples/test/pt2pt/Makefile.in
@@ -12,7 +12,6 @@ F90          = @MPIF90@
 FLINKER      = @MPIF77@
 OPTFLAGS     = @OPTFLAGS@
 MPIFDEP      = @MPIFDEP@
-F77_OPTFLAGS = @F77_EXTRA_FLAG@
 ### End User configurable options ###
 
 SHELL = /bin/sh
@@ -32,15 +31,15 @@ FLIBS = @FLIB_PATH@ @LIB_LIST@
 EXECS = overtake sendrecv isndrcv third fourth fifth sixth hvectest \
 	hvectest2 hvec probe probe1 testtest1 ssendtest ssendtest2 typetest\
 	dtypelife issendtest issend2 issendinit relrank nullproc trunc \
-	truncmult typeub typeub2 typeub3 irecvtest htmsg \
+	truncmult typeub typeub2 typeub3 irecvtest htmsg nullproc2 \
 	isendtest self sendrecv2 sendrecv3 sendrecv4 persistent waitany \
 	pack bsendtest typebase irsend irsendinit longmsgs waitall waitall2 \
 	testsome getelm testall sndrcv nbtest nblock sendmany order hindexed \
 	commit cancel persist typecreate reqcreate sndrcvrep flood flood2 \
 	persist2 dataalign dtyperecv reqfree sndrcvrpl2 cancel2 cancel3 \
-	cancelmessages cancelibm sendorder exittest
+	cancelmessages cancelibm sendorder exittest selfvsworld
 OTHEREXECS = testtypes secondf allpair systest send1 \
-		systest1 allpair2 bsendtest structf typebasef 
+		systest1 allpair2 bsendtest structf typebasef sendfort bcastf
 default: $(EXECS)
 
 #
@@ -54,11 +53,13 @@ linktest:
 	@if [ ! -x overtake ] ; then \
 	    echo "Could not link a C program with MPI libraries" ; \
 	    exit 1 ; fi
-	-$(MAKE) secondf
-	@if [ ! -x secondf ] ; then \
-	    echo "Could not link a Fortran program with MPI libraries" ; \
-	    exit 1 ; fi
 	$(MAKE) clean
+#
+# This now becomes part of the Fortran module
+#	-$(MAKE) secondf
+#	@if [ ! -x secondf ] ; then \
+#	    echo "Could not link a Fortran program with MPI libraries" ; \
+#	    exit 1 ; fi
 
 linktest1: 
 	-$(MAKE) overtake
@@ -69,7 +70,8 @@ linktest1:
 
 all: testing
 
-fortran_tests: secondf allpair allpair2 structf typebasef send1 pingpong
+fortran_tests: secondf allpair allpair2 structf typebasef send1 pingpong \
+	sendfort
 
 #f90_tests: secondf90 allpair90 allpair290 structf90 typebasef90 send190 \
 #	pingpong90
@@ -161,8 +163,11 @@ reqfree: reqfree.o
 isndrcv: isndrcv.o test.o
 	$(CLINKER) $(OPTFLAGS) -o isndrcv isndrcv.o test.o $(LIBS)
 
-nullproc: nullproc.o test.o
-	$(CLINKER) $(OPTFLAGS) -o nullproc nullproc.o test.o $(LIBS)
+nullproc: nullproc.o
+	$(CLINKER) $(OPTFLAGS) -o nullproc nullproc.o $(LIBS)
+
+nullproc2: nullproc2.o
+	$(CLINKER) $(OPTFLAGS) -o nullproc2 nullproc2.o $(LIBS)
 
 trunc: trunc.o
 	$(CLINKER) $(OPTFLAGS) -o trunc trunc.o $(LIBS)
@@ -293,6 +298,9 @@ sendorder: sendorder.o
 exittest: exittest.o
 	$(CLINKER) $(OPTFLAGS) -o exittest exittest.o $(LIBS)
 
+selfvsworld: selfvsworld.o
+	$(CLINKER) $(OPTFLAGS) -o selfvsworld selfvsworld.o $(LIBS)
+
 # This has a test for HAS_FORTRAN so that the link test target will work
 # even when -nof77 is selected.
 secondf: $(MPIFDEP) secondf.o
@@ -311,6 +319,9 @@ structf: $(MPIFDEP) structf.o
 send1: $(MPIFDEP) send1.o
 	$(FLINKER) $(OPTFLAGS) -o ./send1 send1.o $(FLIBS)
 
+sendfort: $(MPIFDEP) sendfort.o
+	$(FLINKER) $(OPTFLAGS) -o ./sendfort sendfort.o $(FLIBS)
+
 pingpong: $(MPIFDEP) pingpong.o
 	$(FLINKER) $(OPTFLAGS) -o ./pingpong pingpong.o $(FLIBS)
 
@@ -321,7 +332,7 @@ typebasef: $(MPIFDEP) typebasef.o
 # Make sure that we remove executables for specific architectures
 clean:
 	@-/bin/rm -f *.o *~ PI* $(EXECS) *.out core pt2pt.diff $(OTHEREXECS) \
-		*.trace rdb.* startup.* mpif.h ${srcdir}/*.o
+		*.trace rdb.* startup.* mpif.h ${srcdir}/*.o *.stdo
 	@-for file in $(EXECS) Makefile ; do \
 	   /bin/rm -f $$file.sun4 $$file.alpha $$file.IRIX $$file.freebsd ;\
 	done
@@ -329,4 +340,4 @@ clean:
 .c.o:
 	$(CC) $(CFLAGS) -c $<
 .f.o:
-	$(F77) $(FFLAGS) $(F77_OPTFLAGS) -c $<
+	$(F77) $(FFLAGS) -c $<
diff --git a/f90modules/CreateChoiceSrc b/f90modules/CreateChoiceSrc
--- a/f90modules/CreateChoiceSrc
+++ b/f90modules/CreateChoiceSrc
@@ -1,5 +1,10 @@
 #! /bin/sh
 #
+# Change to the naming convention
+# To make life easier on systems with short variable names, we make the
+# file names use just the first two characters of the type, e.g., 
+# re (real), lo (logical), in (integer), co (complex)
+#
 choicetype="traditional"
 F90SUFFIX=f90
 for arg in "$@" ; do
@@ -56,11 +61,12 @@ if [ -z "$types" ] ; then
 fi
 rm -f mpi.add
 if [ -z "$types" ] ; then
-    echo "Could not determine types!"
+    echo "Could not determine types for type $choicetype!"
     if [ -s kinderr.log ] ; then
         echo "Log of make attempts to build test programs follows"
 	cat kinderr.log
     fi
+    exit 1
 fi
 echo "Types are $types"
 for type in $types ; do
@@ -70,35 +76,38 @@ for type in $types ; do
       f90typestring=`echo $type | \
          sed -e 's/\([a-z]*\)\([0-9][0-9]*\)/\1 (KIND=\2)/'`
     fi
-    rm -f mpi1__${type}_v.${F90SUFFIX} mpi1__${type}_s.${F90SUFFIX} mpi1__${type}_sv.${F90SUFFIX} \
-	mpi1__${type}_vs.${F90SUFFIX}
-    rm -f mpi2__${type}_v.${F90SUFFIX} mpi2__${type}_s.${F90SUFFIX} mpi2__${type}_sv.${F90SUFFIX} \
-	mpi2__${type}_vs.${F90SUFFIX}
+    # Convert type name to ccnnn
+    typename=`echo A$type | sed 's/^A\(..\)[^0-9]*\([0-9]*\)/\1\2/'`
+    #
+    rm -f mpi1__${typename}_v.${F90SUFFIX} mpi1__${typename}_s.${F90SUFFIX} mpi1__${typename}_sv.${F90SUFFIX} \
+	mpi1__${typename}_vs.${F90SUFFIX}
+    rm -f mpi2__${typename}_v.${F90SUFFIX} mpi2__${typename}_s.${F90SUFFIX} mpi2__${typename}_sv.${F90SUFFIX} \
+	mpi2__${typename}_vs.${F90SUFFIX}
     TYPEUC=`echo $type | tr '[a-z]' '[A-Z]'`
     # Create the files
     sed -e "s/MODULE MPI1__<type>_v/MODULE MPI1__${TYPEUC}_V/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_v.f90 > mpi1__${type}_v.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_v.f90 > mpi1__${typename}_v.${F90SUFFIX}
     sed -e "s/MODULE MPI1__<type>_s/MODULE MPI1__${TYPEUC}_S/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_s.f90 > mpi1__${type}_s.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_s.f90 > mpi1__${typename}_s.${F90SUFFIX}
     sed -e "s/MODULE MPI1__<type>_vs/MODULE MPI1__${TYPEUC}_VS/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_vs.f90 > mpi1__${type}_vs.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_vs.f90 > mpi1__${typename}_vs.${F90SUFFIX}
     sed -e "s/MODULE MPI1__<type>_sv/MODULE MPI1__${TYPEUC}_SV/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_sv.f90 > mpi1__${type}_sv.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_sv.f90 > mpi1__${typename}_sv.${F90SUFFIX}
     sed -e "s/MODULE MPI1__<type>_v2/MODULE MPI1__${TYPEUC}_V2/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_v2.f90 > mpi1__${type}_v2.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi1__type_v2.f90 > mpi1__${typename}_v2.${F90SUFFIX}
 
     sed -e "s/MODULE MPI2__<type>_v/MODULE MPI2__${TYPEUC}_V/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_v.f90 > mpi2__${type}_v.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_v.f90 > mpi2__${typename}_v.${F90SUFFIX}
     sed -e "s/MODULE MPI2__<type>_s/MODULE MPI2__${TYPEUC}_S/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_s.f90 > mpi2__${type}_s.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_s.f90 > mpi2__${typename}_s.${F90SUFFIX}
 # Until we change the exclude file, these two modules are empty.  Some
 # compilers will complain about the empty modules
 #    sed -e "s/MODULE MPI2__<type>_vs/MODULE MPI2__${TYPEUC}_VS/g" \
-#        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_vs.f90 > mpi2__${type}_vs.${F90SUFFIX}
+#        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_vs.f90 > mpi2__${typename}_vs.${F90SUFFIX}
 #    sed -e "s/MODULE MPI2__<type>_sv/MODULE MPI2__${TYPEUC}_SV/g" \
-#        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_sv.f90 > mpi2__${type}_sv.${F90SUFFIX}
+#        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_sv.f90 > mpi2__${typename}_sv.${F90SUFFIX}
     sed -e "s/MODULE MPI2__<type>_v2/MODULE MPI2__${TYPEUC}_V2/g" \
-        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_v2.f90 > mpi2__${type}_v2.${F90SUFFIX}
+        -e "s/<type>/$f90typestring/g" ${srcdir}/mpi2__type_v2.f90 > mpi2__${typename}_v2.${F90SUFFIX}
     # Add them to the mpi.f90 file
     echo "        USE MPI1__${TYPEUC}_V"  >>mpi.add
     echo "        USE MPI1__${TYPEUC}_VS" >>mpi.add
diff --git a/mpe/contrib/test/Makefile.in b/mpe/contrib/test/Makefile.in
--- a/mpe/contrib/test/Makefile.in
+++ b/mpe/contrib/test/Makefile.in
@@ -1,83 +1,100 @@
 
 ##### User configurable options #####
 
-CC          = @MPI_CC@
-F77         = @MPI_F77@
-CLINKER     = $(CC)
-FLINKER     = $(F77)
-MAKE        = @MAKE@
-OPTFLAGS    = @OPTFLAGS@
-#
-DEBUG_LIBS  = @DEBUG_LIBS@
-MPI_INC     = @MPI_INC@
-MPI_LIBS    = @MPI_LIBS@
-LIB_PATH    = -L@MPE_LIBPATH@ -lmpe @X_LIB@ $(MPI_LIBS) -lm 
-FLIB_PATH   = @EXTRA_FLIB@ @FLIB_PATH_LEADER@@MPE_LIBPATH@ @FLIBS@ $(MPI_LIBS)
-MPE_DIR     = @MPE_HOME@
-LOG_LIB     = -L@MPE_LIBPATH@ @LOGLIB@ $(MPI_LIBS)
-TRACE_LIB   = -L@MPE_LIBPATH@ @TRACELIB@ $(MPI_LIBS)
-ANIM_LIB    = -L@MPE_LIBPATH@ @ANIMLIB@ $(MPI_LIBS)
-PROF_LIB    = -L@MPE_LIBPATH@ @PROFLIB@ $(MPI_LIBS)
-#
-INCLUDE_DIR = @INCLUDEDIR@ -I$(MPE_DIR) $(MPI_INC)
-LDFLAGS     = @OPTFLAGS@
-NO_X        = @NO_X@
-NOF77       = @NOF77@
+MAKE          = @MAKE@
 
-RM          = rm
+MPI_CC        = @MPI_CC@
+MPI_F77       = @MPI_F77@
+MPI_CLINKER   = $(MPI_CC)
+MPI_FLINKER   = $(MPI_F77)
+#
+DEBUG_LIBS    = @DEBUG_LIBS@
+MPI_INC       = @MPI_INC@
+MPI_LIBS      = @MPI_LIBS@
+MPE_CFLAGS    = @MPE_CFLAGS@
+MPE_FFLAGS    = @MPE_FFLAGS@
+MPE_INCDIR    = @includebuild_dir@
+MPE_LIBDIR    = @libbuild_dir@
+PROF_LIBS     = -L$(MPE_LIBDIR) @PROF_LIBS@ $(MPI_LIBS)
+LOG_LIBS      = -L$(MPE_LIBDIR) @LOG_LIBS@ $(MPI_LIBS)
+TRACE_LIBS    = -L$(MPE_LIBDIR) @TRACE_LIBS@ $(MPI_LIBS)
+ANIM_LIBS     = -L$(MPE_LIBDIR) @ANIM_LIBS@ $(MPI_LIBS)
+F2CMPI_LIBS   = @F2CMPI_LIBS@
+FLIB_PATH     = @FLIB_PATH_LEADER@$(MPE_LIBDIR) $(F2CMPI_LIBS) @LOG_LIBS@ \
+                $(MPI_LIBS)
+#
+INCLUDE_DIR   = -I$(MPE_INCDIR) $(MPI_INC)
+LDFLAGS       = @LDFLAGS@
+NO_X          = @NO_X@
+NOF77         = @NOF77@
+RM            = /bin/rm
 
 ### End User configurable options ###
 
 @VPATH@
-top_srcdir = @top_srcdir@
-srcdir     = @srcdir@
 
-CFLAGS  = @MPE_CFLAGS@ $(OPTFLAGS) $(INCLUDE_DIR) 
-FFLAGS  = @MPE_FFLAGS@ $(OPTFLAGS) $(INCLUDE_DIR)
-EXECS   = cpilog cpi fpilog
+srcdir        = @srcdir@
+
+CFLAGS        = $(MPE_CFLAGS) $(INCLUDE_DIR) 
+FFLAGS        = $(MPE_FFLAGS) $(INCLUDE_DIR)
+CC_LDFLAGS    = $(LDFLAGS) $(MPE_CFLAGS)
+FC_LDFLAGS    = $(LDFLAGS) $(MPE_FFLAGS)
+EXECS         = cpilog srtest
+
+
+.c.o:
+	$(MPI_CC) $(CFLAGS) -c $<
+.f.o:
+	$(MPI_F77) $(FFLAGS) -c $<
 
 default: $(EXECS)
+	-if [ $(NOF77) = 0 ] ; then \
+	     $(MAKE) fpilog ; \
+	 fi
 
 cpi_log: cpi.o
-	$(CLINKER) $(LDFLAGS) -o cpi_log cpi.o $(LOG_LIB) $(DEBUG_LIBS) -lm
+	$(MPI_CLINKER) $(CC_LDFLAGS) -o $@ $? $(LOG_LIBS) $(DEBUG_LIBS) -lm
 
 cpi_trace: cpi.o
-	$(CLINKER) $(LDFLAGS) -o cpi_trace cpi.o $(TRACE_LIB) $(DEBUG_LIBS) -lm
+	$(MPI_CLINKER) $(CC_LDFLAGS) -o $@ $? $(TRACE_LIBS) $(DEBUG_LIBS) -lm
 
 cpi_anim: cpi.o
-	$(CLINKER) $(LDFLAGS) -o cpi_anim cpi.o $(ANIM_LIB) $(DEBUG_LIBS) -lm 
+	$(MPI_CLINKER) $(CC_LDFLAGS) -o $@ $? $(ANIM_LIBS) $(DEBUG_LIBS) -lm 
 
-cpilog.o: ${srcdir}/cpilog.c
-	$(CC) $(CFLAGS) -DUSE_GRAPHICS -o cpilog.o -c ${srcdir}/cpilog.c
-
-cpilog: cpilog.o $(MPE_DIR)/mpe.h
-	$(CLINKER) $(LDFLAGS)  -o cpilog cpilog.o $(LOG_LIB) $(DEBUG_LIBS) -lm 
+cpilog: cpilog.o
+	$(MPI_CLINKER) $(CC_LDFLAGS)  -o $@ $? $(LOG_LIBS) $(DEBUG_LIBS) -lm 
 
 fpilog: fpi.o
-	$(FLINKER) $(OPTFLAGS) -o fpilog fpi.o $(FLIB_PATH) $(DEBUG_LIBS) -lm
+	$(MPI_FLINKER) $(FC_LDFLAGS) -o $@ $? $(FLIB_PATH) $(DEBUG_LIBS) -lm
 
+srtest: srtest.o
+	$(MPI_CLINKER) $(CC_LDFLAGS)  -o $@ $? $(LOG_LIBS) $(DEBUG_LIBS) -lm 
+	
 linktest: linktest_C
 
 linktest_C: 
-	@-echo "** Testing if C application can be linked with logging library" ; \
+	@-echo ; \
+	echo "** Testing if C application can be linked with logging library" ; \
 	$(RM) -f cpi_log ; \
 	$(MAKE) cpi_log ; \
 	if test -x cpi_log ; then \
 	    echo "** C application can be linked with logging library" ; \
 	    $(RM) -f cpi_log ; \
 	else \
-	    echo "** C application cannot be linked with logging library" ; \
+	    echo "** C application CANNOT be linked with logging library" ; \
 	fi 
-	@-echo "** Testing if C application can be linked with tracing library" ; \
+	@-echo ; \
+	echo "** Testing if C application can be linked with tracing library" ; \
 	$(RM) -f cpi_trace ; \
 	$(MAKE) cpi_trace ; \
 	if test -x cpi_trace ; then \
 	    echo "** C application can be linked with tracing library" ; \
 	    $(RM) -f cpi_trace ; \
 	else \
-	    echo "** C application cannot be linked with tracing library" ; \
+	    echo "** C application CANNOT be linked with tracing library" ; \
 	fi 
 	@-if [ $(NO_X) = 0 ] ; then \
+	    echo ; \
 	    echo "** Testing if C application can be linked with animation library" ; \
 	    $(RM) -f cpi_anim ; \
 	    $(MAKE) cpi_anim ; \
@@ -85,38 +102,38 @@ linktest_C:
 	        echo "** C application can be linked with animation library" ; \
 	        $(RM) -f cpi_anim ; \
 	    else \
-	        echo "** C application cannot be linked with animation library" ; \
+	        echo "** C application CANNOT be linked with animation library" ; \
 	    fi \
 	fi  
-	@-echo "** Testing if C application can use both automatic and manual logging together" ; \
+	@-echo ; \
+	echo "** Testing if C application can use both automatic and manual logging together" ; \
 	$(RM) -f cpilog ; \
 	$(MAKE) cpilog ; \
 	if test -x cpilog ; then \
 	    echo "** C application can use both automatic and manual logging together" ; \
 	    $(RM) -f cpilog ; \
 	else \
-	    echo "** C application cannot use both automatic and manual logging together" ; \
+	    echo "** C application CANNOT use both automatic and manual logging together" ; \
 	fi 
-	$(MAKE) clean
+	@-$(MAKE) clean
 
 linktest_f77: 
-	@if [ $(NOF77) = 0 ] ; then \
-	    echo "** Testing if Fortran77 application can be linked with logging library" ; \
-	    $(RM) -f fpilog ; \
-	    $(MAKE) fpilog ; \
-	    if test -x fpilog ; then \
-	        echo "** Fortran77 application can be linked with logging library" ; \
-	        $(RM) -f fpilog ; \
-	    else \
-	        echo "** Fortran77 application cannot be linked with logging library***" ; \
-	    fi \
-	fi
+	@-if [ $(NOF77) = 0 ] ; then \
+	      echo ; \
+	      echo "** Testing if Fortran77 application can be linked with logging library" ; \
+	      $(RM) -f fpilog ; \
+	      $(MAKE) fpilog ; \
+	      if test -x fpilog ; then \
+	          echo "** Fortran77 application can be linked with logging library" ; \
+	          $(RM) -f fpilog ; \
+	      else \
+	          echo "** Fortran77 application CANNOT be linked with logging library" ; \
+	      fi ; \
+	      $(MAKE) clean ; \
+	  fi
 
 clean:
-	$(RM) -f *.o *~ PI* $(EXECS) cpilog cpi_anim cpi_trace cpi_log fpilog
+	@-$(RM) -f *.o *~ PI* $(EXECS) cpilog cpi_anim cpi_trace cpi_log fpilog
 
-.c.o:
-	$(CC) $(CFLAGS) -c $<
-.f.o:
-	$(F77) $(FFLAGS) -c $<
-
+distclean: clean
+	@-$(RM) -f Makefile
diff --git a/mpid/ch_p4/mpirun.ch_p4.in b/mpid/ch_p4/mpirun.ch_p4.in
--- a/mpid/ch_p4/mpirun.ch_p4.in
+++ b/mpid/ch_p4/mpirun.ch_p4.in
@@ -1,17 +1,6 @@
 #! /bin/sh
 exitstatus=1
 #
-if [ -z "$MPIR_HOME" ] ; then 
-    MPIR_HOME=#MPIR_HOME#
-fi
-if [ "$MPIR_HOME" = "#""MPIR_HOME""#" ] ; then
-    MPIR_HOME=`pwd`/..
-fi
-if [ "#MPIRUN_BIN#" = "#""MPIRUN_BIN""#" ] ; then 
-    MPIRUN_HOME=$MPIR_HOME/bin
-else
-    MPIRUN_HOME=#MPIRUN_BIN#
-fi
 if [ -z "$argsset" ] ; then
    . $MPIRUN_HOME/mpirun.args
    argsset=1
@@ -60,7 +49,7 @@ fi
 # Construct the procgroup file.
 # If p4 was built with comm=shared, set MPI_MAX_CLUSTER_SIZE to 16 unless
 # it has already been set.
-if [ "#COMM#" = "shared" ] ; then
+if [ "$COMM" = "shared" ] ; then
     if [ -z "$MPI_MAX_CLUSTER_SIZE" ] ; then
         MPI_MAX_CLUSTER_SIZE=16
     fi
@@ -79,7 +68,12 @@ fi
 prognamemain=$progname
 if [ -z "$p4pgfile"  ] ; then
     p4pgfile="$PWD_TRIAL/PI$$"
-    echo "Test" > $p4pgfile
+    # We need to explicitly redirect stderr.
+    # Under Solaris, an echo that fails aborts the script (!)  There is
+    # no way around this using echo, so we use cat instead.
+    cat <<EOF 2>/dev/null > $p4pgfile
+Test
+EOF
     if [ ! -s $p4pgfile ] ; then
 	# May not be able to write there.  Try the user's home directory
 	p4pgfile=$HOME/PI$$
@@ -167,7 +161,7 @@ fi
 # to start a job.  As a partial fix for this, we do a sync.  It would help,
 # of course, if NFS worked correctly.
 #
-#SYNCLOC# > /dev/null 2>&1
+$SYNCLOC > /dev/null 2>&1
 #
 #
 # get current directory (where mpirun is being executed) as proposed 
@@ -177,118 +171,58 @@ fi
 if [ "$p4workdir" = "" ] ; then
     p4workdir=$PWD_TRIAL
 fi
-#
-#
-# Handle debuggers
-#
-#startpgm="eval"
 startpgm="$prognamemain $cmdLineArgs -p4pg $p4pgfile -p4wd $p4workdir"
 # The following could use the -stdin filename from mpirun, though
 # it doesn't handle the problem of the created jobs.
 #if [ -n "$stdinfile" ] ; then
 # startpgm="$startpgm < $stdinfile"
 #fi
+#
+# Handle debuggers
+#
 if [ "$debugger" != "" ] ; then
-    if [ "$debugger" = "totalview" ] ; then
-        if [ "$TOTALVIEW" = "" ] ; then
-	   TOTALVIEW="totalview"
-        fi
-        startpgm="$TOTALVIEW $prognamemain -a $cmdLineArgs -p4pg $p4pgfile -p4wd $p4workdir -mpichtv"	        
+    if [ -x "$MPIRUN_HOME/mpirun_dbg.$debugger" ] ; then
+        $MPIRUN_HOME/mpirun_dbg.$debugger -progname $prognamemain -p4pg $p4pgfile -p4wd $p4workdir -cmdlineargs "$cmdLineArgs"
     else
-        dbgfile=$PWD_TRIAL/PId$$
-        echo "Test" > $dbgfile
-        if [ -s $dbgfile ] ; then
-	    /bin/rm -f $dbgfile
-        else
-            dbgfile=$HOME/PId$$
-        fi
-        # If gdb has an equivalent, the documentation is well hidden.
-        #  - .gdbinit - and the documentation IS well hidden.  Fortunately,
-        # the .gbdinit file is read; gdb provides the -nx (instead of -x)
-        # command if you don't want to read the default init file.
-        if [ "$debugger" = "dbx" -a -r $HOME/.dbxinit ] ; then
-	    cat $HOME/.dbxinit > $dbgfile
-# DEC dbx requires
-#    set stopall_on_step = 1
-# for proper behavior
-        fi
-        # Regretably, xxgdb does NOT provide this argument (even though it
-        # claims to).
-    #    if [ "$debugger" = "xxgdb" -a -r $HOME/.gdbinit ] ; then
-    #	cat $HOME/.gdbini > $dbgfile
-    #    fi
-        # handle USR1 pass for gdb; add an initial break 
-        if [ "$debugger" = "gdb" -o "$debugger" = "xxgdb" -o \
-	     "$debugger" = "ddd" ] ; then
-	    echo "handle SIGUSR1 nostop pass" >> $dbgfile
-	    echo "br MPI_Init" >> $dbgfile
-	    echo "set args $cmdLineArgs -p4pg $p4pgfile -p4wd $p4workdir" >> $dbgfile
-	    echo "run" >> $dbgfile
-        else 
-            echo "ignore USR1" >> $dbgfile
-            # This may not work, depending on when the symbol table is read.
-            # An alternative is to use the startup file to load the 
-            # program with "debug $prognamemain" ,followed with this, followed
-	    # with run command args.
-	    echo "debug $prognamemain" >> $dbgfile
-   	    echo "stop in MPI_Init" >> $dbgfile
-	    echo "run $cmdLineArgs -p4pg $p4pgfile -p4wd $p4workdir" >> $dbgfile
-        fi
-    #	cat >> $dbgfile <<.
-    ## Use this command to start your programm:
-    #run  $cmdLineArgs -p4pg $p4pgfile -p4wd $p4workdir
-    #.
-	    commandfile=`echo $commandfile | sed -e s@%f@$dbgfile@g`
-	    startpgm="$debugger $commandfile $prognamemain"
+        echo "CANNOT RUN DEBUGGER - NO DEBUGGER SCRIPT" 
+	exit 1
     fi
-fi
-#
-# Pass to the program that the device is ch_p4
-#
-MPIRUN_DEVICE="ch_p4"
-export MPIRUN_DEVICE
-#
-# Build a suitable command for the whole thing
-#
-if [ $just_testing = 1 ] ; then
-  doitall="echo"
 else
-  # We need the eval to handle arguments containing blanks.
-  doitall="eval"
-fi
-#
-# Add rsh'ery if requested
-#
-if [ $nolocal = 1 ] ; then
-    if [ "$stdinfile" = "/dev/null" ] ; then
-        doitall="$doitall $rshcmd $machinehead"
+    # Pass to the program that the device is ch_p4
+    #
+    MPIRUN_DEVICE="ch_p4"
+    export MPIRUN_DEVICE
+    #
+    # Build a suitable command for the whole thing
+    #
+    if [ $just_testing = 1 ] ; then
+        doitall="echo"
     else
-        doitall="$doitall $rshcmd -n $machinehead"
+        # We need the eval to handle arguments containing blanks.
+        doitall="eval"
+    fi
+    #
+    # Add rsh'ery if requested
+    #
+    if [ $nolocal = 1 ] ; then
+        if [ "$stdinfile" = "/dev/null" ] ; then
+            doitall="$doitall $rshcmd $machinehead"
+        else
+            doitall="$doitall $rshcmd -n $machinehead"
+        fi
+    fi
+
+    $doitall $startpgm
+    exitstatus=$?
+fi
+if [ $just_testing != 1 ] ; then
+    if [ $leavePGFile = 1 ] ; then
+        echo "P4 procgroup file is $p4pgfile."
+    else
+        /bin/rm "$p4pgfile"
+    fi
+    if [ "$MPIRUN_RANDOM" = "yes" ] ; then
+        /bin/rm -f "$TEMPDIR/mpirand-$LOGNAME"*
     fi
 fi
-
-$doitall $startpgm
-exitstatus=$?
-
-#else
-#  if [ $nolocal = 1 ] ; then
-#    if [ "$debugger" != "" ] ; then
-#	  $rshcmd $machinehead $debugger $commandfile $prognamemain
-#    else
-#	  $rshcmd $machinehead $prognamemain $cmdLineArgs -p4pg "$p4pgfile"
-#    fi
-#  else
-#   if [ "$debugger" != "" ] ; then
-#	    $debugger $commandfile $prognamemain
-#    else
-#	    $prognamemain $cmdLineArgs -p4pg "$p4pgfile"
-#    fi
-#  fi # nolocal
-if [ $just_testing != 1 ] ; then
-  if [ $leavePGFile = 1 ] ; then
-	echo "P4 procgroup file is $p4pgfile."
-  else
-    /bin/rm "$p4pgfile"
-  fi
-fi #just testing
 exit $exitstatus
diff --git a/mpid/ch_p4/p4/configure b/mpid/ch_p4/p4/configure
--- a/mpid/ch_p4/p4/configure
+++ b/mpid/ch_p4/p4/configure
@@ -173,8 +173,8 @@ LISTENER_PATHNAME=""
 
 
 # It is important to remove the p4_config.h file if we are performing
-# a VPATH build
-rm -f config.log p4_config.h
+# a VPATH build (the include target is a link)
+rm -f config.log p4_config.h include/p4_config.h
 trap 'rm -fr conftest* confdefs* core; exit 1' 1 3 15
 trap 'rm -f confdefs*' 0
 
@@ -230,7 +230,8 @@ if test -z "$top_srcdir" -o "$top_srcdir" = "." ; then
     top_srcdir=$srcdir
 fi
 # Remove the config file from the srcdir if this is a VPATH build.
-rm -f $top_srcdir/p4_config.h
+# (the include target is a link)
+rm -f $top_srcdir/p4_config.h $top_srcdir/include/p4_config.h
 
 
 if test -z "$exec_prefix" ; then 
@@ -5980,7 +5981,13 @@ if test -n "$p4listener_pathname"; then
 fi
 #
 # Check for cross-compilation.
-if test -z "$ac_echo_n" ; then
+
+if test -n "$pac_cv_cross_compiling" ; then
+    if test "$pac_cv_cross_compiling" = "yes" ; then
+	cross_compiling=1
+    fi
+else
+    if test -z "$ac_echo_n" ; then
 ac_echo_n=yes
 if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
   # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
@@ -6006,8 +6013,8 @@ echo $ac_n "checking whether cross-compiling""... $ac_c"
 else
 echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
 fi
-# If we cannot run a trivial program, we must be cross compiling.
-cat > conftest.c <<EOF
+    # If we cannot run a trivial program, we must be cross compiling.
+    cat > conftest.c <<EOF
 #include "confdefs.h"
 main(){exit(0);}
 EOF
@@ -6019,8 +6026,8 @@ else
   pac_ok=0
 fi
 rm -fr conftest*
-if test $pac_ok = 1 ; then
-    cat > conftest.c <<EOF
+    if test $pac_ok = 1 ; then
+         cat > conftest.c <<EOF
 #include "confdefs.h"
 main(){exit(1);}
 EOF
@@ -6030,27 +6037,31 @@ if test -s conftest && (./conftest; exit) 2>/dev/null; then
 
 fi
 rm -fr conftest*
-    if test $pac_ok = 1 ; then
-        if test -z "$ac_echo_test" -a 1 = 1 ; then
+        if test $pac_ok = 1 ; then
+	    pac_cv_cross_compiling="no"
+            if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""no"
 else
 echo "$ac_t""no" 1>&1
 fi
+        else
+            cross_compiling=1
+	    pac_cv_cross_compiling="yes"
+            if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+        fi
     else
         cross_compiling=1
+        pac_cv_cross_compiling="yes"
         if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""yes"
 else
 echo "$ac_t""yes" 1>&1
 fi
     fi
-else
-    cross_compiling=1
-    if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo "$ac_t""yes"
-else
-echo "$ac_t""yes" 1>&1
-fi
 fi
 
 #
@@ -6579,90 +6590,6 @@ fi
 fi
 done
 
-ac_safe=`echo "stdarg.h" | tr '[a-z]./' '[A-Z]__'`
-if test -z "$ac_echo_n" ; then
-ac_echo_n=yes
-if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
-  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
-  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
-    ac_n= ac_c='
-' ac_t='	'
-  else
-    ac_n=-n ac_c= ac_t=
-  fi
-else
-  ac_n= ac_c='\c' ac_t=
-fi
-ac_echo_test=`echo foo 1>&1`
-if test -z "$ac_echo_test" ; then
-     print_error "Your sh shell does not handle the output redirection"
-     print_error "1>&1 correctly.  Configure will work around this problem,"
-     print_error "but you should report the problem to your vendor."
-fi
-
-fi
-if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo $ac_n "checking for stdarg.h""... $ac_c"
-else
-echo $ac_n "checking for stdarg.h""... $ac_c" 1>&1
-fi
-if test ! -f confdefs.h ; then
-    if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo "$ac_t"""!! SHELL ERROR !!""
-else
-echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
-fi
-    echo "The file confdefs.h created by configure has been removed"
-    echo "This may be a problem with your shell; some versions of LINUX"
-    echo "have this problem.  See the Installation guide for more"
-    echo "information."
-    exit 1
-fi
-cat > conftest.c <<EOF
-#include "confdefs.h"
-
-#include <stdarg.h>
-int main() { exit(0); }
-int t() { main(); }
-EOF
-if eval $compile; then
-  
-  
-  eval "ac_cv_header_$ac_safe=yes"
-
-else
-  cat conftest.c >> config.log
-  if test -s conftest.out ; then cat conftest.out >> config.log 
-  else
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >> config.log 2>&1
-  fi
-  eval "ac_cv_header_$ac_safe=no"
-   
-fi
-rm -f conftest*
-if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
-  if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo "$ac_t""yes"
-else
-echo "$ac_t""yes" 1>&1
-fi
-  
-{
-test -n "$verbose" && \
-echo "	defining HAVE_STDARG_H"
-echo "#define" HAVE_STDARG_H 1 >> confdefs.h
-DEFS="$DEFS -DHAVE_STDARG_H=1"
-}
-
-havestdarg=1
-else
-  if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo "$ac_t""no"
-else
-echo "$ac_t""no" 1>&1
-fi
-fi
-
 for ac_hdr in string.h
 do
 ac_safe=`echo "$ac_hdr" | tr '[a-z]./' '[A-Z]__'`
@@ -7167,7 +7094,232 @@ fi
 # on some systems, the gcc version of stdio.h loads stdarg.h WITH THE WRONG
 # OPTIONS (causing it to choose the OLD STYLE va_start etc).
 #
-if test -n "$havestdarg" ; then
+
+ac_safe=`echo "stdarg.h" | tr '[a-z]./' '[A-Z]__'`
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for stdarg.h""... $ac_c"
+else
+echo $ac_n "checking for stdarg.h""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+
+#include <stdarg.h>
+int main() { exit(0); }
+int t() { main(); }
+EOF
+if eval $compile; then
+  
+  
+  eval "ac_cv_header_$ac_safe=yes"
+
+else
+  cat conftest.c >> config.log
+  if test -s conftest.out ; then cat conftest.out >> config.log 
+  else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >> config.log 2>&1
+  fi
+  eval "ac_cv_header_$ac_safe=no"
+   
+fi
+rm -f conftest*
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+  
+{
+test -n "$verbose" && \
+echo "	defining HAVE_STDARG_H"
+echo "#define" HAVE_STDARG_H 1 >> confdefs.h
+DEFS="$DEFS -DHAVE_STDARG_H=1"
+}
+
+havestdarg=1
+else
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+fi
+
+#
+# It isn't enough to check for stdarg.  Even gcc doesn't get it right;
+# on some systems, the gcc version of stdio.h loads stdarg.h WITH THE WRONG
+# OPTIONS (causing it to choose the OLD STYLE va_start etc).
+#
+# The original test tried the two-arg version first; the old-style
+# va_start took only a single arg.
+# This turns out to be VERY tricky, because some compilers (e.g., Solaris) 
+# are quite happy to accept the *wrong* number of arguments to a macro!
+# Instead, we try to find a clean compile version, using our special
+# TRY_COMPILE_CLEAN command
+#
+USE_STDARG=0
+
+#
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking that stdarg is oldstyle""... $ac_c"
+else
+echo $ac_n "checking that stdarg is oldstyle""... $ac_c" 1>&1
+fi
+
+check_compile=2
+rm -f conftest*
+if test -z "$TRY_COMPLILE_CLEAN" ; then
+    echo 'int try(void);int try(void){return 0;}' > conftest.c
+    if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+	if test -s conftest.bas ; then 
+	    TRY_COMPILE_CLEAN_OUT=`cat conftest.bas`
+        fi
+        TRY_COMPILE_CLEAN=1
+    else
+	if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: Could not compile simple test program!"
+else
+echo "$ac_t""Warning: Could not compile simple test program!" 1>&1
+fi
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+    fi
+fi
+rm -f conftest*
+cat >conftest.c <<EOF
+#include "confdefs.h"
+#include <stdio.h>
+#include <stdarg.h>
+int func( int a, ... ){
+int b;
+va_list ap;
+va_start( ap );
+b = va_arg(ap, int);
+printf( "%d-%d\n", a, b );
+va_end(ap);
+fflush(stdout);
+return 0;
+}
+int main() { func( 1, 2 ); return 0;}
+EOF
+if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+        if test "$TRY_COMPILE_CLEAN_OUT" = "`cat conftest.bas`" ; then
+	check_compile=0
+    else
+        cat conftest.c >>config.log
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+        check_compile=1
+    fi
+else
+        cat conftest.c >>config.log
+    if test -s conftest.bas ; then cat conftest.bas >> config.log ; fi
+    check_compile=2
+fi
+rm -f conftest*
+
+pac_old_warning=no
+case $check_compile in 
+    0)  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+        
+{
+test -n "$verbose" && \
+echo "	defining USE_STDARG"
+echo "#define" USE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_STDARG=1"
+}
+
+	
+{
+test -n "$verbose" && \
+echo "	defining USE_OLDSTYLE_STDARG"
+echo "#define" USE_OLDSTYLE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_OLDSTYLE_STDARG=1"
+}
+
+	
+{
+test -n "$verbose" && \
+echo "	defining USE_OLDSTYLE_STDARG"
+echo "#define" USE_OLDSTYLE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_OLDSTYLE_STDARG=1"
+}
+
+	USE_STDARG=1
+	;;
+    1)  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""hmm, warnings from compiler.  Trying newstyle"
+else
+echo "$ac_t""hmm, warnings from compiler.  Trying newstyle" 1>&1
+fi
+	pac_old_warning=yes
+	;;
+    2)  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+	;;
+esac
+
+if test -n "$havestdarg" -a "$USE_STDARG" != 1 ; then
     if test -z "$ac_echo_n" ; then
 ac_echo_n=yes
 if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
@@ -7190,9 +7342,163 @@ fi
 
 fi
 if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo $ac_n "checking for stdarg is correct""... $ac_c"
+echo $ac_n "checking stdarg is correct""... $ac_c"
 else
-echo $ac_n "checking for stdarg is correct""... $ac_c" 1>&1
+echo $ac_n "checking stdarg is correct""... $ac_c" 1>&1
+fi
+    
+check_compile=2
+rm -f conftest*
+if test -z "$TRY_COMPLILE_CLEAN" ; then
+    echo 'int try(void);int try(void){return 0;}' > conftest.c
+    if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+	if test -s conftest.bas ; then 
+	    TRY_COMPILE_CLEAN_OUT=`cat conftest.bas`
+        fi
+        TRY_COMPILE_CLEAN=1
+    else
+	if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: Could not compile simple test program!"
+else
+echo "$ac_t""Warning: Could not compile simple test program!" 1>&1
+fi
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+    fi
+fi
+rm -f conftest*
+cat >conftest.c <<EOF
+#include "confdefs.h"
+
+#include <stdio.h>
+#include <stdarg.h>
+
+int func( int a, ... ){
+int b;
+va_list ap;
+va_start( ap, a );
+b = va_arg(ap, int);
+printf( "%d-%d\n", a, b );
+va_end(ap);
+fflush(stdout);
+return 0;
+}
+int main() { func( 1, 2 ); return 0;}
+EOF
+if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+        if test "$TRY_COMPILE_CLEAN_OUT" = "`cat conftest.bas`" ; then
+	check_compile=0
+    else
+        cat conftest.c >>config.log
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+        check_compile=1
+    fi
+else
+        cat conftest.c >>config.log
+    if test -s conftest.bas ; then cat conftest.bas >> config.log ; fi
+    check_compile=2
+fi
+rm -f conftest*
+
+case $check_compile in 
+    0)  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+        
+{
+test -n "$verbose" && \
+echo "	defining USE_STDARG"
+echo "#define" USE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_STDARG=1"
+}
+
+        USE_STDARG=1
+	
+{
+test -n "$verbose" && \
+echo "	defining USE_STDARG"
+echo "#define" USE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_STDARG=1"
+}
+
+	;;
+    1)  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes with warnings"
+else
+echo "$ac_t""yes with warnings" 1>&1
+fi
+        
+{
+test -n "$verbose" && \
+echo "	defining USE_STDARG"
+echo "#define" USE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_STDARG=1"
+}
+
+        USE_STDARG=1
+	if test $pac_old_warning = "yes" ; then
+	    # A Risky move: if both gave warnings, choose old-style
+    	    
+{
+test -n "$verbose" && \
+echo "	defining USE_OLDSTYLE_STDARG"
+echo "#define" USE_OLDSTYLE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_OLDSTYLE_STDARG=1"
+}
+
+	else
+	    
+{
+test -n "$verbose" && \
+echo "	defining USE_STDARG"
+echo "#define" USE_STDARG 1 >> confdefs.h
+DEFS="$DEFS -DUSE_STDARG=1"
+}
+
+        fi
+	;;
+    2)  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+	
+	;;
+esac
+fi
+#
+# We need to check that these functions are also available to 
+# the other compilers (C++ and Fortran).  For Solaris /usr/ucb/cc, these
+# are found but not for the stock C++ and Fortran compilers.
+for func in sighold
+do
+trfunc=HAVE_`echo $func | tr '[a-z]' '[A-Z]'`
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for ${func}""... $ac_c"
+else
+echo $ac_n "checking for ${func}""... $ac_c" 1>&1
 fi
 if test ! -f confdefs.h ; then
     if test -z "$ac_echo_test" -a 1 = 1 ; then
@@ -7208,55 +7514,50 @@ fi
 fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
-
-#include <stdio.h>
-#include <stdarg.h>
-int func( int a, ... ){
-int b;
-va_list ap;
-va_start( ap, a );
-b = va_arg(ap, int);
-printf( "%d-%d\n", a, b );
-va_end(ap);
-fflush(stdout);
-return 0;
-}
-int main() { func( 1, 2 ); return 0;}
+#include <ctype.h>
+int main() { exit(0); }
+int t() { 
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_${func}) || defined (__stub___${func})
+choke me
+#else
+/* Override any gcc2 internal prototype to avoid an error.  */
+extern char ${func}(); ${func}();
+#endif
+ }
 EOF
-if test -z "$ac_compile_link" ; then 
-    ac_compile_link='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
-fi
-echo "$ac_compile_link" >>config.log
-cat conftest.c >>config.log
-if eval $ac_compile_link; then
+if eval $compile; then
   if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""yes"
 else
 echo "$ac_t""yes" 1>&1
 fi
-  rm -rf conftest*
   
-{
+  {
 test -n "$verbose" && \
-echo "	defining USE_STDARG"
-echo "#define" USE_STDARG 1 >> confdefs.h
-DEFS="$DEFS -DUSE_STDARG=1"
+echo "	defining ${trfunc}"
+echo "#define" ${trfunc} 1 >> confdefs.h
+DEFS="$DEFS -D${trfunc}=1"
 }
 
 
-else
-    rm -rf conftest*
-    
-    if test -z "$ac_echo_test" -a 1 = 1 ; then
+   else if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""no"
 else
 echo "$ac_t""no" 1>&1
 fi
-fi
-rm -f conftest*
+    cat conftest.c >> config.log
+    if test -s conftest.out ; then cat conftest.out >> config.log 
+    else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >> config.log 2>&1
+    fi
 
 fi
-#
+rm -f conftest*
+done
+
 for func in sigsetmask
 do
 trfunc=HAVE_`echo $func | tr '[a-z]' '[A-Z]'`
@@ -8225,11 +8526,10 @@ if test -z "$TRY_COMPLILE_CLEAN" ; then
         fi
         TRY_COMPILE_CLEAN=1
     else
-	
-if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo $ac_n "Warning: Could not compile simple test program!""... $ac_c"
+	if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: Could not compile simple test program!"
 else
-echo $ac_n "Warning: Could not compile simple test program!""... $ac_c" 1>&1
+echo "$ac_t""Warning: Could not compile simple test program!" 1>&1
 fi
 	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
     fi
@@ -8321,11 +8621,10 @@ if test -z "$TRY_COMPLILE_CLEAN" ; then
         fi
         TRY_COMPILE_CLEAN=1
     else
-	
-if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo $ac_n "Warning: Could not compile simple test program!""... $ac_c"
+	if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: Could not compile simple test program!"
 else
-echo $ac_n "Warning: Could not compile simple test program!""... $ac_c" 1>&1
+echo "$ac_t""Warning: Could not compile simple test program!" 1>&1
 fi
 	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
     fi
@@ -8754,6 +9053,7 @@ libdir='$libdir'
 libbuild_dir='$libbuild_dir'
 RANLIB='$RANLIB'
 VPATH='$VPATH'
+USE_STDARG='$USE_STDARG'
 P4ARCH='$P4ARCH'
 MAKE='$MAKE'
 CC='$CC'
@@ -8811,6 +9111,7 @@ s%@libdir@%$libdir%g
 s%@libbuild_dir@%$libbuild_dir%g
 s%@RANLIB@%$RANLIB%g
 s%@VPATH@%$VPATH%g
+s%@USE_STDARG@%$USE_STDARG%g
 s%@P4ARCH@%$P4ARCH%g
 s%@MAKE@%$MAKE%g
 s%@CC@%$CC%g
diff --git a/mpid/ch_p4mpd/p4mpd/configure b/mpid/ch_p4mpd/p4mpd/configure
--- a/mpid/ch_p4mpd/p4mpd/configure
+++ b/mpid/ch_p4mpd/p4mpd/configure
@@ -380,13 +380,22 @@ if test -n "$p4arch_NETBSD"; then
       DEFINE_SYSV_IPC="#define SYSV_IPC"
     fi
 fi
-#						486 running Linux
+#						x86 running Linux
 if test -n "$p4arch_LINUX"; then
     P4ARCH=LINUX
     if test -n "$p4comm_shared"; then
       DEFINE_SYSV_IPC="#define SYSV_IPC"
     fi
 fi
+
+#                                                Alpha running Linux
+if test -n "$p4arch_LINUX_ALPHA"; then
+    P4ARCH=LINUX
+    if test -n "$p4comm_shared"; then
+      DEFINE_SYSV_IPC="#define SYSV_IPC"
+    fi
+fi
+
 #                                             KSR
 if test -n "$p4arch_KSR"; then
     P4ARCH=KSR
@@ -764,7 +773,13 @@ echo $ac_n "checking for how many arguments gettimeofday takes""... $ac_c" 1>&1
 fi
 # Test sets "wierd" only for FAILURE to accept 2
 
-if test -z "$ac_echo_n" ; then
+
+if test -n "$pac_cv_cross_compiling" ; then
+    if test "$pac_cv_cross_compiling" = "yes" ; then
+	cross_compiling=1
+    fi
+else
+    if test -z "$ac_echo_n" ; then
 ac_echo_n=yes
 if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
   # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
@@ -790,8 +805,8 @@ echo $ac_n "checking whether cross-compiling""... $ac_c"
 else
 echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
 fi
-# If we cannot run a trivial program, we must be cross compiling.
-cat > conftest.c <<EOF
+    # If we cannot run a trivial program, we must be cross compiling.
+    cat > conftest.c <<EOF
 #include "confdefs.h"
 main(){exit(0);}
 EOF
@@ -803,8 +818,8 @@ else
   pac_ok=0
 fi
 rm -fr conftest*
-if test $pac_ok = 1 ; then
-    cat > conftest.c <<EOF
+    if test $pac_ok = 1 ; then
+         cat > conftest.c <<EOF
 #include "confdefs.h"
 main(){exit(1);}
 EOF
@@ -814,27 +829,31 @@ if test -s conftest && (./conftest; exit) 2>/dev/null; then
 
 fi
 rm -fr conftest*
-    if test $pac_ok = 1 ; then
-        if test -z "$ac_echo_test" -a 1 = 1 ; then
+        if test $pac_ok = 1 ; then
+	    pac_cv_cross_compiling="no"
+            if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""no"
 else
 echo "$ac_t""no" 1>&1
 fi
+        else
+            cross_compiling=1
+	    pac_cv_cross_compiling="yes"
+            if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+        fi
     else
         cross_compiling=1
+        pac_cv_cross_compiling="yes"
         if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""yes"
 else
 echo "$ac_t""yes" 1>&1
 fi
     fi
-else
-    cross_compiling=1
-    if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo "$ac_t""yes"
-else
-echo "$ac_t""yes" 1>&1
-fi
 fi
 
 
@@ -5571,7 +5590,13 @@ if test -n "$p4listener_pathname"; then
 fi
 #
 # Check for cross-compilation.
-if test -z "$ac_echo_n" ; then
+
+if test -n "$pac_cv_cross_compiling" ; then
+    if test "$pac_cv_cross_compiling" = "yes" ; then
+	cross_compiling=1
+    fi
+else
+    if test -z "$ac_echo_n" ; then
 ac_echo_n=yes
 if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
   # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
@@ -5597,8 +5622,8 @@ echo $ac_n "checking whether cross-compiling""... $ac_c"
 else
 echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
 fi
-# If we cannot run a trivial program, we must be cross compiling.
-cat > conftest.c <<EOF
+    # If we cannot run a trivial program, we must be cross compiling.
+    cat > conftest.c <<EOF
 #include "confdefs.h"
 main(){exit(0);}
 EOF
@@ -5610,8 +5635,8 @@ else
   pac_ok=0
 fi
 rm -fr conftest*
-if test $pac_ok = 1 ; then
-    cat > conftest.c <<EOF
+    if test $pac_ok = 1 ; then
+         cat > conftest.c <<EOF
 #include "confdefs.h"
 main(){exit(1);}
 EOF
@@ -5621,27 +5646,31 @@ if test -s conftest && (./conftest; exit) 2>/dev/null; then
 
 fi
 rm -fr conftest*
-    if test $pac_ok = 1 ; then
-        if test -z "$ac_echo_test" -a 1 = 1 ; then
+        if test $pac_ok = 1 ; then
+	    pac_cv_cross_compiling="no"
+            if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""no"
 else
 echo "$ac_t""no" 1>&1
 fi
+        else
+            cross_compiling=1
+	    pac_cv_cross_compiling="yes"
+            if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+        fi
     else
         cross_compiling=1
+        pac_cv_cross_compiling="yes"
         if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""yes"
 else
 echo "$ac_t""yes" 1>&1
 fi
     fi
-else
-    cross_compiling=1
-    if test -z "$ac_echo_test" -a 1 = 1 ; then
-echo "$ac_t""yes"
-else
-echo "$ac_t""yes" 1>&1
-fi
 fi
 
 #
@@ -7692,6 +7721,276 @@ DEFS="$DEFS -DRSH_HAS_NO_L=1"
 
 fi
 #
+#
+#
+# The following are necessary for AIX in particular because in 64 bit mode,
+# some of the socket functions use size_t (unsigned long, 64 bits) instead of
+# int (signed int, 32 bits) as a return value.  Getting the wrong type
+# causes all sorts of chaos.  Unfortunately, there isn't any consensus on what
+# the arguments *should* be.
+found_sockopt_type=0
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for if getsockopt wants socklen_t""... $ac_c"
+else
+echo $ac_n "checking for if getsockopt wants socklen_t""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <sys/types.h>
+#include <sys/socket.h>
+int main() { exit(0); }
+int t() { socklen_t dummy; int rc, skt; void *ssz;
+rc = getsockopt(skt,SOL_SOCKET,SO_SNDBUF,ssz,&dummy); }
+EOF
+if eval $compile; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+  
+  found_sockopt_type=1
+
+   else if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+    cat conftest.c >> config.log
+    if test -s conftest.out ; then cat conftest.out >> config.log 
+    else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >> config.log 2>&1
+    fi
+
+fi
+rm -f conftest*
+
+if test $found_sockopt_type = 1 ; then
+    MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_SOCKLEN_T"
+fi
+if test $found_sockopt_type = 0 ; then
+    # This case is harder.  size_t is a valid type, but it may not be the 
+    # one that getsockopt etc wants.
+    if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking if getsockopt wants size_t""... $ac_c"
+else
+echo $ac_n "checking if getsockopt wants size_t""... $ac_c" 1>&1
+fi
+    
+found_sockopt_type=2
+rm -f conftest*
+if test -z "$TRY_COMPLILE_CLEAN" ; then
+    echo 'int try(void);int try(void){return 0;}' > conftest.c
+    if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+	if test -s conftest.bas ; then 
+	    TRY_COMPILE_CLEAN_OUT=`cat conftest.bas`
+        fi
+        TRY_COMPILE_CLEAN=1
+    else
+	if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: Could not compile simple test program!"
+else
+echo "$ac_t""Warning: Could not compile simple test program!" 1>&1
+fi
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+    fi
+fi
+rm -f conftest*
+cat >conftest.c <<EOF
+#include "confdefs.h"
+#include <sys/types.h>
+#include <sys/socket.h>
+int try(void){size_t dummy; int rc, skt; void *ssz;
+rc = getsockopt(skt,SOL_SOCKET,SO_SNDBUF,ssz,&dummy);
+return rc;}
+EOF
+if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+        if test "$TRY_COMPILE_CLEAN_OUT" = "`cat conftest.bas`" ; then
+	found_sockopt_type=0
+    else
+        cat conftest.c >>config.log
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+        found_sockopt_type=1
+    fi
+else
+        cat conftest.c >>config.log
+    if test -s conftest.bas ; then cat conftest.bas >> config.log ; fi
+    found_sockopt_type=2
+fi
+rm -f conftest*
+
+    case $found_sockopt_type in 
+	0) if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+           MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_SIZE_T_FOR_SOCKLEN_T"
+	;;
+	1) if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no (warnings from compiler)"
+else
+echo "$ac_t""no (warnings from compiler)" 1>&1
+fi
+	;;
+	2) if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+	;;
+    esac
+fi
+#
+# Check whether u_int should be used for xdr_array 
+use_u_int=0
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking if xdr_array wants u_int""... $ac_c"
+else
+echo $ac_n "checking if xdr_array wants u_int""... $ac_c" 1>&1
+fi
+
+use_u_int=2
+rm -f conftest*
+if test -z "$TRY_COMPLILE_CLEAN" ; then
+    echo 'int try(void);int try(void){return 0;}' > conftest.c
+    if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+	if test -s conftest.bas ; then 
+	    TRY_COMPILE_CLEAN_OUT=`cat conftest.bas`
+        fi
+        TRY_COMPILE_CLEAN=1
+    else
+	if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: Could not compile simple test program!"
+else
+echo "$ac_t""Warning: Could not compile simple test program!" 1>&1
+fi
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+    fi
+fi
+rm -f conftest*
+cat >conftest.c <<EOF
+#include "confdefs.h"
+#include <rpc/xdr.h>
+
+int try(void){
+u_int l, ms, el; xdrproc_t elproc; XDR *xdrs; int rc; char **arrp;
+rc = xdr_array(xdrs,arrp,&l,ms,el,elproc);
+return rc;}
+EOF
+if ${CC-cc} $CFLAGS -c conftest.c >conftest.bas 2>&1 ; then
+        if test "$TRY_COMPILE_CLEAN_OUT" = "`cat conftest.bas`" ; then
+	use_u_int=0
+    else
+        cat conftest.c >>config.log
+	if test -s conftest.bas ; then 	cat conftest.bas >> config.log ; fi
+        use_u_int=1
+    fi
+else
+        cat conftest.c >>config.log
+    if test -s conftest.bas ; then cat conftest.bas >> config.log ; fi
+    use_u_int=2
+fi
+rm -f conftest*
+
+case $use_u_int in 
+    0) if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+       MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_U_INT_FOR_XDR"
+       ;;
+    1) if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no (compiler warnings)"
+else
+echo "$ac_t""no (compiler warnings)" 1>&1
+fi
+       ;;
+    2) if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+       ;;
+esac
+
+
 if test $threaded_listener = 1 ; then
     # Try to find a thread package
     has_pthread=0
diff --git a/util/tstmachines.in b/util/tstmachines.in
--- a/util/tstmachines.in
+++ b/util/tstmachines.in
@@ -8,10 +8,15 @@
 # in the remote shell commands
 #
 verbose=0
-rsh="#RSHCOMMAND#"
-machineDir=#datadir#
-# Could use #DEFAULT_ARCH#
-# and #DEFAULT_DEVICE# to see if we should check....
+rsh="@RSHCOMMAND@"
+prefix=@prefix@
+bindir=@binbuild_dir@
+# Use the same definition as in mpirun.in
+datadir=@builddir@/util/machines
+machineDir=$datadir
+CC="@CC@"
+CLINKER="@CLINKER@"
+
 for arg in "$@" ; do
     case $arg in 
         -echo) set -x ;;
@@ -36,9 +41,13 @@ output.  The option -v may be used to see what tests are being run.
     esac
 done
 #
-MPIR_HOME="#MPIR_HOME#"
 if [ -z "$arch" ] ; then
-    arch=`$MPIR_HOME/bin/tarch`
+    if [ -x $bindir/tarch ] ; then
+        arch=`$bindir/tarch` 
+    else 
+        echo "Could not determine architecture - provide as argument"
+	exit 1
+    fi
 fi
 #
 if [ -z "$machineFile" ] ; then
@@ -52,8 +61,8 @@ list=`cat $machineFile | sed -e '/\#/d' | tr -s '\012' ' '`
 /bin/rm -f mpichfoo
 echo "A test" > mpichfoo
 # Use same mechanism as in mpirun to get the value of pwd...
-if [ -n "#AUTOMOUNTFIX#" ] ; then
-    PWDtest=`pwd | #AUTOMOUNTFIX#`
+if [ -n "@AUTOMOUNTFIX@" ] ; then
+    PWDtest=`pwd | @AUTOMOUNTFIX@`
     if [ ! -d $PWDtest ] ; then
         PWDtest=`pwd`
     fi
@@ -105,7 +114,7 @@ for machine in $list ; do
     output=`$rsh $machine -n true 2>&1`
     if [ -n "$output" ] ; then
 	if [ -z "$printedheader" ] ; then
-	    echo "Errors while trying to run true"
+	    echo "Errors while trying to run $rsh $machine -n true"
 	    printedheader=1
 	fi
 	echo "Unexpected response from $machine:"
@@ -180,7 +189,7 @@ for machine in $list ; do
     output=`$rsh $machine -n /bin/ls $myprog 2>&1`
     if [ "$output" != "$tstout" ] ; then
 	if [ -z "$printedheader" ] ; then
-	    echo "Errors while trying to run ls $myprog"
+	    echo "Errors while trying to run $rsh $machine -n /bin/ls $myprog"
 	    printedheader=1
 	fi
 	echo "Unexpected response from $machine:"
@@ -214,10 +223,10 @@ fi
 cat >tstfoo.c <<.
 main(){return 0;}
 .
-#CC# -c tstfoo.c
-#CLINKER# -o tstfoo tstfoo.o
+$CC -c tstfoo.c
+$CLINKER -o tstfoo tstfoo.o
 if [ ! -x tstfoo ] ; then
-    echo "Could not build a sample program using #CC# and #CLINKER#!"
+    echo "Could not build a sample program using $CC and $CLINKER!"
     /bin/rm -f tstfoo.c
     exit 1
 fi
@@ -233,7 +242,7 @@ for machine in $list ; do
     output=`$rsh $machine -n $myprog 2>&1`
     if [ "$output" != "" ] ; then
 	if [ -z "$printedheader" ] ; then
-	    echo "Errors while trying to run a simple C program"
+	    echo "Errors while trying to run a simple C program with $rsh $machine -n"
 	    printedheader=1
 	fi
 	echo "Unexpected response from $machine:"
