1.1.0

diff --git a/examples/test/coll/runtests b/examples/test/coll/runtests
--- a/examples/test/coll/runtests
+++ b/examples/test/coll/runtests
@@ -24,6 +24,7 @@ fi
 #
 runtests=1
 makeeach=0
+quiet=0
 MAKE="make"
 for arg in "$@" ; do
     case $arg in 
@@ -36,6 +37,10 @@ for arg in "$@" ; do
 	;;
 	-small)
 	makeeach=1
+	;;
+	-quiet)
+	shift
+	quiet=1
 	;;
 	-help|-u)
 	echo "runtests [-checkonly] [-margs='...']"
@@ -57,11 +62,25 @@ done
 MakeExe() {
     if [ ! -x $1 ] ; then
 	$MAKE $1
+        if [ ! -x $1 ] ; then 
+	    echo "Could not build executable $1; aborting tests"
+	    exit 1
+        fi
     fi
 }
 CleanExe() {
     if [ $makeeach = 1 ] ; then
 	/bin/rm -f $1 $1.o
+    fi
+}
+# Output marker
+OutTime() {
+    if [ $quiet = 0 ] ; then
+	if [ -z "$hostname" ] ; then
+	    hostname=`hostname`
+	fi
+	d=`date`
+	echo "$hostname : $d"
     fi
 }
 
@@ -74,6 +93,7 @@ testfiles=""
 if [ $runtests = 1 ] ; then
 echo '**** Testing MPI Collective routines ****'
 
+OutTime
 testfiles="$testfiles barrier.out"
 /bin/rm -f barrier.out barrier-0.out
 MakeExe barrier
@@ -85,6 +105,7 @@ cat barrier-0.out >> barrier.out
 echo '*** Barrier Test ***' >> barrier.out
 CleanExe barrier
 
+OutTime
 testfiles="$testfiles bcast.out"
 /bin/rm -f bcast.out bcast-[0-3].out
 MakeExe bcast
@@ -98,6 +119,7 @@ cat bcast-[0123].out >> bcast.out
 echo '*** Broadcast Test ***' >> bcast.out
 CleanExe bcast
 
+OutTime
 testfiles="$testfiles coll1.out"
 /bin/rm -f coll1.out
 MakeExe coll1
@@ -107,6 +129,7 @@ $mpirun $args -np 4 coll1 $* >> coll1.out 2>&1
 echo '*** coll1 ***' >> coll1.out
 CleanExe coll1
 
+OutTime
 testfiles="$testfiles coll2.out"
 /bin/rm -f coll2.out
 MakeExe coll2
@@ -116,6 +139,7 @@ $mpirun $args -np 5 coll2 $* >> coll2.out 2>&1
 echo '*** coll2 ***' >> coll2.out
 CleanExe coll2
 
+OutTime
 testfiles="$testfiles coll3.out"
 /bin/rm -f coll3.out
 MakeExe coll3
@@ -125,6 +149,7 @@ $mpirun $args -np 5 coll3 $* >> coll3.out 2>&1
 echo '*** coll3 ***' >> coll3.out
 CleanExe coll3
 
+OutTime
 testfiles="$testfiles coll4.out"
 /bin/rm -f coll4.out
 MakeExe coll4
@@ -134,6 +159,7 @@ $mpirun $args -np 4 coll4 $* >> coll4.out 2>&1
 echo '*** coll4 ***' >> coll4.out
 CleanExe coll4
 
+OutTime
 testfiles="$testfiles coll5.out"
 /bin/rm -f coll5.out
 MakeExe coll5
@@ -143,6 +169,7 @@ $mpirun $args -np 4 coll5 $* >> coll5.out 2>&1
 echo '*** coll5 ***' >> coll5.out
 CleanExe coll5
 
+OutTime
 testfiles="$testfiles coll6.out"
 /bin/rm -f coll6.out
 MakeExe coll6
@@ -152,6 +179,7 @@ $mpirun $args -np 5 coll6 $* >> coll6.out 2>&1
 echo '*** coll6 ***' >> coll6.out
 CleanExe coll6
 
+OutTime
 testfiles="$testfiles coll7.out"
 /bin/rm -f coll7.out
 MakeExe coll7
@@ -161,6 +189,7 @@ $mpirun $args -np 5 coll7 $* >> coll7.out 2>&1
 echo '*** coll7 ***' >> coll7.out
 CleanExe coll7
 
+OutTime
 testfiles="$testfiles coll8.out"
 /bin/rm -f coll8.out
 MakeExe coll8
@@ -170,6 +199,7 @@ $mpirun $args -np 4 coll8 $* >> coll8.out 2>&1
 echo '*** coll8 ***' >> coll8.out
 CleanExe coll8
 
+OutTime
 testfiles="$testfiles coll9.out"
 /bin/rm -f coll9.out
 MakeExe coll9
@@ -179,6 +209,7 @@ $mpirun $args -np 4 coll9 $* >>  coll9.out 2>&1
 echo '*** coll9 ***' >> coll9.out
 CleanExe coll9
 
+OutTime
 testfiles="$testfiles coll10.out"
 /bin/rm -f coll10.out
 MakeExe coll10
@@ -188,6 +219,7 @@ $mpirun -np 4 $args coll10 $* >> coll10.out 2>&1
 echo '*** coll10 ***' >> coll10.out
 CleanExe coll10
 
+OutTime
 testfiles="$testfiles coll11.out"
 /bin/rm -f coll11.out
 MakeExe coll11
@@ -197,6 +229,7 @@ $mpirun -np 4 $args coll11 $* >> coll11.out 2>&1
 echo '*** coll11 ***' >> coll11.out
 CleanExe coll11
 
+OutTime
 testfiles="$testfiles coll12.out"
 /bin/rm -f coll12.out
 MakeExe coll12
@@ -206,6 +239,7 @@ $mpirun -np 4 $args coll12 $* >> coll12.out 2>&1
 echo '*** coll12 ***' >> coll12.out
 CleanExe coll12
 
+OutTime
 testfiles="$testfiles coll13.out"
 /bin/rm -f coll13.out
 MakeExe coll13
@@ -216,6 +250,45 @@ $mpirun -np 4 $args coll13 >> coll13.out 2>&1
 echo '*** coll13 ***' >> coll13.out
 CleanExe coll13
 
+OutTime
+testfiles="$testfiles longuser.out"
+/bin/rm -f longuser.out
+MakeExe longuser
+echo '**** longuser ****'
+echo '*** longuser ***' >> longuser.out
+$mpirun -np 4 $args longuser >> longuser.out 2>&1
+echo '*** longuser ***' >> longuser.out
+CleanExe longuser
+
+OutTime
+# Some implementations (e.g., IBM's) forget to handle the np = 1 case.
+testfiles="$testfiles longuser1.out"
+/bin/rm -f longuser1.out
+MakeExe longuser
+echo '**** longuser (np == 1) ****'
+echo '*** longuser (np == 1) ***' >> longuser1.out
+$mpirun -np 1 $args longuser >> longuser1.out 2>&1
+echo '*** longuser (np == 1) ***' >> longuser1.out
+CleanExe longuser
+
+#OutTime
+#testfiles="$testfiles allredmany.out"
+#/bin/rm -f allredmany.out
+#MakeExe allredmany
+#echo '**** allredmany ****'
+#echo '*** allredmany ***' >> allredmany.out
+#cnt=0
+## Run several times to try and catch timing/race conditions in managing
+## the flood of one-way messages.
+#while [ $cnt -lt 20 ] ; do
+#    echo "*** allredmany run $cnt ***" >> allredmany.out
+#    $mpirun -np 2 $args allredmany >> allredmany.out 2>&1
+#    cnt=`expr $cnt + 1`
+#done
+#echo '*** allredmany ***' >> allredmany.out
+#CleanExe allredmany
+
+OutTime
 testfiles="$testfiles grouptest.out"
 /bin/rm -f grouptest.out
 MakeExe grouptest
@@ -225,6 +298,7 @@ $mpirun $args -np 4 grouptest  $* >> grouptest.out 2>&1
 echo '*** grouptest ***' >> grouptest.out
 CleanExe grouptest
 
+OutTime
 testfiles="$testfiles allred.out"
 /bin/rm -f allred.out
 MakeExe allred
@@ -234,6 +308,7 @@ $mpirun $args -np 4 allred  $* >> allred.out 2>&1
 echo '*** Allred ***' >> allred.out
 CleanExe allred
 
+OutTime
 testfiles="$testfiles scatterv.out"
 /bin/rm -f scatterv.out
 MakeExe scatterv
@@ -243,6 +318,7 @@ $mpirun $args -np 4 scatterv  $* >> scatterv.out 2>&1
 echo '*** Scatterv ***' >> scatterv.out
 CleanExe scatterv
 
+OutTime
 testfiles="$testfiles redscat.out"
 /bin/rm -f redscat.out
 MakeExe redscat
@@ -252,6 +328,7 @@ $mpirun $args -np 4 redscat  $* >> redscat.out 2>&1
 echo '*** Reduce_scatter ***' >> redscat.out
 CleanExe redscat
 
+OutTime
 testfiles="$testfiles alltoallv.out"
 /bin/rm -f alltoallv.out
 MakeExe alltoallv
@@ -266,6 +343,7 @@ CleanExe alltoallv
 if [ 1 = 1 ] ; then 
     echo "FORTRAN TESTS"
     #
+    OutTime
     testfiles="$testfiles allredf.out"
     /bin/rm -f allredf.out
     MakeExe allredf
@@ -275,6 +353,7 @@ if [ 1 = 1 ] ; then
     echo '*** Testing allreduce from Fortran ***' >> allredf.out
     CleanExe allredf
     #
+    OutTime
     testfiles="$testfiles assocf.out"
     /bin/rm -f assocf.out
     MakeExe assocf
diff --git a/examples/test/context/runtests.in b/examples/test/context/runtests.in
--- a/examples/test/context/runtests.in
+++ b/examples/test/context/runtests.in
@@ -26,7 +26,9 @@ if [ -z "$mpirun" ] ; then
 fi
 #
 #
+test_mpi2=@HAS_MPI2@
 runtests=1
+quiet=0
 makeeach=0
 MAKE="@MAKE@"
 for arg in "$@" ; do
@@ -40,6 +42,10 @@ for arg in "$@" ; do
 	;;
 	-small)
 	makeeach=1
+	;;
+	-quiet)
+	shift
+	quiet=1
 	;;
 	-help|-u)
 	echo "runtests [-checkonly] [-margs='...']"
@@ -61,11 +67,25 @@ done
 MakeExe() {
     if [ ! -x $1 ] ; then
 	$MAKE $1
+        if [ ! -x $1 ] ; then 
+	    echo "Could not build executable $1; aborting tests"
+	    exit 1
+        fi
     fi
 }
 CleanExe() {
     if [ $makeeach = 1 ] ; then
 	/bin/rm $1 $1.o
+    fi
+}
+# Output marker
+OutTime() {
+    if [ $quiet = 0 ] ; then
+	if [ -z "$hostname" ] ; then
+	    hostname=`hostname`
+	fi
+	d=`date`
+	echo "$hostname : $d"
     fi
 }
 
@@ -80,6 +100,7 @@ if [ $runtests = 1 ] ; then
 #
 # Run Fortran tests ONLY if Fortran available
 if [ @HAS_FORTRAN@ = 1 ] ; then 
+    OutTime
     testfiles="$testfiles attrf.out"
     /bin/rm -f attrf.out
     MakeExe attrtest
@@ -88,8 +109,23 @@ if [ @HAS_FORTRAN@ = 1 ] ; then
     $mpirun $args -np 2 attrtest $* >> attr.out 2>&1
     echo '*** Testing attributes from Fortran ***' >> attrf.out
     CleanExe attrtest
+
+    if [ $test_mpi2 = 1 ] ; then
+
+    OutTime
+    testfiles="$testfiles commnamesf.out"
+    /bin/rm -f commnamesf.out
+    MakeExe commnamesf
+    echo '*** Testing Communicator Names from Fortran ***'
+    echo '*** Testing Communicator Names from Fortran ***' >> commnamesf.out
+    $mpirun $args -np 1 commnamesf $* >> commnamesf.out 2>&1
+    echo '*** Testing Communicator Names from Fortran ***' >> commnamesf.out
+    CleanExe commnamesf
+
+    fi
 fi
 
+OutTime
 testfiles="$testfiles attr.out"
 /bin/rm -f attr.out
 MakeExe attrt
@@ -99,6 +135,17 @@ $mpirun $args -np 2 attrt $* >> attr.out 2>&1
 echo '*** Testing attributes ***' >> attr.out
 CleanExe attrt
 
+OutTime
+testfiles="$testfiles attrerr.out"
+/bin/rm -f attrerr.out
+MakeExe attrerr
+echo '*** Testing attributes (2) ***'
+echo '*** Testing attributes (2) ***' >> attrerr.out
+$mpirun $args -np 1 attrerr $* >> attrerr.out 2>&1
+echo '*** Testing attributes (2) ***' >> attrerr.out
+CleanExe attrerr
+
+OutTime
 testfiles="$testfiles grouptest.out"
 /bin/rm -f grouptest.out
 MakeExe grouptest
@@ -108,6 +155,17 @@ $mpirun $args -np 4 grouptest $* >> grouptest.out 2>&1
 echo '*** Testing Groups ***' >> grouptest.out
 CleanExe grouptest
 
+OutTime
+testfiles="$testfiles groupcreate.out"
+/bin/rm -f groupcreate.out
+MakeExe groupcreate
+echo '*** Testing Group creation ***'
+echo '*** Testing Group creation ***' >> groupcreate.out
+$mpirun $args -np 4 groupcreate $* >> groupcreate.out 2>&1
+echo '*** Testing Group creation ***' >> groupcreate.out
+CleanExe groupcreate
+
+OutTime
 testfiles="$testfiles ictest.out"
 /bin/rm -f ictest.out
 MakeExe ictest
@@ -134,6 +192,7 @@ CleanExe ictest
 #echo '*** Testing Intercommunicators (2) ***' >> ictest2.out
 #CleanExe ictest2
 
+OutTime
 testfiles="$testfiles ictest3.out"
 /bin/rm -f ictest3.out
 MakeExe ictest3
@@ -143,6 +202,19 @@ $mpirun $args -np 4 ictest3 $* >> ictest3.out 2>&1
 echo '*** Testing Intercommunicators (3) ***' >> ictest3.out
 CleanExe ictest3
 
+if [ $test_mpi2 = 1 ] ; then
+
+    OutTime
+    testfiles="$testfiles commnames.out"
+    /bin/rm -f commnames.out
+    MakeExe commnames
+    echo '*** Testing Communicator Names ***'
+    echo '*** Testing Communicator Names ***' >> commnames.out
+    $mpirun $args -np 2 commnames $* >> commnames.out 2>&1
+    echo '*** Testing Communicator Names ***' >> commnames.out
+    CleanExe commnames
+
+fi
 else
     # Just run checks
     testfiles=`echo *.out`
diff --git a/examples/test/pt2pt/runtests b/examples/test/pt2pt/runtests
--- a/examples/test/pt2pt/runtests
+++ b/examples/test/pt2pt/runtests
@@ -29,6 +29,7 @@ fi
 runtests=1
 makeeach=0
 check_at_once=1
+quiet=0
 MAKE="make"
 # Using shifts should  remove args from the list.
 for arg in "$@" ; do
@@ -45,6 +46,10 @@ for arg in "$@" ; do
 	-echo)
 	shift
 	set -x
+	;;
+	-quiet)
+	shift
+	quiet=1
 	;;
 	-small)
 	shift
@@ -78,6 +83,10 @@ done
 MakeExe() {
     if [ ! -x $1 ] ; then
 	$MAKE $1
+        if [ ! -x $1 ] ; then 
+	    echo "Could not build executable $1; aborting tests"
+	    exit 1
+        fi
     fi
 }
 # CleanExe program-name
@@ -86,6 +95,17 @@ CleanExe() {
 	/bin/rm -f $1 $1.o
     fi
 }
+# Output marker
+OutTime() {
+    if [ $quiet = 0 ] ; then
+	if [ -z "$hostname" ] ; then
+	    hostname=`hostname`
+	fi
+	d=`date`
+	echo "$hostname : $d"
+    fi
+}
+
 # Do an "on the fly" check for problems.
 CheckOutput() {
   if [ $check_at_once = 1 ] ; then
@@ -135,6 +155,7 @@ testfiles=""
 if [ $runtests = 1 ] ; then
 echo '**** Testing MPI Point-to-point routines ****'
 
+OutTime
 testfiles="$testfiles sendrecv.out"
 /bin/rm -f sendrecv.out
 MakeExe sendrecv
@@ -148,6 +169,7 @@ echo '**** Testing MPI_Send and MPI_Recv ****' >> sendrecv.out
 CheckOutput sendrecv
 CleanExe sendrecv
 #
+OutTime
 testfiles="$testfiles sendrecv2.out"
 /bin/rm -f sendrecv2.out
 MakeExe sendrecv2
@@ -158,6 +180,7 @@ echo '**** Testing MPI_Send and MPI_Recv (2) ****' >> sendrecv2.out
 CheckOutput sendrecv2
 CleanExe sendrecv2
 #
+OutTime
 testfiles="$testfiles sendrecv3.out"
 /bin/rm -f sendrecv3.out
 MakeExe sendrecv3
@@ -168,6 +191,7 @@ echo '**** Testing MPI_Send and MPI_Recv (3) ****' >> sendrecv3.out
 CheckOutput sendrecv3
 CleanExe sendrecv3
 #
+OutTime
 testfiles="$testfiles sendrecv4.out"
 /bin/rm -f sendrecv4.out
 MakeExe sendrecv4
@@ -178,6 +202,7 @@ echo '**** Testing MPI_Send and MPI_Recv (4) ****' >> sendrecv4.out
 CheckOutput sendrecv4
 CleanExe sendrecv4
 #
+OutTime
 testfiles="$testfiles bsendtest.out"
 /bin/rm -f bsendtest.out
 MakeExe bsendtest
@@ -188,6 +213,7 @@ echo '**** Testing MPI_Bsend and MPI_Recv (4) ****' >> bsendtest.out
 CheckOutput bsendtest
 CleanExe bsendtest
 #
+OutTime
 testfiles="$testfiles isndrcv.out"
 /bin/rm -f isndrcv.out
 MakeExe isndrcv
@@ -201,6 +227,7 @@ echo '**** Testing MPI_Isend and MPI_Irecv ****' >> isndrcv.out
 CheckOutput isndrcv
 CleanExe isndrcv
 #
+OutTime
 testfiles="$testfiles irsend.out"
 /bin/rm -f irsend.out
 MakeExe irsend
@@ -211,6 +238,7 @@ echo '**** Testing MPI_Irsend ****' >> irsend.out
 CheckOutput irsend
 CleanExe irsend
 #
+OutTime
 testfiles="$testfiles irsendinit.out"
 /bin/rm -f irsendinit.out
 MakeExe irsendinit
@@ -221,6 +249,7 @@ echo '**** Testing MPI_Rsend_init ****' >> irsendinit.out
 CheckOutput irsendinit
 CleanExe irsendinit
 #
+OutTime
 testfiles="$testfiles testsome.out"
 /bin/rm -f testsome.out
 MakeExe testsome
@@ -231,6 +260,7 @@ echo '**** Testing MPI_Testsome/Testany/Waitsome ****' >> testsome.out
 CheckOutput testsome
 CleanExe testsome
 #
+OutTime
 testfiles="$testfiles testall.out"
 /bin/rm -f testall.out
 MakeExe testall
@@ -241,6 +271,7 @@ echo '**** Testing MPI_Testall ****' >> testall.out
 CheckOutput testall
 CleanExe testall
 #
+OutTime
 testfiles="$testfiles cancel.out"
 /bin/rm -f cancel.out
 MakeExe cancel
@@ -251,6 +282,7 @@ echo '**** Checking MPI_Cancel ****' >> cancel.out
 CheckOutput cancel
 CleanExe cancel
 #
+OutTime
 testfiles="$testfiles sndrcv.out"
 /bin/rm -f sndrcv.out
 MakeExe sndrcv
@@ -261,6 +293,18 @@ echo '**** Testing MPI_Sendrecv ****' >> sndrcv.out
 CheckOutput sndrcv
 CleanExe sndrcv
 #
+OutTime
+testfiles="$testfiles sndrcvrep.out"
+/bin/rm -f sndrcvrep.out
+MakeExe sndrcvrep
+echo '**** Testing MPI_Sendrecv_replace ****' >> sndrcvrep.out
+echo '**** Testing MPI_Sendrecv_replace ****' 
+$mpirun $args -np 2 sndrcvrep "$@" >> sndrcvrep.out 2>&1
+echo '**** Testing MPI_Sendrecv_replace ****' >> sndrcvrep.out
+CheckOutput sndrcvrep
+CleanExe sndrcvrep
+#
+OutTime
 testfiles="$testfiles getelm.out"
 /bin/rm -f getelm.out
 MakeExe getelm
@@ -271,6 +315,7 @@ echo '**** Testing MPI_Get_elements ****' >> getelm.out
 CheckOutput getelm
 CleanExe getelm
 #
+OutTime
 testfiles="$testfiles overtake.out"
 /bin/rm -f overtake.out
 MakeExe overtake
@@ -284,6 +329,7 @@ echo '**** Verifying that messages are non-overtaking ****' >> overtake.out
 CheckOutput overtake
 CleanExe overtake
 #
+OutTime
 testfiles="$testfiles ssendtest.out"
 /bin/rm -f ssendtest.out
 MakeExe ssendtest
@@ -294,6 +340,7 @@ echo '**** Verifying ssend ****' >> ssendtest.out
 CheckOutput ssendtest
 CleanExe ssendtest
 #
+OutTime
 testfiles="$testfiles ssendtest2.out"
 /bin/rm -f ssendtest2.out
 MakeExe ssendtest2
@@ -304,6 +351,7 @@ echo '**** Verifying ssend (2) ****' >> ssendtest2.out
 CheckOutput ssendtest2
 CleanExe ssendtest2
 #
+OutTime
 testfiles="$testfiles issendtest.out"
 /bin/rm -f issendtest.out
 MakeExe issendtest
@@ -314,6 +362,18 @@ echo '**** Verifying Issend ****' >> issendtest.out
 CheckOutput issendtest
 CleanExe issendtest
 #
+OutTime
+testfiles="$testfiles reqcreate.out"
+/bin/rm -f reqcreate.out
+MakeExe reqcreate
+echo '**** Checking the request creation routines ****'
+echo '**** Checking the request creation routines ****' >> reqcreate.out
+$mpirun $args -np 1 reqcreate "$@" >> reqcreate.out 2>&1
+echo '**** Checking the request creation routines ****' >> reqcreate.out
+CheckOutput reqcreate
+CleanExe reqcreate
+#
+OutTime
 testfiles="$testfiles typebase.out"
 /bin/rm -f typebase.out
 MakeExe typebase
@@ -324,6 +384,18 @@ echo '**** Checking the type (sizes) routines ****' >> typebase.out
 CheckOutput typebase
 CleanExe typebase
 #
+OutTime
+testfiles="$testfiles typecreate.out"
+/bin/rm -f typecreate.out
+MakeExe typecreate
+echo '**** Checking the type creation routines ****'
+echo '**** Checking the type creation routines ****' >> typecreate.out
+$mpirun $args -np 1 typecreate "$@" >> typecreate.out 2>&1
+echo '**** Checking the type creation routines ****' >> typecreate.out
+CheckOutput typecreate
+CleanExe typecreate
+#
+OutTime
 testfiles="$testfiles typetest.out"
 /bin/rm -f typetest.out
 MakeExe typetest
@@ -339,6 +411,7 @@ echo '**** Checking the type routines ****' >> typetest.out
 CheckOutput typetest
 CleanExe typetest
 #
+OutTime
 testfiles="$testfiles typeub.out"
 /bin/rm -f typeub.out
 MakeExe typeub
@@ -349,6 +422,29 @@ echo '**** Checking the type routines: MPI_UB ****' >> typeub.out
 CheckOutput typeub
 CleanExe typeub
 #
+OutTime
+testfiles="$testfiles typeub2.out"
+/bin/rm -f typeub2.out
+MakeExe typeub2
+echo '**** Checking the type routines: MPI_UB(2) ****'
+echo '**** Checking the type routines: MPI_UB(2) ****' >> typeub2.out
+$mpirun $args -np 1 typeub2 "$@" >> typeub2.out 2>&1
+echo '**** Checking the type routines: MPI_UB(2) ****' >> typeub2.out
+CheckOutput typeub2
+CleanExe typeub2
+#
+OutTime
+testfiles="$testfiles typeub3.out"
+/bin/rm -f typeub3.out
+MakeExe typeub3
+echo '**** Checking the type routines: MPI_UB(3) ****'
+echo '**** Checking the type routines: MPI_UB(3) ****' >> typeub3.out
+$mpirun $args -np 1 typeub3 "$@" >> typeub3.out 2>&1
+echo '**** Checking the type routines: MPI_UB(3) ****' >> typeub3.out
+CheckOutput typeub3
+CleanExe typeub3
+#
+OutTime
 testfiles="$testfiles dtypelife.out"
 /bin/rm -f dtypelife.out
 MakeExe dtypelife
@@ -359,6 +455,7 @@ echo '**** Checking the type routines: MPI_Type_free ****' >> dtypelife.out
 CheckOutput dtypelife
 CleanExe dtypelife
 #
+OutTime
 testfiles="$testfiles commit.out"
 /bin/rm -f commit.out
 MakeExe commit
@@ -369,6 +466,7 @@ echo '**** Checking the type routines: MPI_Type_commit ****' >> commit.out
 CheckOutput commit
 CleanExe commit
 #
+OutTime
 testfiles="$testfiles third.out"
 /bin/rm -f third.out
 MakeExe third
@@ -379,6 +477,7 @@ echo '*** Testing Unexpected messages ***' >> third.out
 CheckOutput third
 CleanExe third
 #
+OutTime
 testfiles="$testfiles fourth.out"
 /bin/rm -f fourth.out
 MakeExe fourth
@@ -389,6 +488,7 @@ echo '*** Testing Irecv/Isend/Wait ***' >> fourth.out
 CheckOutput fourth
 CleanExe fourth
 #
+OutTime
 testfiles="$testfiles fifth.out"
 /bin/rm -f fifth.out
 MakeExe fifth
@@ -399,6 +499,7 @@ echo '*** Testing Irecv/Isend/Waitall ***' >> fifth.out
 CheckOutput fifth
 CleanExe fifth
 #
+OutTime
 testfiles="$testfiles sixth.out"
 /bin/rm -f sixth.out
 MakeExe sixth
@@ -409,6 +510,7 @@ echo '*** Testing attribute manipulation ***' >> sixth.out
 CheckOutput sixth
 CleanExe sixth
 #
+OutTime
 testfiles="$testfiles nblock.out"
 /bin/rm -f nblock.out
 MakeExe nblock
@@ -419,6 +521,7 @@ echo '*** Testing Isend/Irecv (large numbers) ***' >> nblock.out
 CheckOutput nblock
 CleanExe nblock
 #
+OutTime
 testfiles="$testfiles nbtest.out"
 /bin/rm -f nbtest.out
 MakeExe nbtest
@@ -429,6 +532,7 @@ echo '*** Testing Isend/Probe/Recv (large numbers) ***' >> nbtest.out
 CheckOutput nbtest
 CleanExe nbtest
 #
+OutTime
 testfiles="$testfiles sendmany.out"
 /bin/rm -f sendmany.out
 MakeExe sendmany
@@ -439,6 +543,7 @@ echo '*** Testing Send (many procs) ***' >> sendmany.out
 CheckOutput sendmany
 CleanExe sendmany
 #
+OutTime
 testfiles="$testfiles order.out"
 /bin/rm -f order.out
 MakeExe order
@@ -449,6 +554,7 @@ echo '*** Testing Recv ordering ***' >> order.out
 CheckOutput order
 CleanExe order
 #
+OutTime
 testfiles="$testfiles trunc.out"
 /bin/rm -f trunc.out
 MakeExe trunc
@@ -459,6 +565,29 @@ echo '*** Testing Message trunction ***' >> trunc.out
 CheckOutput trunc
 CleanExe trunc
 #
+OutTime
+testfiles="$testfiles nullproc.out"
+/bin/rm -f nullproc.out
+MakeExe nullproc
+echo '*** Testing handling of MPI_PROC_NULL ***'
+echo '*** Testing handling of MPI_PROC_NULL ***' >> nullproc.out
+$mpirun $args -np 2 nullproc "$@" >> nullproc.out 2>&1
+echo '*** Testing handling of MPI_PROC_NULL ***' >> nullproc.out
+CheckOutput nullproc
+CleanExe nullproc
+#
+OutTime
+testfiles="$testfiles relrank.out"
+/bin/rm -f relrank.out
+MakeExe relrank
+echo '*** Testing handling of relative rank ***'
+echo '*** Testing handling of relative rank ***' >> relrank.out
+$mpirun $args -np 2 relrank "$@" >> relrank.out 2>&1
+echo '*** Testing handling of relative rank ***' >> relrank.out
+CheckOutput relrank
+CleanExe relrank
+#
+OutTime
 testfiles="$testfiles hvectest.out"
 /bin/rm -f hvectest.out
 MakeExe hvectest
@@ -469,6 +598,7 @@ echo '*** Testing Vector type ***' >> hvectest.out
 CheckOutput hvectest
 CleanExe hvectest
 #
+OutTime
 testfiles="$testfiles hvectest2.out"
 /bin/rm -f hvectest2.out
 MakeExe hvectest2
@@ -479,6 +609,7 @@ echo '*** Testing struct type for vectors (MPI_UB) ***' >> hvectest2.out
 CheckOutput hvectest2
 CleanExe hvectest2
 #
+OutTime
 testfiles="$testfiles hvec.out"
 /bin/rm -f hvec.out
 MakeExe hvec
@@ -489,6 +620,7 @@ echo '*** Testing Type_Hvector ***' >> hvec.out
 CheckOutput hvec
 CleanExe hvec
 #
+OutTime
 testfiles="$testfiles hindexed.out"
 /bin/rm -f hindexed.out
 MakeExe hindexed
@@ -499,6 +631,7 @@ echo '*** Testing Type_Hindexed ***' >> hindexed.out
 CheckOutput hindexed
 CleanExe hindexed
 #
+OutTime
 testfiles="$testfiles probe.out"
 /bin/rm -f probe.out
 MakeExe probe
@@ -509,6 +642,7 @@ echo '*** Testing Probe and Get_count ***' >> probe.out
 CheckOutput probe
 CleanExe probe
 #
+OutTime
 testfiles="$testfiles probe1.out"
 /bin/rm -f probe1.out
 MakeExe probe1
@@ -519,6 +653,7 @@ echo '*** Testing Iprobe and Get_count ***' >> probe1.out
 CheckOutput probe1
 CleanExe probe1
 #
+OutTime
 testfiles="$testfiles self.out"
 /bin/rm -f self.out
 MakeExe self
@@ -530,6 +665,7 @@ CheckOutput self
 CleanExe self
 #
 #
+OutTime
 testfiles="$testfiles testtest1.out"
 /bin/rm -f testtest1.out
 MakeExe testtest1
@@ -540,6 +676,7 @@ echo '*** Testing MPI_Test ***' >> testtest1.out
 CheckOutput testtest1
 CleanExe testtest1
 #
+OutTime
 testfiles="$testfiles persistent.out"
 /bin/rm -f persistent.out
 MakeExe persistent
@@ -550,6 +687,18 @@ echo '*** Testing MPI_Recv_init ***' >> persistent.out
 CheckOutput persistent
 CleanExe persistent
 #
+OutTime
+testfiles="$testfiles persist.out"
+/bin/rm -f persist.out
+MakeExe persist
+echo '*** Testing MPI_Startall/Request_free ***' 
+echo '*** Testing MPI_Startall/Request_free ***' >> persist.out
+$mpirun $args -np 4 persist "$@" >> persist.out 2>&1
+echo '*** Testing MPI_Startall/Request_free ***' >> persist.out
+CheckOutput persist
+CleanExe persist
+#
+OutTime
 testfiles="$testfiles waitall.out"
 /bin/rm -f waitall.out
 MakeExe waitall
@@ -560,6 +709,7 @@ echo '*** Testing MPI_Waitall ***' >> waitall.out
 CheckOutput waitall
 CleanExe waitall
 #
+OutTime
 testfiles="$testfiles pack.out"
 /bin/rm -f pack.out
 MakeExe pack
@@ -570,6 +720,28 @@ echo '*** Testing MPI_Pack ***' >> pack.out
 CheckOutput pack
 CleanExe pack
 #
+OutTime
+testfiles="$testfiles flood.out"
+/bin/rm -f flood.out
+MakeExe flood
+echo '**** Testing large messages ****' >> flood.out
+echo '**** Testing large messages ****' 
+$mpirun $args -np 2 flood "$@" >> flood.out 2>&1
+echo '**** Testing large messages ****' >> flood.out
+CheckOutput flood
+CleanExe flood
+#
+#OutTime
+#testfiles="$testfiles flood2.out"
+#/bin/rm -f flood2.out
+#MakeExe flood2
+#echo '**** Testing large numbers of messages ****' >> flood2.out
+#echo '**** Testing large numbers of messages ****' 
+#$mpirun $args -np 2 flood2 "$@" >> flood2.out 2>&1
+#echo '**** Testing large numbers of messages ****' >> flood2.out
+#CheckOutput flood2
+#CleanExe flood2
+#
 # Run Fortran tests ONLY if Fortran available
 if [ 1 = 1 ] ; then 
     echo "FORTRAN TESTS"
@@ -577,6 +749,7 @@ if [ 1 = 1 ] ; then
     #echo "*** secondf ***" >> pt2pt.out
     #$mpirun $args -np 2 secondf "$@" >> pt2pt.out 2>&1
     #
+    OutTime
     testfiles="$testfiles allpair.out"
     /bin/rm -f allpair.out
     MakeExe allpair
@@ -587,6 +760,7 @@ if [ 1 = 1 ] ; then
     CheckOutput allpair
     CleanExe allpair
     #
+    OutTime
     testfiles="$testfiles allpair2.out"
     /bin/rm -f allpair2.out
     MakeExe allpair2
@@ -597,6 +771,7 @@ if [ 1 = 1 ] ; then
     CheckOutput allpair2
     CleanExe allpair2
     #
+    OutTime
     testfiles="$testfiles structf.out"
     /bin/rm -f structf.out
     MakeExe structf
@@ -616,6 +791,7 @@ if [ 1 = 1 ] ; then
     CheckOutput structf
     CleanExe structf
     #
+    OutTime
     testfiles="$testfiles send1.out"
     /bin/rm -f send1.out
     MakeExe send1
diff --git a/examples/test/topol/runtests.in b/examples/test/topol/runtests.in
--- a/examples/test/topol/runtests.in
+++ b/examples/test/topol/runtests.in
@@ -29,6 +29,7 @@ fi
 #
 runtests=1
 makeeach=0
+quiet=0
 MAKE="@MAKE@"
 for arg in "$@" ; do
     case $arg in 
@@ -41,6 +42,10 @@ for arg in "$@" ; do
 	;;
 	-small)
 	makeeach=1
+	;;
+	-quiet)
+	shift
+	quiet=1
 	;;
 	-help|-u)
 	echo "runtests [-checkonly] [-margs='...'] [-small]"
@@ -62,11 +67,25 @@ done
 MakeExe() {
     if [ ! -x $1 ] ; then
 	$MAKE $1
+        if [ ! -x $1 ] ; then 
+	    echo "Could not build executable $1; aborting tests"
+	    exit 1
+        fi
     fi
 }
 CleanExe() {
     if [ $makeeach = 1 ] ; then
 	/bin/rm -f $1 $1.o
+    fi
+}
+# Output marker
+OutTime() {
+    if [ $quiet = 0 ] ; then
+	if [ -z "$hostname" ] ; then
+	    hostname=`hostname`
+	fi
+	d=`date`
+	echo "$hostname : $d"
     fi
 }
 
@@ -77,6 +96,7 @@ fi
 testfiles=""
 if [ $runtests = 1 ] ; then
 
+OutTime
 testfiles="$testfiles cart.out"
 /bin/rm -f cart.out
 MakeExe cart
@@ -86,6 +106,7 @@ $mpirun $args -np 4 cart $* >> cart.out 2>&1
 echo '**** Testing MPI_Cart_create etc ****' >> cart.out
 CleanExe cart
 #
+OutTime
 testfiles="$testfiles cart2.out"
 /bin/rm -f cart2.out
 MakeExe cart2
@@ -95,6 +116,7 @@ $mpirun $args -np 4 cart2 $* >> cart2.out 2>&1
 echo '**** Testing MPI_Cart_coords etc ****' >> cart2.out
 CleanExe cart2
 #
+OutTime
 testfiles="$testfiles cartmap.out"
 /bin/rm -f cartmap.out
 MakeExe cartmap
@@ -104,6 +126,7 @@ $mpirun $args -np 4 cartmap $* >> cartmap.out 2>&1
 echo '**** Testing MPI_Cart_map etc ****' >> cartmap.out
 CleanExe cartmap
 #
+OutTime
 testfiles="$testfiles cartorder.out"
 /bin/rm -f cartorder.out
 MakeExe cartorder
@@ -113,6 +136,7 @@ $mpirun $args -np 4 cartorder $* >> cartorder.out 2>&1
 echo '**** Testing MPI_Cart_create etc (2) ****' >> cartorder.out
 CleanExe cartorder
 #
+OutTime
 testfiles="$testfiles graphtest.out"
 /bin/rm -f graphtest.out
 MakeExe graphtest
@@ -127,39 +151,43 @@ if [ @HAS_FORTRAN@ = 1 ] ; then
     echo "FORTRAN TESTS"
     #
     #
+    OutTime
     testfiles="$testfiles cartf.out"
     /bin/rm -f cartf.out
     MakeExe cartf
     echo '*** Testing cart from Fortran ***'
     echo '*** Testing cart from Fortran ***' >> cartf.out
-    $mpirun $args -np 4 cartf "$@" >> cartf.out
+    $mpirun $args -np 4 cartf "$@" >> cartf.out 2>&1
     echo '*** Testing cart from Fortran ***' >> cartf.out
     CleanExe
     #
+    OutTime
     testfiles="$testfiles cart1f.out"
     /bin/rm -f cart1f.out
     MakeExe cart1f
     echo '*** Testing cart1 from Fortran ***'
     echo '*** Testing cart1 from Fortran ***' >> cart1f.out
-    $mpirun $args -np 4 cart1f "$@" >> cart1f.out
+    $mpirun $args -np 4 cart1f "$@" >> cart1f.out 2>&1
     echo '*** Testing cart1 from Fortran ***' >> cart1f.out
     CleanExe
     #
+    OutTime
     testfiles="$testfiles cart2f.out"
     /bin/rm -f cart2f.out
     MakeExe cart2f
     echo '*** Testing cart2 from Fortran ***'
     echo '*** Testing cart2 from Fortran ***' >> cart2f.out
-    $mpirun $args -np 4 cart2f "$@" >> cart2f.out
+    $mpirun $args -np 4 cart2f "$@" >> cart2f.out 2>&1
     echo '*** Testing cart2 from Fortran ***' >> cart2f.out
     CleanExe
     #
+    OutTime
     testfiles="$testfiles twod.out"
     /bin/rm -f twod.out
     MakeExe twod
     echo '*** Testing twod from Fortran ***'
     echo '*** Testing twod from Fortran ***' >> twod.out
-    $mpirun $args -np 2 twod "$@" >> twod.out
+    $mpirun $args -np 2 twod "$@" >> twod.out 2>&1
     echo '*** Testing twod from Fortran ***' >> twod.out
     CleanExe
 fi
diff --git a/util/maketar b/util/maketar
--- a/util/maketar
+++ b/util/maketar
@@ -3,18 +3,52 @@
 # This just assembles the tar file in /tmp
 # You can change the name with -name= and add directories with -add=
 #
+# Change to distribution approach:
+#  Because of the difficulties in getting "contributed" devices updated, 
+#  and because we want to emphasize the flexibility of the package, 
+#  we need multiple distributions.  I'm going to start with:
+#      Full distribution (as now)
+#      Workstations only (ch_p4, ch_shmem)
+#      MPPs only (ch_mpl, ch_nx, ch_cmmd)
+#      No devices at all
+#
+#  with separate distributions for the devices
+#    ch_cenju3
+#    ch_lfshmem
+#    ch_nc
+#    ch_nexus
+#    meiko
+#    nx
+#    t3d
+#    t3e
+#    tests
+#
+#  Note that the meiko, nx, t3d, t3e all will fail
+#  because they are ADI-2.  
+#
+# In addition, we build the various MPI/MPE standalone packages if
+# -mpienv is specified
+#
 OTHERDEVICES="mpid/ch_nx mpid/ch_p4 mpid/ch_nc mpid/ch_cmmd mpid/ch_mpl \
 		mpid/ch_meiko mpid/ch_shmem mpid/ch_lfshmem mpid/t3d \
 		mpid/sgi mpid/nx mpid/ch_nexus mpid/ch_cenju3"
 MAKE=make
 MPIR_HOME=/home/MPI/mpich
-relname=1.0.13
+relname=1.1.0
+# By default, destdir is the misc tryout directory.
+destdir=/home/ftp/pub/mpi/misc
 if [ -s $MPIR_HOME/relname ] ; then
     relname=`cat $MPIR_HOME/relname`
 fi
 tarname=mpich
 extrafiles=""
 cleanonly=0
+do_autoconf=1
+verbose=1
+mpienv=0
+do_all_tar=1
+do_copy=1
+rmtmpfile=1
 for arg in "$@" ; do
     case $arg in 
 	-name=* )
@@ -33,6 +67,34 @@ for arg in "$@" ; do
 	set -x
 	;;
 
+	-quiet)
+	verbose=0
+	;;
+
+	-noautoconf)
+	do_autoconf=0
+	;;
+
+	-mainonly)
+	do_all_tar=0
+	;;
+
+	-nocopy)
+	do_copy=0
+	;;
+	
+	-mpienv)
+	mpienv=1
+	;;
+
+	-destdir=*)
+	destdir="`echo A$arg | sed -e 's/A-destdir=//'`"
+	if [ ! -d "$destdir" ] ; then 
+	    echo "$destdir is not a valid directory"
+	    exit 1
+	fi
+	;;
+
 	*)
 	if test -n "$arg" ; then
    	    echo "port: Unknown argument ($arg)"
@@ -45,6 +107,8 @@ done
 cd $MPIR_HOME
 #
 # First, clean out the various files.
+# We export make for the Makefiles just in case we need a different make...
+export MAKE
 $MAKE clean
 for dir in $OTHERDEVICES ; 
      do echo cleaning $dir
@@ -61,33 +125,64 @@ if [ $cleanonly = 1 ] ; then
     exit 0
 fi
 #
+# Update the configure programs
+if [ $do_autoconf = 1 ] ; then
+    autoconf
+    /bin/rm -f .tmp
+    sed -e 's/PAC_CHECK_HEADERS/AC_HAVE_HEADERS/g' \
+        -e 's/PAC_CHECK_HEADER/AC_HAVE_HEADERS/g' configure.in > .tmp
+    autoheader .tmp > mpichconf.h.in
+    /bin/rm -f .tmp
+    maint/splitsed < configure > configure.2
+    echo "Some configure creations may generate errors; these can be ignored"
+    if [ -s mpid/ch_tcp/p3/configure.in ] ; then
+        (cd mpid/ch_tcp/p3 ; /bin/rm -f configure ; /usr/local/bin/autoconf )
+    fi
+    for dir in mpid/ch_p4/p4-1.4 mpid/ch_shmem/p2ptest profiling/wrappergen \
+	    profiling/nupshot mpe examples/perftest examples/test ; do
+        if [ -s $dir/configure.in ] ; then
+	    ( cd $dir ; /bin/rm -f configure ; autoconf )
+        fi
+    done
+    # The generalized server is autoconf 2
+    (cd mpid/server ; /usr/local/cvs-test/bin/cvs update ; \
+		/usr/local/bin/autoconf )
+    echo "Done with configure updates"
+fi
+#
 /bin/rm -rf /tmp/$tarname /tmp/mpich-tmp /tmp/mpifoo.tar
 # This relies on bin being a link to util.
 #tar cXf Xclude /tmp/mpifoo.tar 
 # SGI versions of tar don't support X (eXclude); use the following line instead
 #tar cf /tmp/mpifoo.tar 
+# This creates a temporary directory containing the part of MPICH that
+# we will distribute.
+if [ $verbose = 1 ] ; then echo "Copying MPICH into /tmp..." ; fi
+# Removed mpid/chameleon
 tar cXf Xclude /tmp/mpifoo.tar \
  COPYRIGHT README \
- Makefile.in configure aclocal.m4 bin ptx_ifile \
+ Makefile.in configure configure.2 aclocal.m4 bin ptx_ifile \
  doc/functions.ps.Z doc/perf.ps.Z doc/guide.ps.Z doc/install.ps.Z \
  doc/port.in doc/portbuild.in doc/portperf.in doc/porttest.in \
  doc/latexinfo.sty doc/epsf.sty doc/epsf.tex doc/doc.bib \
  doc/docgather doc/portrun doc/docmake \
  ref/adiman.ps.Z ref/mpiman.ps.Z \
- configure.in examples include man mpe ccbugs \
+ configure.in mpichconf.h.in acconfig.h examples include man mpe ccbugs \
  mpid/ch2 mpid/util mpid/tests \
- mpid/ch_nx mpid/chameleon mpid/ch_p4 \
+ mpid/ch_nx mpid/ch_p4 \
  mpid/ch_mpl mpid/ch_cmmd mpid/ch_nc mpid/ch_meiko mpid/ch_shmem \
- mpid/meiko mpid/t3d mpid/nx mpid/ch_nexus mpid/ch_lfshmem mpid/ch_cenju3 \
- mpid/NewDevice mpid/updatedev \
+ mpid/meiko mpid/t3d mpid/t3e mpid/nx mpid/ch_nexus mpid/ch_lfshmem \
+ mpid/ch_cenju3 \
+ mpid/NewDevice mpid/updatedev mpid/server \
  installtest src util/mandesc util/finderrors util/insttest \
  util/mpirun.* util/mpireconfig.in util/execer util/machines \
  util/mpiman.in util/upshot util/tarch util/tdevice \
  util/mpicc.in util/mpiCC.in util/mpif77.in util/mpiinstall.in \
  util/tstmachines.in util/chp4_servs.in util/cleanipcs \
- util/maketar util/chkserv util/chkmachine profiling
+ util/maketar util/chkserv util/chkmachine util/Makefile.in profiling
 #
 # Untar into /tmp, remove stuff we don't want in the full file
+if [ $verbose = 1 ] ; then echo "Cleaning distribution directories..." ; fi
 curdir=`pwd`
 mkdir /tmp/mpich-tmp
 cd /tmp/mpich-tmp
@@ -102,7 +197,9 @@ cd /tmp
 	      mpich-tmp/profiling/upshot/bin/upshot.old \
 	      mpich-tmp/profiling/upshot/logfiles \
 	      mpich-tmp/util/machines/machines.* \
-	      mpich-tmp/mpe/Makefile_nompi
+	      mpich-tmp/mpe/Makefile_nompi \
+	      mpich-tmp/examples/perftest/save \
+	      mpich-tmp/examples/perftest/*.cit
 mkdir mpich-tmp/profiling/upshot/logfiles
 cp $MPIR_HOME/profiling/upshot/logfiles/fft.trf \
 	mpich-tmp/profiling/upshot/logfiles
@@ -112,7 +209,8 @@ cp $MPIR_HOME/profiling/upshot/logfiles/states.c \
 	mpich-tmp/profiling/upshot/logfiles
 cp $MPIR_HOME/util/machines/machines.sample mpich-tmp/util/machines
 find mpich-tmp \( -name 'RCS' -o -name '*.o' -o -name '#*#' -o \
-              -name '*~' -o -name 'mputil.mp*' \) -print | \
+              -name '*~' -o -name 'mputil.mp*' -o -name Makefile -o \
+	      -name makefile -o -name 'CVS' \) -print | \
 	sed 's%^%/bin/rm -rf %g' | sh
 find mpich-tmp/examples -name '*.pg' -exec /bin/rm \{\} \;
 find mpich-tmp/mpe -name '*.pg' -exec /bin/rm \{\} \;
@@ -120,6 +218,9 @@ find mpich-tmp/mpe -name 'Makefile' -exec /bin/rm \{\} \;
 find mpich-tmp/examples -name 'Makefile' -exec /bin/rm \{\} \;
 find mpich-tmp/src -name 'Makefile' -exec /bin/rm \{\} \;
 find mpich-tmp/profiling -name 'Makefile' -exec /bin/rm \{\} \;
+# Files of the form rdb.* appear to be Nexus files that are not being
+# removed and that have not been added to the clean target in the Makefiles
+find mpich-tmp/examples -name 'rdb.*' -exec /bin/rm \{\} \;
 #
 # Remove the 'LOCAL' information from the main Makefile, if present.
 sed -e 's/mpi: Makefile.in/mpi:/g' \
@@ -133,11 +234,112 @@ find /tmp/mpich-tmp -name '#*#' -print
 # This requires prune.
 find /tmp/mpich-tmp -name 'lib' -prune -o -name '*.o' -print 
 #
-# Finally, compress the file
+# Finally, create the tar files and compress the results
 cd /tmp
 mv /tmp/mpich-tmp /tmp/$tarname
+if [ $verbose = 1 ] ; then echo "Full distribution" ; fi
+# Full distribution
+/bin/rm -f /tmp/$tarname-$relname.tar.Z /tmp/$tarname-$relname.tar.gz
 tar cof - $tarname | compress > /tmp/$tarname-$relname.tar.Z
 tar cof - $tarname | gzip > /tmp/$tarname-$relname.tar.gz
-/bin/rm -rf /tmp/$tarname /tmp/mpifoo.tar 
-echo "Tar file is in /tmp/$tarname-$relname.tar.Z"
-echo "Tar file is in /tmp/$tarname-$relname.tar.gz"
+tarfiles="$tarname-$relname.tar"
+if [ $do_all_tar = 1 ] ; then 
+    # Individual devices
+    if [ $verbose = 1 ] ; then echo "Individual devices" ; fi
+    cd $tarname/mpid
+    for dev in ch_p4 ch_shmem ch_lfshmem ch_nc ch_nexus ch_cenju3 \
+    	   meiko nx t3d t3e tests ; do
+        /bin/rm -f /tmp/$dev-$relname.tar.Z /tmp/$dev-$relname.tar.gz	
+        tar cof - $dev | compress > /tmp/$dev-$relname.tar.Z
+        tar cof - $dev | gzip > /tmp/$dev-$relname.tar.gz
+        tarfiles="$tarfiles $dev-$relname.tar"
+    done
+
+    cd /tmp
+    # Workstation build.  From mpid, include only util, ch2, ch_p4, ch_shmem
+    if [ $verbose = 1 ] ; then echo "Workstation version" ; fi
+    /bin/rm -rf /tmp/mpid
+    mv $tarname/mpid .
+    mkdir $tarname/mpid
+    mv mpid/ch_p4 $tarname/mpid
+    mv mpid/ch_shmem $tarname/mpid
+    mv mpid/server $tarname/mpid
+    mv mpid/ch2 $tarname/mpid
+    mv mpid/util $tarname/mpid
+    /bin/rm -f /tmp/$tarname-ws-$relname.tar.Z
+    /bin/rm -f /tmp/$tarname-ws-$relname.tar.gz
+    tar cof - $tarname | compress > /tmp/$tarname-ws-$relname.tar.Z
+    tar cof - $tarname | gzip > /tmp/$tarname-ws-$relname.tar.gz
+    tarfiles="$tarfiles $tarname-ws-$relname.tar"
+    mv $tarname/mpid/ch_p4 mpid
+    mv $tarname/mpid/ch_shmem mpid
+    mv $tarname/mpid/server mpid
+    #
+    # Mpp build only (ch_mpl, ch_nx, ch_cmmd)
+    if [ $verbose = 1 ] ; then echo "MPP version" ; fi
+    mv mpid/ch_mpl $tarname/mpid
+    mv mpid/ch_nx $tarname/mpid
+    mv mpid/ch_cmmd $tarname/mpid
+    /bin/rm -f /tmp/$tarname-mpp-$relname.tar.Z 
+    /bin/rm -f /tmp/$tarname-mpp-$relname.tar.gz
+    tar cof - $tarname | compress > /tmp/$tarname-mpp-$relname.tar.Z
+    tar cof - $tarname | gzip > /tmp/$tarname-mpp-$relname.tar.gz
+    tarfiles="$tarfiles $tarname-mpp-$relname.tar"
+    mv $tarname/mpid/ch_mpl mpid
+    mv $tarname/mpid/ch_nx mpid
+    mv $tarname/mpid/ch_cmmd mpid
+    #
+    # No devices (I've left util and ch2 as examples and for support)
+    # 
+    if [ $verbose = 1 ] ; then echo "No device version" ; fi
+    /bin/rm -f /tmp/$tarname-nodev-$relname.tar.Z
+    /bin/rm -f /tmp/$tarname-nodev-$relname.tar.gz
+    tar cof - $tarname | compress > /tmp/$tarname-nodev-$relname.tar.Z
+    tar cof - $tarname | gzip > /tmp/$tarname-nodev-$relname.tar.gz
+    tarfiles="$tarfiles $tarname-ws-$relname.tar"
+    #
+fi
+/bin/rm -rf /tmp/$tarname /tmp/mpifoo.tar /tmp/mpid
+if [ $do_copy = 1 ] ; then
+    for tarfile in $tarfiles ; do
+        if [ -f $tarfile.gz ] ; then 
+	    if [ $verbose = 1 ] ; then 
+	        echo -n "Copying $tarfile.gz to $destdir ... "
+	    fi
+	    cp $tarfile.gz $destdir
+	    if [ $rmtmpfile = 1 ] ; then 
+	        /bin/rm $tarfile.gz
+	    fi
+	    if [ $verbose = 1 ] ; then echo " done." ; fi
+        fi
+        if [ -f $tarfile.Z ] ;  then 
+	    if [ $verbose = 1 ] ; then 
+	        echo -n "Copying $tarfile.Z to $destdir ... "
+	    fi
+	    cp $tarfile.Z $destdir
+	    if [ $rmtmpfile = 1 ] ; then 
+	        /bin/rm $tarfile.Z
+	    fi
+	    if [ $verbose = 1 ] ; then echo " done." ; fi
+        fi
+    done
+else
+    echo "Created tar files are $tarfiles"
+fi
+#
+if [ $mpienv = 1 ] ; then
+    # This one moves directly into /home/ftp/pub/mpi/mpi-test
+    (cd examples/test ; ./maketar )
+    # This leaves in /tmp
+    (cd examples/perftest ; ./maketar )
+    cp /tmp/perftest.tar.gz /home/ftp/pub/mpi/misc
+    if [ $rmtmpfile = 1 ] ; then
+	/bin/rm /tmp/perftest.tar.gz
+    fi 
+    # This leaves in /tmp
+    (cd mpe ; ./maketar )
+    cp /tmp/mpe.tar.gz /home/ftp/pub/mpi/misc
+    if [ $rmtmpfile = 1 ] ; then
+	/bin/rm /tmp/mpe.tar.gz
+    fi 
+fi
diff --git a/util/mpirun.ch_cenju3.in b/util/mpirun.ch_cenju3.in
--- a/util/mpirun.ch_cenju3.in
+++ b/util/mpirun.ch_cenju3.in
@@ -1,11 +1,11 @@
 #! /bin/sh
-if [ "$MPIR_HOME" = "" ] ; then
+if [ "$MPIR_HOME" = "" ] ; then 
     MPIR_HOME=#MPIR_HOME#
 fi
 if [ "$MPIR_HOME" = "#""MPIR_HOME""#" ] ; then
     MPIR_HOME=`pwd`/..
 fi
-if [ "#MPIRUN_BIN#" = "#""MPIRUN_BIN""#" ] ; then
+if [ "#MPIRUN_BIN#" = "#""MPIRUN_BIN""#" ] ; then 
     MPIRUN_HOME=$MPIR_HOME/bin
 else
     MPIRUN_HOME=$MPIR_HOME/#MPIRUN_BIN#
@@ -15,50 +15,219 @@ if [ "$argsset" = "" ] ; then
    argsset=1
 fi
 #
-#  set arguments for batch mode -- cjbr
+#==================== machine dependent =============================
 #
-if [ -n "$batch" ] ; then
-   cjarg=
-   if [ -n "$stdinfile" ] ; then
-      cjarg="-i $stdinfile"
-   else
-      cjarg=
-   fi
-   if [ -n "$stdoutfile" ] ; then
-      cjarg="$cjarg -o $stdoutfile"
-   fi
-   if [ -n "$stderrfile" ] ; then
-      cjarg="$cjarg -e $stderrfile"
-   fi
-fi
+#  Options which depends on the queuing system used on the machine :
+#  -----------------------------------------------------------------
 #
-#  get number of processors available
+#  use : Option which kind of commands should be used in order
+#        to execute and submit programs.
 #
-free=`cjpes | fgrep ST_PE_ACTIV | wc -l`
+#        use = CJ   : Use native CJ commands
+#        use = EASY : Use Easy commands
 #
-#   Specify request (only active for GMD)
+#  easybin  : Full path name (including last /) of directory
+#             containing the EASY commands of Cenju-3 or
+#             empty string if general path should be used.
+#  easywait : Option for interactive mode of EASY
+#             easywait = prompt : Wait for prompt of user
+#                                 before user program is started.
+#             easywait = wait   : Wait and inspect easy queue
+#                                 and try to start user program.
 #
-#   if [ $free -lt $np ] ; then
-#      if [ $mpirun_verbose = 1 ] ; then
-#         echo requesting $np processors
-#      fi
+#===> Select one of the following
 #
-#      $Show /vol/local/bin/request_nodes $np
-#   fi
+    use=CJ
 #
-#   Execute Job in batch mode or interactive
+#   use=EASY
+    easybin=/opt/EASY/bin/
+#   easybin=
+    easywait=wait
+#
+#============ End of machine dependent =============================
+#
+#---------------- Batch Mode -------------------------------------
 #
     if [ -n "$batch" ] ; then
+#
+#   Execute Job in batch mode
+#
        if [ $mpirun_verbose = 1 ] ; then
           echo executing job in batch mode
        fi
+#
+       case $use in 
+#
+       EASY)
+            if [ -z "$stdoutfile" ] ; then
+               stdoutfile=$PWD_TRIAL/stdout.$$
+            else
+               tail=`echo $stdoutfile | sed 's/\/.*//'`
+               if  [ -z "$tail" = "" ] ; then
+                  stdoutfile="$PWD_TRIAL/$stdoutfile"
+               fi
+            fi
+#
+            if [ -z "$stderrfile" ] ; then
+               stderrfile=$PWD_TRIAL/stderr.$$
+            else
+               tail=`echo $stderrfile | sed 's/\/.*//'`
+               if  [ -z "$tail" = "" ] ; then
+                  stderrfile="$PWD_TRIAL/$stderrfile"
+               fi
+            fi
+#
+            if [ -z "$stdinfile" ] ; then
+               stdinfile=/dev/null
+            else
+               tail=`echo $stdinfile | sed 's/\/.*//'`
+               if  [ -z "$tail" = "" ] ; then
+                  stderrfile="$PWD_TRIAL/$stdinfile"
+               fi
+            fi
+#
+#           tempfile=$PWD_TRIAL/batch_script.mpirun.$$
+            tempfile=batch_script.mpirun.$$
+#
+            rm -f $tempfile
+#
+            cat << EOF > $tempfile
+#! /bin/sh
+cd $PWD_TRIAL
+#
+# Standard-Input  will be read from  $stdinfile
+# Standard-Output will be written to $stdoutfile
+# Error   -Output will be written to $stderrfile
+#
+${easybin}prun -j \$1 -n $np -p $progname -a "$cmdLineArgs" < $stdinfile > $stdou
+tfile 2> $stderrfile
+EOF
+#
+            echo "=== submitting batch job : Number of processors = $np"
+            echo "===                        Maximal time         = $max_time min
+utes"
+            chmod +x $tempfile
+            $Show ${easybin}psubmit -n $np -t $max_time -b $tempfile
+            rm -f $tempfile
+            ;;
 
-       $Show cjbr $cjarg $np $progname $cmdLineArgs
+       CJ | *)
+            cjarg=
+#
+            if [ -n "$stdinfile" ] ; then
+               cjarg="-i $stdinfile"
+            else
+               cjarg=
+            fi
+#
+            if [ -n "$stdoutfile" ] ; then
+               cjarg="$cjarg -o $stdoutfile"
+            fi
+#
+            if [ -n "$stderrfile" ] ; then
+               cjarg="$cjarg -e $stderrfile"
+            fi
+#
+            $Show cjbr $cjarg $np $progname $cmdLineArgs
+#
+            ;;
+       esac
 #
     else
-       if [ $mpirun_verbose = 1 -o $free -lt $np ] ; then
-          echo waiting for $np processors available
-       fi
 #
-       $Show cjsh -w -n $np $progname $cmdLineArgs
+#------------------------- Interactive mode ----------------------------
+#
+       case $use in 
+#
+       EASY)
+          if [ -n "$easy_jid" ] ; then
+#
+#===> ... user has allocated node. Execute parallel program
+#
+             $Show ${easybin}prun -j $easy_jid -n $np -p $progname -a \"$cmdLineArgs\"
+          else
+
+             tempfile=.tEmP_EaSy.OuTpUt.$$
+             rm -f $tempfile
+#
+             sleep=0
+#
+             while [ "$status" != 0 -o -z "$easy_jid" ]
+             do
+                if [ $sleep != 0 ] ; then
+                    echo "=== mpirun doesn't return a job id; waiting"
+                    sleep 30
+                fi
+#
+                $Show ${easybin}psubmit -i -n $np -t $max_time | tee -a $tempfile
+                status=$?
+                easy_jid=`fgrep 'JID for this job is' $tempfile | sed -e 's/.*: *\([0-9]*\) */\1/'`
+#
+                rm -f $tempfile
+                sleep=30
+             done
+#
+             if [ "$easywait" = wait ] ; then
+#
+                tempfile=.tEmP.sEdFiLe.$$
+                cat << EOF > $tempfile
+/^$easy_jid/!d
+s/$easy_jid  *[^ ]* * [^ ]* *[^ ]* . . *\(.\).*/\1/
+EOF
+#
+                echo === Waiting until processors are available
+#
+                status=W
+                while [ "$status" != R ]
+                do
+                   sleep 5
+                   status=`pq | sed -f $tempfile`
+                done
+#
+                rm -f $tempfile
+             else
+#
+#===> Wait for a prompt
+#
+                cat << EOF
+=== Type <ENTER> if the CENJU-3 nodes requested for JID \`\`$easy_jid''
+===                 are available (i.e. if you got mail) :"
+=== After that, this script will start the parallel program
+=== \`\`$progname''.
+
+EOF
+#
+                read answer
+                if [ $? != 0 ]
+                then
+                   echo '### Error in read : Probably attempted background read'
+                exit 1
+                fi 
+             fi
+#
+#===> Start parallel program
+#
+             $Show ${easybin}prun -j $easy_jid -n $np -p $progname -a \"$cmdLineArgs\"
+#
+#===> Release nodes allocated
+#
+             $Show ${easybin}prelease $easy_jid < /dev/null
+          fi
+          ;;
+
+       CJ | *)
+#
+#===> Get number of processors available
+#
+          free=`cjpes | fgrep ST_PE_ACTIV | wc -l`
+          if [ $mpirun_verbose = 1 -o "$free" -lt $np ] ; then
+             echo === waiting for $np processors available
+          fi
+#
+          $Show cjsh -w -n $np $progname $cmdLineArgs
+#
+          ;;
+       esac
     fi
+#
+    exit 0
