1.2.6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -236,7 +236,7 @@ specify options for just the C or Fortran compilers.  Use -cflags and
 -fflags for options not related to optimization.  
 
 Note that the '-opt' options are not passed to the 'mpicc', 'mpif77', 
-'mpiCC', and 'mpif90' scripts.  The '-opt' options are used only in 
+'mpicxx', and 'mpif90' scripts.  The '-opt' options are used only in 
 building MPICH.
 
 The option '-lib' allows you to specify the location of a library that
@@ -1363,6 +1363,11 @@ esac
 # Save the original args to write them into config.status later.
 configure_args="$*"
 
+#
+# Export variables that should be used by all called scripts and configure
+export OPTFLAGS
+export OPTFLAGSC
+export OPTFLAGSF
 
 # We may need to delete this
 
@@ -7317,7 +7322,7 @@ if test -f "$srcdir/mpid/$DEVICE/$device_setupfile" ; then
     if test ! -x "$top_srcdir_val/mpid/$DEVICE/configure" -a \
 	      -s "$top_srcdir_val/mpid/$DEVICE/configure.in" -a \
 	      -x "$top_srcdir_val/mpid/$DEVICE/makeconfigure" ; then
-	(cd "$top_srcdir_val/mpid/$DEVICE" ; ./makeconfigure)
+	(cd "$top_srcdir_val/mpid/$DEVICE" && ./makeconfigure)
     fi
     echo "Running device-specific setup program"
     #
@@ -11083,6 +11088,9 @@ DEFS="$SAVEDEFS"
 #
 # Test that the functions used by the device are availble to the C++ and
 # Fortran compilers.
+# FIXME:
+# Not all systems use or need gethostbyname.  (One was Jason OS)
+# The name of these functions should be provided by the device.
 testfuncs="gethostbyname"
 if test -n "$device_functions" ; then 
     testfuncs="$testfuncs $device_functions"
@@ -14175,7 +14183,12 @@ SEDDEFS="${SEDDEFS}\${SEDdA}POINTER_64_BITS\${SEDdB}POINTER_64_BITS\${SEDdC}1\${
 }
 
 fi
-Pac_name="void *"
+# Normally, we compute AINT_SIZE to be the same as the size of void *.  
+# However, in some situations, we may want to use something larger
+# than the size of void*.  By setting MPI_AINT_SIZE, we can bypass the
+# code that computes the size of void *
+if test -z "MPI_AINT_SIZE" ; then
+    Pac_name="void *"
  Pac_varname=`echo "$Pac_name" | sed -e 's/ /_/g' -e 's/\*/star/g'`
 eval Pac_testval=\$"${Pac_varname}_len"
 if test -z "$Pac_testval" ; then
@@ -14293,9 +14306,10 @@ echo "$ac_t""unavailable" 1>&1
 fi
  fi
 fi
-address_size=$Pac_CV_NAME
+MPI_AINT_SIZE=$Pac_CV_NAME
 
-if test "$address_size" != "unknown" ; then
+fi
+if test "$MPI_AINT_SIZE" != "unknown" ; then
     if test -z "$ac_echo_n" ; then
 ac_echo_n=yes
 if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
@@ -14327,14 +14341,15 @@ echo "$ac_t"""
 else
 echo "$ac_t""" 1>&1
 fi
-    for c_type in int long short "long long" ; do
-        Pac_name="$c_type"
+    # We'd like to use a loop here, but the pac GET_TYPE_SIZE
+    # macro requires an autoconf-time constant
+    Pac_name="int"
  Pac_varname=`echo "$Pac_name" | sed -e 's/ /_/g' -e 's/\*/star/g'`
 eval Pac_testval=\$"${Pac_varname}_len"
 if test -z "$Pac_testval" ; then
    
       
-   eval Pac_testval=\$"CROSS_SIZEOF_$C_TYPE"
+   eval Pac_testval=\$"CROSS_SIZEOF_INT"
 fi
 if test -n "$Pac_testval" ; then
     Pac_CV_NAME=$Pac_testval
@@ -14448,12 +14463,388 @@ fi
 fi
 type_len=$Pac_CV_NAME
 
-        if test "$type_len" = "$address_size" ; then
-            MPI_AINT_FOUND=yes
-	    MPI_AINT=$c_type
-            break
+    if test "$type_len" = "$MPI_AINT_SIZE" ; then
+        MPI_AINT_FOUND=yes
+        MPI_AINT=int
+    fi
+    if test "$MPI_AINT_FOUND" != yes ; then 
+        Pac_name="long"
+ Pac_varname=`echo "$Pac_name" | sed -e 's/ /_/g' -e 's/\*/star/g'`
+eval Pac_testval=\$"${Pac_varname}_len"
+if test -z "$Pac_testval" ; then
+   
+      
+   eval Pac_testval=\$"CROSS_SIZEOF_LONG"
+fi
+if test -n "$Pac_testval" ; then
+    Pac_CV_NAME=$Pac_testval
+else
+ if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for size of $Pac_name""... $ac_c"
+else
+echo $ac_n "checking for size of $Pac_name""... $ac_c" 1>&1
+fi
+ /bin/rm -f conftestval
+ 
+
+if test "$cross_compiling" = 1 -a -z "$TESTCC" ; then
+    
+    Pac_CV_NAME=0
+else
+    if test -n "$TESTCC" ; then
+      CCsav="$CC"
+      CC="$TESTCC"
+    fi
+    cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <stdio.h>
+main() { 
+  FILE *f=fopen("conftestval","w");
+  if (!f) exit(1);
+  fprintf( f, "%d\n", sizeof($Pac_name));
+  exit(0);
+}
+EOF
+        if test -n "$compile" ; then 	
+	eval $compile
+    else
+	eval $ac_compile
+	eval $ac_link
+    fi
+    if test ! -s conftest ; then
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
         fi
-    done
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+    Pac_CV_NAME=""
+
+    else
+      /bin/rm -f conftestout
+      if test -s conftest && (./conftest; exit) 2>conftestout; then
+          Pac_CV_NAME=`cat conftestval`
+
+      else
+        Pac_CV_NAME=""
+
+	if test -s conftestout ; then cat conftestout >> config.log ; fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+        
+      fi
+    fi
+  if test -n "$TESTCC" ; then
+        CC="$CCsav"
+  fi
+  rm -fr conftest*
+fi
+
+ if test -n "$Pac_CV_NAME" -a "$Pac_CV_NAME" != 0 ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""$Pac_CV_NAME"
+else
+echo "$ac_t""$Pac_CV_NAME" 1>&1
+fi
+    eval ${Pac_varname}_len=$Pac_CV_NAME
+ else
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""unavailable"
+else
+echo "$ac_t""unavailable" 1>&1
+fi
+ fi
+fi
+type_len=$Pac_CV_NAME
+
+        if test "$type_len" = "$MPI_AINT_SIZE" ; then
+            MPI_AINT_FOUND=yes
+            MPI_AINT=long
+        fi
+    fi
+    if test "$MPI_AINT_FOUND" != yes ; then 
+        Pac_name="short"
+ Pac_varname=`echo "$Pac_name" | sed -e 's/ /_/g' -e 's/\*/star/g'`
+eval Pac_testval=\$"${Pac_varname}_len"
+if test -z "$Pac_testval" ; then
+   
+      
+   eval Pac_testval=\$"CROSS_SIZEOF_SHORT"
+fi
+if test -n "$Pac_testval" ; then
+    Pac_CV_NAME=$Pac_testval
+else
+ if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for size of $Pac_name""... $ac_c"
+else
+echo $ac_n "checking for size of $Pac_name""... $ac_c" 1>&1
+fi
+ /bin/rm -f conftestval
+ 
+
+if test "$cross_compiling" = 1 -a -z "$TESTCC" ; then
+    
+    Pac_CV_NAME=0
+else
+    if test -n "$TESTCC" ; then
+      CCsav="$CC"
+      CC="$TESTCC"
+    fi
+    cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <stdio.h>
+main() { 
+  FILE *f=fopen("conftestval","w");
+  if (!f) exit(1);
+  fprintf( f, "%d\n", sizeof($Pac_name));
+  exit(0);
+}
+EOF
+        if test -n "$compile" ; then 	
+	eval $compile
+    else
+	eval $ac_compile
+	eval $ac_link
+    fi
+    if test ! -s conftest ; then
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+    Pac_CV_NAME=""
+
+    else
+      /bin/rm -f conftestout
+      if test -s conftest && (./conftest; exit) 2>conftestout; then
+          Pac_CV_NAME=`cat conftestval`
+
+      else
+        Pac_CV_NAME=""
+
+	if test -s conftestout ; then cat conftestout >> config.log ; fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+        
+      fi
+    fi
+  if test -n "$TESTCC" ; then
+        CC="$CCsav"
+  fi
+  rm -fr conftest*
+fi
+
+ if test -n "$Pac_CV_NAME" -a "$Pac_CV_NAME" != 0 ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""$Pac_CV_NAME"
+else
+echo "$ac_t""$Pac_CV_NAME" 1>&1
+fi
+    eval ${Pac_varname}_len=$Pac_CV_NAME
+ else
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""unavailable"
+else
+echo "$ac_t""unavailable" 1>&1
+fi
+ fi
+fi
+type_len=$Pac_CV_NAME
+
+        if test "$type_len" = "$MPI_AINT_SIZE" ; then
+            MPI_AINT_FOUND=yes
+            MPI_AINT=short
+        fi
+    fi
+    if test "$MPI_AINT_FOUND" != yes ; then 
+        Pac_name="long long"
+ Pac_varname=`echo "$Pac_name" | sed -e 's/ /_/g' -e 's/\*/star/g'`
+eval Pac_testval=\$"${Pac_varname}_len"
+if test -z "$Pac_testval" ; then
+   
+      
+   eval Pac_testval=\$"CROSS_SIZEOF_LONG_LONG"
+fi
+if test -n "$Pac_testval" ; then
+    Pac_CV_NAME=$Pac_testval
+else
+ if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for size of $Pac_name""... $ac_c"
+else
+echo $ac_n "checking for size of $Pac_name""... $ac_c" 1>&1
+fi
+ /bin/rm -f conftestval
+ 
+
+if test "$cross_compiling" = 1 -a -z "$TESTCC" ; then
+    
+    Pac_CV_NAME=0
+else
+    if test -n "$TESTCC" ; then
+      CCsav="$CC"
+      CC="$TESTCC"
+    fi
+    cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <stdio.h>
+main() { 
+  FILE *f=fopen("conftestval","w");
+  if (!f) exit(1);
+  fprintf( f, "%d\n", sizeof($Pac_name));
+  exit(0);
+}
+EOF
+        if test -n "$compile" ; then 	
+	eval $compile
+    else
+	eval $ac_compile
+	eval $ac_link
+    fi
+    if test ! -s conftest ; then
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+    Pac_CV_NAME=""
+
+    else
+      /bin/rm -f conftestout
+      if test -s conftest && (./conftest; exit) 2>conftestout; then
+          Pac_CV_NAME=`cat conftestval`
+
+      else
+        Pac_CV_NAME=""
+
+	if test -s conftestout ; then cat conftestout >> config.log ; fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+        
+      fi
+    fi
+  if test -n "$TESTCC" ; then
+        CC="$CCsav"
+  fi
+  rm -fr conftest*
+fi
+
+ if test -n "$Pac_CV_NAME" -a "$Pac_CV_NAME" != 0 ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""$Pac_CV_NAME"
+else
+echo "$ac_t""$Pac_CV_NAME" 1>&1
+fi
+    eval ${Pac_varname}_len=$Pac_CV_NAME
+ else
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""unavailable"
+else
+echo "$ac_t""unavailable" 1>&1
+fi
+ fi
+fi
+type_len=$Pac_CV_NAME
+
+        if test "$type_len" = "$MPI_AINT_SIZE" ; then
+            MPI_AINT_FOUND=yes
+            MPI_AINT="long long"
+        fi
+    fi
     
 if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo $ac_n "C integer type for MPI_Aint is""... $ac_c"
@@ -15587,7 +15978,7 @@ fi
 if test "$NO_F90" = "0" ; then 
     MPIF90=$binbuild_dir/mpif90
 fi
-MPICPLUSPLUS=$binbuild_dir/mpiCC
+MPICPLUSPLUS=$binbuild_dir/mpicxx
 ### FIXME: IS THIS CORRECT OR NEEDED???
 LIB_DIR=$exec_prefix
 #
@@ -15618,7 +16009,7 @@ if test "$NOF77" != 1 ; then
   if test ! -x "$top_srcdir_val/src/fortran/configure" -a \
             -s "$top_srcdir_val/src/fortran/configure.in" -a \
 	    -x "$top_srcdir_val/src/fortran/makeconfigure" ; then
-      (cd "$top_srcdir_val/src/fortran" ; ./makeconfigure)
+      (cd "$top_srcdir_val/src/fortran" && ./makeconfigure)
   fi
   # The test versions (e.g., TESTCC) are used for cross-compilation cases when
   # they allow programs to be built and run
@@ -15887,6 +16278,9 @@ if test $ROMIO = 1 -a -d "${top_srcdir}/romio" ; then
   MPI_BIN_DIR=$binbuild_dir 
   MPI_LIB=$libbuild_dir/lib$MPILIBNAME.a
   MPI_INCLUDE_DIR=$includebuild_dir
+  # We force the romio configure to use a null cache file.  Without this,
+  # ROMIO may pick up its local config.cache, which may not be current
+  # (autoconf caching is very dangerous)
   (cd romio ; \
   LIBNAME=$libbuild_dir/lib$MPILIBNAME.a ; export LIBNAME ; \
   export MPI_BIN_DIR ; export MPI_LIB ; export MPI_INCLUDE_DIR ; \
@@ -15901,7 +16295,8 @@ if test $ROMIO = 1 -a -d "${top_srcdir}/romio" ; then
   export int_len ; export void_star_len ; export OFFSET_KIND ; \
   export long_long_len ; \
   "${top_srcdir}/romio/configure" $ROMIO_ARGS $ROMIO_FILE_SYSTEM \
-            --with-mpi=mpich $romio_config_args $enable_args $with_args )
+            --with-mpi=mpich $romio_config_args $enable_args $with_args \
+            --cache-file=/dev/null )
   rc=$?
   if test "$rc" != 0 ; then
       if test -z "$ac_echo_test" -a 1 = 1 ; then
@@ -15956,8 +16351,11 @@ exit 1
   # If a VPATH build, the examples dir may not exist
   if test ! -d examples ; then mkdir examples ; fi
   if test ! -d examples/test ; then mkdir examples/test ; fi
-  (cd examples; \rm -f io; ln -s ../romio/test io; \
-   (cd test; \rm -f io; ln -s ../../romio/test io))
+  # We do not create the io link because we need to have the 
+  # test configure create these files, using sources copied from
+  # the romio distribution
+  (cd examples && rm -f io && ln -s ../romio/test io )
+  #  (cd examples/test && rm -f io && ln -s ../../romio/test io)
   echo "Finished configuring ROMIO"
 fi
 if test "$ROMIO" = 1 ; then
@@ -16007,6 +16405,62 @@ fi
 if test "$Use_Intercomm_coll" = "yes" ; then
     MPI2OPTIONAL="src/coll2"
 fi
+#
+# Check for the command line format for head.  Some versions of the GNU
+# utilities no longer accept the arguments for the classic head command,
+# making any script that uses head non-portable (this was a very bad thing
+# for GNU to do).
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking whether head command is broken""... $ac_c"
+else
+echo $ac_n "checking whether head command is broken""... $ac_c" 1>&1
+fi
+ac_cv_prog_head_ok=no
+rm -f conftest
+echo "line 1" > conftest
+echo "line 2" >> conftest
+nline=`head -1 conftest 2>&1`
+if test "$nline" = "line 1" ; then
+    ac_cv_prog_head_ok=yes
+fi
+rm -f conftest
+if test "$ac_cv_prog_head_ok" = yes ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+    HEADARG="-"
+else
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes (incompatible syntax)"
+else
+echo "$ac_t""yes (incompatible syntax)" 1>&1
+fi
+    HEADARG="-n "
+fi
+
 #
 # Substitute variables
 # Variables used in scripts only
@@ -16176,6 +16630,7 @@ F77_IN_C_LIBS='$F77_IN_C_LIBS'
 F90_SUFFIX='$F90_SUFFIX'
 F90_MODINCFLAG='$F90_MODINCFLAG'
 FLIBNAME='$FLIBNAME'
+HEADARG='$HEADARG'
 AUTOMOUNTFIX='$AUTOMOUNTFIX'
 RSHCOMMAND='$RSHCOMMAND'
 SYNCLOC='$SYNCLOC'
@@ -16345,6 +16800,7 @@ s%@F77_IN_C_LIBS@%$F77_IN_C_LIBS%g
 s%@F90_SUFFIX@%$F90_SUFFIX%g
 s%@F90_MODINCFLAG@%$F90_MODINCFLAG%g
 s%@FLIBNAME@%$FLIBNAME%g
+s%@HEADARG@%$HEADARG%g
 s%@AUTOMOUNTFIX@%$AUTOMOUNTFIX%g
 s%@RSHCOMMAND@%$RSHCOMMAND%g
 s%@SYNCLOC@%$SYNCLOC%g
@@ -16369,8 +16825,8 @@ s%@DEFAULT_MACHINE@%$DEFAULT_MACHINE%g
 s%@DEVCFLAGS@%$DEVCFLAGS%g
 s%@DEVCFILES@%$DEVCFILES%g
 s%@DEVOFILES@%$DEVOFILES%g
-s%@DEV_DEFS@%$DEV_DEFS%g
-s%@DEVICE@%$DEVICE%g" | sed -e "
+s%@DEV_DEFS@%$DEV_DEFS%g" | sed -e "
+s%@DEVICE@%$DEVICE%g
 s%@DEVICE_MAKE_INCLUDE@%$DEVICE_MAKE_INCLUDE%g
 s%@F77@%$F77%g
 s%@FAST_COPY@%$FAST_COPY%g
@@ -16411,8 +16867,8 @@ s%@NEWTESTDIRS@%$NEWTESTDIRS%g
 s%@OPTFLAGS@%$OPTFLAGS%g
 s%@OPTFLAGSC@%$OPTFLAGSC%g
 s%@OPTFLAGSF@%$OPTFLAGSF%g
-s%@P4_ARCH@%$P4_ARCH%g
-s%@P4_DIR@%$P4_DIR%g" | sed -e "
+s%@P4_ARCH@%$P4_ARCH%g" | sed -e "
+s%@P4_DIR@%$P4_DIR%g
 s%@RHS_COMMAND@%$RHS_COMMAND%g
 s%@PREFIX@%$PREFIX%g
 s%@USER_CFLAGS@%$USER_CFLAGS%g
@@ -16671,7 +17127,7 @@ fi
 if test ! -x "$top_srcdir_val/examples/perftest/configure" -a \
           -s "$top_srcdir_val/examples/perftest/configure.in" -a \
 	  -x "$top_srcdir_val/examples/perftest/makeconfigure" ; then
-    (cd "$top_srcdir_val/examples/perftest" ; ./makeconfigure)
+    (cd "$top_srcdir_val/examples/perftest" && ./makeconfigure)
 fi
 (cd examples/perftest ; \
     export MAKE ; export CC ; export F77 ; export MPICC ; export MPIF77 ; \
diff --git a/mpid/ch_p4/p4/configure b/mpid/ch_p4/p4/configure
--- a/mpid/ch_p4/p4/configure
+++ b/mpid/ch_p4/p4/configure
@@ -42,7 +42,8 @@ MDEP_LIBS=
 MDEP_CFLAGS=
 MDEP_FFLAGS=
 MDEP_LFLAGS=
-OPTFLAGS="-g"
+# Use imported optflags if possible
+OPTFLAGS=${OPTFLAGS:-"-g"}
 USERCC=0
 CC=${CC:-cc}
 USERF77=0
@@ -455,6 +456,14 @@ fi
 #						486 running FreeBSD
 if test -n "$p4arch_FREEBSD"; then
     P4ARCH=FREEBSD
+    if test -n "$p4comm_shared"; then
+      DEFINE_SYSV_IPC="#define SYSV_IPC"
+    fi
+fi
+
+if test -n "$p4arch_FREEBSD_PPC"; then
+    # This may be Darwin as well.
+    P4ARCH=FREEBSD_PPC
     if test -n "$p4comm_shared"; then
       DEFINE_SYSV_IPC="#define SYSV_IPC"
     fi
@@ -7682,6 +7691,157 @@ fi
 fi
 done
 
+# time.h is needed to declare time
+# Note.  On some systems, including both time.h and sys/time.h can 
+# cause problems.  autoconf2 has a special test for this
+ac_cv_both_time_systime=no
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking that time.h and sys/time.h can both be included""... $ac_c"
+else
+echo $ac_n "checking that time.h and sys/time.h can both be included""... $ac_c" 1>&1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <sys/time.h>
+#include <time.h>
+int main() {
+struct tm *tp;
+; return 0; }
+EOF
+eval $compile
+if test -s conftest && (./conftest; exit) 2>/dev/null; then
+  ac_cv_both_time_systime=yes
+
+fi
+rm -fr conftest*
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""$ac_cv_both_time_systime"
+else
+echo "$ac_t""$ac_cv_both_time_systime" 1>&1
+fi
+if test "$ac_cv_both_time_systime" = yes ; then
+    
+{
+test -n "$verbose" && \
+echo "	defining TIME_WITH_SYS_TIME"
+echo "#define" TIME_WITH_SYS_TIME 1 >> confdefs.h
+DEFS="$DEFS -DTIME_WITH_SYS_TIME=1"
+}
+
+fi
+
+for ac_hdr in time.h
+do
+ac_safe=`echo "$ac_hdr" | tr '[a-z]./' '[A-Z]__'`
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for $ac_hdr""... $ac_c"
+else
+echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+
+#include <$ac_hdr>
+int main() { exit(0); }
+int t() { main(); }
+EOF
+if eval $compile; then
+  
+  
+  eval "ac_cv_header_$ac_safe=yes"
+
+else
+  expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+  eval echo "configure:$expandcompile" >> config.log
+  echo "configure: failed program was:" >>config.log
+  cat confdefs.h >> config.log
+  cat conftest.c >> config.log
+  if test -s conftest.out ; then cat conftest.out >> config.log 
+  else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+  fi
+  eval "ac_cv_header_$ac_safe=no"
+   
+fi
+rm -f conftest*
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+    ac_tr_hdr=HAVE_`echo $ac_hdr | tr '[a-z]./' '[A-Z]__'`
+  
+{
+test -n "$verbose" && \
+echo "	defining $ac_tr_hdr"
+echo "#define" $ac_tr_hdr 1 >> confdefs.h
+DEFS="$DEFS -D$ac_tr_hdr=1"
+}
+ 
+else
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+fi
+done
+
 #
 # In some cases, we need both string.h and strings.h .  Some systems
 # apparently complain, so we try to include them both
@@ -10192,6 +10352,99 @@ DEFS="$DEFS -DUSE_YIELD=1"
 
 fi
 
+# Check for the getwd function (used in alog/alog.h)
+for func in getwd
+do
+trfunc=HAVE_`echo $func | tr '[a-z]' '[A-Z]'`
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for ${func}""... $ac_c"
+else
+echo $ac_n "checking for ${func}""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <ctype.h>
+int main() { exit(0); }
+int t() { 
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_${func}) || defined (__stub___${func})
+choke me
+#else
+/* Override any gcc2 internal prototype to avoid an error.  */
+extern char ${func}(); ${func}();
+#endif
+ }
+EOF
+if eval $compile; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+  
+  {
+test -n "$verbose" && \
+echo "	defining ${trfunc}"
+echo "#define" ${trfunc} 1 >> confdefs.h
+DEFS="$DEFS -D${trfunc}=1"
+}
+
+
+   else if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+    expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+    eval echo "configure:$expandcompile" >> config.log
+    echo "configure: failed program was:" >>config.log
+    cat confdefs.h >> config.log
+    cat conftest.c >> config.log
+    if test -s conftest.out ; then cat conftest.out >> config.log 
+    else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+    fi
+
+fi
+rm -f conftest*
+done
+
+
 #
 # Test for sgttyb and the ability to set noecho on terminals
 if test -z "$ac_echo_n" ; then
@@ -10702,7 +10955,6 @@ fi
 fi
 #
 #
-#
 # Some systems don't include support for xdr.  Check for it.
 # Also, some versions of FreeBSD don't inlude xdr_float (later ones apparently
 # do).  Check for that as well.
@@ -10881,8 +11133,211 @@ fi
 fi
 rm -f conftest*
 
+
+# Before asserting that we have XDR, check that it works in this environment:
+
+#
+# Some combinations of compilers and operating systems expose inconsistent
+# system header files.  For example, the Intel version 8 compilers claim to 
+# be gcc (but they aren't, causing other problems), but at least the SuSE 
+# Linux header files fail to define int64_t unless GCC is specified but 
+# use int64_t unconditionally.  
+#
+if test "$HAS_XDR" = 1 ; then 
+    if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for rpc/xdr.h compiles""... $ac_c"
+else
+echo $ac_n "checking for rpc/xdr.h compiles""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+
+#include <sys/types.h>
+#include <rpc/xdr.h>
+int main() { exit(0); }
+int t() { return 0; }
+EOF
+if eval $compile; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+  
+  xdr_compiles=yes
+
+else
+  expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+  eval echo "configure:$expandcompile" >> config.log
+  echo "configure: failed program was:" >>config.log
+  cat confdefs.h >> config.log
+  cat conftest.c >> config.log
+  if test -s conftest.out ; then cat conftest.out >> config.log 
+  else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+  fi
+  xdr_compiles=no
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+    expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+    eval echo "configure:$expandcompile" >> config.log
+    echo "configure: failed program was:" >>config.log
+    cat confdefs.h >> config.log
+    cat conftest.c >> config.log
+    if test -s conftest.out ; then cat conftest.out >> config.log 
+    else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+    fi
+
+fi
+rm -f conftest*
+
+    if test "$xdr_compiles" != "yes" ; then
+        # See if we need to define int64_t and uint64_t
+	# FIXME: We should really check that sizeof(long long) is 8
+        if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for that xdr.h compiles if int64_t defined""... $ac_c"
+else
+echo $ac_n "checking for that xdr.h compiles if int64_t defined""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+
+#include <sys/types.h>
+typedef long long int64_t;
+typedef unsigned long long uint64_t;
+#include <rcp/xdr.h>
+int main() { exit(0); }
+int t() { return 0; }
+EOF
+if eval $compile; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+  
+  xdr_needs_int64=yes
+
+else
+  expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+  eval echo "configure:$expandcompile" >> config.log
+  echo "configure: failed program was:" >>config.log
+  cat confdefs.h >> config.log
+  cat conftest.c >> config.log
+  if test -s conftest.out ; then cat conftest.out >> config.log 
+  else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+  fi
+  xdr_needs_int64=no
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+    expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+    eval echo "configure:$expandcompile" >> config.log
+    echo "configure: failed program was:" >>config.log
+    cat confdefs.h >> config.log
+    cat conftest.c >> config.log
+    if test -s conftest.out ; then cat conftest.out >> config.log 
+    else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+    fi
+
+fi
+rm -f conftest*
+
+        if test "$xdr_needs_int64" = "yes" ;then
+	    
+{
+test -n "$verbose" && \
+echo "	defining NEEDS_INT64_DEFINITION"
+echo "#define" NEEDS_INT64_DEFINITION 1 >> confdefs.h
+DEFS="$DEFS -DNEEDS_INT64_DEFINITION=1"
+}
+
+        else
+	    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: Unable to compile header file rcp/xdr.h"
+else
+echo "$ac_t""Warning: Unable to compile header file rcp/xdr.h" 1>&1
+fi
+	    HAS_XDR=0
+        fi
+    fi
+fi
 if test "$HAS_XDR" = 1 ; then
-	
+    
 {
 test -n "$verbose" && \
 echo "	defining HAS_XDR"
@@ -11169,6 +11624,15 @@ echo "#define" P4_DO_NOT_USE_SERVER 1 >> confdefs.h
 DEFS="$DEFS -DP4_DO_NOT_USE_SERVER=1"
 }
 
+    # If we don't find the needed headers, about the configuration
+    if test "$ac_cv_header_SYS_BPROC_H" != yes ; then
+        if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Error: Unable to build with bproc because sys/bproc.h is not available"
+else
+echo "$ac_t""Error: Unable to build with bproc because sys/bproc.h is not available" 1>&1
+fi
+exit 1
+    fi    
 fi
 #
 # We do NOT add the CFLAGS and DEFS to the MDEP_CFLAGS because they are 
diff --git a/mpid/ch_shmem/configure b/mpid/ch_shmem/configure
--- a/mpid/ch_shmem/configure
+++ b/mpid/ch_shmem/configure
@@ -754,7 +754,7 @@ else
 fi
 echo "$ac_t""$CPP" 1>&1
 
-for ac_hdr in sched.h
+for ac_hdr in sched.h errno.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&1
@@ -1819,8 +1819,8 @@ else
 fi
 rm -f conftest*
 #
-# Look for sigaction routine (instead of signal)
-for ac_hdr in signal.h
+# Check for important headers
+for ac_hdr in stdlib.h unistd.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&1
@@ -1860,12 +1860,54 @@ else
 fi
 done
 
+#
+# Look for sigaction routine (instead of signal)
+for ac_hdr in signal.h
+do
+ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&1
+echo "configure:1870: checking for $ac_hdr" >&2
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&1
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1875 "configure"
+#include "confdefs.h"
+#include <$ac_hdr>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1880: \"$ac_try\") 1>&2; (eval $ac_try) 2>&2; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&2
+  echo "configure: failed program was:" >&2
+  cat conftest.$ac_ext >&2
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&1
+    ac_tr_hdr=HAVE_`echo $ac_hdr | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+ 
+else
+  echo "$ac_t""no" 1>&1
+fi
+done
+
 for ac_func in sigaction
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:1867: checking for $ac_func" >&2
+echo "configure:1909: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 1869 "configure"
+#line 1911 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -1886,7 +1928,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1890: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1932: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1911,9 +1953,9 @@ done
 # To use sigaction, you also need the struct sigaction.  We've had
 # some systems mess this up
 echo $ac_n "checking for struct sigaction""... $ac_c" 1>&1
-echo "configure:1915: checking for struct sigaction" >&2
+echo "configure:1957: checking for struct sigaction" >&2
 cat > conftest.$ac_ext <<EOF
-#line 1917 "configure"
+#line 1959 "configure"
 #include "confdefs.h"
 #include <signal.h>
 int main() {
@@ -1921,7 +1963,7 @@ int main() {
 struct sigaction act; sigaddset( &act.sa_mask, SIGINT );
 ; return 0; }
 EOF
-if { (eval echo configure:1925: \"$ac_compile\") 1>&2; (eval $ac_compile) 2>&2; }; then
+if { (eval echo configure:1967: \"$ac_compile\") 1>&2; (eval $ac_compile) 2>&2; }; then
   rm -rf conftest*
   sigaction_ok="yes"
 else
@@ -1935,9 +1977,9 @@ echo "$ac_t""$sigaction_ok" 1>&1
 for ac_func in sigprocmask signal sigmask sigset
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:1939: checking for $ac_func" >&2
+echo "configure:1981: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 1941 "configure"
+#line 1983 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -1958,7 +2000,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1962: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2004: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1984,9 +2026,9 @@ done
 # one SGI installation had trouble with this.
 if test "$ac_cv_func_sigprocmask" = "yes" ; then
     echo $ac_n "checking that sigset_t is defined""... $ac_c" 1>&1
-echo "configure:1988: checking that sigset_t is defined" >&2
+echo "configure:2030: checking that sigset_t is defined" >&2
     cat > conftest.$ac_ext <<EOF
-#line 1990 "configure"
+#line 2032 "configure"
 #include "confdefs.h"
 
 #include <signal.h>
@@ -1995,7 +2037,7 @@ int main() {
 sigset_t newset;
 ; return 0; }
 EOF
-if { (eval echo configure:1999: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2041: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   echo "$ac_t""yes" 1>&1
 else
@@ -2013,7 +2055,7 @@ fi
 
 
 echo $ac_n "checking that signals work correctly""... $ac_c" 1>&1
-echo "configure:2017: checking that signals work correctly" >&2
+echo "configure:2059: checking that signals work correctly" >&2
 cat >conftest.c <<EOF
 #include <signal.h>
 static int rc = 0, irc = 1, maxcnt=5;
@@ -2056,12 +2098,12 @@ fi
 /bin/rm -f conftest conftest.c conftest.o conftest.out
 
 echo $ac_n "checking return type of signal handlers""... $ac_c" 1>&1
-echo "configure:2060: checking return type of signal handlers" >&2
+echo "configure:2102: checking return type of signal handlers" >&2
 if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
   cat > conftest.$ac_ext <<EOF
-#line 2065 "configure"
+#line 2107 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -2078,7 +2120,7 @@ int main() {
 int i;
 ; return 0; }
 EOF
-if { (eval echo configure:2082: \"$ac_compile\") 1>&2; (eval $ac_compile) 2>&2; }; then
+if { (eval echo configure:2124: \"$ac_compile\") 1>&2; (eval $ac_compile) 2>&2; }; then
   rm -rf conftest*
   ac_cv_type_signal=void
 else
@@ -2100,9 +2142,9 @@ EOF
 for ac_func in gettimeofday BSDgettimeofday
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:2104: checking for $ac_func" >&2
+echo "configure:2146: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 2106 "configure"
+#line 2148 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -2123,7 +2165,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:2127: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2169: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
