1.0.12

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,7 +1,7 @@
 # create Makefile from this file with configure script
 ##### User configurable options #####
 ALL: mpi
-ARCH        = @ARCH@
+LARCH       = @ARCH@
 COMM        = @COMM@
 DEVICE      = @DEVICE@
 BOPT        = @BOPT@
@@ -30,11 +30,10 @@ DIRS     = $(MPIDIRS) mpid/$(DEVICE) @CPP_DIR@ @MPE_DIR@ \
 # This is a list of the devices that are available
 DEVICES  = mpid/chameleon mpid/ch_nx mpid/ch_p4 mpid/ch_nc mpid/ch_cmmd \
 	   mpid/ch_eui mpid/meiko mpid/t3d mpid/ch_meiko mpid_ch_shmem \
-	   mpid/ch_tcp mpid/ch_spp mpid/sgi mpid/nx
+	   mpid/ch_tcp mpid/sgi mpid/nx
 OTHERDEVICES  = mpid/ch_nx mpid/ch_p4 mpid/ch_nc mpid/ch_cmmd mpid/ch_eui \
 		mpid/ch_meiko mpid/ch_shmem mpid/t3d \
-		mpid/ch_spp mpid/sgi mpid/nx
-# mpid/ch_tcp 
+		mpid/sgi mpid/nx
 # 
 # Build the device FIRST in case the device include, used in mpiimpl.h, 
 # needs to be built (e.g., ch_p4 device)
@@ -57,8 +56,14 @@ mpi:
 	$(MAKE) clean
 	$(MAKE) profile
 	$(MAKE) clean
+	@if [ $(COMM) = "ch_p4" ] ; then \
+	    echo "You may want to do" ; \
+	    echo "    $(MAKE) serv_p4" ; \
+	    echo "as well." ; \
+	fi
 	/bin/rm -f util/mpirun
 	$(MAKE) mpirun
+	/bin/rm -f util/mpireconfig
 	$(MAKE) mpireconfig
 	$(MAKE) mpiman
 	$(MAKE) upshot
@@ -66,12 +71,12 @@ mpi:
 	@echo "Also try executing 'make testing' in examples/test"
 	@echo "(This relies on mpirun, which currently works for many"
 	@echo "but not all systems.  mpirun requires that you first"
-	@echo "setup the util/machines/machines.$(ARCH) file for the"
+	@echo "setup the util/machines/machines.$(LARCH) file for the"
 	@echo "ch_p4 device.  Other devices do not need that file)."
 	@echo " "
 	@echo "Send bugs and comments to mpi-bugs@mcs.anl.gov"
 	@echo "With any bug report, please send"
-	@echo "     The version of MPICH (e.g., 1.0.10)"
+	@echo "     The version of MPICH (e.g., 1.0.12)"
 	@echo " "
 	@echo "The output of running your program with the -mpiversion argument"
 	@echo "(e.g., mpirun -np 1 a.out -mpiversion)"
@@ -95,23 +100,44 @@ examples: util/mpirun
 linktest:
 	( cd examples/test/pt2pt; $(MAKE) linktest )
 
+#
+# This is the target for the report function.  The optional lines on the make
+# are
+#   AUTHOR=string
+#   CONFIGLOG=file
+#
+report:
+	( if [ -n "$(AUTHOR)" ] ; then auth=-author="$(AUTHOR)" ; fi ; \
+	  if [ -n "$(CONFIGLOG)" ] ; then conf=-config=$(CONFIGLOG) ; fi ; \
+	doc/port -dotest $$auth $$conf ; )
+	doc/docgather
+	mv doc.tar doc$(ARCH)$(DEVICE).tar
+	@echo "Final location of tar file is doc$(DEVICE).tar"
+	@echo "util/insttest -prefix=install_directory"
+	@echo "may be run to complete the testing.  This must be run"
+	@echo "in the foreground.  It will try to start Upshot and Nupshot."
+	@echo "It also does an installation into 'install_directory'"
+	
 
-
+#
+# Make sure that a failure during the make causes the make to stop at 
+# that point.
 mpilib: Makefile.in
 	@for dir in $(CODEDIRS) ;\
 	  do \
 	  echo " " ;\
 	  echo making mpir in directory $$dir ;\
 	  (cd $$dir; \
-	  $(MAKE) default_all ;) ;\
+	  $(MAKE) default_all ; if [ $$? != 0 ] ; then \
+		echo "Exit status from make was $$?" ; exit 1 ; fi ;) ;\
 	  done
-	@RANLIB@ lib/$(ARCH)/$(COMM)/libmpi.a
-	@if test -w lib/$(ARCH)/$(COMM)/libmpi++.a ; then \
-		@RANLIB@ lib/$(ARCH)/$(COMM)/libmpi++.a ; fi
-	@if test -w lib/$(ARCH)/$(COMM)/libmpe.a ; then \
-		@RANLIB@ lib/$(ARCH)/$(COMM)/libmpe.a ; fi
-	@if test -w lib/$(ARCH)/$(COMM)/libmpe_nompi.a ; then \
-		@RANLIB@ lib/$(ARCH)/$(COMM)/libmpe_nompi.a ; fi
+	@RANLIB@ lib/$(LARCH)/$(COMM)/libmpi.a
+	@if test -w lib/$(LARCH)/$(COMM)/libmpi++.a ; then \
+		@RANLIB@ lib/$(LARCH)/$(COMM)/libmpi++.a ; fi
+	@if test -w lib/$(LARCH)/$(COMM)/libmpe.a ; then \
+		@RANLIB@ lib/$(LARCH)/$(COMM)/libmpe.a ; fi
+	@if test -w lib/$(LARCH)/$(COMM)/libmpe_nompi.a ; then \
+		@RANLIB@ lib/$(LARCH)/$(COMM)/libmpe_nompi.a ; fi
 
 mpiflib: Makefile.in
 	@for dir in $(MPIDIRS) ;\
@@ -121,13 +147,13 @@ mpiflib: Makefile.in
 	  (cd $$dir; \
 	  $(MAKE) wrapperlib ) ;\
 	  done
-	@RANLIB@ lib/$(ARCH)/$(COMM)/libfmpi.a
+	@RANLIB@ lib/$(LARCH)/$(COMM)/libfmpi.a
 	
 #
 # This target is used to remove the libraries for this configuration; this
 # can lead to better performance when rebuilding.
 rmlib:
-	/bin/rm -f lib/$(ARCH)/$(COMM)/lib*.a
+	/bin/rm -f lib/$(LARCH)/$(COMM)/lib*.a
 #
 # This is a special target for just the device part of the transport
 # (used to speed builds for multiple Chameleon transport layers)
@@ -162,14 +188,14 @@ mpilibdebug:
 	  (cd $$dir ; $(MAKE) clean ; \
 	  $(MAKE) profile_all MPIPROFILE="-DMPIR_DEBUG_MEM -DMPI_BUILD_PROFILING");\
 	  done 
-	@RANLIB@ lib/$(ARCH)/$(COMM)/libmpi.a
-	@RANLIB@ lib/$(ARCH)/$(COMM)/libpmpi.a
-	@if test -w lib/$(ARCH)/$(COMM)/libmpi++.a ; then \
-		@RANLIB@ lib/$(ARCH)/$(COMM)/libmpi++.a ; fi
-	@if test -w lib/$(ARCH)/$(COMM)/libmpe.a ; then \
-		@RANLIB@ lib/$(ARCH)/$(COMM)/libmpe.a ; fi
-	@if test -w lib/$(ARCH)/$(COMM)/libmpe_nompi.a ; then \
-		@RANLIB@ lib/$(ARCH)/$(COMM)/libmpe_nompi.a ; fi
+	@RANLIB@ lib/$(LARCH)/$(COMM)/libmpi.a
+	@RANLIB@ lib/$(LARCH)/$(COMM)/libpmpi.a
+	@if test -w lib/$(LARCH)/$(COMM)/libmpi++.a ; then \
+		@RANLIB@ lib/$(LARCH)/$(COMM)/libmpi++.a ; fi
+	@if test -w lib/$(LARCH)/$(COMM)/libmpe.a ; then \
+		@RANLIB@ lib/$(LARCH)/$(COMM)/libmpe.a ; fi
+	@if test -w lib/$(LARCH)/$(COMM)/libmpe_nompi.a ; then \
+		@RANLIB@ lib/$(LARCH)/$(COMM)/libmpe_nompi.a ; fi
 	
 
 profile:
@@ -180,7 +206,7 @@ profile:
 	  (cd $$dir; \
 	  $(MAKE) profile_all MPIPROFILE="-DMPI_BUILD_PROFILING" ) ;\
 	  done
-	@RANLIB@ lib/$(ARCH)/$(COMM)/libpmpi.a
+	@RANLIB@ lib/$(LARCH)/$(COMM)/libpmpi.a
 
 #
 # Make mpirun from mpirun.*.in
@@ -190,7 +216,7 @@ mpirun: util/mpirun
 #
 # If you change this, ALSO change it in the install target!
 # Note that the csh version is no longer built
-util/mpirun: util/mpirun.sh.in
+util/mpirun: util/mpirun.sh.in util/mpirun.pg.in util/mpirun.ch_p4.in
 	-(cd util ; for file in mpirun.*.in tstmachines.in ; do \
 	bfile=`basename $$file .in` ; \
 	/bin/rm -f $$bfile ; \
@@ -203,24 +229,25 @@ util/mpirun: util/mpirun.sh.in
 		-e "s%\#CC\#%@CC@%g" \
 		-e "s%\#CLINKER\#%@CLINKER@%g" \
 		-e "s%\#DEFAULT_MACHINE\#%$(DEFAULT_MACHINE)%g" \
-		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" > $$bfile ; \
+		-e "s%\#DEFAULT_ARCH\#%$(LARCH)%g" > $$bfile ; \
 	chmod 775 $$bfile ; \
-	/bin/rm -f ../lib/$(ARCH)/$(COMM)/$$bfile ; \
-	cp $$bfile ../lib/$(ARCH)/$(COMM) ; done ; \
+	/bin/rm -f ../lib/$(LARCH)/$(COMM)/$$bfile ; \
+	cp $$bfile ../lib/$(LARCH)/$(COMM) ; done ; \
+        mv ../lib/$(LARCH)/$(COMM)/mpirun.sh ../lib/$(LARCH)/$(COMM)/mpirun ; \
 	mv mpirun.sh mpirun )
 #
 # If you change this, ALSO change it in the install target!
 mpireconfig: util/mpireconfig
 util/mpireconfig: util/mpireconfig.in
 	cat util/mpireconfig.in | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
-			    -e "s%\#ARCH\#%$(ARCH)%g" \
+			    -e "s%\#ARCH\#%$(LARCH)%g" \
 			    -e "s%\#PREFIX\#%$(PREFIX)%g" \
 			    -e "s%\#COMM\#%$(COMM)%g" > \
 		    util/mpireconfig ;\
 	chmod 775 util/mpireconfig
-	-/bin/rm -f lib/$(ARCH)/$(COMM)/mpireconfig \
-		lib/$(ARCH)/$(COMM)/config.status 
-	-cp util/mpireconfig config.status lib/$(ARCH)/$(COMM)
+	-/bin/rm -f lib/$(LARCH)/$(COMM)/mpireconfig \
+		lib/$(LARCH)/$(COMM)/config.status 
+	-cp util/mpireconfig config.status lib/$(LARCH)/$(COMM)
 
 #
 # Make mpiman from mpiman.in
@@ -249,6 +276,7 @@ profiling/upshot/bin/upshot: profiling/upshot/bin/upshot.in
 	/bin/rm -f profiling/upshot/bin/upshot ; \
 	cat profiling/upshot/bin/upshot.in | sed \
 	  -e "s%\#wishloc\#%@wishloc@%g" \
+	  -e "s%\#TK_VERSION\#%@TK_VERSION@%g" \
 	  -e "s%\#BITMAP_DIR\#%$(MPIR_HOME)/profiling/upshot/bitmaps%g" > \
 	    profiling/upshot/bin/upshot;\
 	chmod 775 profiling/upshot/bin/upshot ; \
@@ -263,17 +291,17 @@ nupshot:
 #
 # If you change this, ALSO change it in the install target!
 serv_p4:
-	( cd mpid/ch_p4/p4-1.4/servers ; make serv_p4 ; \
-	  cp ../bin/serv_p4 ../../../../lib/$(ARCH)/ch_p4 )
+	( cd mpid/ch_p4/p4-1.4/servers ; $(MAKE) serv_p4 ; \
+	  cp ../bin/serv_p4 ../../../../lib/$(LARCH)/ch_p4 )
 	/bin/rm -f util/chp4_servs
 	cat util/chp4_servs.in | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
  		-e "s%\#DEFAULT_DEVICE\#%$(DEVICE)%g" \
 		-e "s%\#RSH_COMMAND\#%$(RSH_COMMAND)%g" \
 		-e "s%\#DEFAULT_MACHINE\#%$(DEFAULT_MACHINE)%g" \
-		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" > \
+		-e "s%\#DEFAULT_ARCH\#%$(LARCH)%g" > \
 		    util/chp4_servs ;\
 	chmod 775 util/chp4_servs
-	-cp util/chp4_servs lib/$(ARCH)/$(COMM)
+	-cp util/chp4_servs lib/$(LARCH)/$(COMM)
 
 #
 # Changed clean to not remove the library, only the object files
@@ -307,7 +335,7 @@ clean:
 # Realclean removes mpirun etc as well as the libraries.
 realclean: clean
 	@/bin/rm -f *~ *.ln util/mpirun util/mpireconfig util/tstmachines \
-			    util/mpicc util/mpif77 util/mpiinstall \
+			    util/mpicc util/mpiCC util/mpif77 util/mpiinstall \
 			    installtest/Makefile \
 	  		    profiling/upshot/bin/upshot
 	-/bin/rm -f lib/*/*/*.[oa]
@@ -318,7 +346,7 @@ realclean: clean
 	@-for dir in $(OTHERDEVICES) ; do echo cleaning $$dir ; \
 	     (cd $$dir ; if [ -s Makefile ] ; then $(MAKE) clean ; fi ) ; done
 	if [ -s mpid/ch_p4/p4-1.4/Makefile ] ; then \
-	    (cd  mpid/ch_p4/p4-1.4 ; make realclean ) ; fi
+	    (cd  mpid/ch_p4/p4-1.4 ; $(MAKE) realclean ) ; fi
 	@for dir in $(DIRS) ;\
 	  do \
 	  echo removing Makefile in $$dir ;\
@@ -349,10 +377,18 @@ anltcp: configure
 	configure -arch=sun4 -device=ch_tcp -mpe -var_pkt -mpedbg -opt="-g"
 	-cp config.status lib/sun4/ch_tcp
 	@-chmod g+ws lib lib/sun4 lib/sun4/ch_tcp >/dev/null 2>&1
+anlnexus: configure 
+	@if [ `umask` != 0002 ] ; then echo "Set umask 2 first!" ; exit 1; fi
+	configure -arch=sun4 -device=ch_nexus -mpe -mpedbg -opt="-g" -cc=gcc
+	-cp config.status lib/sun4/ch_tcp
+	@-chmod g+ws lib lib/sun4 lib/sun4/ch_tcp >/dev/null 2>&1
+#
+# Start using rendevous for ch_p4.
 anlchp4mem: configure
 	@if [ `umask` != 0002 ] ; then echo "Set umask 2 first!" ; exit 1; fi
 	configure -arch=sun4 -device=ch_p4 -mpe -var_pkt -mpedbg -memdebug \
-		-opt="-g"
+		-opt="-g" 
+	# -use_rndv
 	-cp config.status lib/sun4/ch_p4
 	@-chmod g+ws lib lib/sun4 lib/sun4/ch_p4 >/dev/null 2>&1
 anlchp4rndv: configure
@@ -382,6 +418,12 @@ anlchp4alphamem: configure
 	configure -arch=alpha -comm=ch_p4 -device=ch_p4 -mpe \
 		-make=/usr/bin/make -no_short_longs -memdebug -mpedbg
 	@-chmod g+ws lib lib/alpha lib/alpha/ch_p4 >/dev/null 2>&1
+anlchp4fbsd: configure
+	@if [ `umask` != 0002 ] ; then echo "Set umask 2 first!" ; exit 1; fi
+	configure -arch=freebsd -device=ch_p4 -mpe -var_pkt -mpedbg -memdebug \
+		-opt="-g" 
+	-cp config.status lib/freebsd/ch_p4
+	@-chmod g+ws lib lib/freebsd lib/freebsd/ch_p4 >/dev/null 2>&1
 # RS6000 sh umask returns 3 digits, not four!
 anlp4ibm: configure
 	@if [ `umask` != 002 -a `umask` != 0002 ] ; then \
@@ -481,11 +523,11 @@ install-all: install
 	-$(CPRP) -r examples $(PREFIX)
 	# Update the makefiles
 	(cd $(PREFIX)/examples ; \
-		$(PREFIX)/lib/$(ARCH)/$(COMM)/mpireconfig Makefile ; \
+		$(PREFIX)/lib/$(LARCH)/$(COMM)/mpireconfig Makefile ; \
 		for dir in `find -type d -print` ; do \
 			(cd $$dir ; \
 			if [ -s Makefile.in ] ; then \
-			$(PREFIX)/lib/$(ARCH)/$(COMM)/mpireconfig Makefile ; \
+			$(PREFIX)/lib/$(LARCH)/$(COMM)/mpireconfig Makefile ; \
 			fi ) ; \
 		done \
 	)
diff --git a/doc/port.in b/doc/port.in
--- a/doc/port.in
+++ b/doc/port.in
@@ -16,6 +16,7 @@
 # Some systems don't have whoami.  Use $LOGNAME instead
 #author="`whoami`"
 author="$LOGNAME"
+MAKE="@MAKE@"
 nomake=0
 noperf=0
 dotest=0
@@ -47,6 +48,7 @@ for arg in "$@" ; do
  	-nomake )
 	nomake=1
 	;;
+
 
  	-noperf )
 	noperf=1
@@ -118,7 +120,7 @@ cat >> $filename <<.
 This document describes the porting of the Argonne National 
 Laboratory/Mississippi State University portable implementation of MPI
 to the $systemname system.  The MPI standard is given in
-\cite{mpi-forum:final}; a introduction to using MPI may be found in
+\cite{mpi-forum:final}; an introduction to using MPI may be found in
 \cite{usingmpi}. 
 
 The MPICH implementation relies on a abstract device interface (ADI) for its
@@ -470,7 +472,7 @@ There are a large number of configure variables.  This table sumarizes the
 variables not described elsewhere and their values.
 
 \begin{description}
-\item[MPIR_HOME]@MPIR_HOME@\\\\
+\item[MPIR_HOME]\file{@MPIR_HOME@}\\\\
 Location of MPICH
 \item[AUTOMOUNTFIX]\code{@AUTOMOUNTFIX@}\\\\
 Fix for automounters
@@ -510,6 +512,11 @@ echo "\\end{description}" >> $filename
 # should read locally)
 if test $nomake = 0 ; then
     @MPIR_HOME@/doc/portbuild -file=$filebase
+    if test $? != 0 ; then 
+	# The make failed; don't generate any data!
+	dotest=0
+	noperf=1
+    fi
 fi
 cat >> $filename <<.
 \readfile{${fileroot}make.tex}
@@ -517,17 +524,29 @@ cat >> $filename <<.
 #
 # Special case for p4: see if we can build the server
 if test "@DEVICE@" = "ch_p4" ; then
-    make serv_p4  > serv_p4.log 2>&1
+    $MAKE serv_p4  > serv_p4.log 2>&1
     if [ $? != 0 ] ; then 
 	cat >> $filename <<EOF
 \subsection{P4 startup server}
-The make of the P4 server, used to speed job startup, failed.  The make output
+The make of the P4 server, used to speed job startup, failed.  
+EOF
+    if [ -s serv_p4.log ] ; then 
+        cat >> $filename <<EOF
+The make output
 was
 \begin{verbatim}
 EOF
 	cat serv_p4.log >> $filename
 	cat >> $filename <<EOF
 \end{verbatim}
+EOF
+    else
+	cat >> $filename <<EOF
+There was no output from make, but the make returned a non-zero status.
+
+EOF
+    fi
+	cat >> $filename <<EOF
 This may not be a serious problem; some systems do not support the P4 server.
 On these systems, MPICH will use the remote shell command \code{@RSH_COMMAND@}
 to start remote jobs.
@@ -548,7 +567,7 @@ if test $noperf = 0 -o $dotest = 1 ; then
     if test "@DEVICE@" = "ch_p4" ; then
 	if test -x @MPIR_HOME@/lib/@ARCH@/ch_p4/tstmachines ; then 
 	    /bin/rm -f .tmp
-	    if @MPIR_HOME@/lib/@ARCH@/ch_p4/tstmachines > .tmp 2>&1 ; then
+	    if @MPIR_HOME@/lib/@ARCH@/ch_p4/tstmachines @ARCH@ > .tmp 2>&1 ; then
 		true
 	    else 
 		cat >>$filename <<EOF
diff --git a/doc/portbuild.in b/doc/portbuild.in
--- a/doc/portbuild.in
+++ b/doc/portbuild.in
@@ -8,6 +8,8 @@
 # -nomake               Do not run make
 # -noperf               Do not run performance tests
 # -file=name            Output LaTeX file (default is doc/doc1.tex)
+#
+# If the make fails, exits with status 1; else exits with zero.
 author="$LOGNAME"
 nomake=0
 noperf=0
@@ -111,12 +113,15 @@ It took $hours $mins to build the MPI libraries.
 \begin{verbatim}
 .
         cat doc/doc1make.log >> $filename
-        echo "\\end{verbatim}"   >> $filename
+        cat >> $filename <<.
+\end{verbatim}
+.
     else
         echo "Make detected no errors during the build." >> $filename
     fi
     if test $makefailed = 1 ; then
         echo "The make failed to complete." >> $filename
+	exit 1
     fi
 else
     cat >>$filename <<.
@@ -124,3 +129,4 @@ else
 MPICH was not built using the the automated build and document program.
 .
 fi
+exit 0
diff --git a/util/mpiinstall.in b/util/mpiinstall.in
--- a/util/mpiinstall.in
+++ b/util/mpiinstall.in
@@ -3,6 +3,9 @@
 # This is a script to install mpi.  It can be called from the top-level 
 # Makefile or directly.  Note that this script needs to be built by configure.
 #
+# As the install takes place, it keeps a list of files that were installed
+# in a form that allows their easy removal
+#
 ARCH=@ARCH@
 COMM=@COMM@
 PREFIX=@PREFIX@
@@ -14,6 +17,15 @@ DEFAULT_MACHINE=@DEFAULT_MACHINE@
 # File access mode
 MODE=0664
 XMODE=0775
+# Uninstall filename
+UNINSTALLFILE="util/mpiuninstall"
+# dirlist is used to uninstall empty directories at the end
+dirlist=""
+#
+errs=0
+#
+# set failmode to soft to let failures accumulate
+failmode="hard"
 Show=eval
 just_testing=0
 for arg in "$@" ; do
@@ -79,10 +91,26 @@ if [ -f $dest ] ; then
     echo "$dest exists; not changed"
 elif [ -d $1 ] ; then
     echo ">>> $1 is a directory; not copied <<<"
+    errs=`expr $errs + 1`
+    if [ $failmode = "hard" ] ; then exit 1 ; fi
 else
     echo "Copying $1 to $dest"
     $Show $CP $1 $dest
+    rc=$?
+    if [ $rc != 0 ] ; then
+	echo "**Error copying file $1 to $dest **"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    else
+	echo "/bin/rm -f $dest" >> $UNINSTALLFILE
+    fi
     $Show chmod $mode $dest
+    rc=$?
+    if [ $rc != 0 ] ; then
+	echo "**Error setting mode on file $dest**"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    fi
 fi
 }
 
@@ -98,7 +126,22 @@ MkDir() {
 if [ ! -d $1 ] ; then
     echo "Creating directory $1"
     $Show mkdir $1
+    rc=$?
+    if [ $rc != 0 ] ; then
+	echo "**Error making directory $1**"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    else
+	# Note that we store in inverse order
+	dirlist="$1 $dirlist"
+    fi
     $Show chmod $XMODE $1
+    rc=$?
+    if [ $rc != 0 ] ; then
+	echo "**Error setting mode on directory $dest**"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    fi
 fi
 }
 #
@@ -142,6 +185,14 @@ else
 	-e "s%\#SYNCLOC\#%@SYNCLOC@%g" \
 	-e "s%\#wishloc\#%@wishloc@%g" \
 	$1 > $dest
+        rc=$?
+        if [ $rc != 0 ] ; then
+	    echo "**Error fixing up file $dest**"
+            errs=`expr $errs + 1`
+            if [ $failmode = "hard" ] ; then exit $rc ; fi
+        else
+	    echo "/bin/rm -f $dest" >> $UNINSTALLFILE
+        fi
     else
 	echo "Fixup $1.in and copy to $dest"
     fi
@@ -152,6 +203,12 @@ else
     mode=$3
 fi
 $Show chmod $mode $2
+rc=$?
+if [ $rc != 0 ] ; then
+    echo "**Error setting mode on file $2**"
+    errs=`expr $errs + 1`
+    if [ $failmode = "hard" ] ; then exit $rc ; fi
+fi
 }
 
 #
@@ -181,8 +238,10 @@ else
 	-e "s%[@]FINC[@]%@FINC@%g" \
         -e "s%[@]BITMAP_DIR[@]%$PREFIX/lib/bitmaps%g" \
 	-e "s%[@]CC[@]%@CC@%g" \
+	-e "s%[@]CCC[@]%@CCC@%g" \
 	-e "s%[@]CFLAGS[@]%@CFLAGS@%g" \
 	-e "s%[@]CLINKER[@]%@CLINKER@%g" \
+	-e "s%[@]CCLINKER[@]%@CCLINKER@%g" \
 	-e "s%[@]COMM[@]%$COMM%g" \
 	-e "s%[@]DEFAULT_ARCH[@]%$ARCH%g" \
 	-e "s%[@]DEFAULT_DEVICE[@]%$DEVICE%g" \
@@ -206,6 +265,14 @@ else
 	-e "s%[@]wishloc[@]%@wishloc@%g" \
 	-e "s%[@]X_LIB[@]%@X_LIB@%g" \
 	$1 > $dest
+        rc=$?
+        if [ $rc != 0 ] ; then
+	    echo "**Error fixing up file $dest**"
+            errs=`expr $errs + 1`
+            if [ $failmode = "hard" ] ; then exit $rc ; fi
+        else
+	    echo "/bin/rm -f $dest" >> $UNINSTALLFILE
+        fi
     else
 	echo "Fixup $1.in and copy to $dest"
     fi
@@ -216,6 +283,12 @@ else
     mode=$3
 fi
 $Show chmod $mode $2
+rc=$?
+if [ $rc != 0 ] ; then
+    echo "**Error setting mode on file $2**"
+    errs=`expr $errs + 1`
+    if [ $failmode = "hard" ] ; then exit $rc ; fi
+fi
 }
 
 ##############################################################################
@@ -311,6 +384,12 @@ if [ -z "$libonly" ] ; then
     CopyFile $PREFIX/bin/mpicc $PREFIX/lib/$ARCH/$COMM $XMODE
     FixupFileWithAt util/mpif77.in $PREFIX/bin/mpif77 $XMODE
     CopyFile $PREFIX/bin/mpif77 $PREFIX/lib/$ARCH/$COMM $XMODE
+    #
+    # mpiCC, if C++ selected
+    if [ -n "@CCC@" ] ; then 
+	FixupFileWithAt util/mpiCC.in $PREFIX/bin/mpiCC $XMODE
+        CopyFile $PREFIX/bin/mpiCC $PREFIX/lib/$ARCH/$COMM $XMODE
+    fi
 else
     # libonly
     #
@@ -322,6 +401,9 @@ else
     done
     $Show mv $PREFIX/lib/$ARCH/$COMM/mpirun.sh $PREFIX/lib/$ARCH/$COMM/mpirun
     FixupFileWithAt util/mpicc.in $PREFIX/lib/$ARCH/$COMM/mpicc $XMODE
+    if [ -n "@CCC@" ] ; then
+        FixupFileWithAt util/mpiCC.in $PREFIX/lib/$ARCH/$COMM/mpiCC $XMODE
+    fi
     FixupFileWithAt util/mpif7.in $PREFIX/lib/$ARCH/$COMM/mpif77 $XMODE
     FixupFile util/mpireconfig.in $PREFIX/lib/$ARCH/$COMM/mpireconfig $XMODE
 fi
@@ -361,6 +443,7 @@ if [ -z "$libonly" ] ; then
     CopyFile mpe/mpe.h $PREFIX/include
     CopyFile mpe/mpe_graphics.h $PREFIX/include
     CopyFile mpe/mpe_log.h $PREFIX/include
+    CopyFile mpe/mpetools.h $PREFIX/include
     CopyFile mpe/basex11.h $PREFIX/include
 fi
 #
@@ -384,8 +467,7 @@ if [ -z "$noman" -a -z "$libonly" ] ; then
     done
 fi
 if [ -z "$libonly" ] ; then
-    for file in adiman.ps.Z functions.ps.Z guide.ps.Z install.ps.Z \
-	mpiman.ps.Z  ; do
+    for file in functions.ps.Z guide.ps.Z install.ps.Z ; do
         CopyFile doc/$file $PREFIX/doc
     done
     #$Show $CPRP -r doc $PREFIX
@@ -402,6 +484,7 @@ if [ $just_testing = 0 ] ; then
     -e "s%^FLIB_PATH=\([^/]*\)/.*\$%FLIB_PATH=\1$PREFIX/lib/$ARCH/$COMM'%g" \
 		-e "s%MPE_DIR=.*\$%MPE_DIR='$PREFIX/mpe'%g" \
 		        > $PREFIX/lib/$ARCH/$COMM/config.status 
+    echo "/bin/rm -f $PREFIX/lib/$ARCH/$COMM/config.status" >> $UNINSTALLFILE
     chmod $XMODE $PREFIX/lib/$ARCH/$COMM/config.status 
 else 
 cat <<.
@@ -444,5 +527,17 @@ $Show "(cd $PREFIX/examples; $MAKE)"
 #
 # Use the alternate method, using mpif77 and mpicc
 $Show "(cd $PREFIX/examples ; $MAKE clean ; $MAKE alternate)"
-
+#
+# Add the directory removes to the UNINSTALL file
+for dir in $dirlist ; do
+    echo "rmdir $dir" >> $UNINSTALLFILE
+done
+#
 echo installed $ARCH/$COMM/$DEVICE MPI in $PREFIX
+
+if [ $errs -gt 0 ] ; then
+    rc=1
+else
+    rc=0
+fi
+exit $rc
