1.0.9

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,6 +1,6 @@
 # create Makefile from this file with configure script
 ##### User configurable options #####
-
+ALL: mpi
 ARCH        = @ARCH@
 COMM        = @COMM@
 DEVICE      = @DEVICE@
@@ -22,14 +22,16 @@ MPIDIRS  = src/pt2pt src/env src/dmpi src/util src/context src/coll \
 	   src/topol src/profile
 DIRS     = $(MPIDIRS) mpid/$(DEVICE) @CPP_DIR@ @MPE_DIR@ \
 	   examples examples/basic examples/test/pt2pt examples/test/coll \
-	   examples/test/topol examples/contrib examples/perftest \
+	   examples/test/topol examples/test/context \
+	   examples/contrib examples/perftest \
            profiling/examples profiling/lib profiling/wrappergen
 # 
 # This is a list of the devices that are available
 DEVICES  = mpid/chameleon mpid/ch_nx mpid/ch_p4 mpid/ch_nc mpid/ch_cmmd \
-	   mpid/ch_eui mpid/ch_meiko mpid_ch_shmem mpid/ch_tcp
+	   mpid/ch_eui mpid/meiko mpid/t3d mpid/ch_meiko mpid_ch_shmem \
+	   mpid/ch_tcp mpid/ch_spp
 OTHERDEVICES  = mpid/ch_nx mpid/ch_p4 mpid/ch_nc mpid/ch_cmmd mpid/ch_eui \
-		mpid/ch_meiko mpid/ch_shmem
+		mpid/ch_meiko mpid/ch_shmem mpid/t3d mpid/ch_spp
 # 
 # Build the device FIRST in case the device include, used in mpiimpl.h, 
 # needs to be built (e.g., ch_p4 device)
@@ -44,6 +46,7 @@ CODEDIRS = mpid/$(DEVICE) $(MPIDIRS) @CPP_DIR@ @MPE_DIR@
 # object files .
 mpi:
 	$(MAKE) clean
+	$(MAKE) rmlib
 	$(MAKE) mpilib
 	@echo "Testing that MPI applications can be linked..."
 	$(MAKE) linktest
@@ -52,6 +55,7 @@ mpi:
 	$(MAKE) clean
 	$(MAKE) mpirun
 	$(MAKE) mpireconfig
+	$(MAKE) mpiman
 	$(MAKE) upshot
 	@echo "Completed build of MPI.  Check the output for errors"
 	@echo "Also try executing 'make testing' in examples/test"
@@ -153,32 +157,25 @@ mpirun: util/mpirun
 #
 # If you change this, ALSO change it in the install target!
 util/mpirun: util/mpirun.in
-	/bin/rm -f util/mpirun
-	cat util/mpirun.in | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
+	-(cd util ; for file in mpirun.in mpirun.*.in tstmachines.in ; do \
+	bfile=`basename $$file .in` ; \
+	/bin/rm -f $$bfile ; \
+	cat $$file | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
 		-e "s%\#EXECER_DIR\#%$(MPIR_HOME)/util%g" \
  		-e "s%\#DEFAULT_DEVICE\#%$(DEVICE)%g" \
 		-e "s%\#RSH_COMMAND\#%$(RSH_COMMAND)%g" \
 		-e "s%\#DEFAULT_MACHINE\#%$(DEFAULT_MACHINE)%g" \
-		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" > \
-		    util/mpirun;\
-	chmod 775 util/mpirun
-	/bin/rm -f util/tstmachines
-	cat util/tstmachines.in | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
-		-e "s%\#EXECER_DIR\#%$(MPIR_HOME)/util%g" \
- 		-e "s%\#DEFAULT_DEVICE\#%$(DEVICE)%g" \
-		-e "s%\#RSH_COMMAND\#%$(RSH_COMMAND)%g" \
-		-e "s%\#DEFAULT_MACHINE\#%$(DEFAULT_MACHINE)%g" \
-		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" > \
-		    util/tstmachines ;\
-	chmod 775 util/tstmachines
-	-/bin/rm -f lib/$(ARCH)/$(COMM)/mpirun lib/$(ARCH)/$(COMM)/tstmachines
-	-cp util/mpirun util/tstmachines lib/$(ARCH)/$(COMM)
+		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" > $$bfile ; \
+	chmod 775 $$bfile ; \
+	/bin/rm -f ../lib/$(ARCH)/$(COMM)/$$bfile ; \
+	cp $$bfile ../lib/$(ARCH)/$(COMM) ; done )
 #
 # If you change this, ALSO change it in the install target!
 mpireconfig: util/mpireconfig
 util/mpireconfig: util/mpireconfig.in
 	cat util/mpireconfig.in | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
 			    -e "s%\#ARCH\#%$(ARCH)%g" \
+			    -e "s%\#PREFIX\#%$(PREFIX)%g" \
 			    -e "s%\#COMM\#%$(COMM)%g" > \
 		    util/mpireconfig ;\
 	chmod 775 util/mpireconfig
@@ -187,10 +184,25 @@ util/mpireconfig: util/mpireconfig.in
 	-cp util/mpireconfig config.status lib/$(ARCH)/$(COMM)
 
 #
+# Make mpiman from mpiman.in
+#
+mpiman: util/mpiman
+
+#
+# If you change this, ALSO change it in the install target!
+util/mpiman: util/mpiman.in
+	/bin/rm -f util/mpiman
+	cat util/mpiman.in \
+	    | sed -e "s%\#INSTALL_DIR\#%$(MPIR_HOME)%g" > util/mpiman
+	chmod 755 util/mpiman
+#
+#
 # Make upshot from upshot.in
 #
 upshot: profiling/upshot/bin/upshot
 
+#
+# Update the install if you change this!
 profiling/upshot/bin/upshot: profiling/upshot/bin/upshot.in
 	/bin/rm -f profiling/upshot/bin/upshot
 	cat profiling/upshot/bin/upshot.in | sed \
@@ -200,7 +212,10 @@ profiling/upshot/bin/upshot: profiling/upshot/bin/upshot.in
 	chmod 775 profiling/upshot/bin/upshot
 
 nupshot:
-	(cd profiling/nupshot; $(MAKE) )
+	(cd profiling/nupshot; \
+	if [ ! -s Makefile ] ; then \
+	    configure ; fi ; \
+	$(MAKE) )
 
 #
 # If you change this, ALSO change it in the install target!
@@ -234,7 +249,7 @@ clean:
 	@-for dir in $(DIRS) ;\
 	  do \
 	  echo cleaning $$dir ;\
-	  (cd $$dir; $(MAKE) clean) ;\
+	  (cd $$dir; if [ -s Makefile ] ; then $(MAKE) clean ; fi ) ;\
 	  done
 	if [ -n "$(TOOLS_DIR)" ] ; then  \
 	    echo "cleaning mpid/chameleon" ; \
@@ -254,7 +269,7 @@ realclean: clean
 	    echo "cleaning mpid/chameleon" ; \
 	    (cd mpid/chameleon ; $(MAKE) clean )  ; fi
 	@-for dir in $(OTHERDEVICES) ; do echo cleaning $$dir ; \
-		(cd $$dir ; $(MAKE) clean ) ; done
+	     (cd $$dir ; if [ -s Makefile ] ; then $(MAKE) clean ; fi ) ; done
 	if [ -s mpid/ch_p4/p4-1.4/Makefile ] ; then \
 	    (cd  mpid/ch_p4/p4-1.4 ; make realclean ) ; fi
 	@for dir in $(DIRS) ;\
@@ -290,6 +305,11 @@ anltcp: configure
 anlchp4mem: configure
 	@if [ `umask` != 0002 ] ; then echo "Set umask 2 first!" ; exit 1; fi
 	configure -arch=sun4 -device=ch_p4 -mpe -var_pkt -mpedbg -memdebug
+	-cp config.status lib/sun4/ch_p4
+	@-chmod g+ws lib lib/sun4 lib/sun4/ch_p4 >/dev/null 2>&1
+anlchp4rndv: configure
+	@if [ `umask` != 0002 ] ; then echo "Set umask 2 first!" ; exit 1; fi
+	configure -arch=sun4 -device=ch_p4 -mpe -var_pkt -mpedbg -use_rndv
 	-cp config.status lib/sun4/ch_p4
 	@-chmod g+ws lib lib/sun4 lib/sun4/ch_p4 >/dev/null 2>&1
 anlp4sgi: configure
@@ -351,13 +371,13 @@ anlchmpl: configure
 	@if [ `umask` != 002 -a `umask` != 0002 ] ; then \
 		echo "Set umask 2 first!" ; exit 1; fi
 	configure -arch=rs6000 -device=ch_eui -comm=ch_eui -mpe -opt="-O" \
-		-limited_buffers -no_mpegraphics -nodevdebug -no_short_longs
+		-limited_buffers -nodevdebug -no_short_longs
 	@-chmod g+ws lib lib/rs6000 lib/rs6000/ch_eui >/dev/null 2>&1
 anlchmplg: configure
 	@if [ `umask` != 002 -a `umask` != 0002 ] ; then \
 		echo "Set umask 2 first!" ; exit 1; fi
 	configure -arch=rs6000 -device=ch_eui -comm=ch_eui -mpe -opt="-g" \
-		-limited_buffers -no_mpegraphics -no_short_longs -mpedbg
+		-limited_buffers -no_short_longs -mpedbg
 	@-chmod g+ws lib lib/rs6000 lib/rs6000/ch_eui >/dev/null 2>&1
 # This is for testing the rendevous code
 anlchmplrndv: configure
@@ -366,11 +386,6 @@ anlchmplrndv: configure
 	configure -arch=rs6000 -device=ch_eui -comm=ch_eui -mpe -opt="-g" \
 		-no_mpegraphics -use_rndv -no_short_longs
 	@-chmod g+ws lib lib/rs6000 lib/rs6000/ch_eui >/dev/null 2>&1
-anlpvm: configure
-	@if [ `umask` != 0002 ] ; then echo "Set umask 2 first!" ; exit 1; fi
-	configure -arch=sun4 -comm=pvm -bopt=g -device=chameleon \
-	    -devicedir=/home/gropp/tools.n -transportdir=/home/gropp/pvm -mpe
-	@-chmod g+ws lib lib/sun4 lib/sun4/pvm >/dev/null 2>&1
 anlpvm3: configure
 	@if [ `umask` != 0002 ] ; then echo "Set umask 2 first!" ; exit 1; fi
 	configure -arch=sun4 -comm=pvm3 -bopt=g -device=chameleon \
@@ -391,6 +406,11 @@ anlchp4pg: configure
 	-@chmod g+ws lib lib/sun4 lib/sun4/p4 >/dev/null 2>&1
 
 INSTALLDIR = /usr/local/mpi
+#
+# The install target really needs to use some for of 'install' program that
+# will create directories, set modes and owners, etc.  Alas, such a function
+# is not standard.
+#
 install:
 	@if [ ! -n "$(PREFIX)" ] ; then \
 	  echo "Set an installation location with --prefix=<location>";\
@@ -417,78 +437,105 @@ install:
 	    mkdir $(PREFIX)/mpid/$(DEVICE) ; fi
 	@if [ ! -d $(PREFIX)/examples ] ; then mkdir $(PREFIX)/examples; fi
 	@if [ ! -d $(PREFIX)/bin ] ; then mkdir $(PREFIX)/bin; fi
+	cp util/tarch $(PREFIX)/bin
+	cp util/tdevice $(PREFIX)/bin
+	#
+	# mpiman
 	/bin/rm -f $(PREFIX)/bin/mpiman
 	cat util/mpiman.in \
 	    | sed -e "s%\#INSTALL_DIR\#%$(PREFIX)%g" > $(PREFIX)/bin/mpiman
 	chmod 755 $(PREFIX)/bin/mpiman
-	cat util/tstmachines.in \
-	    | sed -e "s%\#INSTALL_DIR\#%$(PREFIX)%g" > \
-		$(PREFIX)/bin/tstmachines
-	chmod 755 $(PREFIX)/bin/tstmachines
-	cat util/chp4_servs.in \
-	    | sed -e "s%\#INSTALL_DIR\#%$(PREFIX)%g" > $(PREFIX)/bin/chp4_servs
-	chmod 755 $(PREFIX)/bin/chp4_servs
+	#
+	# Upshot and Nupshot
 	/bin/rm -f $(PREFIX)/bin/upshot
-	cat profiling/upshot/bin/upshot.in | \
-	    sed -e "s%\#BITMAP_DIR\#%$(PREFIX)/lib/bitmaps%g" > \
+	cat profiling/upshot/bin/upshot.in | sed  \
+		-e "s%\#wishloc\#%@wishloc@%g" \
+	  	-e "s%\#BITMAP_DIR\#%$(PREFIX)/lib/bitmaps%g" > \
 		$(PREFIX)/bin/upshot
 	chmod 755 $(PREFIX)/bin/upshot
-	/bin/rm -f $(PREFIX)/bin/mpirun
-	cat util/mpirun.in | \
-	    sed -e "s%\#MPIR_HOME\#%$(PREFIX)%g" \
-		-e "s%\#EXECER_DIR\#%$(PREFIX)/bin%g" \
+	#
+	# Should clean upshot sources  (*.c/h) 
+	-if [ -n "@TCL_DIR@" ] ; then \
+	    $(CPRP) -r profiling/nupshot $(PREFIX) ; \
+	    (cd $(PREFIX)/nupshot ; configure ; $(MAKE) clean ; $(MAKE) ; \
+	    mv nupshot ../bin ) ; \
+	fi
+	#
+	# mpirun et al.
+	-(cd util ; for file in mpirun.in mpirun.*.in tstmachines.in ; do \
+	bfile=`basename $$file .in` ; \
+	cat $$file | sed -e "s%\#MPIR_HOME\#%$(PREFIX)%g" \
+		-e "s%\#EXECER_DIR\#%$(PREFIX)/util%g" \
  		-e "s%\#DEFAULT_DEVICE\#%$(DEVICE)%g" \
- 		-e "s%\#DEFAULT_MACHINE\#%$(DEFAULT_MACHINE)%g" \
 		-e "s%\#RSH_COMMAND\#%$(RSH_COMMAND)%g" \
-		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" >$(PREFIX)/bin/mpirun
-	chmod 755 $(PREFIX)/bin/mpirun	
-	/bin/rm -f $(PREFIX)/bin/tstmachines
-	cat util/tstmachines.in | \
-	    sed -e "s%\#MPIR_HOME\#%$(PREFIX)%g" \
-		-e "s%\#EXECER_DIR\#%$(PREFIX)/bin%g" \
- 		-e "s%\#DEFAULT_DEVICE\#%$(DEVICE)%g" \
 		-e "s%\#DEFAULT_MACHINE\#%$(DEFAULT_MACHINE)%g" \
-		-e "s%\#RSH_COMMAND\#%$(RSH_COMMAND)%g" \
-		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" >$(PREFIX)/bin/tstmachines
-	chmod 755 $(PREFIX)/bin/tstmachines
+		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" > $(PREFIX)/bin/$$bfile ; \
+	chmod 775 $(PREFIX)/bin/$$bfile ; \
+	/bin/rm -f $(PREFIX)/lib/$(ARCH)/$(COMM)/$$bfile ; \
+	cp $(PREFIX)/bin/$$bfile $(PREFIX)/lib/$(ARCH)/$(COMM) ; done )
 	/bin/rm -f $(PREFIX)/bin/mpireconfig
-	cat util/mpireconfig.in | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
+	cat util/mpireconfig.in | sed -e "s%\#MPIR_HOME\#%$(PREFIX)%g" \
 		    -e "s%\#ARCH\#%$(ARCH)%g" \
+		    -e "s%\#PREFIX\#%$(PREFIX)%g" \
 		    -e "s%\#COMM\#%$(COMM)%g" > \
-		    util/mpireconfig ;\
-	chmod 775 util/mpireconfig
+		    $(PREFIX)/bin/mpireconfig ; \
+	chmod 775 $(PREFIX)/bin/mpireconfig
 	/bin/rm -f $(PREFIX)/bin/execer
 	cp util/execer $(PREFIX)/bin/execer
 	chmod 755 $(PREFIX)/bin/execer
-	cat util/chp4_servs.in | sed -e "s%\#MPIR_HOME\#%$(MPIR_HOME)%g" \
+	# 
+	# P4 server
+	-if [ "$(DEVICE)" = "ch_p4" ] ; then \
+	( cd mpid/ch_p4/p4-1.4/servers ; make serv_p4 ; \
+	  cp serv_p4 $(PREFIX)/bin ; chmod a+x $(PREFIX)/bin/serv_p4 ; ) \
+	fi
+	/bin/rm -f util/chp4_servs
+	cat util/chp4_servs.in | sed -e "s%\#MPIR_HOME\#%$(PREFIX)%g" \
  		-e "s%\#DEFAULT_DEVICE\#%$(DEVICE)%g" \
 		-e "s%\#RSH_COMMAND\#%$(RSH_COMMAND)%g" \
 		-e "s%\#DEFAULT_MACHINE\#%$(DEFAULT_MACHINE)%g" \
 		-e "s%\#DEFAULT_ARCH\#%$(ARCH)%g" > \
-		    util/chp4_servs ;\
-	chmod 775 util/chp4_servs
-	-cp util/chp4_servs lib/$(ARCH)/$(COMM)
+		    $(PREFIX)/util/chp4_servs ;\
+	chmod 775 $(PREFIX)/util/chp4_servs
+	-cp $(PREFIX)/util/chp4_servs $(PREFIX)/lib/$(ARCH)/$(COMM)
+	#
+	# Machines database
 #	@if [ ! -d $(PREFIX)/util/machines.anl ] ; then \
 #	    mkdir $(PREFIX)/util/machines.anl ; fi
 #	$(CPRP) -r util/machines $(PREFIX)/util/machines.anl
 	$(CPRP) -r util/machines $(PREFIX)/util/machines
 	$(CPRP) -r profiling/upshot/bitmaps $(PREFIX)/lib/bitmaps
+	#
+	# Include files
 	cp include/mpi.h $(PREFIX)/include
 	cp include/mpi++.h $(PREFIX)/include
 	cp include/mpi++P.h $(PREFIX)/include
 	cp include/mpif.h $(PREFIX)/include
 	cp include/mpi_errno.h $(PREFIX)/include
 	cp include/binding.h $(PREFIX)/include
+	cp include/patchlevel.h $(PREFIX)/include
 	cp mpe/mpe.h $(PREFIX)/include
 	cp mpe/mpe_graphics.h $(PREFIX)/include
 	cp mpe/mpe_log.h $(PREFIX)/include
 	cp mpe/basex11.h $(PREFIX)/include
+	(cd $(PREFIX)/include ; chmod ug+rw mpi.h mpi++.h mpi++P.h mpif.h \
+	mpi_errno.h binding.h patchlevel.h mpe.h mpe_graphics.h mpe_log.h \
+	basex11.h )
+	#
+	# Libaries
 	$(CPRP) -p lib/$(ARCH)/$(COMM)/* $(PREFIX)/lib/$(ARCH)/$(COMM)
+	#
+	# Documentation
 	$(CPRP) -r man $(PREFIX)
 	$(CPRP) -r doc $(PREFIX)
 	cp ref/adiman.ps.Z $(PREFIX)/doc
 	cp ref/mpiman.ps.Z $(PREFIX)/doc
+	#
+	# Example programs
 	cp installtest/Makefile.in $(PREFIX)/examples
+	chmod ug+wr $(PREFIX)/examples/Makefile.in
+	#
+	# This SHOULD use mpireconfig...
 	@cat installtest/makefile.proto | sed \
 		-e "s%\#ARCH\#%@ARCH@%g" \
 		-e "s%\#COMM\#%@COMM@%g" \
@@ -507,15 +554,24 @@ install:
 	cp installtest/pi3.f $(PREFIX)/examples
 	cp installtest/cpilog.c $(PREFIX)/examples
 	cp installtest/Makefile $(PREFIX)/examples
+	(cd $(PREFIX)/examples ; chmod ug+rw Makefile cpi.c pi3.f cpilog.c \
+	Makefile )
+	#
+	# Test build the examples
 	(cd $(PREFIX)/examples ; /bin/rm -f mpirun ; \
-	  ln -s ../bin/mpirun )
-	cp config.status $(PREFIX)
-	rm -f $(PREFIX)/examples/mpif.h
+	  ln -s ../bin/mpirun mpirun )
+	cat config.status | sed -e "s%MPIR_HOME=.*$$%MPIR_HOME='$(PREFIX)'%g" \
+  -e "s%^LIB_PATH=\([^/]*\)/.*$$%LIB_PATH=\1$(PREFIX)/lib/$(ARCH)/$(COMM)'%g" \
+-e "s%^FLIB_PATH=\([^/]*\)/.*$$%FLIB_PATH=\1$(PREFIX)/lib/$(ARCH)/$(COMM)'%g" \
+			-e "s%MPE_DIR=.*$$%MPE_DIR='$(PREFIX)/mpe'%g" \
+			        > $(PREFIX)/config.status
+	/bin/rm -f $(PREFIX)/examples/mpif.h
 	ln -s $(PREFIX)/include/mpif.h $(PREFIX)/examples/mpif.h
 	-chmod -R ug+rw $(PREFIX)
 	echo "About to run installation test..."
 	(cd $(PREFIX)/examples; $(MAKE))
 	@echo installed $(ARCH)/$(COMM)/$(DEVICE) MPI in $(PREFIX)
+
 
 installlib:
 	@if [ ! -n "$(PREFIX)" ]; then \
diff --git a/doc/portperf.in b/doc/portperf.in
--- a/doc/portperf.in
+++ b/doc/portperf.in
@@ -93,12 +93,24 @@ if test $noperf = 0 ; then
 	/bin/rm -f maketst.log 
  	make mpptest goptest > maketst.log 2>&1
 	
+ 	if test ! -x mpptest ; then 
+	    echo "Failed to build performance test program!" >> $filename
+	    echo "Output of \\code{make mpptest goptest} is" >> $filename
+	    cat >> $filename <<.
+\begin{verbatim}
+.
+	    cat maketst.log >> $filename
+	    cat >> $filename <<.
+\end{verbatim}
+.
+	    exit 1
+	fi
 	mpirun -np 2 -mvhome -mvback mppout.gpl -arch=@ARCH@ mpptest -gnuplot \
-		-tgoal 0.1 -auto > short.gpl
+		-tgoal 0.1 -auto -givdy > short.gpl
 	RefineGnuplotfile "short"
 	#
 	mpirun -np 2 -mvhome -mvback mppout.gpl -arch=@ARCH@ mpptest -gnuplot \
-		-tgoal 0.2 -auto -reps 25 -size 16384 65536 1024 > long.gpl
+	   -tgoal 0.2 -auto -reps 25 -size 16384 65536 1024 -givedy > long.gpl
 	RefineGnuplotfile "long"
 	#
 	# The collective routines need to aggregate over several values of
@@ -120,7 +132,7 @@ if test $noperf = 0 ; then
 	RefineGnuplotfile "dsum8"
 	#
 	mpirun -np 4 -mvhome -mvback mppout.gpl -arch=@ARCH@ mpptest -gnuplot \
-		-bisect > bisect.gpl
+		-bisect -givedy > bisect.gpl
 	RefineGnuplotfile "bisect"
 	cd $curdir
     fi
diff --git a/util/execer b/util/execer
--- a/util/execer
+++ b/util/execer
@@ -1,118 +1,153 @@
-#!/bin/csh
-#set verbose
-set jobid = 5555  # default
-set arch = ('' '' '' '' '' '' '' '' '' '' '' '')
-set host = ('' '' '' '' '' '' '' '' '' '' '' '')
-set pgm  = ('' '' '' '' '' '' '' '' '' '' '' '')
-set numprocs = ('' '' '' '' '' '' '' '' '' '' '' '')
-set repeat = ('' '' '' '' '' '' '' '' '' '' '' '')
-set logname = ('' '' '' '' '' '' '' '' '' '' '' '')
-set comm = ('' '' '' '' '' '' '' '' '' '' '' '')
-set args = ('' '' '' '' '' '' '' '' '' '' '' '')
-set remoteinfo = ('' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' \
-		     '' '' '' '' '' '' '' '' '' '' '' '' '' '' )
-
-@ j = 1
-@ line = 0
-while ($j <= $#argv)
-    set arg = "$argv[$j]"
-    switch ("$arg")
-      case -jobid=*:
-        set jobid = `echo $arg | sed 's/-jobid=//'`
-        breaksw
-      case -arch=*:
-        @ line += 1
-        @ repeat[$line]	  = 1              # default
-        @ numprocs[$line] = 1              # default
-        set arch[$line] = `echo $arg | sed 's/-arch=//'`
+#!/bin/sh
+# We use sh because it is quiter while spawning jobs.  It is awkward 
+# because the original code used arrays in csh
+#
+jobid=5555  # default
+dbx=0
+j=1
+line=0
+for arg in "$@" ; do
+    case $arg in 
+      -echo)
+	set -x
+	;;
+      -jobid=*)
+        jobid=`echo $arg | sed 's/-jobid=//'`
+	;;
+      -arch=*)
+        line=`expr $line + 1`
+        eval repeat$line=1
+        eval numprocs$line=1
+        eval arch$line=`echo $arg | sed 's/-arch=//'`
         echo -arch not yet implemented
-        breaksw
-      case -host=*:
-        @ line += 1
-        @ repeat[$line]	  = 1              # default
-        @ numprocs[$line] = 1              # default
-        set host[$line] = `echo $arg | sed 's/-host=//'`
-        breaksw
-      case -pgm=*:
-        set pgm[$line] = `echo $arg | sed 's/-pgm=//'`
-        breaksw
-      case -numprocs=*:
-        set numprocs[$line] = `echo $arg | sed 's/-numprocs=//'`
-        breaksw
-      case -repeat=*:
-        set repeat[$line] = `echo $arg | sed 's/-repeat=//'`
-        breaksw
-      case -logname=*:
-        set logname[$line] = `echo $arg | sed 's/-logname=//'`
-        breaksw
-      case -comm=*:
-        set comm[$line] = `echo $arg | sed 's/-comm=//'`
-        breaksw
-      case -args=*:
-        set args[$line] = "`echo $arg | sed 's/-args=//'`"
-        breaksw
-      case -arg=*:
-        set args[$line] = "$args[$line] `echo $arg | sed 's/-arg=//'`"
-        breaksw
-      case *:
-        echo invalid argument $arg  argument should be one of
+        ;;
+      -host=*)
+        line=`expr $line + 1`
+        eval repeat$line=1  
+        eval numprocs$line=1
+        eval host$line=`echo $arg | sed 's/-host=//'`
+        ;;
+      -pgm=*)
+        eval pgm$line=`echo $arg | sed 's/-pgm=//'`
+        ;;
+      -numprocs=*)
+	echo $arg
+	# This wierd code is because a -n at the begining of echo 
+	# causes echo to silently IGNORE THE LINE!!!!!!
+	value=`echo a"$arg" | sed 's/a-numprocs=//'`
+        eval numprocs$line=$value
+        ;;
+      -repeat=*)
+        eval repeat$line=`echo $arg | sed 's/-repeat=//'`
+        ;;
+      -logname=*)
+        eval logname$line=`echo $arg | sed 's/-logname=//'`
+        ;;
+      -comm=*)
+        eval comm$line=`echo $arg | sed 's/-comm=//'`
+        ;;
+      -args=*)
+        eval args$line="`echo $arg | sed 's/-args=//'`"
+        ;;
+      -arg=*)
+        eval args=$"args$line"
+        eval args$line="'""$args `echo $arg | sed 's/-arg=//'`""'"
+        ;;
+      -dbx)
+        dbx=1
+	;;
+      *)
+        echo invalid argument $arg argument should be one of
         echo '-host=<host> -arch=<arch> numprocs repeat logname comm args'
-    endsw
-    @ j++
-end
+    esac
+done
 
 # Count number of processes (nodes) to be started.  This includes
 # multiple nodes on a single host, if requested.
-@ numnodes = 0
-@ i = 1
-while ( $i <= $line )
-    @ numnodes = $numnodes + $repeat[$i]
-    @ i++
-end
+numnodes=0
+i=1
+while [ $i -le $line ] ; do
+    eval repeat=$"repeat$line"
+    numnodes=`expr $numnodes + $repeat`
+    i=`expr $i + 1`
+done
 
 # Compute remoteinfo
-# @ i = 2
+# @ i=2
 # while ( $i <= $line )
-    # set remoteinfo = " $host[$i] $i $numprocs[$i] $pgm[$i] "
+    # remoteinfo=" $host[$i] $i $numprocs[$i] $pgm[$i] "
 # end
-
+MYDISPLAY=`hostname`:0
 # Start the processes.
-@ nodenum = 1
-@ i = 1
-while ( $i <= $line )
-    @ j = 1   
-    while ( $j <= $repeat[$i] )
-        @ nodenum  = $i - 1
-	set remotecmd = " $pgm[$i] "
-	set remotecmd = " $remotecmd -execer_id PDQS "
-        set remotecmd = " $remotecmd -master_host $host[1] "
-        set remotecmd = " $remotecmd -my_hostname $host[$i] "
-        set remotecmd = " $remotecmd -my_nodenum $nodenum "
-        set remotecmd = " $remotecmd -my_numprocs $numprocs[$i] "
-	set remotecmd = " $remotecmd -total_numnodes $numnodes "
-	set remotecmd = " $remotecmd -job_id $jobid "
-	set remotecmd = " $remotecmd -remote_info "
-	@ k = 1
-	while ( $k <= $line )
-	    set remotecmd = " $remotecmd $host[$k] "
-	    @ n = $k - 1
-	    set remotecmd = " $remotecmd $n $numprocs[$k] $pgm[$k] "
-	    @ k++
-	end
-
-	set remotecmd = " $remotecmd $args[$i] "
-
-	if ( ( $j == $repeat[$i] ) && ( $i == $line ) ) then
-	  echo backgrounding on $host[$i]
-	  echo remotecmd: $remotecmd
-	  rsh $host[$i] $remotecmd
+nodenum=1
+i=$line
+while [ $i -ge 1 ] ; do
+    j=1   
+    eval repeati=$"repeat$i"
+    while [ $j -le $repeati ] ; do
+        nodenum=`expr $i - 1`
+	if [ $dbx != 1 ] ; then
+            eval pgm=$"pgm$i"
+	    remotecmd=" $pgm "
         else
-          rsh $host[$i] $remotecmd &
-	endif
-	echo ""
-
-	@ nodenum++
-        @ j++
-    end   
-    @ i++
-end
+	    remotecmd=" "
+        fi
+	remotecmd=" $remotecmd -execer_id PDQS "
+        remotecmd=" $remotecmd -master_host $host1 "
+	eval host=$"host$i"
+        remotecmd=" $remotecmd -my_hostname $host "
+        remotecmd=" $remotecmd -my_nodenum $nodenum "
+	eval numprocs=$"numprocs$i"
+	if [ -z "$numprocs" ] ; then
+	   echo "Invalid number of processes for host $host ($i)"
+	   exit 1
+	fi
+        remotecmd=" $remotecmd -my_numprocs $numprocs "
+	remotecmd=" $remotecmd -total_numnodes $numnodes "
+	remotecmd=" $remotecmd -job_id $jobid "
+	remotecmd=" $remotecmd -remote_info "
+	k=1
+	while [ $k -le $line ] ; do
+	    eval host=$"host$k"
+	    remotecmd=" $remotecmd $host "
+	    n=`expr $k - 1`
+	    eval numprocs=$"numprocs$k"
+	    eval pgm=$"pgm$k"
+	    remotecmd=" $remotecmd $n $numprocs $pgm "
+	    k=`expr $k + 1`
+	done
+	eval args=$"args$i"
+	remotecmd=" $remotecmd $args "
+	if [ $dbx = 1 ] ; then
+	    cat > ~/.exs$i <<.
+cd `pwd`
+run $remotecmd	
+.
+	fi
+	eval repeat=$"repeat$i"
+	eval host=$"host$i"
+	eval pgm=$"pgm$i"
+	if [ $j -eq $repeat -a $i -eq 1 ] ; then
+#	  echo backgrounding on $host
+#	  echo remotecmd: $remotecmd
+	  if [ $dbx = 1 ] ; then
+	      rsh $host xterm -display $MYDISPLAY -e /usr/ucb/dbx $pgm -sr ~/.exs$i
+          else
+	      rsh $host $remotecmd
+	  fi
+        else
+#	  echo backgrounding on $host
+#	  echo remotecmd: $remotecmd
+	  if [ $dbx = 1 ] ; then
+	      rsh $host xterm -display $MYDISPLAY -e /usr/ucb/dbx $pgm -sr ~/.exs$i &
+	  else
+              rsh $host $remotecmd &
+          fi
+	fi
+#	echo ""
+	nodenum=`expr $nodenum + 1`
+        j=`expr $j + 1`
+    done
+    i=`expr $i - 1`
+done
+wait
diff --git a/util/mpirun.in b/util/mpirun.in
--- a/util/mpirun.in
+++ b/util/mpirun.in
@@ -8,7 +8,9 @@
 # Note that the -f is important to ensure that commands needed by csh are
 # not aliased to commands with the same name and different behavior.
 #
-
+#
+# THIS PROGRAM IS OBSOLETE.  SEE mpirun.*.in, PARTICULARLY mpirun.sh.in .
+#
 #set verbose
 set MPIR_HOME = #MPIR_HOME#
 set EXECER = #EXECER_DIR#/execer
@@ -24,6 +26,7 @@ set machine = '#DEFAULT_MACHINE#'
 set default_device='#DEFAULT_DEVICE#'
 set execer_machine=1
 set cmdLineArgs=''
+set cmdLineArgsExecer=''
 set cmdline=''
 set CAC=''
 set use_execer = 0
@@ -111,6 +114,10 @@ while ("$j" <= "$#argv")
       set leavePGFile = 1
       breaksw
     case -p4pg:
+      if ($np > 1) then
+	echo "-p4pg and -np are mutually exclusive; -np $np being ignored."
+        set np = 1
+      endif
       @ j++
       set p4pgfile = "$argv[$j]"
       set leavePGFile = 1
@@ -186,23 +193,21 @@ while ("$j" <= "$#argv")
 	@ j++
         # any following unrecognized arguments are assumed to be arguments
         # to be passed to the program, as well as all future args
+	# We can't use use_execer here to decide how to store the
+	# arguments, since we may later change it (see the switch on arch)
+	# Thus we store the args in tow forms
 	while ("$j" <= "$#argv")
 	  set arg = "$argv[$j]"
-          if ($use_execer) then
-            set cmdLineArgs = "$cmdLineArgs -arg=${argv[$j]}"
-          else
-            set cmdLineArgs = "$cmdLineArgs ${argv[$j]}"
-          endif
+          set cmdLineArgsExecer = "$cmdLineArgsExecer -arg=${argv[$j]}"
+          set cmdLineArgs = "$cmdLineArgs ${argv[$j]}"
 	  @ j++
         end
       else
 	echo "Warning: Command line arguments for program should be given"
         echo "after the program name.  Assuming that ${argv[$j]} is a"
         echo "command line argument for the program."
-        if ($use_execer) then
-            set cmdLineArgs = "$cmdLineArgs -arg=${argv[$j]}"
-        else
-            set cmdLineArgs = "$cmdLineArgs ${argv[$j]}"
+        set cmdLineArgsExecer = "$cmdLineArgsExecer -arg=${argv[$j]}"
+        set cmdLineArgs = "$cmdLineArgs ${argv[$j]}"
         endif	
       endif
       breaksw
@@ -211,7 +216,9 @@ while ("$j" <= "$#argv")
 end
 
 if ($?MPI_USEP4SSPORT && $?MPI_P4SSPORT) then
-    set p4ssport = $MPI_P4SSPORT
+    if ($MPI_USEP4SSPORT == "yes" || $MPI_USEP4SSPORT == "YES") then
+        set p4ssport = $MPI_P4SSPORT
+    endif
 endif
 
 # We need at least the program name
@@ -220,7 +227,7 @@ if ("$progname" == "") then
   echo "Missing: program name"
   if ("$fake_progname" != "") then
       echo "Program $fake_progname either does not exist, is not "
-      echo "executable, or it an erroneous argument to mpirun."
+      echo "executable, or is an erroneous argument to mpirun."
   endif
   exit 1
 endif
@@ -260,6 +267,9 @@ if ("$arch" == "") then
       endif
   endif
 
+  # archlist contains a list of synonyms for the arch; this is needed for
+  # the machines file (which has one choice of extension).
+  set archlist = "$arch"
   switch ("$ARCH")
     case sun4:
     case sun4m:
@@ -279,7 +289,9 @@ if ("$arch" == "") then
       else
         set arch="sun4"
       endif
+      set archlist = "$arch"
       breaksw
+    case "cray":
     case "CRAY Y-MP":
       set arch="CRAY"
       breaksw
@@ -290,6 +302,7 @@ if ("$arch" == "") then
     case hp9000s735:
     case HP-UX:
       set arch=HP-UX
+      set archlist = "hpux hp9000s700 hp9000s735 HP-UX"
       breaksw
     case NeXT:
       set arch=NeXT
@@ -300,6 +313,7 @@ if ("$arch" == "") then
     case IRIX:
     case sgi:
       set arch="IRIX"
+      set archlist = "IRIX sgi"
       breaksw
     case freebsd:
       set arch="freebsd"
@@ -313,15 +327,18 @@ if ("$arch" == "") then
     case i386:
     case symm_ptx:
       set arch="symm_ptx"
+      set archlist = "i386 symm_ptr"
       breaksw
     case IP19:
     case IP21:
       set arch="sgi_mp"
+      set archlist = "sgi_mp IP19 IP21"
       breaksw
     case ipsc860:
     case i860:
     case ipsc:
       set arch="ipsc860"
+      set archlist = "ipsc860 i860 ipsc"
       breaksw
     default:
       echo "Cannot determine machine architecture. Use the '-arch <arch>'"
@@ -330,6 +347,9 @@ if ("$arch" == "") then
       set arch=$default_arch
       breaksw
   endsw
+endif
+if ( "$archlist" == "" ) then
+    set archlist = "$arch"
 endif
 #
 # Some last-minute fixups
@@ -368,6 +388,7 @@ if ("$machine" == "") then
       endif
       endif
       breaksw
+    case cray:
     case CRAY:
     case HP-UX:
     case NeXT:
@@ -502,7 +523,7 @@ if (("$machine" == "execer") || ("$machine" == "p4")) then
   else
     # echo run local instance
     if ("$machine" == "execer") then
-      set cmdline = "$cmdline -host=${HOST} -pgm=${progname} -numprocs=1 $cmdLineArgs"
+      set cmdline = "$cmdline -host=${HOST} -pgm=${progname} -numprocs=1 $cmdLineArgsExecer"
     endif
     set procFound = 1
   endif
@@ -512,13 +533,17 @@ if (("$machine" == "execer") || ("$machine" == "p4")) then
     if ("$machine" == "ibmspx" && -e /usr/local/bin/getjid) then
 	set machineFile = "/sphome/$LOGNAME/SPnodes.`/usr/local/bin/getjid`"
     else
-        set machineFile = "${MPIR_HOME}/util/machines/machines.${arch}"
+        foreach march ($archlist)
+            set machineFile = "${MPIR_HOME}/util/machines/machines.${march}"
+	    if ( -e $machineFile ) break
+	end
     endif
   endif
 
   if (!(-e "$machineFile" && -r "$machineFile")) then
     if ($nolocal != 0 || $np != 1) then
         echo Cannot read $machineFile.  Exiting.
+	echo Looked for files with extension $archlist.
         exit 1
     endif
   endif
@@ -554,7 +579,7 @@ if (("$machine" == "execer") || ("$machine" == "p4")) then
     endif
     if ("$machine" == "execer") then
       if ("$nolocal" || $KeepHost || ("$machineName" != "$HOST")) then
-	set cmdline = "$cmdline -host=${machineName} -pgm=${progname} -numprocs=1 $cmdLineArgs"
+	set cmdline = "$cmdline -host=${machineName} -pgm=${progname} -numprocs=1 $cmdLineArgsExecer"
 	@ procFound++
       endif
     else
@@ -571,6 +596,9 @@ endif
 
 switch ($machine)
   case meiko:
+    # Note that the file /opt/MEIKOcs2/<machinename>/machine.des contains
+    # detailed information on the structure of the machine (i.e., 
+    # which nodes have disks, vector boards, etc).
     if ($just_testing) then
       if ("$debugger" != "") then
           echo "totalview prun -a -n$np $progname $cmdLineArgs"
@@ -656,7 +684,7 @@ switch ($machine)
         echo $progname -npes $np $cmdLineArgs
     else
         $progname -npes $np $cmdLineArgs
-    fi
+    endif
     breaksw
   case ibmspx:
     # This only works on SPx running release 2 software and with
@@ -725,6 +753,13 @@ switch ($machine)
 	    # If you don't remove the file first, sometimes the 
 	    # WRONG FILE (the OLD ONE) is found by the system.
 	    /bin/rm -f /sphome/$LOGNAME/$localpgm
+	    if (-e /sphome/$LOGNAME/$localpgm) then
+	        echo "Could not move $progname to /sphome/$LOGNAME/$localpgm"
+		if (-d /sphome/$LOGNAME/$localpgm) then
+		   echo "Destination is a directory!"
+		endif
+	        exit 1
+	    endif
 	    cp $progname /sphome/$LOGNAME/$localpgm
 	endif
 	set PWD_LOCAL = /sphome/$LOGNAME
@@ -775,7 +810,7 @@ exit 0
        set CAC = `whatcac | head -1 | cut -d' ' -f 9 | sed -e s/\"//g -e s/://`
     endif
     if ($just_testing) then
-	echo "spsubmit <<."
+	echo "spsubmit2 -nomail <<."
 	echo $CAC
 	echo $max_time
 	echo $np
@@ -796,7 +831,13 @@ exit 0
     else
         # Send output to /dev/null in case we're trying to 
         # use this to match up output
-	spsubmit <<. >& /dev/null 
+	set JID = `/usr/local/bin/getjid`
+	if "$JID" != "" then 
+	    echo "Can not start SP job while one is in the queue"
+	    echo "Job $JID was found"
+	    exit 1
+	endif
+	spsubmit2 -nomail <<. >& /dev/null 
 $CAC
 $max_time
 $np
@@ -807,10 +848,12 @@ $PWD_LOCAL/PIrun
 
 C
 .
+	set JID = `/usr/local/bin/getjid`
 	spwait
 	if ($rmhome == 1) then
 	   /bin/rm /sphome/$LOGNAME/$localpgm
 	endif
+	/bin/rm -f /sphome/$LOGNAME/SPnodes.$JID
 	if ("$mvback" != "") then
 	    (cd $PWD_LOCAL ; cp $mvback $PWD_TRIAL ; /bin/rm $mvback )
         endif
@@ -867,10 +910,17 @@ C
     endif
     breaksw
   case execer:
+    set PWD_LOCAL = $HOME
     if ($just_testing) then
       echo $EXECER "-jobid=$jobid" $cmdline
+      if ("$mvback" != "") then
+	 echo "(cd $PWD_LOCAL ; cp $mvback $PWD_TRIAL ; /bin/rm $mvback )"
+      endif
     else
       $EXECER "-jobid=$jobid" $cmdline
+      if ("$mvback" != "") then
+	  (cd $PWD_LOCAL ; cp $mvback $PWD_TRIAL ; /bin/rm $mvback )
+      endif
     endif
     breaksw
   case p4:
