1.0.11

diff --git a/profiling/nupshot/configure b/profiling/nupshot/configure
--- a/profiling/nupshot/configure
+++ b/profiling/nupshot/configure
@@ -16,6 +16,11 @@
 
 
 
+
+
+
+
+
 progname="`echo $0 | sed 's:^\./\./:\./:'`"
 print_error() {
     echo "*# $*" 2>&1 ;
@@ -311,7 +316,30 @@ done
 #--------------------------------------------------------------------
 
 echo checking for sys/select.h
-echo checking for fd_set
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for fd_set""... $ac_c" 1>&1
+if test ! -f confdefs.h ; then
+    echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
 #include <sys/types.h>
@@ -319,6 +347,7 @@ int main() { exit(0); }
 int t() { fd_set readMask, writeMask; }
 EOF
 if eval $compile; then
+  echo "$ac_t""yes" 1>&1
   :
 else
   rm -rf conftest*
@@ -349,6 +378,7 @@ DEFS="$DEFS -DNO_FD_SET=1"
 fi
 rm -f conftest*
 
+    echo "$ac_t""no" 1>&1
 fi
 rm -f conftest*
 
@@ -508,7 +538,30 @@ rm -f conftest*
 LIBS_save="${LIBS}"
 LIBS="${LIBS} -lXt"
 have_lib=""
-echo checking for -lXt
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for -lXt""... $ac_c" 1>&1
+if test ! -f confdefs.h ; then
+    echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
 
@@ -516,9 +569,11 @@ int main() { exit(0); }
 int t() { main(); }
 EOF
 if eval $compile; then
+  echo "$ac_t""yes" 1>&1
   rm -rf conftest*
   have_lib="1"
 
+   else echo "$ac_t""no" 1>&1
 fi
 rm -f conftest*
 LIBS="${LIBS_save}"
@@ -602,7 +657,30 @@ else
     LIBS_save="${LIBS}"
 LIBS="${LIBS} -lX11"
 have_lib=""
-echo checking for -lX11
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for -lX11""... $ac_c" 1>&1
+if test ! -f confdefs.h ; then
+    echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
 
@@ -610,9 +688,11 @@ int main() { exit(0); }
 int t() { main(); }
 EOF
 if eval $compile; then
+  echo "$ac_t""yes" 1>&1
   rm -rf conftest*
   have_lib="1"
 
+   else echo "$ac_t""no" 1>&1
 fi
 rm -f conftest*
 LIBS="${LIBS_save}"
@@ -635,7 +715,30 @@ if test "$XLIBSW" = nope ; then
     LIBS_save="${LIBS}"
 LIBS="${LIBS} -lXwindow"
 have_lib=""
-echo checking for -lXwindow
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for -lXwindow""... $ac_c" 1>&1
+if test ! -f confdefs.h ; then
+    echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
 
@@ -643,9 +746,11 @@ int main() { exit(0); }
 int t() { main(); }
 EOF
 if eval $compile; then
+  echo "$ac_t""yes" 1>&1
   rm -rf conftest*
   have_lib="1"
 
+   else echo "$ac_t""no" 1>&1
 fi
 rm -f conftest*
 LIBS="${LIBS_save}"
@@ -671,7 +776,30 @@ fi
 LIBS_save="${LIBS}"
 LIBS="${LIBS} -lXbsd"
 have_lib=""
-echo checking for -lXbsd
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for -lXbsd""... $ac_c" 1>&1
+if test ! -f confdefs.h ; then
+    echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
 
@@ -679,9 +807,11 @@ int main() { exit(0); }
 int t() { main(); }
 EOF
 if eval $compile; then
+  echo "$ac_t""yes" 1>&1
   rm -rf conftest*
   have_lib="1"
 
+   else echo "$ac_t""no" 1>&1
 fi
 rm -f conftest*
 LIBS="${LIBS_save}"
@@ -694,7 +824,30 @@ fi
 LIBS_save="${LIBS}"
 LIBS="${LIBS} -lsocket"
 have_lib=""
-echo checking for -lsocket
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for -lsocket""... $ac_c" 1>&1
+if test ! -f confdefs.h ; then
+    echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
 
@@ -702,9 +855,11 @@ int main() { exit(0); }
 int t() { main(); }
 EOF
 if eval $compile; then
+  echo "$ac_t""yes" 1>&1
   rm -rf conftest*
   have_lib="1"
 
+   else echo "$ac_t""no" 1>&1
 fi
 rm -f conftest*
 LIBS="${LIBS_save}"
@@ -717,7 +872,30 @@ fi
 LIBS_save="${LIBS}"
 LIBS="${LIBS} -lnsl"
 have_lib=""
-echo checking for -lnsl
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for -lnsl""... $ac_c" 1>&1
+if test ! -f confdefs.h ; then
+    echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
 cat > conftest.c <<EOF
 #include "confdefs.h"
 
@@ -725,9 +903,11 @@ int main() { exit(0); }
 int t() { main(); }
 EOF
 if eval $compile; then
+  echo "$ac_t""yes" 1>&1
   rm -rf conftest*
   have_lib="1"
 
+   else echo "$ac_t""no" 1>&1
 fi
 rm -f conftest*
 LIBS="${LIBS_save}"
@@ -743,7 +923,22 @@ if test -z "$TCL_DIR" ; then
    
 # Look for Tcl
 if test -z "$TCL_DIR" ; then
-echo checking for Tcl
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for Tcl""... $ac_c" 1>&1
 for dir in \
     /usr \
     /usr/local \
@@ -751,8 +946,14 @@ for dir in \
     /usr/local/tcl7.3-tk3.6 \
     /usr/local/tcl7.0 \
     /usr/local/tcl7.0-tk3.3 \
+    /usr/contrib \
+    /usr/contrib/tk3.6 \
+    /usr/contrib/tcl7.3-tk3.6 \
+    /usr/contrib/tk3.3 \
+    /usr/contrib/tcl7.0-tk3.3 \
     $HOME/tcl \
     $HOME/tcl7.3 \
+    /opt/Tcl \
     /opt/local \
     /opt/local/tcl7.0 \
     /local/encap/tcl-7.1 ; do
@@ -763,11 +964,28 @@ for dir in \
 done
 fi
 if test -n "$TCL_DIR" ; then 
-  echo "$ac_t""found $TCL_DIR" 1>&1
+  echo "$ac_t""found $TCL_DIR/include/tcl.h and $TCL_DIR/lib/libtcl.a" 1>&1
+else
+  echo "$ac_t""no" 1>&1
 fi
-# Look for Tk
+# Look for Tk (look in tcl dir if the code is nowhere else)
 if test -z "$TK_DIR" ; then
-echo checking for Tk
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
+fi
+echo $ac_n "checking for Tk""... $ac_c" 1>&1
 for dir in \
     /usr \
     /usr/local \
@@ -775,11 +993,17 @@ for dir in \
     /usr/local/tcl7.3-tk3.6 \
     /usr/local/tk3.3 \
     /usr/local/tcl7.0-tk3.3 \
+    /usr/contrib \
+    /usr/contrib/tk3.6 \
+    /usr/contrib/tcl7.3-tk3.6 \
+    /usr/contrib/tk3.3 \
+    /usr/contrib/tcl7.0-tk3.3 \
     $HOME/tcl \
     $HOME/tcl7.3 \
+    /opt/Tcl \
     /opt/local \
     /opt/local/tk3.6 \
-    /local/encap/tk-3.4 ; do
+    /local/encap/tk-3.4 $TCL_DIR ; do
     if test -r $dir/include/tk.h -a -r $dir/lib/libtk.a ; then
 	TK_DIR=$dir
 	break
@@ -787,19 +1011,38 @@ for dir in \
 done
 fi
 if test -n "$TK_DIR" ; then 
-  echo "$ac_t""found $TK_DIR" 1>&1
+  echo "$ac_t""found $TK_DIR/include/tk.h and $TK_DIR/lib/libtk.a" 1>&1
+else
+  echo "$ac_t""no" 1>&1
 fi
 
 fi
 if test -z "$TCL_DIR" ; then 
     print_error "Could not find libraries for TCL (needed for Upshot)"
     print_error "Please specify them with the -tcldir=path option."
+    print_error "Aborting build of nupshot"
     exit 1
 fi
 if test -z "$TK_DIR" ; then 
     print_error "Could not find libraries for TK (needed for Upshot)"
     print_error "Please specify them with the -tkdir=path option."
+    print_error "Aborting build of nupshot"
     exit 1
+fi
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+
 fi
 echo $ac_n "checking for version of TK""... $ac_c" 1>&1
 /bin/rm -f conftestval
@@ -826,6 +1069,7 @@ echo "$ac_t""$TK_VERSION" 1>&1
 if test "$TK_VERSION" != 3.6 ; then
     print_error "This version of nupshot requires tk 3.6  The version in"
     print_error "$TK_DIR seems to be version $TK_VERSION."
+    print_error "Aborting build of nupshot"
     exit 1
 fi
 
diff --git a/util/tstmachines.in b/util/tstmachines.in
--- a/util/tstmachines.in
+++ b/util/tstmachines.in
@@ -4,23 +4,35 @@
 # to make sure that it is accessible and can run programs.  This is only
 # a partial test
 #
+verbose=0
 rsh="#RSH_COMMAND#"
 # Could use #DEFAULT_ARCH#
 # and #DEFAULT_DEVICE# to see if we should check....
 for arg in "$@" ; do
     case $arg in 
         -echo) set -x ;;
+	-v) verbose=1 ;;
         -help) cat <<.
+Usage: 
+     tstmachines [ -echo ] [ -v ] architecture
 Tests that you can run remote shells with $rsh on the systems in 
 your machines file and that executables are all cross-mounted.  To run this
 test, you must be able to create files in the current directory.
+
+If there are problems with some of the machines, this test may take several
+minutes per problem machine.  
 .
         exit 1 
 	;;
         *) arch=$arg ;;
     esac
 done
+#
 MPIR_HOME="#MPIR_HOME#"
+if [ -z "$arch" ] ; then
+    arch=`$MPIR_HOME/bin/tarch`
+fi
+#
 machineFile="${MPIR_HOME}/util/machines/machines.${arch}"
 if [ ! -f $machineFile ] ; then
     echo "Cannot read list of nodes $machineFile"
@@ -30,32 +42,104 @@ list=`cat $machineFile | sed -e '/\#/d' | tr -s '\012' ' '`
 /bin/rm -f foo
 echo "A test" > foo
 # Use same mechanism as in mpirun to get the value of pwd...
+if [ -n "#AUTOMOUNTFIX#" ] ; then
+    PWDtest=`pwd | #AUTOMOUNTFIX#`
+    if [ ! -d $PWDtest ] ; then
+        PWDtest=`pwd`
+    fi
+    if [ -n "$PWD" ] ; then
+        /bin/rm -f $PWDtest/.mpirtmp $PWD/.mpirtmp
+        echo "test" > $PWD/.mpirtmp
+        if [ ! -s $PWDtest/.mpirtmp ] ; then
+            PWD=$PWDtest
+        fi
+        /bin/rm -f $PWDtest/.mpirtmp $PWD/.mpirtmp
+    else 
+        PWD=$PWDtest
+    fi
+else
+    PWD=`pwd`
+fi
+#
 if [ -n "$PWD" ] ; then
     PWD_TRIAL=$PWD
 else
+    PWD_TRIAL=$PWDtest
+fi
+if [ ! -d $PWD_TRIAL ] ; then 
+    echo "Warning: your default path uses the automounter; this may"
+    echo "cause some problems if you use other NFS-connected systems."
     PWD_TRIAL=`pwd`
 fi
-if [ -n "$PWD_TRIAL" ] ; then
-    PWD_TRIAL=`echo $PWD_TRIAL | sed -e 's%/tmp_mnt/%/%g'`
-    if [ ! -d $PWD_TRIAL ] ; then 
-        echo "Warning: your default path uses the automounter; this may"
-        echo "cause some problems if you use other NFS-connected systems."
-        PWD_TRIAL=`pwd`
-    fi
-fi
+#
+# First try running ls
 myprog=$PWD_TRIAL/foo
 errcnt=0
+livelist=""
+printedheader=""
 for machine in $list ; do
+    if [ $verbose = 1 ] ; then 
+	echo "Trying ls on $machine ..."
+    fi
     output=`$rsh $machine ls $myprog 2>&1`
     if [ "$output" != "$myprog" ] ; then
+	if [ -z "$printedheader" ] ; then
+	    echo "Errors while trying to run ls $myprog"
+	    printedheader=1
+	fi
 	echo "Unexpected response from $machine:"
         echo "--> $output"
 	errcnt=`expr $errcnt + 1`
+    else
+	livelist="$livelist $machine"
     fi
 done
 /bin/rm -f foo
+#
+# Now, try running a simple program
+/bin/rm -f tstfoo.c 
+cat >tstfoo.c <<.
+main(){return 0;}
+.
+#CC# -c tstfoo.c
+#CLINKER# -o tstfoo tstfoo.o
+if [ ! -x tstfoo ] ; then
+    echo "Could not build a sample program using #CC# and #CLINKER#!"
+    exit 1
+fi
+myprog=$PWD_TRIAL/tstfoo
+list="$livelist"
+livelist=""
+printedheader=""
+for machine in $list ; do
+    if [ $verbose = 1 ] ; then 
+	echo "Trying user program on $machine ..."
+    fi
+    output=`$rsh $machine $myprog 2>&1`
+    if [ "$output" != "" ] ; then
+	if [ -z "$printedheader" ] ; then
+	    echo "Errors while trying to run a simple C program"
+	    printedheader=1
+	fi
+	echo "Unexpected response from $machine:"
+        echo "--> $output"
+	errcnt=`expr $errcnt + 1`
+    else
+	livelist="$livelist $machine"
+    fi
+done
+/bin/rm -f tstfoo tstfoo.c tstfoo.o
 if [ $errcnt -gt 0 ] ; then
+    echo " "
     echo "$errcnt errors were encountered while testing the machines list for $arch"
+    if [ -n "$livelist" ] ; then
+	echo "Only these machines seem to be available"
+	for machine in $livelist ; do
+	    echo "    $machine"
+	done
+    else
+	echo "No machines seem to be available!"
+    fi
     exit 1
 fi
 exit 0
