1.2.7p1

diff --git a/MPI-2-C++/configure b/MPI-2-C++/configure
--- a/MPI-2-C++/configure
+++ b/MPI-2-C++/configure
@@ -1516,6 +1516,16 @@ EOF
 		if test -z "$MPICH_BIN"; then
 		    { echo "configure: error: when configuring for 1.2.6, --with-mpichbin must be specified" 1>&2; exit 1; }
 		fi
+	    elif test "$MPICH_VERSION" = "1.2.7."; then
+		cat >> confdefs.h <<\EOF
+#define MPI2CPP_MPICH121 1
+EOF
+
+		echo "$ac_t""1.2.7 (good)" 1>&6
+		WANT_UPGRADE=0
+		if test -z "$MPICH_BIN"; then
+		    { echo "configure: error: when configuring for 1.2.7, --with-mpichbin must be specified" 1>&2; exit 1; }
+		fi
 	    else
 		cat >> confdefs.h <<\EOF
 #define MPI2CPP_MPICHUNKNOWN 1
@@ -2223,6 +2233,11 @@ fi
 
 LOCAL_CXXFLAGS_SAVE=$CXXFLAGS
 CXXFLAGS="$CXXFLAGS"
+#
+# Note that PROG_CXX looks in CCC, not CXX !!
+if test -z "$CCC" -a -n "$CXX" ; then
+    CCC="$CXX"
+fi
 for ac_prog in $CCC c++ g++ gcc CC cxx cc++ cl
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
diff --git a/mpid/globus2/setup_globus2 b/mpid/globus2/setup_globus2
--- a/mpid/globus2/setup_globus2
+++ b/mpid/globus2/setup_globus2
@@ -10,27 +10,6 @@ print_error()
 }
 
 #
-# mpidi_mkdir_p()
-#
-# Simulate "mkdir -p" since it is not available everywhere.  Portions
-# of this code were taken from mpich2/confdb/aclocal.m4.
-#
-mpidi_mkdir_p()
-{(
-    saveIFS="${IFS}"
-    IFS="/"
-    tmp_curdir=""
-    for tmp_subdir in $1 ; do
-        tmp_curdir="${tmp_curdir}${tmp_subdir}"
-        if test -n "${tmp_curdir}" -a ! -d "${tmp_curdir}" ; then
-	    mkdir "${tmp_curdir}"
-	fi
-        tmp_curdir="${tmp_curdir}/"
-    done
-    IFS="${saveIFS}"
-)}
-
-#
 # Rename the MPICH libraries for G2 over vMPI-MPICH
 #
 MPILIBNAME="mpichg2"
@@ -158,7 +137,6 @@ EOF
     esac
 done
 
-mpidi_mkdir_p mpid/${DEVICE}
 if test $globus_packaged -eq 0 ; then
     if test -z "$GLOBUSDIR" ; then
     	if test -x $GLOBUS_INSTALL_PATH/bin/globus-development-path ; then
@@ -271,7 +249,6 @@ fi
 #
 # We need to supply some header files to do the VMPI name transformations
 #
-mpidi_mkdir_p ${includebuild_dir}
 if test $VMPI -ne 0 ; then
     HAVE_MPID_DEFS_H=1
     cp ${top_srcdir}/mpid/$DEVICE/mpid_defs.h ${includebuild_dir}
@@ -285,14 +262,12 @@ if test $F77_SED -ne 0 ; then
     # doing sed replacement causes some problems with F90 modules.
     # we could probably fix this, but not before the first release. -- (Brian)
     NO_F90=1
+    HAVE_MPID_FORTDEFS_H=1
+    export HAVE_MPID_FORTDEFS_H
+    cp ${top_srcdir}/mpid/$DEVICE/mpid_fortdefs.h \
+    	${builddir}/src/fortran/include
+    cp ${top_srcdir}/mpid/$DEVICE/mpid_fortdefs.h ${includebuild_dir}
 fi
-mpidi_mkdir_p ${builddir}/src/fortran/include
-HAVE_MPID_FORTDEFS_H=1
-export HAVE_MPID_FORTDEFS_H
-sed -e "s!@F77_SED@!${F77_SED}!" ${top_srcdir}/mpid/$DEVICE/mpid_fortdefs.h.in \
-    >${builddir}/src/fortran/include/mpid_fortdefs.h
-sed -e "s!@F77_SED@!${F77_SED}!" ${top_srcdir}/mpid/$DEVICE/mpid_fortdefs.h.in \
-    >${includebuild_dir}/mpid_fortdefs.h
 
 #
 # Get the libraries, etc (there's also a globuslibpath and globuslib)
@@ -471,15 +446,15 @@ get_globus_setting globus_threads_enabled globus_threads_enabled
 #
 if test "$ARCH" = "rs6000" -a $VMPI -ne 0 ; then
     if test "$globus_threads_enabled" = "yes" ; then    
-    	GLOBUS_TEST_CLINKER=xlc_r
-    	GLOBUS_TEST_CXXLINKER=xlC_r
-    	GLOBUS_TEST_F77LINKER=xlf_r
-    	GLOBUS_TEST_F90LINKER=xlf90_r
+    	GLOBUS_TEST_CLINKER="xlc_r`echo $GLOBUS_CLINKER | sed 's/[^ ]*//'`"
+    	GLOBUS_TEST_CXXLINKER="xlC_r`echo $GLOBUS_CXXLINKER | sed 's/[^ ]*//'`"
+    	GLOBUS_TEST_F77LINKER="xlf_r`echo $GLOBUS_F77LINKER | sed 's/[^ ]*//'`"
+    	GLOBUS_TEST_F90LINKER="xlf90_r`echo $GLOBUS_F90LINKER | sed 's/[^ ]*//'`"
     else
-    	GLOBUS_TEST_CLINKER=xlc
-    	GLOBUS_TEST_CXXLINKER=xlC
-    	GLOBUS_TEST_F77LINKER=xlf
-    	GLOBUS_TEST_F90LINKER=xlf90
+    	GLOBUS_TEST_CLINKER="xlc`echo $GLOBUS_CLINKER | sed 's/[^ ]*//'`"
+    	GLOBUS_TEST_CXXLINKER="xlC`echo $GLOBUS_CXXLINKER | sed 's/[^ ]*//'`"
+    	GLOBUS_TEST_F77LINKER="xlf`echo $GLOBUS_F77LINKER | sed 's/[^ ]*//'`"
+    	GLOBUS_TEST_F90LINKER="xlf90`echo $GLOBUS_F90LINKER | sed 's/[^ ]*//'`"
     fi
 fi
 
@@ -495,7 +470,6 @@ export MPICH_GLOBUS2_CONFIGURE_ACTIVE
 #
 # Create compiler scripts
 #
-mpidi_mkdir_p ${binbuild_dir}
 sed -e "s!@GC@!$GLOBUS_CC!" \
     -e "s!@GCFLAGS@!$GLOBUS_CFLAGS!" \
     -e "s!@GL@!$GLOBUS_CLINKER!" \
@@ -554,6 +528,58 @@ if test $NO_F90 -eq 0 ; then
     	${top_srcdir}/mpid/$DEVICE/mpich-globus2-fc.in \
     	>${binbuild_dir}/mpich-globus2-f90
     chmod +x ${binbuild_dir}/mpich-globus2-f90
+fi
+
+#
+# The AIX "ar" command require the option "-X 64" when building 64-bit
+# libraries.  MPICH doesn't seem to do this detection for us, so we
+# must do it here.
+#
+if test "$ARCH" = "rs6000" -a $VMPI -ne 0 ; then
+    cat >conftest.c <<EOF
+int foo(int bar);
+
+int foo(int bar)
+{
+    return bar;
+}
+EOF
+    if test -z "$ac_echo_test" ; then
+	echo $ac_n "checking if ar requires -X64""... $ac_c"
+    else
+	echo $ac_n "determing if ar requires -X64""... $ac_c" 1>&1
+    fi
+    errmsg=""
+    if $CC -c conftest.c >>conftest.out 2>&1; then
+	test_XAR=`echo ${AR} | sed 's/ / -X64 /'`
+	if $AR conftest.a conftest.o >>conftest.out 2>&1 ; then
+	    result=no
+	elif $test_XAR conftest.a conftest.o >>conftest.out 2>&1 ; then
+	    result=yes
+	    AR=$test_XAR
+	    export AR
+	    ARCMD="ar -X64"
+	    export ARCMD
+	    ARNAME="ar -X64"
+	    export ARNAME
+	else
+	    result="all trials failed"
+	    errmsg="unable to build a library with ar"
+	fi
+    else
+	result="compile failure"
+	errmsg="unable to compile a simple program"
+    fi
+    if test -z "$ac_echo_test" ; then
+	echo "$ac_t""$result"
+    else
+	echo "$ac_t""$result" 1>&1
+    fi
+    if test -n "$errmsg" ; then
+	echo "ERROR: $errmsg"
+	exit 1
+    fi
+    rm -f conftest*
 fi
 
 #
@@ -670,7 +696,7 @@ if test "$vmpi" = "yes" ; then
     #       it may be larger.
     #
     get_vendor_size MPI_Aint
-    MPI_AINT_SIZE = $VENDOR_MPI_AINT_SIZE
+    MPI_AINT_SIZE=$VENDOR_MPI_AINT_SIZE
 
     #
     # If the vendor's MPI doesn't support MPI_LONG_LONG or MPI_LONG_LONG_INT
diff --git a/romio/configure b/romio/configure
--- a/romio/configure
+++ b/romio/configure
@@ -852,6 +852,7 @@ Optional Features:
 --enable-aio - Request use of asynchronous I/O routines (default)
 --enable-echo  - Turn on strong echoing. The default is enable=no.
 --enable-f77 - Turn on support for Fortran 77 (default)
+--enable-f90 - Turn on support for Fortran 90 (default)
 --enable-weak-symbols - Turn on support for weak symbols
 --enable-debug - Build a debugging version
 
@@ -1323,6 +1324,7 @@ fi
 
 
 NOF77=0
+NOF90=0
 ARCH=""
 arch_IRIX=""
 MPI=""
@@ -1427,6 +1429,13 @@ if test "${enable_f77+set}" = set; then
 else
   enable_f77=yes
 fi;
+# Check whether --enable-f90 or --disable-f90 was given.
+if test "${enable_f90+set}" = set; then
+  enableval="$enable_f90"
+
+else
+  enable_f90=yes
+fi;
 # Check whether --enable-weak-symbols or --disable-weak-symbols was given.
 if test "${enable_weak_symbols+set}" = set; then
   enableval="$enable_weak_symbols"
@@ -1453,6 +1462,9 @@ if test "${with_mpi+set}" = set; then
 fi;
 if test "$enable_f77" != "yes" ; then
    NOF77=1
+fi
+if test "$enable_f90" != "yes" ; then
+   NOF90=1
 fi
 if test "$enable_debug" = "yes" ; then
     DEBUG=yes
@@ -2943,7 +2955,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2946:" \
+echo "$as_me:2958:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6029,7 +6041,7 @@ if test -n "$OFFSET_KIND" -a "A$MPI_OFFSET_KIND1" = "A!" ; then
   MPI_OFFSET_KIND1="        INTEGER MPI_OFFSET_KIND"
   MPI_OFFSET_KIND2="        PARAMETER (MPI_OFFSET_KIND=$OFFSET_KIND)"
 else
- if test "$FORTRAN_MPI_OFFSET" = "integer*8" && test "A$MPI_OFFSET_KIND2" = "A!" && test $NOF77 = 0 ; then
+ if test "$FORTRAN_MPI_OFFSET" = "integer*8" && test "A$MPI_OFFSET_KIND2" = "A!" && test $NOF77 = 0 && test $NOF90 = 0 ; then
    rm -f conftest*
 # Determine the extension for Fortran 90 files (not all compilers accept
 # .f and not all accept .f90)
@@ -6146,7 +6158,7 @@ fi
 
  fi
  #
-  if test "$FORTRAN_MPI_OFFSET" = "integer" && test "A$MPI_OFFSET_KIND2" = "A!" && test $NOF77 = 0 ; then
+  if test "$FORTRAN_MPI_OFFSET" = "integer" && test "A$MPI_OFFSET_KIND2" = "A!" && test $NOF77 = 0 && test $NOF90 = 0 ; then
    echo "$as_me:$LINENO: checking for Fortran 90 KIND parameter for 4-byte integers" >&5
 echo $ECHO_N "checking for Fortran 90 KIND parameter for 4-byte integers... $ECHO_C" >&6
 rm -f kind.f kind.o kind
@@ -7074,6 +7086,15 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
+
+cat >>confdefs.h <<\_ACEOF
+#define ROMIO_PVFS2 1
+_ACEOF
+
+else
+  { { echo "$as_me:$LINENO: error: PVFS support requested but cannot find pvfs.h header file" >&5
+echo "$as_me: error: PVFS support requested but cannot find pvfs.h header file" >&2;}
+   { (exit 1); exit 1; }; }
 
 fi
 
@@ -10191,7 +10212,7 @@ elif test $FROM_MPICH2 = yes ; then
    USER_CFLAGS=""
    USER_FFLAGS=""
    TEST_LIBNAME=""
-   MPIRUN=${master_top_builddir}/mpiexec
+   MPIRUN=${master_top_builddir}/bin/mpiexec
    #
    # Turn off the building of the Fortran interface and the Info routines
    EXTRA_DIRS=""
@@ -10447,6 +10468,173 @@ if test "$pac_cv_func_decl_strdup" = "yes" ; then
 
 cat >>confdefs.h <<_ACEOF
 #define NEEDS_STRDUP_DECL 1
+_ACEOF
+
+
+fi
+
+fi
+
+for ac_func in snprintf
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
+
+if test "$ac_cv_func_snprintf" = "yes" ; then
+    # Do we need to declare snprintf?
+
+echo "$as_me:$LINENO: checking whether snprintf needs a declaration" >&5
+echo $ECHO_N "checking whether snprintf needs a declaration... $ECHO_C" >&6
+if test "${pac_cv_func_decl_snprintf+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdio.h>
+int
+main ()
+{
+int a=snprintf(1.0,27,1.0,"foo");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_func_decl_snprintf=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_func_decl_snprintf=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $pac_cv_func_decl_snprintf" >&5
+echo "${ECHO_T}$pac_cv_func_decl_snprintf" >&6
+if test "$pac_cv_func_decl_snprintf" = "yes" ; then
+
+cat >>confdefs.h <<_ACEOF
+#define NEEDS_SNPRINTF_DECL 1
 _ACEOF
 
 
@@ -11164,6 +11352,286 @@ if test -n "$MPIOF_H_INCLUDED"; then
 else
    F77MPIOINC="include 'mpiof.h'"
 fi
+
+
+echo "$as_me:$LINENO: checking for restrict" >&5
+echo $ECHO_N "checking for restrict... $ECHO_C" >&6
+if test "${pac_cv_c_restrict+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+int * restrict a;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_c_restrict="restrict"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_c_restrict="no"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+if test "$pac_cv_c_restrict" = "no" ; then
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+int * _Restrict a;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_c_restrict="_Restrict"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_c_restrict="no"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+if test "$pac_cv_c_restrict" = "no" ; then
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+int * __restrict a;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_c_restrict="__restrict"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_c_restrict="no"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+fi
+echo "$as_me:$LINENO: result: $pac_cv_c_restrict" >&5
+echo "${ECHO_T}$pac_cv_c_restrict" >&6
+if test "$pac_cv_c_restrict" = "no" ; then
+  restrict_val=""
+elif test "$pac_cv_c_restrict" != "restrict" ; then
+  restrict_val=$pac_cv_c_restrict
+fi
+if test "$restrict_val" != "restrict" ; then
+
+cat >>confdefs.h <<_ACEOF
+#define restrict $restrict_val
+_ACEOF
+
+fi
+
+
+
+
+if test "$ac_cv_c_compiler_gnu" = "yes" ; then
+    echo "$as_me:$LINENO: checking whether __attribute__ allowed" >&5
+echo $ECHO_N "checking whether __attribute__ allowed... $ECHO_C" >&6
+if test "${pac_cv_gnu_attr_pure+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+int foo(int) __attribute__ ((pure));
+int
+main ()
+{
+int a;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_gnu_attr_pure=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_gnu_attr_pure=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $pac_cv_gnu_attr_pure" >&5
+echo "${ECHO_T}$pac_cv_gnu_attr_pure" >&6
+echo "$as_me:$LINENO: checking whether __attribute__((format)) allowed" >&5
+echo $ECHO_N "checking whether __attribute__((format)) allowed... $ECHO_C" >&6
+if test "${pac_cv_gnu_attr_format+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+int foo(char *,...) __attribute__ ((format(printf,1,2)));
+int
+main ()
+{
+int a;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_gnu_attr_format=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_gnu_attr_format=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $pac_cv_gnu_attr_format" >&5
+echo "${ECHO_T}$pac_cv_gnu_attr_format" >&6
+    if test "$pac_cv_gnu_attr_pure" = "yes" -a "$pac_cv_gnu_attr_format" = "yes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GCC_ATTRIBUTE 1
+_ACEOF
+
+    fi
+fi
+
 
 echo "setting CC to $CC"
 echo "setting F77 to $F77"
