1.2.5.3

diff --git a/MPI-2-C++/configure b/MPI-2-C++/configure
--- a/MPI-2-C++/configure
+++ b/MPI-2-C++/configure
@@ -1496,6 +1496,26 @@ EOF
 		if test -z "$MPICH_BIN"; then
 		    { echo "configure: error: when configuring for 1.2.4, --with-mpichbin must be specified" 1>&2; exit 1; }
 		fi
+	    elif test "$MPICH_VERSION" = "1.2.5."; then
+		cat >> confdefs.h <<\EOF
+#define MPI2CPP_MPICH121 1
+EOF
+
+		echo "$ac_t""1.2.5 (good)" 1>&6
+		WANT_UPGRADE=0
+		if test -z "$MPICH_BIN"; then
+		    { echo "configure: error: when configuring for 1.2.5, --with-mpichbin must be specified" 1>&2; exit 1; }
+		fi
+	    elif test "$MPICH_VERSION" = "1.2.6."; then
+		cat >> confdefs.h <<\EOF
+#define MPI2CPP_MPICH121 1
+EOF
+
+		echo "$ac_t""1.2.6 (good)" 1>&6
+		WANT_UPGRADE=0
+		if test -z "$MPICH_BIN"; then
+		    { echo "configure: error: when configuring for 1.2.6, --with-mpichbin must be specified" 1>&2; exit 1; }
+		fi
 	    else
 		cat >> confdefs.h <<\EOF
 #define MPI2CPP_MPICHUNKNOWN 1
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1197,7 +1197,7 @@ do
        NO_F90=1
        HAS_FORTRAN=0
        CFLAGS="-DMPID_NO_FORTRAN $CFLAGS"
-       romio_config_args="$romio_config_args -nof77"
+       romio_config_args="$romio_config_args --disable-f77"
        enable_args="$enable_args --disable-f77"
        ;;
 
@@ -1711,7 +1711,8 @@ if test -n "$arch_tflops"; then
    CROSS_F77_SIZEOF_DOUBLE_PRECISION=${CROSS_F77_SIZEOF_DOUBLE_PRECISION:-8}
    CROSS_BIGENDIAN=${CROSS_BIGENDIAN:-false}
    FORT_INT8=1
-   ROMIO_ARGS="-intsize=$CROSS_SIZEOF_INT -ptrsize=$CROSS_SIZEOF_VOID_P -longsize=$CROSS_SIZEOF_LONG -longlongsize=$CROSS_SIZEOF_LONG_LONG"
+   # Romio now looks at the CROSS_args
+#   ROMIO_ARGS="-intsize=$CROSS_SIZEOF_INT -ptrsize=$CROSS_SIZEOF_VOID_P -longsize=$CROSS_SIZEOF_LONG -longlongsize=$CROSS_SIZEOF_LONG_LONG --without-setbytes"
 
 fi
 #
@@ -5364,7 +5365,7 @@ if test "$HAS_F77" = "0" ; then
     NOF77=1
     HAS_FORTRAN=0
     CFLAGS="-DMPID_NO_FORTRAN $CFLAGS"
-    romio_config_args="$romio_config_args -nof77"
+    romio_config_args="$romio_config_args -disable-f77"
 fi
 #
 
@@ -7528,16 +7529,29 @@ return 0;
 }
 
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     ac_cv_mmap=0
 
     else
@@ -8936,16 +8950,29 @@ else
 main() {struct timeval tp;
 gettimeofday(&tp,(void*)0);return 0;}
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""one!"
 else
@@ -9789,16 +9816,29 @@ main () {
   exit (u.c[sizeof (long) - 1] == 1);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     pac_r=1
 
     else
@@ -13697,16 +13737,29 @@ main() {
   exit(0);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     Pac_CV_NAME=""
 
     else
@@ -13864,16 +13917,29 @@ main() {
   exit(0);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     Pac_CV_NAME=""
 
     else
@@ -13972,16 +14038,29 @@ main() {
   exit(0);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     Pac_CV_NAME=""
 
     else
@@ -14154,16 +14233,29 @@ main() {
   exit(0);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     Pac_CV_NAME=""
 
     else
@@ -14294,16 +14386,29 @@ main() {
   exit(0);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     Pac_CV_NAME=""
 
     else
@@ -14418,16 +14523,29 @@ int main() {
    has the same problem on some systems */
 exit(sizeof(long long) < sizeof(long)); }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     has_long_long=0
 
     else
@@ -14665,16 +14783,29 @@ int main() {
 /* On Ultrix 4.3 cc, long double is 4 and double is 8.  */
 exit(sizeof(long double) < sizeof(double)); }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""no"
 else
@@ -14787,16 +14918,29 @@ main()
   exit(0);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     ac_cv_sizeof_double=0
 
     else
@@ -14895,16 +15039,29 @@ main()
   exit(0);
 }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     ac_cv_sizeof_long_double=0
 
     else
@@ -15715,26 +15872,46 @@ if test $ROMIO = 1 -a -d "${top_srcdir}/romio" ; then
   if test -z "$FILE_SYSTEM" ; then
       ROMIO_FILE_SYSTEM=""
   else
-      ROMIO_FILE_SYSTEM="-file_system=$FILE_SYSTEM"
+      ROMIO_FILE_SYSTEM="--with-file-system=$FILE_SYSTEM"
   fi
+  FROM_MPICH=yes
   if test ! -d romio ; then mkdir romio ; fi
   # We set -fc to F77 since we set F77 to either $FC or the value f77
+#            -mpiincdir=$includebuild_dir \
+#	    -mpibindir=$binbuild_dir \
+#            -mpilib=$libbuild_dir/lib$MPILIBNAME.a \
+#            -mpiolib=$libbuild_dir/lib$MPILIBNAME.a \
+#            -cc="$CC" -cflags="$ROMIO_CFLAGS $CC_SHARED_OPT" \
+#            -fc="$F77" -fflags="$ROMIO_FFLAGS $FC_SHARED_OPT" \
+#	    -f90="$F90"
+  MPI_BIN_DIR=$binbuild_dir 
+  MPI_LIB=$libbuild_dir/lib$MPILIBNAME.a
+  MPI_INCLUDE_DIR=$includebuild_dir
   (cd romio ; \
+  LIBNAME=$libbuild_dir/lib$MPILIBNAME.a ; export LIBNAME ; \
+  export MPI_BIN_DIR ; export MPI_LIB ; export MPI_INCLUDE_DIR ; \
   export CROSS_SIZEOF_INT; \
   export CROSS_SIZEOF_VOID_P; \
+  export CROSS_SIZEOF_LONG_LONG; \
+  export CROSS_SIZEOF_LONG;\
+  export MAKE;\
+  export ARCH;\
+  export CC; export F77; export F90; export MPILIBNAME ; \
+  export FROM_MPICH;\
   export int_len ; export void_star_len ; export OFFSET_KIND ; \
   export long_long_len ; \
-  "${top_srcdir}/romio/configure" -arch="$ARCH" $ROMIO_ARGS $ROMIO_FILE_SYSTEM \
-            --with-mpi=mpich -from_mpich \
-	    -make="$MAKE" \
-            -mpiincdir=$includebuild_dir \
-	    -mpibindir=$binbuild_dir \
-            -mpilib=$libbuild_dir/lib$MPILIBNAME.a \
-            -mpiolib=$libbuild_dir/lib$MPILIBNAME.a \
-            -cc="$CC" -cflags="$ROMIO_CFLAGS $CC_SHARED_OPT" \
-            -fc="$F77" -fflags="$ROMIO_FFLAGS $FC_SHARED_OPT" \
-	    -f90="$F90" $romio_config_args $enable_args $with_args )
-  /bin/rm -f include/mpio.h "${top_srcdir}/include/mpio.h"
+  "${top_srcdir}/romio/configure" $ROMIO_ARGS $ROMIO_FILE_SYSTEM \
+            --with-mpi=mpich $romio_config_args $enable_args $with_args )
+  rc=$?
+  if test "$rc" != 0 ; then
+      if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Error: ROMIO Configure failed, aborting configure"
+else
+echo "$ac_t""Error: ROMIO Configure failed, aborting configure" 1>&1
+fi
+exit 1
+  fi
+  rm -f include/mpio.h "${top_srcdir}/include/mpio.h"
   cp romio/include/mpio.h include
   ROMIO_LFLAGS="`$MAKE -f romio/Makefile romio_lflags`"
   ROMIO_TCFLAGS="`$MAKE -f romio/Makefile romio_tcflags`"
diff --git a/examples/test/configure b/examples/test/configure
--- a/examples/test/configure
+++ b/examples/test/configure
@@ -101,6 +101,7 @@ FLIB_PATH=""
 OPTFLAGS=""
 OPTFLAGSF=""
 NOF77=0
+enable_coverage=no
 HAS_CXX=no
 F77_EXTRA_FLAG=""
 HAS_FORTRAN=1
@@ -117,7 +118,7 @@ USE_BOOT=no
 MPIFDEP=""
 #
 # By not setting FFLAGS, we get the values from the environment
-MAKE=make
+MAKE=${MAKE:-"make"}
 PREFIX=""
 DEVICE=""
 DEVCFLAGS=""
@@ -132,6 +133,9 @@ cross_compiling=""
 # 
 BASECC=0
 BASEF77=0
+#
+#
+MPIINCDIR=
 #
 # This next variable is a version without quotes.
 # We could also consider `echo $a | sed -e 's/"/\\"/g'`
@@ -298,12 +302,14 @@ do
 	fi
 	MPIRUNARGS='"-mvhome"'
 	MPIRUNMVBACK="-mvback"
+	MPIINCDIR=$mpichpath/../include
 	;;
 
      -with-mpich=*|--with-mpich=*)
         mpichpath=`echo A$arg | sed 's/A-*with-mpich=//'`
 	MPIRUNARGS='"-mvhome"'
 	MPIRUNMVBACK="-mvback"
+	MPIINCDIR=$mpichpath/../include
 	;;
      -mpi2)
 	HAS_MPI2=1
@@ -311,11 +317,23 @@ do
 	IO="io"
 	;;
 
-     -nof77 | --nof77)
+     -nof77 | --nof77 | -disable-f77 | --disable-f77)
        echo "Don't build the tests that need Fortran"
        NOF77=1
        HAS_FORTRAN=0
        FC=true
+       ;;
+
+     -enable-f77 | --enable-f77) 
+       # Nothing to do
+       ;;
+
+     -disable-coverage|--disable-coverage)
+       # Nothing to do
+       ;;
+
+     -enable-coverage|--enable-coverage)
+       enable_coverage=yes
        ;;
 	
      -no-io | -disable-io | --disable-io)
@@ -603,6 +621,13 @@ if test -n "$mpichpath" ; then
     if test "$DEVICE" = "ch_p4mpd" ; then
 	MPIRUNARGS=""
 	MPIRUNMVBACK=""
+	if test "$enable_boot" != "no" ; then
+	    USE_BOOT=yes
+	    if test -z "$MPIBOOT" ; then 
+		MPIBOOT="$mpichpath/mpichboot"
+		MPIUNBOOT="$mpichpath/mpichstop"
+	    fi
+	fi
     fi
 fi
 #
@@ -1661,16 +1686,29 @@ int main() {
 /* On Ultrix 4.3 cc, long double is 4 and double is 8.  */
 exit(sizeof(long double) < sizeof(double)); }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""no"
 else
@@ -1766,16 +1804,29 @@ int main() {
    has the same problem on some systems */
 exit(sizeof(long long) < sizeof(long)); }
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     has_long_long=0
 
     else
@@ -2493,6 +2544,12 @@ fi
 
 #
 
+if test "$enable_coverage" = "yes" ; then
+    # This will only work with GCC.  Note that the switches must be
+    # passed to both the linker and the compiler
+    CFLAGS="$CFLAGS -fprofile-arcs -ftest-coverage"
+    CLINKER="$CLINKER -fprofile-arcs -ftest-coverage"
+fi
 if test "$USE_BOOT" != "yes" ; then
     MPIBOOT=""
     MPIUNBOOT=""
@@ -2501,12 +2558,242 @@ fi
 
 #
 
+#
+# Special values for the ROMIO tests.  These are approximate only
+# The long term solution is to move most of these into a separate
+# file that ROMIO's configure can define; for the command-line
+# values, these should be optional (they really are not needed 
+# by the tests).
+# Override by setting all 5 in the environment.
+if test -z "$FTESTDEFINE" -a "$HAS_FORTRAN" = 1 ; then
+    # The % must have a backslash to keep from confusing sed when 
+    # configure replaces @LL@.
+    LL="\%lld"
+    # We really should try to compute the size of MPI_Offset in bytes
+    # and then use that value.
+    if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for sizeof MPI_Offset""... $ac_c"
+else
+echo $ac_n "checking for sizeof MPI_Offset""... $ac_c" 1>&1
+fi
+    rm -f cftestval
+    saveCPPFLAGS="$CPPFLAGS"
+    saveCFLAGS="$CFLAGS"
+    if test -n "$MPIINCDIR" ; then
+        CPPFLAGS="$CPPFLAGS -I$MPIINCDIR"
+	# Older autoconfs do not include CPPFLAGS in the compile test
+	CFLAGS="$CFLAGS -I$MPIINCDIR"
+    fi
+    
+
+if test "$cross_compiling" = 1 -a -z "$TESTCC" ; then
+    
+    Pac_CV_NAME=0
+else
+    if test -n "$TESTCC" ; then
+      CCsav="$CC"
+      CC="$TESTCC"
+    fi
+    cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <stdio.h>
+#include "mpi.h"
+int main()
+{
+  FILE *f=fopen("cftestval", "w");
+  if (!f) exit(1);
+  fprintf(f, "%d\n", sizeof(MPI_Offset));
+  return 0;
+}
+EOF
+        if test -n "$compile" ; then 	
+	eval $compile
+    else
+	eval $ac_compile
+	eval $ac_link
+    fi
+    if test ! -s conftest ; then
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+    pac_cv_sizeof_mpi_offset=0
+
+    else
+      /bin/rm -f conftestout
+      if test -s conftest && (./conftest; exit) 2>conftestout; then
+          pac_cv_sizeof_mpi_offset=`cat cftestval`
+
+      else
+        pac_cv_sizeof_mpi_offset=0
+
+	if test -s conftestout ; then cat conftestout >> config.log ; fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
+        
+      fi
+    fi
+  if test -n "$TESTCC" ; then
+        CC="$CCsav"
+  fi
+  rm -fr conftest*
+fi
+
+rm -f cftestval
+    CPPFLAGS="$saveCPPFLAGS"
+    CFLAGS="$saveCFLAGS"
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""$pac_cv_sizeof_mpi_offset"
+else
+echo "$ac_t""$pac_cv_sizeof_mpi_offset" 1>&1
+fi
+
+    if test "$pac_cv_sizeof_mpi_offset" -gt 0 ; then
+        FORTRAN_MPI_OFFSET="integer*$pac_cv_sizeof_mpi_offset"
+    else
+        FORTRAN_MPI_OFFSET="integer*8"
+    fi
+    # Use upper case because this works with the Absoft compiler, which
+    # is not monocase.  Since all other Fortran compilers, following the
+    # Fortran standard, map all names to a single case, using upper
+    # case works for all compilers that provide IARGC and GETARG
+    FTESTDEFINE="external IARGC, GETARG"
+    F77IARGC="IARGC()"
+    F77GETARG="call GETARG(i,str)"
+    # Some Fortran compilers require additional libraries to
+    # provide IARGC etc.  
+    # Intel ifc: -lPEPCF90 (or /4Yportlib
+    # Absoft f77: -lU77
+    fcompile='$MPIF77 -o conftest conftest.f $F77EXTRALIBS $ftestlib >>config.log 2>&1'
+    if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for libraries needed for Fortran command line access""... $ac_c"
+else
+echo $ac_n "checking for libraries needed for Fortran command line access""... $ac_c" 1>&1
+fi
+    cat >>conftest.f <<EOF
+        program main
+        print *, "arg count = ", iargc()
+        end
+EOF
+    if eval $fcompile ; then 
+       if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""none"
+else
+echo "$ac_t""none" 1>&1
+fi
+    else
+        addlib=""
+        for ftestlib in -lPEPCF90 -lU77 ; do
+	    echo "$fcompile" >>config.log
+	    fc=`echo $fcompile`
+	    echo "fcompile = $fc" >> config.log
+	    if eval $fcompile ; then 
+		addlib="$ftestlib"
+		break
+	    fi
+        done
+        if test -z "$addlib" ; then
+	    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""unable to determine"
+else
+echo "$ac_t""unable to determine" 1>&1
+fi
+	else
+            if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""$addlib"
+else
+echo "$ac_t""$addlib" 1>&1
+fi
+	    F77EXTRALIBS="$F77EXTRALIBS $addlib"
+	fi
+    fi
+    rm -f conftest*
+fi
+# Use F77MPIOINC to add an "include 'mpiof.h'" statement if necessary
+# (conforming MPI implementations should not require this)
+F77MPIOINC=""
+
+
+
+
+
+
+
+# End of the values for the ROMIO tests
+
 # Substitute variables
 # Variables used in scripts only
 # FINC contains an @MPIR_HOME@, so it needs to come first
 # Variables used by Makefile.in's:
 
 MPICH_VERSION=""
+if test -n "$IO" -a ! -s "$srcdir/$IO/Mfile.in" ; then
+   # Look for romio relative to the srcdir
+   if test -s $srcdir/../../romio/test/Mfile.in ; then
+       # Copy the files (always copy in case there was an update)
+       cp -r $srcdir/../../romio/test $IO
+   else 
+       if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""Warning: No IO directory available for tests"
+else
+echo "$ac_t""Warning: No IO directory available for tests" 1>&1
+fi
+   fi
+fi
 # End configuration file
 # Set default prefixes.
 if test -n "$prefix"; then
@@ -2559,6 +2846,13 @@ HAS_CXX='$HAS_CXX'
 MPIBOOT='$MPIBOOT'
 MPIUNBOOT='$MPIUNBOOT'
 MPIRUNARGS='$MPIRUNARGS'
+LL='$LL'
+FORTRAN_MPI_OFFSET='$FORTRAN_MPI_OFFSET'
+FTESTDEFINE='$FTESTDEFINE'
+F77IARGC='$F77IARGC'
+F77GETARG='$F77GETARG'
+F77MPIOINC='$F77MPIOINC'
+F77EXTRALIBS='$F77EXTRALIBS'
 FINC='$FINC'
 ARCH='$ARCH'
 CFLAGS='$CFLAGS'
@@ -2631,6 +2925,13 @@ s%@HAS_CXX@%$HAS_CXX%g
 s%@MPIBOOT@%$MPIBOOT%g
 s%@MPIUNBOOT@%$MPIUNBOOT%g
 s%@MPIRUNARGS@%$MPIRUNARGS%g
+s%@LL@%$LL%g
+s%@FORTRAN_MPI_OFFSET@%$FORTRAN_MPI_OFFSET%g
+s%@FTESTDEFINE@%$FTESTDEFINE%g
+s%@F77IARGC@%$F77IARGC%g
+s%@F77GETARG@%$F77GETARG%g
+s%@F77MPIOINC@%$F77MPIOINC%g
+s%@F77EXTRALIBS@%$F77EXTRALIBS%g
 s%@FINC@%$FINC%g
 s%@ARCH@%$ARCH%g
 s%@CFLAGS@%$CFLAGS%g
@@ -2654,14 +2955,14 @@ s%@MPE_CFLAGS@%$MPE_CFLAGS%g
 s%@MPICH_VERSION@%$MPICH_VERSION%g
 s%@MPIR_HOME@%$MPIR_HOME%g
 s%@MPI_FOBJECTS@%$MPI_FOBJECTS%g
-s%@MPIFDEP@%$MPIFDEP%g
+s%@MPIFDEP@%$MPIFDEP%g" | sed -e "
 s%@MPILIBNAME@%$MPILIBNAME%g
 s%@MPICC@%$MPICC%g
 s%@MPIF77@%$MPIF77%g
 s%@MPICPLUSPLUS@%$MPICPLUSPLUS%g
 s%@MPIRUN@%$MPIRUN%g
 s%@MPIRUNMVBACK@%$MPIRUNMVBACK%g
-s%@MPI_VERSION@%$MPI_VERSION%g" | sed -e "
+s%@MPI_VERSION@%$MPI_VERSION%g
 s%@OPTFLAGS@%$OPTFLAGS%g
 s%@OPTFLAGSC@%$OPTFLAGSC%g
 s%@OPTFLAGSF@%$OPTFLAGSF%g
@@ -2679,6 +2980,16 @@ chmod +x config.status
 ${CONFIG_SHELL-/bin/sh} ./config.status
 
 
+# Optionally build the io/Mfile
+if test -n "$IO" ; then
+    CONFIG_FILES=io/Mfile
+    export CONFIG_FILES
+    ${CONFIG_SHELL-/bin/sh} ./config.status
+    CONFIG_FILES=""
+    unset CONFIG_FILES
+fi   
+
+
 CONFIG_FILES="pt2pt/runtests coll/runtests topol/runtests context/runtests \
 	command/runtests env/runtests profile/runtests"
 export CONFIG_FILES
@@ -2690,8 +3001,29 @@ for pac_file in pt2pt/runtests coll/runtests topol/runtests context/runtests \
     sed -e '1d' $pac_file > .pactmp
     /bin/rm -f $pac_file
     mv .pactmp $pac_file
-    chmod a+x  $pac_file
+    chmod a+x $pac_file
 done
 
 
+# Optionally build the programs and test files
+if test -n "$IO" ; then
+    CONFIG_FILES="io/rtest io/misc.c io/fmisc.f io/fcoll_test.f io/pfcoll_test.f"
+    export CONFIG_FILES
+    ${CONFIG_SHELL-/bin/sh} ./config.status
+    rm -f .pactmp
+    for file in $CONFIG_FILES ; do
+        sed -e '1d' $file > .pactmp
+        /bin/rm -f $file
+        mv .pactmp $file
+    done
+    CONFIG_FILES=""
+    unset CONFIG_FILES
+    chmod a+x io/rtest
+fi
 
+if test -s io/Mfile ; then
+    mv -f io/Mfile io/Makefile
+fi
+if test -x io/rtest ; then
+    mv -f io/rtest io/runtests
+fi
diff --git a/mpe/sbin/mpeinstall.in b/mpe/sbin/mpeinstall.in
--- a/mpe/sbin/mpeinstall.in
+++ b/mpe/sbin/mpeinstall.in
@@ -38,9 +38,11 @@ sysconfdir=@sysconfdir@
 
 PROF_LIBNAME=@PROF_LIBNAME@
 CPRP="@CPRP@"
-MPICH=@MPICH@
+MPICH=@FROM_MPICH@
+MPICH2=@FROM_MPICH2@
 NOF77=@NOF77@
 LOGVIEWERS=@LOGVIEWERS@
+SLOG2TOOLS=@SLOG2TOOLS@
 MPE_HEADERS="@MPE_HEADERS@"
 
 # File access mode
@@ -126,8 +128,13 @@ EOF
 	    exit 1
 	    ;;
 	*)
-	    echo "mpeinstall: Unrecognized argument $arg ."
-	    exit 1
+	    # Silently skip empty arguments (these can occur on
+	    # some systems and within some scripts; they are
+	    # harmless)
+	    if [ -n "$arg" ] ; then
+  	        echo "mpeinstall: Unrecognized argument $arg ."
+	        exit 1
+	    fi
 	    ;;
     esac
 done
@@ -275,9 +282,9 @@ fi
 
 
 #
-# Fixup files that need #...# replaced
+# Fixup files with various xxxxbuild_dir to xxxxdir, install directory.
 #
-FixupFile() {
+FixInstallFile() {
 dest=$DESTDIR$2
 if [ -d $dest ] ; then
     dest=$dest/`basename $1`
@@ -291,15 +298,22 @@ elif [ -d $1 ] ; then
 else
     if [ -f $dest ] ; then $Show /bin/rm -f $dest ; fi
     if [ $just_testing = 0 ] ; then \
-        sed -e "s%\#MPE_BUILD\#%$top_srcdir%g" \
-            -e "s%\#PREFIX\#%$prefix%g" \
-	    -e "s%\#top_srcdir\#%$top_srcdir%g" \
-	    -e "s%\#bindir\#%$bindir%g" \
-	    -e "s%\#binbuild_dir\#%$bindir%g" \
-        $1 > $dest
+        if [ "$MPICH" = yes -o "$MPICH2" = yes ] ; then
+            sed \
+            -e "s%^MPI_CC\([ ]*\)=\([ ]*\).*\$%MPI_CC\1=\2$bindir/mpicc%g" \
+            -e "s%^MPI_F77\([ ]*\)=\([ ]*\).*\$%MPI_F77\1=\2$bindir/mpif77%g" \
+            -e "s%^MPE_INCDIR\([ ]*\)=\([ ]*\).*\$%MPE_INCDIR\1=\2$includedir%g" \
+            -e "s%^MPE_LIBDIR\([ ]*\)=\([ ]*\).*\$%MPE_LIBDIR\1=\2$libdir%g" \
+            $1 > $dest
+        else
+            sed \
+            -e "s%^MPE_INCDIR\([ ]*\)=\([ ]*\).*\$%MPE_INCDIR\1=\2$includedir%g" \
+            -e "s%^MPE_LIBDIR\([ ]*\)=\([ ]*\).*\$%MPE_LIBDIR\1=\2$libdir%g" \
+            $1 > $dest
+        fi
         rc=$?
         if [ $rc != 0 ] ; then
-	    echo "**Error fixing up file $dest**"
+	    echo "**** Error fixing up file $dest ****"
             errs=`expr $errs + 1`
             if [ $failmode = "hard" ] ; then exit $rc ; fi
         else
@@ -307,7 +321,7 @@ else
             filelist="$filelist $dest"
         fi
     else
-	if [ $verbose = 1 ] ; then echo "Fixup $1.in and copy to $dest" ; fi
+	if [ $verbose = 1 ] ; then echo "Fixup $1 and copy to $dest" ; fi
     fi
 fi
 if [ -z "$3" ] ; then
@@ -400,12 +414,6 @@ if [ -n "$binbuild_dir" ] ; then
          echo "Copying MPE utility programs to $bindir"
          CopyDirRecurP $binbuild_dir $bindir $XMODE
     fi
-    # Create mpereconfig from mpereconfig.in
-    $Show /bin/rm -f $DESTDIR$bindir/mpereconfig
-    if [ $verbose = 1 ] ; then
-        echo "Creating mpereconfig from mpereconfig.in"
-    fi
-    FixupFile $top_srcdir/bin/mpereconfig.in $bindir/mpereconfig $XMODE
 fi
 
 MkDir $sbindir
@@ -416,79 +424,12 @@ examplesdir=$datadir/examples
 MkDir $examplesdir
 
 #
-#
-# Updating the config.status file is trickier, since we need to edit
-# the directories that might have contained the original path.
-# It is important to update the CORRECT file, in the case that we are doing
-# a -libonly installation on a previously constructed version.
-# We also need to remove the code that mucks around with the directories
-#
-if [ $MPICH = 1 ] ; then
-    if test ! -f "$bindir/mpicc" ; then
-	echo "Must install MPICH before you can install MPE"
-	echo "Type 'make install' in the MPICH root directory"
-	exit 1
-    fi
-    if [ $just_testing = 0 ] ; then
-        # If we don't reset ac_given_srcdir, we can't use mpereconfig
-        # in any directory.
-        # Don't overload @CC@ and @F77@ which are meant for serial programs.
-        cat config.status | \
-            sed -e "s%\@MPI_CC\@\([^/ ]*\)/.*\$%\@MPI_CC\@\%$bindir/mpicc\%g%g" \
-                -e "s%\@MPI_F77\@\([^/ ]*\)/.*\$%\@MPI_F77\@\%$bindir/mpif77\%g%g" \
-                -e "s%\@libbuild_dir\@\([^/ ]*\)/.*\$%\@libbuild_dir\@\%$libdir\%g%g" \
-		-e "s%\@includebuild_dir\@\([^/ ]*\)/.*\$%\@includebuild_dir\@\%$includedir\%g%g" \
-		-e "s%^ac_given_srcdir=.*$%ac_given_srcdir=%g" \
-		-e '/if test "\$ac_dir/,/^[ ]*fi[ ]*$/d' \
-		-e 's/ac_dir_suffix/ac_dir/' \
-                > ${DESTDIR}$bindir/mpereconfig.dat
-        filelist="$filelist $bindir/mpereconfig.dat"
-        chmod $XMODE ${DESTDIR}$bindir/mpereconfig.dat
-    else 
-        cat <<.
-            cat config.status | \
-                sed -e "s%^MPI_CC=\([^/ ]*\)/.*\$%MPI_CC=$bindir/mpicc%g" \
-                    -e "s%^MPI_F77=\([^/ ]*\)/.*\$%MPI_F77=$bindir/mpif77%g" \
-                    -e "s%^libbuild_dir=\([^/ ]*\)/[^ ']*%libbuild_dir=$libdir%g" \
-		    -e "s%^includebuild_dir=\([^/ ]*\)/[^ ']*%includebuild_dir=$includedir%g" \
-		    -e "s%^ac_given_srcdir=.*$%ac_given_srcdir=%g" \
-		    -e '/if test "\$ac_dir/,/fi/d' \
-		    -e 's/ac_dir_suffix/ac_dir/' \
-                    > $bindir/mpereconfig.dat
-       chmod $XMODE $bindir/mpereconfig.dat
-.
-    fi
-else
-    if [ $just_testing = 0 ] ; then
-        cat config.status | \
-            sed -e "s%\@libbuild_dir\@\([^/ ]*\)/.*\$%\@libbuild_dir\@\%$libdir\%g%g" \
-		-e "s%\@includebuild_dir\@\([^/ ]*\)/.*\$%\@includebuild_dir\@\%$includedir\%g%g" \
-		-e "s%^ac_given_srcdir=.*$%ac_given_srcdir=%g" \
-		-e '/if test "\$ac_dir/,/^[ ]*fi[ ]*$/d' \
-		-e 's/ac_dir_suffix/ac_dir/' \
-                > $DESTDIR$bindir/mpereconfig.dat
-        filelist="$filelist $bindir/mpereconfig.dat"
-        chmod $XMODE $DESTDIR$bindir/mpereconfig.dat
-    else 
-        cat <<.
-            cat config.status | \
-                sed -e "s%^libbuild_dir=\([^/ ]*\)/[^ ']*%libbuild_dir=$libdir%g" \
-		    -e "s%^includebuild_dir=\([^/ ]*\)/[^ ']*%includebuild_dir=$includedir%g" \
-		    -e "s%^ac_given_srcdir=.*$%ac_given_srcdir=%g" \
-		    -e '/if test "\$ac_dir/,/fi/d' \
-		    -e 's/ac_dir_suffix/ac_dir/' \
-                    > $bindir/mpereconfig.dat
-       chmod $XMODE $bindir/mpereconfig.dat
-.
-    fi
-fi
-
-#
 # Copy MPE Example C and Fortran programs
 CopyDirRecurP $top_srcdir/contrib/test $examplesdir
 
 # Create MPE examples Makefile
-( cd $DESTDIR$examplesdir ; $bindir/mpereconfig Makefile ) 
+( cd $DESTDIR$examplesdir ; \
+  FixInstallFile $libbuild_dir/../contrib/test/Makefile $examplesdir/Makefile ) 
 filelist="$filelist $examplesdir/Makefile"
 
 if [ -x $bindir/mpirun ] ; then
@@ -510,7 +451,7 @@ if [ -z "$DESTDIR" ]; then
 fi
 
 # Remove old uninstall file
-if [ $appendUninstall = 0 -a -f $UNINSTALLFILE ] ; then
+if [ "$appendUninstall" = 0 -a -f $UNINSTALLFILE ] ; then
     /bin/rm -f $UNINSTALLFILE
 fi
 #
@@ -524,18 +465,33 @@ fi
 
 chmod u+x $UNINSTALLFILE
 
-# Install the log viewers
+# Install the old log viewers if they exist
 # Don't set the prefix if the default is chosen.  This
 # lets us use --with-common-prefix with the viewers
-if [ $LOGVIEWERS = 1 ] ; then
+if [ "$LOGVIEWERS" = 1 ] ; then
     if [ "$prefix_override" = "1" ] ; then
-    ( cd $sbinbuild_dir/../viewers ; \
-      ./sbin/install-viewers -prefix=$prefix -uninstall=$UNINSTALLFILE \
-	-mode=$MODE -xmode=$XMODE )
+        ( cd $sbinbuild_dir/../viewers ; \
+          ./sbin/install-viewers -prefix=$prefix -uninstall=$UNINSTALLFILE \
+          -mode=$MODE -xmode=$XMODE )
     else
-    ( cd $sbinbuild_dir/../viewers ; \
-      ./sbin/install-viewers -uninstall=$UNINSTALLFILE \
-	-mode=$MODE -xmode=$XMODE )
+        ( cd $sbinbuild_dir/../viewers ; \
+          ./sbin/install-viewers -uninstall=$UNINSTALLFILE \
+          -mode=$MODE -xmode=$XMODE )
+    fi
+fi
+
+# Install the SLOG-2 tools if they exist
+# Don't set the prefix if the default is chosen.  This
+# lets us use --with-common-prefix with the viewers
+if [ -s $sbinbuild_dir/../slog2sdk -a $SLOG2TOOLS = 1 ] ; then
+    if [ "$prefix_override" = "1" ] ; then
+        ( cd $sbinbuild_dir/../slog2sdk ; \
+          ./sbin/install-package -prefix=$prefix -uninstall=$UNINSTALLFILE \
+          -mode=$MODE -xmode=$XMODE -copymode=core)
+    else
+        ( cd $sbinbuild_dir/../slog2sdk ; \
+          ./sbin/install-package -uninstall=$UNINSTALLFILE \
+          -mode=$MODE -xmode=$XMODE -copymode=core )
     fi
 fi
 
@@ -548,7 +504,7 @@ for file in $filelist ; do
     echo "/bin/rm -f $file" >> $UNINSTALLFILE
 done
 
-if [ $appendUninstall = 0 ] ; then
+if [ "$appendUninstall" = 0 ] ; then
     echo "/bin/rm -f $sbindir/mpeuninstall" >> $UNINSTALLFILE
     echo "/bin/rm -f $UNINSTALLFILE" >> $UNINSTALLFILE
 fi
@@ -558,7 +514,7 @@ for dir in $dirlist ; do
     echo "if [ -d $dir ] ; then rmdir $dir ; fi" >> $UNINSTALLFILE
 done
  
-if [ $appendUninstall = 0 ] ; then
+if [ "$appendUninstall" = 0 ] ; then
     cp $UNINSTALLFILE $sbinbuild_dir/mpeuninstall
 #
     echo "Installed MPE in $prefix"
diff --git a/mpe/src/Makefile.in b/mpe/src/Makefile.in
--- a/mpe/src/Makefile.in
+++ b/mpe/src/Makefile.in
@@ -7,6 +7,7 @@
 top_srcdir     = @top_srcdir@
 
 CC             = @CC@
+CC_SHL         = @CC_SHL@
 CLINKER        = @CLINKER@
 MPI_CC         = @MPI_CC@
 MPI_CLINKER    = $(MPI_CC)
@@ -41,7 +42,7 @@ MPEGRAPHICS_SOURCE  = @MPEGRAPHICS_SOURCE@
 MPEGRAPHICS_FSOURCE = @MPEGRAPHICS_FSOURCE@
 ### End User configurable options ###
 SHELL = /bin/sh
-RM    = /bin/rm
+RM    = rm
 
 @VPATH@
 
@@ -56,34 +57,44 @@ libbuild_dir = @libbuild_dir@
 binbuild_dir = @binbuild_dir@
 srcdir       = @srcdir@
 
-EXECS        = dbxtest dbxtest2 testlog clog_print clog2alog clog2slog
+EXECS        = dbxtest@EXEEXT@ dbxtest2@EXEEXT@ testlog@EXEEXT@ \
+               clog_print@EXEEXT@ clog2alog@EXEEXT@ clog2slog@EXEEXT@
 
 # GETNAME_DEFS are needed by mpehname.c
 CFLAGS       = $(MPE_CFLAGS) $(MPE_GRAPHICS) $(INCLUDE_DIR) @CFLAGS@
 CC_LDFLAGS   = $(LDFLAGS) $(MPE_CFLAGS)
 
+C2S1_SRC     = @C2S1_SRC@
 MPE_CSOURCES = $(MPEGRAPHICS_SOURCE) clog_sysio.c mpe_log.c clog.c \
                clog_merge.c clog_time.c clog_util.c clog2alog.c decomp.c \
                mpe_seq.c dbxerr.c examine.c privtags.c getgrank.c mpehname.c \
-               mpe_io.c c2s_util.c	
+               mpe_io.c $(C2S1_SRC)
 MPE_TSOURCES = decomp.c mpe_seq.c dbxerr.c getgrank.c
-MPE_COBJECTS = $(MPE_CSOURCES:.c=.o)
+MPE_COBJECTS = $(MPE_CSOURCES:.c=.@OBJEXT@)
 
 MPE_WSOURCES = $(MPEGRAPHICS_FSOURCE) mpe_logf.c decompf.c mpe_seqf.c \
                getgrankf.c
-MPE_WOBJECTS = $(MPE_WSOURCES:.c=.o)
+MPE_WOBJECTS = $(MPE_WSOURCES:.c=.@OBJEXT@)
 
 MPE_SOURCES = $(MPE_CSOURCES) $(MPE_WSOURCES)
 MPE_OBJECTS = $(MPE_COBJECTS) $(MPE_WOBJECTS)
+MPE_SHLOBJECTS = $(MPE_OBJECTS:.@OBJEXT@=.lo)
 
 C2S_CSOURCES = clog2slog.c c2s_util.c c2s_assist.c
-C2S_OBJECTS  = $(C2S_CSOURCES:.c=.o)
+C2S_OBJECTS  = $(C2S_CSOURCES:.c=.@OBJEXT@)
 
-.c.o:
+.SUFFIXES: .c .@OBJEXT@ .lo .a @EXEEXT@
+
+.c.@OBJEXT@:
 	$(MPI_CC) $(CFLAGS) -c $<
 
 .c.a:
 	$(MPI_CC) $(CFLAGS) -c $<
+
+# Allow compilers that do not allow -o for renaming object files
+.c.lo:
+	$(CC_SHL) $(CFLAGS) -c $< $(INC_DIR)
+	@mv $*.@OBJEXT@ $*.lo
 
 # default_all is the same as default, but without the RANLIB.  This
 # can speed up the build (ranlibs can take a LONG time).  profile_all 
@@ -105,17 +116,19 @@ default: clean rmprog rmlib
 	 $(MAKE) ${libbuild_dir}/lib$(TRACE_LIBNAME).a 
 	 $(MAKE) ${libbuild_dir}/lib$(LOG_LIBNAME).a 
 	@if [ -n "$(MPE_GRAPHICS)" ] ; then \
-	 $(MAKE) ${libbuild_dir}/lib$(ANIM_LIBNAME).a ; \
+	     $(MAKE) ${libbuild_dir}/lib$(ANIM_LIBNAME).a ; \
 	fi
 	 $(MAKE) ${libbuild_dir}/lib$(PROF_LIBNAME)_nompi.a 
-	 $(MAKE) ${libbuild_dir}/mpe_prof.o 
+	 $(MAKE) ${libbuild_dir}/mpe_prof.@OBJEXT@ 
 	@if [ "$(F2CMPI_LIBS)" = "-l$(F2CMPI_LIBNAME)" ] ;  then \
 	     $(MAKE) ${libbuild_dir}/lib$(F2CMPI_LIBNAME).a ; \
 	 fi
 	 $(MAKE) clog_print
 	 $(MAKE) clog2alog
-	 $(MAKE) slog_print
-	 $(MAKE) clog2slog
+	@if [ -n "$(C2S1_SRC)" ] ; then \
+	     $(MAKE) slog_print ; \
+	     $(MAKE) clog2slog ; \
+     fi
 
 #
 # This target will get compiled if the user specified --with-mpedbg option
@@ -129,8 +142,10 @@ mpe_debug_objs:
 # This must refer to a relative directory incase we are in a VPATH build.
 # Because VPATH searches are applied to targets as well as sources, we
 # set this up to a dummy directory.
+# Use && to ensure that the second test is only performed if the
+# first is true.
 libslog.a:
-	@if [ "$(SLOG_HOME)" != "" -a -d $(SLOG_HOME) ]; then \
+	@if [ "$(SLOG_HOME)" != "" ] && [ -d "$(SLOG_HOME)" ]; then \
 	    ( cd ../slog_api ; \
 	      $(MAKE) "SLOG_DESTLIB=${libbuild_dir}/lib$(PROF_LIBNAME).a" )   \
 	fi
@@ -152,6 +167,16 @@ ${libbuild_dir}/lib$(PROF_LIBNAME).a: $(MPE_OBJECTS)
 	$(RANLIB) $@
 #	-$(RM) -f $?
 
+#
+# Building a shared library requires different tools on different systems.
+# The following will work *ONLY* for gcc.  Eventually, this should invoke
+# the approriate command to handle other shared libraries on other systems.
+${libbuild_dir}/lib$(PROF_LIBNAME).so: $(MPE_SHLOBJECTS)
+	if [ "@SHAREDKIND@" = "gcc" ] ; then \
+	$(CLINKER) -shared -Wl,-soname,lib$(PROF_LIBNAME).so.1.0 -Wl,-rpath,$(libdir) -o $@.1.0 $(MPE_SHLOBJECTS) -L /usr/X11R6/lib -lX11 -L ../slog_api/lib -lslog -lm ; \
+	ln -sf lib$(PROF_LIBNAME).so.1.0 ${libbuild_dir}/lib$(PROF_LIBNAME).so ; \
+	fi
+
 ${libbuild_dir}/lib$(PROF_LIBNAME)_nompi.a:  $(MPEGRAPHICS_SOURCE)
 	@if [ "$(MPEGRAPHICS_SOURCE)" != "" ] ; then \
 	    $(MAKE) -f Makefile_nompi clean ; \
@@ -160,42 +185,44 @@ ${libbuild_dir}/lib$(PROF_LIBNAME)_nompi.a:  $(MPEGRAPHICS_SOURCE)
 	fi
 
 # mpe_plog.o: mpe_log.c mpe_log_genproc.c mpe_log_merge.c mpe_log_adjusttime.c
-mpe_plog.o: mpe_log.c
+mpe_plog.@OBJEXT@: mpe_log.c
 	$(MPI_CC) $(CFLAGS) -c -DUSE_PMPI $?
-	@/bin/mv mpe_log.o mpe_plog.o
+	@mv mpe_log.@OBJEXT@ mpe_plog.@OBJEXT@
 
-${libbuild_dir}/lib$(TRACE_LIBNAME).a: trc_wrappers.o
+${libbuild_dir}/lib$(TRACE_LIBNAME).a: trc_wrappers.@OBJEXT@
 	$(AR) $(ARFLAGS) $@ $?
 	$(RANLIB) $@
 #	-$(RM) -f $?
 
-${libbuild_dir}/lib$(LOG_LIBNAME).a: log_wrap.o mpe_plog.o clog.o clog_util.o \
-                                     clog_merge.o clog2alog.o clog_time.o
+${libbuild_dir}/lib$(LOG_LIBNAME).a: log_wrap.@OBJEXT@ mpe_plog.@OBJEXT@ \
+                                     clog.@OBJEXT@ clog_util.@OBJEXT@ \
+                                     clog_merge.@OBJEXT@ clog2alog.@OBJEXT@ \
+                                     clog_time.@OBJEXT@
 	$(AR) $(ARFLAGS) $@ $?
 	$(RANLIB) $@
 #	-$(RM) -f $?
 
-${libbuild_dir}/lib$(ANIM_LIBNAME).a: visual_mess.o
+${libbuild_dir}/lib$(ANIM_LIBNAME).a: visual_mess.@OBJEXT@
 	$(AR) $(ARFLAGS) $@ $?
 	$(RANLIB) $@
 #	-$(RM) -f $?
 
-${libbuild_dir}/mpe_prof.o: mpe_prof.o
-	@-if [ ${libbuild_dir} != "." ] ; then \
+${libbuild_dir}/mpe_prof.@OBJEXT@: mpe_prof.@OBJEXT@
+	@-if [ "${libbuild_dir}" != "." ] ; then \
 	      /bin/cp $? ${libbuild_dir} ; \
 	  fi
 
-${libbuild_dir}/lib$(F2CMPI_LIBNAME).a: mpe_proff.o
+${libbuild_dir}/lib$(F2CMPI_LIBNAME).a: mpe_proff.@OBJEXT@
 	$(AR) $(ARFLAGS) $@ $?
 	$(RANLIB) $@
 
 # The old dependency and rule involes too many unnecessary code.  A.Chan
 # clog_print: printlog.o clog.o clog_time.o clog_util.o clog_merge.o
 #	$(CLINKER) $(CC_LDFLAGS) -o $@ printlog.o $(PROF_LIBS) 
-clog_print: printlog.o clog_util.o clog_sysio.o
-	$(CLINKER) $(CC_LDFLAGS) -o $@ $?
-	@if [ -n "$(binbuild_dir)" -a -d $(binbuild_dir) ] ; then \
-	     mv $@ $(binbuild_dir) ; \
+clog_print: printlog.@OBJEXT@ clog_util.@OBJEXT@ clog_sysio.@OBJEXT@
+	$(CLINKER) $(CC_LDFLAGS) -o $@@EXEEXT@ $?
+	@if [ -n "$(binbuild_dir)" ] && [ -d "$(binbuild_dir)" ] ; then \
+	     mv $@@EXEEXT@ $(binbuild_dir) ; \
 	 fi
 	 $(RM) -f $?
 
@@ -203,20 +230,21 @@ clog_print: printlog.o clog_util.o clog_sysio.o
 # $(PROF_LIBS) is needed on Linux but on IRIX/AIX/Solaris
 # clog2alog: ctoalog.o clog2alog.o clog.o clog_time.o clog_merge.o
 #	$(CLINKER) $(CC_LDFLAGS) -o $@ ctoalog.o clog2alog.o $(PROF_LIBS)
-clog2alog: ctoalog.o clog2alog.o clog_util.o clog_sysio.o
-	$(CLINKER) $(CC_LDFLAGS) -o $@ $?
-	@if [ -n "$(binbuild_dir)" -a -d $(binbuild_dir) ] ; then \
-	     mv $@ $(binbuild_dir) ; \
+clog2alog: ctoalog.@OBJEXT@ clog2alog.@OBJEXT@ \
+           clog_util.@OBJEXT@ clog_sysio.@OBJEXT@
+	$(CLINKER) $(CC_LDFLAGS) -o $@@EXEEXT@ $?
+	@if [ -n "$(binbuild_dir)" ] && [ -d "$(binbuild_dir)" ] ; then \
+	     mv $@@EXEEXT@ $(binbuild_dir) ; \
 	 fi
 
 slog_print: libslog.a
-	@if [ ! -x ../slog_api/bin/slog_printbbufs ] ; then \
+	@if [ ! -x ../slog_api/bin/slog_printbbufs@EXEEXT@ ] ; then \
 	     ( cd ../slog_api ; $(MAKE) ) ; \
 	 fi
-	@if [ -x ../slog_api/bin/slog_printbbufs ] ; then \
-	     cp -p ../slog_api/bin/slog_printbbufs $(binbuild_dir)/$@ ; \
+	@if [ -x ../slog_api/bin/slog_printbbufs@EXEEXT@ ] ; then \
+	     cp -p ../slog_api/bin/slog_printbbufs@EXEEXT@ $(binbuild_dir)/$@@EXEEXT@ ; \
 	 else \
-	     echo "Error in the generation of $@" ; \
+	     echo "Error in the generation of $@@EXEEXT@" ; \
 	 fi
 
 #  -DSTANDALONE turns on the byteswapping code
@@ -232,59 +260,60 @@ clog2slog: $(C2S_CSOURCES)
 	    echo "$(MPI_CC) -DSTANDALONE $(CFLAGS) -c $${srcfile}"; \
 	    $(MPI_CC) -DSTANDALONE $(CFLAGS) -c $${srcfile} ; \
 	done
-	$(CLINKER) $(CC_LDFLAGS) -o $@ $(C2S_OBJECTS) -L../slog_api/lib -lslog $(DEBUG_LIBS)
-	@if [ $(binbuild_dir) != "" -a -d $(binbuild_dir) ] ; then \
-	     mv $@ $(binbuild_dir) ; \
+	$(CLINKER) $(CC_LDFLAGS) -o $@@EXEEXT@ $(C2S_OBJECTS) -L../slog_api/lib -lslog $(DEBUG_LIBS)
+	@if [ "$(binbuild_dir)" != "" ] && [ -d "$(binbuild_dir)" ] ; then \
+	     mv $@@EXEEXT@ $(binbuild_dir) ; \
 	 fi
 	 $(RM) -f $(C2S_OBJECTS)
 
 
 # ********
 
-dbxtest: dbxtest.o ${libbuild_dir}/lib$(PROF_LIBNAME).a
-	$(MPI_CLINKER) $(CC_LDFLAGS) -o dbxtest dbxtest.o \
-		-L${libbuild_dir} -l$(PROF_LIBNAME) \
-		$(MPI_LIBS) 
-dbxtest2: dbxtest2.o 
-	$(MPI_CLINKER) $(CC_LDFLAGS) -o dbxtest2 dbxtest2.o \
+dbxtest: dbxtest.@OBJEXT@ ${libbuild_dir}/lib$(PROF_LIBNAME).a
+	$(MPI_CLINKER) $(CC_LDFLAGS) -o dbxtest@EXEEXT@ dbxtest.@OBJEXT@ \
+		-L${libbuild_dir} -l$(PROF_LIBNAME) $(MPI_LIBS) 
+dbxtest2: dbxtest2.@OBJEXT@ 
+	$(MPI_CLINKER) $(CC_LDFLAGS) -o dbxtest2@EXEEXT@ dbxtest2.@OBJEXT@ \
 		$(LIB_PATH) 
-testlog: testlog.o clog.o clog_time.o clog_merge.o clog_util.o
-	$(MPI_CLINKER) $(CC_LDFLAGS) -o testlog testlog.o \
+testlog: testlog.@OBJEXT@ clog.@OBJEXT@ clog_time.@OBJEXT@ \
+         clog_merge.@OBJEXT@ clog_util.@OBJEXT@
+	$(MPI_CLINKER) $(CC_LDFLAGS) -o testlog@EXEEXT@ testlog.@OBJEXT@ \
 		$(LOG_LIBS) 
 
 #
 # Remove the old libraries before rebuilding (in case they came from another
 # architecture or are otherwise damaged)
 rmlib:
-	@-if [ "$(SLOG_HOME)" != "" -a -d "$(SLOG_HOME)" ]; then \
+	@-if [ "$(SLOG_HOME)" != "" ] && [ -d "$(SLOG_HOME)" ] ; then \
 	    ( cd ../slog_api ; $(MAKE) rmlib ) \
 	fi
 	$(RM) -f ${libbuild_dir}/lib$(PROF_LIBNAME).a 
+	$(RM) -f ${libbuild_dir}/lib$(PROF_LIBNAME).so 
 	$(RM) -f ${libbuild_dir}/lib$(TRACE_LIBNAME).a 
 	$(RM) -f ${libbuild_dir}/lib$(LOG_LIBNAME).a 
 	$(RM) -f ${libbuild_dir}/lib$(ANIM_LIBNAME).a 
 	$(RM) -f ${libbuild_dir}/lib$(PROF_LIBNAME)_nompi.a
 	$(RM) -f ${libbuild_dir}/lib$(F2CMPI_LIBNAME).a
-	$(RM) -f ${libbuild_dir}/mpe_prof.o
+	$(RM) -f ${libbuild_dir}/mpe_prof.@OBJEXT@
 
 rmprog:
-	@-if [ "$(SLOG_HOME)" != "" -a -d "$(SLOG_HOME)" ]; then \
+	@-if [ "$(SLOG_HOME)" != "" ] && [ -d "$(SLOG_HOME)" ] ; then \
 	    ( cd ../slog_api ; $(MAKE) rmprog ) \
 	fi
-	$(RM) -f dbxtest dbxtest2 testlog clog_print clog2alog clog2slog
-	$(RM) -f $(binbuild_dir)/clog_print 
-	$(RM) -f $(binbuild_dir)/clog2alog 
-	$(RM) -f $(binbuild_dir)/slog_print 
-	$(RM) -f $(binbuild_dir)/clog2slog 
+	$(RM) -f $(EXECS)
+	$(RM) -f $(binbuild_dir)/clog_print@EXEEXT@ 
+	$(RM) -f $(binbuild_dir)/clog2alog@EXEEXT@ 
+	$(RM) -f $(binbuild_dir)/slog_print@EXEEXT@ 
+	$(RM) -f $(binbuild_dir)/clog2slog@EXEEXT@ 
 
 clean:
-	@-if [ "$(SLOG_HOME)" != "" -a -d "$(SLOG_HOME)" ]; then \
+	@-if [ "$(SLOG_HOME)" != "" ] && [ -d "$(SLOG_HOME)" ] ; then \
 	    ( cd ../slog_api ; $(MAKE) clean ) \
 	fi
-	-@$(RM) -f *.o ${srcdir}/*.o *~ $(EXECS) PI*
+	-@$(RM) -f *.@OBJEXT@ ${srcdir}/*.@OBJEXT@ *~ $(EXECS) PI*
 
 distclean: clean rmprog rmlib
-	@-if [ "$(SLOG_HOME)" != "" -a -d "$(SLOG_HOME)" ]; then \
+	@-if [ "$(SLOG_HOME)" != "" ] && [ -d "$(SLOG_HOME)" ] ; then \
 	    ( cd ../slog_api ; $(MAKE) distclean ) \
 	fi
 	-@$(RM) -f Makefile Makefile_nompi dbxerr.c
diff --git a/mpid/ch_p4/configure b/mpid/ch_p4/configure
--- a/mpid/ch_p4/configure
+++ b/mpid/ch_p4/configure
@@ -871,16 +871,29 @@ return 0;
 }
 
 EOF
-        if test -n "$compile" ; then 
-        eval $compile
+        if test -n "$compile" ; then 	
+	eval $compile
     else
 	eval $ac_compile
 	eval $ac_link
     fi
     if test ! -s conftest ; then
-      echo "Could not build executable program:"
-      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS"
-      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS 
+        echo "Could not build executable program:" >>config.log
+        if test -n "$compile" ; then
+	    # Autoconf defined a compile command with all output to dev null
+	    # For the configure log, rerun without the redirection
+	    compiletmp='${CC-cc} $CFLAGS conftest.c -o conftest $LIBS >>config.log 2>&1'
+	    echo $compiletmp >>config.log
+	    eval $compiletmp 
+	    echo "Return status was $?" >>config.log
+        else
+	    echo $ac_compile >>config.log
+   	    eval $ac_compile >>config.log 2>&1
+	    echo $ac_link >>config.log
+	    eval $ac_link >>config.log 2>&1
+        fi
+	echo "Test program was" >> config.log
+	cat conftest.c >> config.log
     ac_cv_mmap=0
 
     else
@@ -919,7 +932,7 @@ fi
 # We need to check that semctl is ok.
 # Both of these need to go into aclocal.m4
 echo $ac_n "checking that semget works""... $ac_c" 1>&1
-echo "configure:923: checking that semget works" >&2
+echo "configure:936: checking that semget works" >&2
 ###
 ### Still need to check for SEMUN_UNDEFINED - see mpid/ch_p4/p4/configure.in
 ### 
@@ -1027,7 +1040,7 @@ fi
 
 
 echo $ac_n "checking that signals work correctly""... $ac_c" 1>&1
-echo "configure:1031: checking that signals work correctly" >&2
+echo "configure:1044: checking that signals work correctly" >&2
 cat >conftest.c <<EOF
 #include <signal.h>
 static int rc = 0, irc = 1, maxcnt=5;
@@ -1081,17 +1094,17 @@ if test -n "$pac_cv_cross_compiling" ; then
     fi
 else
     echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
-echo "configure:1085: checking whether cross-compiling" >&2
+echo "configure:1098: checking whether cross-compiling" >&2
     # If we cannot run a trivial program, we must be cross compiling.
             if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1091 "configure"
+#line 1104 "configure"
 #include "confdefs.h"
 main(){exit(0);}
 EOF
-if { (eval echo configure:1095: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1108: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   pac_ok=1
 else
@@ -1108,11 +1121,11 @@ fi
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1112 "configure"
+#line 1125 "configure"
 #include "confdefs.h"
 main(){exit(1);}
 EOF
-if { (eval echo configure:1116: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1129: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   pac_ok=0 
 else
@@ -1140,7 +1153,7 @@ fi
 # Extract the first word of "$program", so it can be a program name with args.
 set dummy $program; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:1144: checking for $ac_word" >&2
+echo "configure:1157: checking for $ac_word" >&2
 if eval "test \"`echo '$''{'ac_cv_path_RSHCOMMAND'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1174,7 +1187,7 @@ fi
 
         if test -n "$RSHCOMMAND" ; then
 	    echo $ac_n "checking whether $RSHCOMMAND works""... $ac_c" 1>&1
-echo "configure:1178: checking whether $RSHCOMMAND works" >&2
+echo "configure:1191: checking whether $RSHCOMMAND works" >&2
             output=`$RSHCOMMAND $machine -n true 2>&1 </dev/null`
             if test -n "$output" ; then
 		echo "$ac_t""no" 1>&1
@@ -1197,7 +1210,7 @@ echo "configure:1178: checking whether $RSHCOMMAND works" >&2
     	# Extract the first word of "ssh", so it can be a program name with args.
 set dummy ssh; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:1201: checking for $ac_word" >&2
+echo "configure:1214: checking for $ac_word" >&2
 if eval "test \"`echo '$''{'ac_cv_path_RSHCOMMAND'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1231,7 +1244,7 @@ fi
 
     	if test -n "$RSHCOMMAND" ; then
     	    echo $ac_n "checking whether $RSHCOMMAND works""... $ac_c" 1>&1
-echo "configure:1235: checking whether $RSHCOMMAND works" >&2
+echo "configure:1248: checking whether $RSHCOMMAND works" >&2
     	    output=`$RSHCOMMAND -o "StrictHostKeyChecking no" \
     	      -o "BatchMode yes" $machine -n true 2>&1 </dev/null`
     	    if test $? -ne 0 ; then
@@ -1257,7 +1270,7 @@ fi
 CROSS_SIZEOF_INT=${CROSS_SIZEOF_INT:-4}
 CROSS_SIZEOF_LONG=${CROSS_SIZEOF_LONG:-4}
 echo $ac_n "checking size of int""... $ac_c" 1>&1
-echo "configure:1261: checking size of int" >&2
+echo "configure:1274: checking size of int" >&2
 if eval "test \"`echo '$''{'ac_cv_sizeof_int'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1265,7 +1278,7 @@ else
   ac_cv_sizeof_int=$CROSS_SIZEOF_INT
 else
   cat > conftest.$ac_ext <<EOF
-#line 1269 "configure"
+#line 1282 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1276,7 +1289,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1280: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1293: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_int=`cat conftestval`
 else
@@ -1296,7 +1309,7 @@ EOF
 
 
 echo $ac_n "checking size of long""... $ac_c" 1>&1
-echo "configure:1300: checking size of long" >&2
+echo "configure:1313: checking size of long" >&2
 if eval "test \"`echo '$''{'ac_cv_sizeof_long'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1304,7 +1317,7 @@ else
   ac_cv_sizeof_long=$CROSS_SIZEOF_LONG
 else
   cat > conftest.$ac_ext <<EOF
-#line 1308 "configure"
+#line 1321 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1315,7 +1328,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1319: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1332: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_long=`cat conftestval`
 else
@@ -1338,9 +1351,9 @@ EOF
 for ac_func in gettimeofday BSDgettimeofday
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:1342: checking for $ac_func" >&2
+echo "configure:1355: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 1344 "configure"
+#line 1357 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -1361,7 +1374,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1365: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1378: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1387,9 +1400,9 @@ done
 for ac_func in setsid isatty
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:1391: checking for $ac_func" >&2
+echo "configure:1404: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 1393 "configure"
+#line 1406 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -1410,7 +1423,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1414: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1427: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1452,13 +1465,14 @@ if test ! -s ${rootdir}/util/machines/machines.$ARCH ; then
         # Extract the first word of "hostname", so it can be a program name with args.
 set dummy hostname; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:1456: checking for $ac_word" >&2
+echo "configure:1469: checking for $ac_word" >&2
 ac_prog_where=""
 if test -n "$HOSTNAME_PGM"; then
   ac_pg_HOSTNAME_PGM="$HOSTNAME_PGM" # Let the user override the test.
 else
   ac_first_char=`expr "hostname" : "\(.\)"`
-  if test "$ac_first_char" = "/" -a -x "hostname" ; then
+  # Use ac_word instead of hostname in case the command has options on it.
+  if test "$ac_first_char" = "/" -a -x "$ac_word" ; then
        ac_pg_HOSTNAME_PGM=""
        ac_prog_where=hostname
   else
