1.0.13

diff --git a/mpid/ch_p4/p4-1.4/configure.in b/mpid/ch_p4/p4-1.4/configure.in
--- a/mpid/ch_p4/p4-1.4/configure.in
+++ b/mpid/ch_p4/p4-1.4/configure.in
@@ -35,7 +35,9 @@ progname="`echo $0 | sed 's:^\./\./:\./:'`"
 usage_msg="
 Usage: ${progname} -p4arch=ARCH_TYPE [-alog={on,off}] [-dprintfl={on,off}]
                    [-p4comm=shared]  [-listener_pathname="\<pathname\>"]
+                   [-rsh=command] [-rshnol] [-cflags=flags]
 "
+RSHCOMMAND=
 OPTFLAGS="-g"
 USERCC=0
 CC=${CC:-cc}
@@ -70,6 +72,16 @@ case $arg in
      p4dprintfl=`echo $arg|sed 's/-dprintfl=//'`
      echo Setting p4dprintfl to $p4dprintfl
      ;;
+  -rsh=*)
+     RSHCOMMAND=`echo A$arg|sed 's/A-rsh=//'`
+     echo Setting RSHCOMMAND to $RSHCOMMAND
+     ;;
+   -rshnol)
+     RSHNOL=1
+     ;;
+  -cflags=*)
+     USER_CFLAGS="`echo A$arg|sed 's/A-*cflags=//'`"
+     ;;
   -listener_pathname=*)
      p4listener_pathname=`echo $arg|sed 's/-listener_pathname=//'`
      echo Setting p4listener_pathname to $p4listener_pathname
@@ -93,8 +105,12 @@ case $arg in
      SOCKSIZE="`echo $arg|sed 's/-*socksize=//'`"
      ;;
    *)
-     echo "Invalid p4 configure option $arg"
-     (echo "${usage_msg}") >& 2
+     # Allow null args
+     if test -n "$arg" ; then
+         echo "Invalid p4 configure option $arg"
+         (echo "${usage_msg}") >& 2
+         exit 1;
+     fi
      ;;
 esac
 done
@@ -113,7 +129,10 @@ MDEP_CFLAGS=
 MDEP_FFLAGS=
 MDEP_LFLAGS=
 P4_OBJ="\$(P4_COMM_OBJ) \$(P4_SOCK_OBJ) \$(P4_SHMEM_OBJ)"
-P4_CONFIGURED_TIME="`date`"
+#
+# date might include various quotes.  Just to be safe, remove anything
+# other than letters, numbers, space, and colon.
+P4_CONFIGURED_TIME="`date | sed -e 's/[^a-zA-Z0-9: ]//g'`"
 DEFINE_ALOG="#undef ALOG_TRACE"
 DEFINE_SYSV_IPC="#undef SYSV_IPC"
 DEFINE_VENDOR_IPC="#undef VENDOR_IPC"
@@ -160,10 +179,29 @@ AR="ar ruv"
 RANLIB=true
 if test -n "$p4comm_shared"; then
   DEFINE_VENDOR_IPC="#define VENDOR_IPC"
+  AC_HAVE_LIBRARY(thread,MDEP_LIBS="$MDEP_LIBS -lthread")
 fi
 AC_HAVE_LIBRARY(socket,MDEP_LIBS=-lsocket)
 AC_HAVE_LIBRARY(nsl,MDEP_LIBS="$MDEP_LIBS -lnsl")
-AC_HAVE_LIBRARY(thread,MDEP_LIBS="$MDEP_LIBS -lthread")
+AC_MSG_CHECKING(for how many arguments gettimeofday takes)
+AC_TEST_PROGRAM([#include <sys/time.h>
+main() {struct timeval tp;
+gettimeofday(&tp);return 0;}],
+MDEP_CFLAGS="$MDEP_CFLAGS -DUSE_WIERDGETTIMEOFDAY"
+AC_MSG_RESULT(one!),AC_MSG_RESULT(two - whew))
+dnl #MDEP_LIBS = /usr/ucblib/libucb.a -lsocket -lnsl  # for fortran
+fi
+#						Intel x86 running Solaris
+if test -n "$p4arch_I86_SOLARIS"; then
+P4ARCH=I86_SOLARIS
+AR="ar ruv"
+RANLIB=true
+if test -n "$p4comm_shared"; then
+  DEFINE_VENDOR_IPC="#define VENDOR_IPC"
+  AC_HAVE_LIBRARY(thread,MDEP_LIBS="$MDEP_LIBS -lthread")
+fi
+AC_HAVE_LIBRARY(socket,MDEP_LIBS=-lsocket)
+AC_HAVE_LIBRARY(nsl,MDEP_LIBS="$MDEP_LIBS -lnsl")
 AC_MSG_CHECKING(for how many arguments gettimeofday takes)
 AC_TEST_PROGRAM([#include <sys/time.h>
 main() {struct timeval tp;
@@ -282,7 +320,31 @@ if test -n "$p4arch_SGI"; then
     P4ARCH=SGI
     RANLIB=true
     AC_HAVE_LIBRARY(sun,MDEP_LIBS=-lsun)
-    MDEP_CFLAGS=-cckr
+    dnl    MDEP_CFLAGS=-cckr
+    if test -n "$p4comm_shared"; then
+      DEFINE_VENDOR_IPC="#define VENDOR_IPC"
+    fi
+fi
+#
+# Force 32-bit objects
+if test -n "$p4arch_SGI32"; then
+    P4ARCH=SGI
+    RANLIB=true
+    AC_HAVE_LIBRARY(sun,MDEP_LIBS=-lsun)
+    MDEP_CFLAGS="-32 -woff 1552,1174"
+    MDEP_FFLAGS="-32 -woff 1552,1174"
+    if test -n "$p4comm_shared"; then
+      DEFINE_VENDOR_IPC="#define VENDOR_IPC"
+    fi
+fi
+#
+# Force 32-bit objects (other way)
+if test -n "$p4arch_SGIN32"; then
+    P4ARCH=SGI
+    RANLIB=true
+    AC_HAVE_LIBRARY(sun,MDEP_LIBS=-lsun)
+    MDEP_CFLAGS="-n32 -woff 1552,1174"
+    MDEP_FFLAGS="-n32 -woff 1552,1174"
     if test -n "$p4comm_shared"; then
       DEFINE_VENDOR_IPC="#define VENDOR_IPC"
     fi
@@ -306,6 +368,8 @@ if test -n "$p4arch_SGI_MP"; then
     P4ARCH=SGI_MP
     RANLIB=true
     AC_HAVE_LIBRARY(sun,MDEP_LIBS=-lsun)
+    AC_HAVE_FUNCS(setsid)
+    AC_HAVE_FUNCS(isatty)
     MDEP_CFLAGS=-cckr
     if test -n "$p4comm_shared"; then
       DEFINE_VENDOR_IPC="#define VENDOR_IPC"
@@ -315,8 +379,22 @@ fi
 if test -n "$p4arch_SGI_CH"; then
     P4ARCH=SGI_CH
     RANLIB=true
-    MDEP_CFLAGS="-cckr -64 -mips3 -non_shared -woff 1552,1174"
-    MDEP_FFLAGS="-cckr -64 -mips3 -non_shared -woff 1552,1174"
+    AC_HAVE_FUNCS(setsid)
+    AC_HAVE_FUNCS(isatty)
+    MDEP_CFLAGS="-cckr -64 -mips3 -woff 1552,1174" # -non_shared
+    MDEP_FFLAGS="-cckr -64 -mips3 -woff 1552,1174" # -non_shared
+    if test -n "$p4comm_shared"; then
+       DEFINE_VENDOR_IPC="#define VENDOR_IPC"
+    fi
+fi
+#						SGI Challenge Series
+if test -n "$p4arch_SGI_CH32"; then
+    P4ARCH=SGI_CH
+    RANLIB=true
+    AC_HAVE_FUNCS(setsid)
+    AC_HAVE_FUNCS(isatty)
+    MDEP_CFLAGS="-n32 -woff 1552,1174"
+    MDEP_FFLAGS="-n32 -woff 1552,1174"
     if test -n "$p4comm_shared"; then
        DEFINE_VENDOR_IPC="#define VENDOR_IPC"
     fi
@@ -325,8 +403,8 @@ fi
 if test -n "$p4arch_SGI_CH64"; then
     P4ARCH=SGI_CH64
     RANLIB=true
-    dnl MDEP_CFLAGS="-cckr -64 -mips4 -non_shared -woff 1552,1174"
-    dnl MDEP_FFLAGS="-cckr -64 -mips4 -non_shared -woff 1552,1174"
+    dnl MDEP_CFLAGS="-cckr -64 -mips4 -woff 1552,1174"# -non_shared
+    dnl MDEP_FFLAGS="-cckr -64 -mips4 -woff 1552,1174"# -non_shared
     MDEP_CFLAGS="-cckr -64 -mips4 -woff 1552,1174"
     MDEP_FFLAGS="-cckr -64 -mips4 -woff 1552,1174"
     AC_HAVE_FUNCS(setsid)
@@ -337,6 +415,14 @@ if test -n "$p4arch_SGI_CH64"; then
 fi
 #                                              UXPM (MPIS chip)
 if test -n "$p4arch_UXPM"; then
+    # Make it think that it is an IRIX v5 SGI
+    P4ARCH=SGI
+    RANLIB=true
+    MDEP_LIBS="-lsocket -lnsl"
+    MDEP_CFLAGS="-DNEEDS_NETINET"
+fi
+#                                              UXPV  (Fujitsu VX,VPP300,VPP700)
+if test -n "$p4arch_UXPV"; then
     # Make it think that it is an IRIX v5 SGI
     P4ARCH=SGI
     RANLIB=true
@@ -383,14 +469,59 @@ fi
 AC_CROSS_CHECK()
 #
 # Look for netinet/in.h and sys/socketvar.h
-AC_HAVE_HEADERS(netinet/in.h)
-AC_HAVE_HEADERS(sys/socketvar.h)
+PAC_CHECK_HEADERS(netinet/in.h)
+PAC_CHECK_HEADERS(sys/socketvar.h)
+PAC_CHECK_HEADERS(stdlib.h)
+PAC_CHECK_HEADERS(unistd.h)
+PAC_CHECK_HEADER(stdarg.h,[AC_DEFINE(HAVE_STDARG_H)
+havestdarg=1])
+PAC_CHECK_HEADERS(string.h)
+PAC_CHECK_HEADERS(strings.h)
+#
+# It isn't enough to check for stdarg.  Even gcc doesn't get it right;
+# on some systems, the gcc version of stdio.h loads stdarg.h WITH THE WRONG
+# OPTIONS (causing it to choose the OLD STYLE va_start etc).
+#
+if test -n "$havestdarg" ; then
+    PAC_COMPILE_CHECK_FUNC(stdarg is correct,[
+/* DEC Alpha compiler by default does NOT define __STDC__ but DOES
+   accept prototypes */
+#if !defined(__STDC__)
+'bad text'
+#endif
+#include <stdio.h>
+#include <stdarg.h>
+int func( int a, ... ){
+int b;
+va_list ap;
+va_start( ap, a );
+b = va_arg(ap, int);
+printf( "%d-%d\n", a, b );
+va_end(ap);
+fflush(stdout);
+return 0;
+}
+int main() { func( 1, 2 ); return 0;}],AC_DEFINE(USE_STDARG))
+fi
 #
 # Look for sigaction routine (instead of signal)
 AC_HAVE_FUNCS(sigaction)
+# strerror is prefered over extern char *sys_errlist[];
+AC_HAVE_FUNCS(strerror)
+AC_HAVE_LIBRARY(crypt,CRYPT_LIBS=-lcrypt)
+
+if test -n "$RSHCOMMAND" ; then
+    AC_DEFINE(HAS_RSHCOMMAND)
+fi
+if test -n "$RSHNOL" ; then
+    AC_DEFINE(RSH_HAS_NO_L)
+fi
 #
 # We do NOT add the CFLAGS and DEFS to the MDEP_CFLAGS because they are 
-# used ONLY in building the p4 package itself.
+# used ONLY in building the p4 package itself.  However, we add USER_CFLAGS
+# which were specified on the configure
+#
+MDEP_CFLAGS="$USER_CFLAGS $MDEP_CFLAGS"
 #
 # Set the sock_buff_size variable through the "optflags" variable
 if test -n "$SOCKSIZE" ; then
@@ -411,6 +542,7 @@ AC_SUBST(RANLIB)dnl
 AC_SUBST(RM)dnl
 AC_SUBST(P4_OBJ)dnl
 AC_SUBST(MDEP_LIBS)dnl
+AC_SUBST(CRYPT_LIBS)dnl
 AC_SUBST(MDEP_CFLAGS)dnl
 AC_SUBST(MDEP_FFLAGS)dnl
 AC_SUBST(MDEP_LFLAGS)dnl
@@ -421,6 +553,7 @@ AC_SUBST(DEFINE_SYSV_IPC)dnl
 AC_SUBST(DEFINE_VENDOR_IPC)dnl
 AC_SUBST(DEFINE_P4_DPRINTFL)dnl
 AC_SUBST(LISTENER_PATHNAME)dnl
+AC_SUBST(RSHCOMMAND)dnl
 AC_OUTPUT(Makefile lib/Makefile alog/Makefile usc/Makefile usc/usctest/Makefile messages/Makefile include/Makefile lib_f/Makefile contrib/Makefile contrib_f/Makefile bin/Makefile doc/Makefile messages_f/Makefile misc/Makefile monitors/Makefile servers/Makefile)
 dnl 
 dnl This code removes that stupid first line placed by ac_output
diff --git a/profiling/nupshot/configure b/profiling/nupshot/configure
--- a/profiling/nupshot/configure
+++ b/profiling/nupshot/configure
@@ -1,41 +1,4 @@
 
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
 progname="`echo $0 | sed 's:^\./\./:\./:'`"
 print_error() {
     echo "*# $*" 2>&1 ;
@@ -552,9 +515,14 @@ else
     /usr/local/include \
     /usr/unsupported/include \
     /usr/x386/include \
+    /usr/local/X11R6/include \
+    /usr/local/X11R5/include \
+    /usr/local/x11r6/include \
     /usr/local/x11r5/include \
+    /usr/include/X11R6 \
     /usr/include/X11R5 \
     /usr/include/X11R4 \
+    /usr/X11R6/include \
     /usr/X11R5/include \
     /usr/X11/include \
     /usr/openwin/include \
@@ -643,9 +611,13 @@ else
   /usr/local/lib \
   /usr/unsupported/lib \
   /usr/x386/lib \
+  /usr/local/X11R6/lib \
+  /usr/local/X11R5/lib \
+  /usr/local/x11r6/lib \
   /usr/local/x11r5/lib \
   /usr/lib/X11 \
   /usr/lib/X11R4 \
+  /usr/X11R6/lib \
   /usr/X11R5/lib \
   /usr/X11/lib \
   /usr/openwin/lib \
@@ -1138,6 +1110,7 @@ for dir in \
     /opt/Tcl \
     /opt/local \
     /opt/local/tcl7.0 \
+    /Tools/tcl \
     /local/encap/tcl-7.1 ; do
     if test -r $dir/include/tcl.h -a -r $dir/lib/libtcl.a ; then
 	TCL_DIR=$dir
@@ -1203,6 +1176,7 @@ for dir in \
     /opt/Tcl \
     /opt/local \
     /opt/local/tk3.6 \
+    /Tools/tk \
     /local/encap/tk-3.4 $TCL_DIR ; do
     if test -r $dir/include/tk.h -a -r $dir/lib/libtk.a ; then
 	TK_DIR=$dir
@@ -1265,24 +1239,114 @@ else
 echo $ac_n "checking for version of TK""... $ac_c" 1>&1
 fi
 /bin/rm -f conftestval
-CFLAGSsave="$CFLAGS"
-CFLAGS="$CFLAGS -I$TK_DIR/include $XINCLUDES"
+#
+# Some systems have a separate tcl dir; since we need both tcl and tk
+# we include both directories
+if test -n "$TK_DIR" -a -n "$TCL_DIR" ; then
+  CFLAGSsave="$CFLAGS"
+  CFLAGS="$CFLAGS -I$TK_DIR/include -I$TCL_DIR/include $XINCLUDES"
+  
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking whether cross-compiling""... $ac_c"
+else
+echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
+fi
+# If we cannot run a trivial program, we must be cross compiling.
 cat > conftest.c <<EOF
 #include "confdefs.h"
+main(){exit(0);}
+EOF
+eval $compile
+if test -s conftest && (./conftest; exit) 2>/dev/null; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+
+else
+  cross_compiling=1;if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+fi
+rm -fr conftest*
+
+
+if test "$cross_compiling" = 1 -a -z "$TESTCC" ; then
+    
+    Pac_CV_NAME=0
+else
+    if test -n "$TESTCC" ; then
+      CCsav="$CC"
+      CC="$TESTCC"
+    fi
+    cat > conftest.c <<EOF
+#include "confdefs.h"
 #include "tk.h"
+#include <stdio.h>
 main() { FILE *fp = fopen( "conftestval", "w" ); 
 fprintf( fp, "%d.%d", TK_MAJOR_VERSION, TK_MINOR_VERSION );
 return 0; }
 EOF
-eval $compile
-if test -s conftest && (./conftest; exit) 2>/dev/null; then
-  TK_VERSION=`cat conftestval`
+    eval $compile
+    if test ! -s conftest ; then
+      echo "Could not build executable program:"
+      echo "${CC-cc} $CFLAGS conftest.c -o conftest $LIBS"
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LIBS 
+    TK_VERSION="unavailable"
 
+    else
+      /bin/rm -f conftestout
+      if test -s conftest && (./conftest; exit) 2>conftestout; then
+          TK_VERSION=`cat conftestval`
+
+      else
+        echo "Execution of test program failed"
+        TK_VERSION="unavailable"
+
+        if test -s conftestout ; then
+            cat conftestout
+        fi
+      fi
+    fi
+  if test -n "$TESTCC" ; then
+        CC="$CCsav"
+  fi
+  rm -fr conftest*
+fi
+
+  CFLAGS="$CFLAGSsave"
+elif test -n "$wishloc" ; then
+  # It is possible to use a wish program with
+  # set tk_version [ string range $tk_patchLevel 0 2 ]
+  # puts stdout $tk_version
+  TK_VERSION="unavailable"
 else
   TK_VERSION="unavailable"
 fi
-rm -fr conftest*
-CFLAGS="$CFLAGSsave"
 if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""$TK_VERSION"
 else
@@ -1295,6 +1359,87 @@ if test "$TK_VERSION" != 3.6 ; then
     print_error "Aborting build of nupshot"
     exit 1
 fi
+#
+# Some damaged implementations of tk (SGI's is known to be one)
+# require an ADDITIONAL library, which may be in the TK lib directory OR
+# in the X directory.  This library is libXpm, it contains routines
+# like Xpm... which, as should be expected, are undocumented.
+# 
+if test -s $TK_DIR/lib/libXpm.a ; then
+    XPMLIB=-lXpm
+else
+    LIBS_save="${LIBS}"
+LIBS="${LIBS} -lXpm"
+have_lib=""
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for -lXpm""... $ac_c"
+else
+echo $ac_n "checking for -lXpm""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+
+int main() { exit(0); }
+int t() { main(); }
+EOF
+if eval $compile; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+  rm -rf conftest*
+  have_lib="1"
+
+   else if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+fi
+rm -f conftest*
+LIBS="${LIBS_save}"
+if test -n "${have_lib}"; then
+   :; XPMLIB="-lXpm"
+else
+   :; 
+fi
+
+fi
+
 
 
 
@@ -1348,6 +1493,7 @@ CPP='$CPP'
 tk_ok='$tk_ok'
 XINCLUDES='$XINCLUDES'
 XLIBSW='$XLIBSW'
+XPMLIB='$XPMLIB'
 TCL_DIR='$TCL_DIR'
 TK_DIR='$TK_DIR'
 OPTFLAGS='$OPTFLAGS'
@@ -1384,6 +1530,7 @@ s%@CPP@%$CPP%g
 s%@tk_ok@%$tk_ok%g
 s%@XINCLUDES@%$XINCLUDES%g
 s%@XLIBSW@%$XLIBSW%g
+s%@XPMLIB@%$XPMLIB%g
 s%@TCL_DIR@%$TCL_DIR%g
 s%@TK_DIR@%$TK_DIR%g
 s%@OPTFLAGS@%$OPTFLAGS%g
diff --git a/util/mpiinstall.in b/util/mpiinstall.in
--- a/util/mpiinstall.in
+++ b/util/mpiinstall.in
@@ -19,6 +19,8 @@ MODE=0664
 XMODE=0775
 # Uninstall filename
 UNINSTALLFILE="util/mpiuninstall"
+# If we're doing -libonly, we may want a different file....
+#
 # dirlist is used to uninstall empty directories at the end
 dirlist=""
 #
@@ -38,6 +40,8 @@ for arg in "$@" ; do
 	-nonupshot)nonupshot=1 ;;
 	-cpnupshot)cpnupshot=1 ;;
 	-noman) noman=1 ;;
+	-device=*) DEVICE=`echo A$arg | sed -e 's/A-device=//g'` 
+	           COMM=$DEVICE ;;
 	-manpath=*)MPIMANPATH=`echo $arg | sed -e 's/-manpath=//g'` ;;
 	-libonly) libonly=1 ;;
 	-t) Show=echo
@@ -59,6 +63,7 @@ for arg in "$@" ; do
 	echo "-cpnupshot   - Do not build nupshot; install the one in"
 	echo "               profiling/nupshot - WARNING - read the "
 	echo "               installation manual first!"
+	echo "-device=name - Select a different device type to install"
 	exit 1
 	;;
 	*)
@@ -70,6 +75,23 @@ done
 if [ -z "$APREFIX" ] ; then
     APREFIX=$PREFIX
 fi
+#
+# Update some fields that contain the build root directory
+# These work by extracting the syntax for specifying the library, and then
+# adding the correct destination to it.
+NFLIB_PATH=`echo "@FLIB_PATH@" | \
+	sed -e "s%^\([^/ ]*\)/[^ ]*%\1$PREFIX/lib/$ARCH/$COMM%g"`
+NFINC=`echo "@FINC@" | \
+	sed -e "s%^\([^/ ]*\)/[^ ]*%\1$PREFIX/include%g"`
+#
+# Remove old uninstall file
+/bin/rm -f $UNINSTALLFILE
+cat > $UNINSTALLFILE <<EOF
+#! /bin/sh
+set -x
+EOF
+chmod +x $UNINSTALLFILE
+#
 #
 # We could use install, but install is too different and too hard to 
 # test.  So here are the routines to copy file, make directories, and 
@@ -91,6 +113,10 @@ if [ -f $dest ] ; then
     echo "$dest exists; not changed"
 elif [ -d $1 ] ; then
     echo ">>> $1 is a directory; not copied <<<"
+    errs=`expr $errs + 1`
+    if [ $failmode = "hard" ] ; then exit 1 ; fi
+elif [ ! -f $1 ] ; then 
+    echo "**File $1 does not exist (or is not a regular file)!"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 else
@@ -178,11 +204,14 @@ else
 	-e "s%\#INCLUDE_PATH\#%@INCLUDE_PATH@%g" \
 	-e "s%\#INSTALL_DIR\#%$PREFIX%g" \
 	-e "s%\#LIB_LIST\#%@LIB_LIST@%g" \
+	-e "s%\#MPIRUN_BIN\#%lib/$ARCH/$COMM%g" \
         -e "s%\#MPIR_HOME\#%$PREFIX%g" \
 	-e "s%\#OPTFLAGS\#%@OPTFLAGS@%g" \
 	-e "s%\#PREFIX\#%$PREFIX%g" \
 	-e "s%\#RSH_COMMAND\#%$RSH_COMMAND%g" \
 	-e "s%\#SYNCLOC\#%@SYNCLOC@%g" \
+	-e "s%\#TK_VERSION\#%@TK_VERSION@%g" \
+	-e "s%\#MPILIBNAME\#%@MPILIBNAME@%g" \
 	-e "s%\#wishloc\#%@wishloc@%g" \
 	$1 > $dest
         rc=$?
@@ -219,8 +248,11 @@ fi
 # This has a few more fields than FixupFile
 #
 FixupFileWithAt() {
+    # Change the FIRST libpath to the new form.  This allows 
+    # the LIB_PATH to contain multiple names, as long as the MPICH libpath
+    # is first
     NLIBPATH=`echo "@LIB_PATH@" | \
-	sed -e "s%^\([^/]*\)/.*\$%\1$PREFIX/lib/$ARCH/$COMM%g"`
+	sed -e "s%^\([^/ ]*\)/[^ ]*%\1$PREFIX/lib/$ARCH/$COMM%g"`
 if [ -d $2 ] ; then
     dest=$2/`basename $1`
 else
@@ -235,7 +267,7 @@ else
         sed \
 	-e "s%[@]ARCH[@]%$ARCH%g" \
 	-e "s%[@]AUTOMOUNTFIX[@]%@AUTOMOUNTFIX@%g" \
-	-e "s%[@]FINC[@]%@FINC@%g" \
+	-e "s%[@]FINC[@]%$NFINC%g" \
         -e "s%[@]BITMAP_DIR[@]%$PREFIX/lib/bitmaps%g" \
 	-e "s%[@]CC[@]%@CC@%g" \
 	-e "s%[@]CCC[@]%@CCC@%g" \
@@ -250,7 +282,7 @@ else
 	-e "s%[@]F77[@]%@F77@%g" \
 	-e "s%[@]FFLAGS[@]%@FFLAGS@%g" \
 	-e "s%[@]FLIB_PATH_LEADER[@]%@FLIB_PATH_LEADER@%g" \
-	-e "s%[@]FLIB_PATH[@]%@FLIB_PATH@%g" \
+	-e "s%[@]FLIB_PATH[@]%$NFLIB_PATH%g" \
 	-e "s%[@]FLINKER[@]%@FLINKER@%g" \
 	-e "s%[@]INCLUDE_PATH[@]%@INCLUDE_PATH@%g" \
 	-e "s%[@]INSTALL_DIR[@]%$PREFIX%g" \
@@ -258,6 +290,7 @@ else
 	-e "s%[@]LIB_LIST[@]%@LIB_LIST@%g" \
 	-e "s%[@]MPE_LIBS[@]%@MPE_LIBS@%g" \
         -e "s%[@]MPIR_HOME[@]%$PREFIX%g" \
+        -e "s%[@]MPILIBNAME[@]%@MPILIBNAME@%g" \
 	-e "s%[@]OPTFLAGS[@]%@OPTFLAGS@%g" \
 	-e "s%[@]PREFIX[@]%$PREFIX%g" \
 	-e "s%[@]RSH_COMMAND[@]%$RSH_COMMAND%g" \
@@ -296,9 +329,9 @@ fi
 # End of routines
 #
 ##############################################################################
-if [ ! -s lib/$ARCH/$COMM/libmpi.a ] ; then 
+if [ ! -s lib/$ARCH/$COMM/lib@MPILIBNAME@.a ] ; then 
     echo "You must make MPI before installing it!"
-    echo "Could not find lib/$ARCH/$COMM/libmpi.a !"
+    echo "Could not find lib/$ARCH/$COMM/lib@MPILIBNAME@.a !"
     exit 1
 fi
 if [ ! -n "$PREFIX" ] ; then 
@@ -341,17 +374,22 @@ if [ -z "$libonly" ] ; then
         FixupFile profiling/upshot/bin/upshot.in $PREFIX/bin/upshot $XMODE
         #
         # Should clean nupshot sources  (*.c/h) 
-        if [ -n "@TCL_DIR@" -a -z "$cpnupshot" ] ; then 
+        if [ -n "@TCL_DIR@" -a -z "$cpnupshot" -a -n "@TK_DIR@" -a \
+	   "@TK_VERSION@" = "3.6" ] ; then 
             echo "Attempting to build nupshot... "
             $Show $CPRP -r profiling/nupshot $PREFIX
+	    echo "/bin/rm -rf $PREFIX/nupshot" >> $UNINSTALLFILE
             $Show "(cd $PREFIX/nupshot ; \
 	        if configure -tcldir=@TCL_DIR@ -tkdir=@TK_DIR@ ; then \
 	        $MAKE clean ; $MAKE ; \
     	        mv nupshot ../bin ; $MAKE clean ; fi )"
+	    echo "/bin/rm -f $PREFIX/bin/nupshot" >> $UNINSTALLFILE
 	elif [ -n "$cpnupshot" -a -f profiling/nupshot ] ; then 
             $Show $CPRP -r profiling/nupshot $PREFIX
+	    echo "/bin/rm -rf $PREFIX/nupshot" >> $UNINSTALLFILE
             $Show "(cd $PREFIX/nupshot ; \
 	        mv nupshot ../bin ; $MAKE clean )"
+	    echo "/bin/rm -f $PREFIX/bin/nupshot" >> $UNINSTALLFILE
         fi
     fi
     #
@@ -371,6 +409,13 @@ if [ -z "$libonly" ] ; then
         CopyFile $PREFIX/bin/$bfile $PREFIX/lib/$ARCH/$COMM $XMODE
     done
     $Show mv $PREFIX/bin/mpirun.sh $PREFIX/bin/mpirun
+    echo "/bin/rm -f $PREFIX/bin/mpirun" >> $UNINSTALLFILE
+    $Show mv $PREFIX/lib/$ARCH/$COMM/mpirun.sh $PREFIX/lib/$ARCH/$COMM/mpirun
+    echo "/bin/rm -f $PREFIX/lib/$ARCH/$COMM/mpirun" >> $UNINSTALLFILE
+    if [ ! -r $PREFIX/lib/$ARCH/$COMM/tarch ] ; then
+	( cd $PREFIX/lib/$ARCH/$COMM ; 	ln -s ../../../bin/tarch tarch )
+        echo "/bin/rm -f $PREFIX/lib/$ARCH/$COMM/tarch" >> $UNINSTALLFILE
+    fi
     #
     $Show /bin/rm -f $PREFIX/bin/mpireconfig
     echo "Creating mpireconfig from util/mpireconfig.in"
@@ -400,11 +445,15 @@ else
         FixupFile $file $PREFIX/lib/$ARCH/$COMM/$bfile $XMODE
     done
     $Show mv $PREFIX/lib/$ARCH/$COMM/mpirun.sh $PREFIX/lib/$ARCH/$COMM/mpirun
+    if [ ! -r $PREFIX/lib/$ARCH/$COMM/tarch ] ; then
+	( cd $PREFIX/lib/$ARCH/$COMM ; 	ln -s ../../../bin/tarch tarch )
+        echo "/bin/rm -f $PREFIX/lib/$ARCH/$COMM/tarch" >> $UNINSTALLFILE
+    fi
     FixupFileWithAt util/mpicc.in $PREFIX/lib/$ARCH/$COMM/mpicc $XMODE
     if [ -n "@CCC@" ] ; then
         FixupFileWithAt util/mpiCC.in $PREFIX/lib/$ARCH/$COMM/mpiCC $XMODE
     fi
-    FixupFileWithAt util/mpif7.in $PREFIX/lib/$ARCH/$COMM/mpif77 $XMODE
+    FixupFileWithAt util/mpif77.in $PREFIX/lib/$ARCH/$COMM/mpif77 $XMODE
     FixupFile util/mpireconfig.in $PREFIX/lib/$ARCH/$COMM/mpireconfig $XMODE
 fi
 #
@@ -412,11 +461,14 @@ fi
 # P4 server
 if [ "$DEVICE" = "ch_p4" ] ; then 
     echo "Attempting to build ch_p4 secure server"
-    $Show "( cd mpid/ch_p4/p4-1.4/servers ; make serv_p4 ; cd ../bin ; \
-            CopyFile serv_p4 $PREFIX/bin $XMODE ; )" 
+    $Show "( cd mpid/ch_p4/p4-1.4/servers ; make serv_p4 ; )" 
+    $Show CopyFile mpid/ch_p4/p4-1.4/bin/serv_p4 $PREFIX/bin $XMODE
+    $Show CopyFile $PREFIX/bin/serv_p4 $PREFIX/lib/$ARCH/$COMM $XMODE
     $Show /bin/rm -f util/chp4_servs
     FixupFile util/chp4_servs.in $PREFIX/util/chp4_servs $XMODE
     CopyFile $PREFIX/util/chp4_servs $PREFIX/lib/$ARCH/$COMM $XMODE
+    CopyFile util/chkserv $PREFIX/util/chkserv $XMODE
+    CopyFile $PREFIX/util/chkserv $PREFIX/lib/$ARCH/$COMM $XMODE
 fi
 #
 if [ -z "$libonly" ] ; then
@@ -454,12 +506,13 @@ done
 # Other files in lib need to be updated...
 #
 # Documentation
+# Note that we're not doing the www pages yet.
 if [ -z "$noman" -a -z "$libonly" ] ; then 
     if [ -z "$MPIMANPATH" ] ; then
         MPIMANPATH=$PREFIX/man
     fi
     CopyFile man/mandesc $MPIMANPATH
-    for dir in man3 man4 man5 ; do
+    for dir in man1 man3 man4 man5 ; do
        MkDir $MPIMANPATH/$dir
         for file in man/$dir/* ; do 
 	    CopyFile $file $MPIMANPATH/$dir
@@ -477,21 +530,31 @@ fi
 #
 # Updating the config.status file is trickier, since we need to edit
 # the directories that might have contained the original path.
+# It is important to update the CORRECT file, in the case that we are doing
+# a -libonly installation on a previously constructed version.
 #
 if [ $just_testing = 0 ] ; then
-    cat config.status | sed -e "s%MPIR_HOME=.*\$%MPIR_HOME='$PREFIX'%g" \
-    -e "s%^LIB_PATH=\([^/]*\)/.*\$%LIB_PATH=\1$PREFIX/lib/$ARCH/$COMM'%g" \
-    -e "s%^FLIB_PATH=\([^/]*\)/.*\$%FLIB_PATH=\1$PREFIX/lib/$ARCH/$COMM'%g" \
+    cat lib/$ARCH/$COMM/config.status | \
+	sed -e "s%MPIR_HOME=.*\$%MPIR_HOME='$PREFIX'%g" \
+    -e "s%^LIB_PATH=\([^/ ]*\)/[^ ']*%LIB_PATH=\1$PREFIX/lib/$ARCH/$COMM%g" \
+    -e "s%^FLIB_PATH=\([^/ ]*\)/[^ ']*%FLIB_PATH=\1$PREFIX/lib/$ARCH/$COMM%g" \
 		-e "s%MPE_DIR=.*\$%MPE_DIR='$PREFIX/mpe'%g" \
+    -e "s%^MPICC=\([^/ ]*\)/.*\$%MPICC=$PREFIX/lib/$ARCH/$COMM/mpicc%g" \
+    -e "s%^MPIF77=\([^/ ]*\)/.*\$%MPIF77=$PREFIX/lib/$ARCH/$COMM/mpif77%g" \
+    -e "s%^MPICPLUSPLUS=\([^/ ]*\)/.*\$%MPICPLUSPLUS=$PREFIX/lib/$ARCH/$COMM/mpiCC%g" \
 		        > $PREFIX/lib/$ARCH/$COMM/config.status 
     echo "/bin/rm -f $PREFIX/lib/$ARCH/$COMM/config.status" >> $UNINSTALLFILE
     chmod $XMODE $PREFIX/lib/$ARCH/$COMM/config.status 
 else 
 cat <<.
-cat config.status | sed -e "s%MPIR_HOME=.*\$%MPIR_HOME='$PREFIX'%g" \
-    -e "s%^LIB_PATH=\([^/]*\)/.*\$%LIB_PATH=\1$PREFIX/lib/$ARCH/$COMM'%g" \
-    -e "s%^FLIB_PATH=\([^/]*\)/.*\$%FLIB_PATH=\1$PREFIX/lib/$ARCH/$COMM'%g" \
+cat lib/$ARCH/$COMM/config.status | \
+	sed -e "s%MPIR_HOME=.*\$%MPIR_HOME='$PREFIX'%g" \
+    -e "s%^LIB_PATH=\([^/ ]*\)/[^ ']*%LIB_PATH=\1$PREFIX/lib/$ARCH/$COMM%g" \
+    -e "s%^FLIB_PATH=\([^/ ]*\)/[^ ']*%FLIB_PATH=\1$PREFIX/lib/$ARCH/$COMM%g" \
 		-e "s%MPE_DIR=.*\$%MPE_DIR='$PREFIX/mpe'%g" \
+    -e "s%^MPICC=\([^/ ]*\)/.*\$%MPICC=$PREFIX/lib/$ARCH/$COMM/mpicc%g" \
+    -e "s%^MPIF77=\([^/ ]*\)/.*\$%MPIF77=$PREFIX/lib/$ARCH/$COMM/mpif77%g" \
+    -e "s%^MPICPLUSPLUS=\([^/ ]*\)/.*\$%MPICPLUSPLUS=$PREFIX/lib/$ARCH/$COMM/mpiCC%g" \
 		        > $PREFIX/lib/$ARCH/$COMM/config.status
     chmod $XMODE $PREFIX/lib/$ARCH/$COMM/config.status 
 .
@@ -501,6 +564,7 @@ if [ -z "$libonly" ] ; then
     #
     $Show /bin/rm -f $PREFIX/examples/mpif.h
     $Show ln -s $PREFIX/include/mpif.h $PREFIX/examples/mpif.h
+    echo "/bin/rm -f $PREFIX/examples/mpif.h" >> $UNINSTALLFILE
 fi
 #
 # Example programs
@@ -511,6 +575,8 @@ Savevar=$PREFIX
 PREFIX=$APREFIX
 #FixupFile installtest/makefile.proto $PREFIX/examples/Makefile
 (cd $PREFIX/examples ; $PREFIX/lib/$ARCH/$COMM/mpireconfig Makefile )
+echo "(cd $PREFIX/examples ; $MAKE clean)" >> $UNINSTALLFILE
+echo "/bin/rm -f $PREFIX/examples/Makefile" >> $UNINSTALLFILE
 PREFIX=$Savevar
 CopyFile $PREFIX/examples/Makefile $PREFIX/lib/$ARCH/$COMM/Makefile.sample
 CopyFile installtest/cpi.c $PREFIX/examples
@@ -521,6 +587,7 @@ CopyFile installtest/README $PREFIX/examples
 # Test build the examples
 $Show "(cd $PREFIX/examples ; /bin/rm -f mpirun ; \
 	  ln -s ../bin/mpirun mpirun )"
+echo "/bin/rm -f $PREFIX/examples/mpirun" >> $UNINSTALLFILE
 #
 echo "About to run installation test..."
 $Show "(cd $PREFIX/examples; $MAKE)"
@@ -528,13 +595,17 @@ $Show "(cd $PREFIX/examples; $MAKE)"
 # Use the alternate method, using mpif77 and mpicc
 $Show "(cd $PREFIX/examples ; $MAKE clean ; $MAKE alternate)"
 #
+echo "/bin/rm -f $PREFIX/mpiuninstall" >> $UNINSTALLFILE
 # Add the directory removes to the UNINSTALL file
 for dir in $dirlist ; do
     echo "rmdir $dir" >> $UNINSTALLFILE
 done
 #
+cp $UNINSTALLFILE $PREFIX/mpiuninstall
+#
 echo installed $ARCH/$COMM/$DEVICE MPI in $PREFIX
-
+echo $PREFIX/mpiuninstall may be used to remove the installation.
+#
 if [ $errs -gt 0 ] ; then
     rc=1
 else
