1.2.5

diff --git a/examples/test/runbase b/examples/test/runbase
--- a/examples/test/runbase
+++ b/examples/test/runbase
@@ -50,8 +50,12 @@ MakeExe() {
     if [ ! -x $1 ] ; then
 	$MAKE $1
         if [ ! -x $1 ] ; then 
-	    echo "Could not build executable $1; aborting tests"
-	    exit 1
+	    if [ "$MPITEST_CONTINUE" = "always" ] ; then
+	        echo "Could not build executable $1; skipping this test"
+	    else 
+	        echo "Could not build executable $1; aborting tests"
+	        exit 1
+	    fi
         fi
     fi
 }
@@ -136,14 +140,19 @@ CheckOutput() {
 <STATUS>$passed</STATUS>
 EOF
 	    if [ $fileok = "no" ] ; then
-	    echo "<TESTDIFF>" >> $summaryfile
-	    if [ ! -s ${bfile}.out ] ; then
-	        echo "No output file" >>$summaryfile
-	    else
-	        diff -b ${bfile}.tout $cmpfile | \
-		sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g' >> $summaryfile
+	        echo "<TESTDIFF>" >> $summaryfile
+	        if [ ! -s ${bfile}.out ] ; then
+	            echo "No output file" >>$summaryfile
+	        else
+	            diff -b ${bfile}.tout $cmpfile | \
+		    sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g' >> $summaryfile
+	        fi
+	        echo "</TESTDIFF>" >> $summaryfile
 	    fi
-	    echo "</TESTDIFF>" >> $summaryfile
+	    if [ -s "$bfile.tbk" ] ; then
+	        echo "<TRACEBACK>" >> $summaryfile
+		echo "$bfile.tbk" >>$summaryfile
+		echo "</TRACEBACK>" >> $summaryfile
 	    fi
 	    echo "</MPITEST>" >> $summaryfile
 	fi
@@ -152,10 +161,12 @@ EOF
 }
 
 # Runtest pgm-name np marker-test args outfiles
+# filename.tbk is a traceback file.  Use a tool like pardump $1 > $1.tbk
+# to get such files
 RunTest() {
     OutTime
     testfiles="$testfiles $1.out"
-    /bin/rm -f $1.out
+    /bin/rm -f $1.out $1.tbk
     MakeExe $1
     mname=$3
     if [ -z "$mname" ] ; then mname="*** $1 ***" ; fi
@@ -189,6 +200,7 @@ EOF
         CheckOutput $1
     fi
     CleanExe $1
+    #ipcs
 }
 
 #
diff --git a/mpe/viewers/jumpshot-2/configure b/mpe/viewers/jumpshot-2/configure
--- a/mpe/viewers/jumpshot-2/configure
+++ b/mpe/viewers/jumpshot-2/configure
@@ -1213,8 +1213,8 @@ fi
     fi
 done
 
-echo $ac_n "checking if $JC compiles Swing code""... $ac_c" 1>&6
-echo "configure:1218: checking if $JC compiles Swing code" >&5
+echo $ac_n "checking if $JC compiles Swing-1.1.1 code""... $ac_c" 1>&6
+echo "configure:1218: checking if $JC compiles Swing-1.1.1 code" >&5
 
 pac_JC="$JC"
 pac_JFLAGS=""
@@ -1264,11 +1264,57 @@ fi
     fi
 fi
 
+if test "$enable_internalswing" = "yes" ; then
+    echo $ac_n "checking if $JC with swing.jar compiles Swing-1.0.3 code""... $ac_c" 1>&6
+echo "configure:1270: checking if $JC with swing.jar compiles Swing-1.0.3 code" >&5
+    
+pac_JC="$JC"
+pac_JFLAGS="-classpath $JAVA_LIBS:$srcdir/swing/swing.jar:. -d ."
+
+    rm -f conftest*
+    cat > conftest.java <<EOF
+
+import com.sun.java.swing.*;
+
+class conftest {
+
+public static void main( String args[] )
+{
+    JFrame frame = new JFrame();
+    System.out.println( "Checking Swing" );
+}
+                          
+}
+EOF
+
+    pac_jcompile='${pac_JC} ${pac_JFLAGS} conftest.java 1>&5'
+    if { (eval echo configure:1292: \"$pac_jcompile\") 1>&5; (eval $pac_jcompile) 2>&5; } && test -s conftest.class ; then
+        rm -rf conftest* ;  pac_java_working=yes 
+    else
+        rm -rf conftest* ;  pac_java_working=no  
+    fi
+
+    if test "$pac_java_working" = "yes" ; then
+        echo "$ac_t""yes" 1>&6
+    else
+        echo "$ac_t""no" 1>&6
+        echo "configure: warning: $JC cannot compile with Jumpshot-2 !" 1>&2
+        
+if test "$enable_softerror" = "yes" ; then
+    echo "configure: warning:  Jumpshot-2 can be compiled with Java 1.1.5 or better but not Java 2. " 1>&2
+    exit 0
+else
+    { echo "configure: error:  Jumpshot-2 can be compiled with Java 1.1.5 or better but not Java 2. " 1>&2; exit 1; }
+fi
+
+    fi
+fi
+
 # CHECK the version of Java used
 # Filter out the version of JDK that causes problem
 if test "$enable_checkversion" = "yes" ; then
     echo $ac_n "checking for Java version""... $ac_c" 1>&6
-echo "configure:1272: checking for Java version" >&5
+echo "configure:1318: checking for Java version" >&5
     VERSION=`$JAVA_HOME/bin/java -fullversion 2>&1`
     case "$VERSION" in
         *1.0*)
@@ -1295,7 +1341,7 @@ else
 fi
 
             ;;
-        *1.1*)
+        *1.1.5*|*1.1.6*|*1.1.7*|*1.1.8*)
             echo "$ac_t""$VERSION, i.e. newer than 1.1.5" 1>&6
             ;;
         *1.2*|*1.3*|*1.4*|*1.5*)
@@ -1350,7 +1396,7 @@ if test "$enable_internalswing" = "yes" ; then
     SWING_LIBRARIES=`echo $SWING_LIBS | sed 's/:/ /g'`
     for library in $SWING_LIBRARIES ; do
         echo $ac_n "checking for $library""... $ac_c" 1>&6
-echo "configure:1354: checking for $library" >&5
+echo "configure:1400: checking for $library" >&5
         if test -f "$library" ; then
             echo "$ac_t""yes" 1>&6
         else
diff --git a/mpe/viewers/jumpshot-3/configure b/mpe/viewers/jumpshot-3/configure
--- a/mpe/viewers/jumpshot-3/configure
+++ b/mpe/viewers/jumpshot-3/configure
@@ -1235,8 +1235,8 @@ fi
     fi
 done
 
-echo $ac_n "checking if $JC compiles Swing code""... $ac_c" 1>&6
-echo "configure:1240: checking if $JC compiles Swing code" >&5
+echo $ac_n "checking if $JC compiles Swing-1.1.1 code""... $ac_c" 1>&6
+echo "configure:1240: checking if $JC compiles Swing-1.1.1 code" >&5
 
 pac_JC="$JC"
 pac_JFLAGS=""
@@ -1286,9 +1286,56 @@ fi
     fi
 fi
 
+if test "$enable_internalswing" = "yes" ; then
+    echo $ac_n "checking if $JC with swing.jar compiles Swing-1.1.1 code""... $ac_c" 1>&6
+echo "configure:1292: checking if $JC with swing.jar compiles Swing-1.1.1 code" >&5
+    
+pac_JC="$JC"
+pac_JFLAGS="-classpath $JAVA_LIBS:$srcdir/swing/swing.jar:. -d ."
+
+    rm -f conftest*
+    cat > conftest.java <<EOF
+
+import javax.swing.*;
+
+class conftest {
+
+public static void main( String args[] )
+{
+    JFrame frame = new JFrame();
+    System.out.println( "Checking Swing" );
+}
+                          
+}
+EOF
+
+    pac_jcompile='${pac_JC} ${pac_JFLAGS} conftest.java 1>&5'
+    if { (eval echo configure:1314: \"$pac_jcompile\") 1>&5; (eval $pac_jcompile) 2>&5; } && test -s conftest.class ; then
+        rm -rf conftest* ;  pac_java_working=yes 
+    else
+        rm -rf conftest* ;  pac_java_working=no  
+    fi
+
+    if test "$pac_java_working" = "yes" ; then
+        echo "$ac_t""yes" 1>&6
+    else
+        echo "$ac_t""no" 1>&6
+        echo "configure: warning: $JC cannot compile with Jumpshot-3 !" 1>&2
+        
+if test "$enable_softerror" = "yes" ; then
+    echo "configure: warning:  Jumpshot-3 can be compiled with Java 1.1.5 or better including any Java 2 SDK. " 1>&2
+    exit 0
+else
+    { echo "configure: error:  Jumpshot-3 can be compiled with Java 1.1.5 or better including any Java 2 SDK. " 1>&2; exit 1; }
+fi
+
+    fi
+fi
+
+
 # Try to filter out the broken RMIC from JDK-1.2 pre-release
 echo $ac_n "checking if $RMIC generates stub""... $ac_c" 1>&6
-echo "configure:1292: checking if $RMIC generates stub" >&5
+echo "configure:1339: checking if $RMIC generates stub" >&5
 
 pac_RMIC="$RMIC"
 pac_JRFLAGS="-classpath $JAVA_LIBS:. -d . $JFLAGS"
@@ -1317,9 +1364,9 @@ public class conftest_rmic extends UnicastRemoteObject
 EOF
 
     pac_jcompile='${pac_JC} ${pac_JFLAGS} conftest_remote.java conftest_rmic.java 1>&5'
-    if { (eval echo configure:1321: \"$pac_jcompile\") 1>&5; (eval $pac_jcompile) 2>&5; } && test -s conftest_rmic.class ; then
+    if { (eval echo configure:1368: \"$pac_jcompile\") 1>&5; (eval $pac_jcompile) 2>&5; } && test -s conftest_rmic.class ; then
         pac_jrmic='${pac_RMIC} ${pac_JRFLAGS} conftest_rmic 1>&5'
-        if { (eval echo configure:1323: \"$pac_jrmic\") 1>&5; (eval $pac_jrmic) 2>&5; } && test -s conftest_rmic_Stub.class ; then
+        if { (eval echo configure:1370: \"$pac_jrmic\") 1>&5; (eval $pac_jrmic) 2>&5; } && test -s conftest_rmic_Stub.class ; then
             rm -rf conftest* ;  pac_java_working=yes 
         else
             rm -rf conftest* ;  pac_java_working=no  
@@ -1339,7 +1386,7 @@ fi
 # Filter out the version of JDK that causes problem
 if test "$enable_checkversion" = "yes" ; then
     echo $ac_n "checking for Java version""... $ac_c" 1>&6
-echo "configure:1343: checking for Java version" >&5
+echo "configure:1390: checking for Java version" >&5
     VERSION=`$JAVA_HOME/bin/java -fullversion 2>&1`
     case "$VERSION" in
 	*1.0*)
@@ -1366,7 +1413,7 @@ else
 fi
 
             ;;
-	*1.1*)
+	*1.1.5*|*1.1.6*|*1.1.7*|*1.1.8*)
             echo "$ac_t""$VERSION, i.e. newer than 1.1.5" 1>&6
             ;;
 	*1.2*|*1.3*|*1.4*|*1.5*)
@@ -1402,7 +1449,7 @@ if test "$enable_internalswing" = "yes" ; then
     SWING_LIBRARIES=`echo $SWING_LIBS | sed 's/:/ /g'`
     for library in $SWING_LIBRARIES ; do
         echo $ac_n "checking for $library""... $ac_c" 1>&6
-echo "configure:1406: checking for $library" >&5
+echo "configure:1453: checking for $library" >&5
         if test -f "$library" ; then
             echo "$ac_t""yes" 1>&6
         else
diff --git a/mpid/ch_p4/configure b/mpid/ch_p4/configure
--- a/mpid/ch_p4/configure
+++ b/mpid/ch_p4/configure
@@ -26,6 +26,10 @@
 ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
+ac_help="$ac_help
+--enable-processgroup - Use a separate process group for the MPICH processes"
+ac_help="$ac_help
+--with-comm=name - Specify the p4 comm type (typically empty or shared"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -534,6 +538,24 @@ print_error() {
     echo "*# $*" 2>&1 ;
     }
 
+# Check whether --enable-processgroup or --disable-processgroup was given.
+if test "${enable_processgroup+set}" = set; then
+  enableval="$enable_processgroup"
+  :
+else
+  enable_processgroup=default
+fi
+
+
+# Check whether --with-comm or --without-comm was given.
+if test "${with_comm+set}" = set; then
+  withval="$with_comm"
+  :
+else
+  with_comm=default
+fi
+
+
 
 
 # Get the compiler (should have been set with CC) and check for 
@@ -541,7 +563,7 @@ print_error() {
 # Extract the first word of "gcc", so it can be a program name with args.
 set dummy gcc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:545: checking for $ac_word" >&2
+echo "configure:567: checking for $ac_word" >&2
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -571,7 +593,7 @@ if test -z "$CC"; then
   # Extract the first word of "cc", so it can be a program name with args.
 set dummy cc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:575: checking for $ac_word" >&2
+echo "configure:597: checking for $ac_word" >&2
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -622,7 +644,7 @@ fi
       # Extract the first word of "cl", so it can be a program name with args.
 set dummy cl; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:626: checking for $ac_word" >&2
+echo "configure:648: checking for $ac_word" >&2
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -654,7 +676,7 @@ fi
 fi
 
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&1
-echo "configure:658: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&2
+echo "configure:680: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&2
 
 ac_ext=c
 # CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
@@ -665,12 +687,12 @@ cross_compiling=$ac_cv_prog_cc_cross
 
 cat > conftest.$ac_ext << EOF
 
-#line 669 "configure"
+#line 691 "configure"
 #include "confdefs.h"
 
 main(){return(0);}
 EOF
-if { (eval echo configure:674: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:696: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   ac_cv_prog_cc_works=yes
   # If we can't run a trivial program, we are probably using a cross compiler.
   if (./conftest; exit) 2>/dev/null; then
@@ -696,12 +718,12 @@ if test $ac_cv_prog_cc_works = no; then
   { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
 fi
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&1
-echo "configure:700: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&2
+echo "configure:722: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&2
 echo "$ac_t""$ac_cv_prog_cc_cross" 1>&1
 cross_compiling=$ac_cv_prog_cc_cross
 
 echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&1
-echo "configure:705: checking whether we are using GNU C" >&2
+echo "configure:727: checking whether we are using GNU C" >&2
 if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -710,7 +732,7 @@ else
   yes;
 #endif
 EOF
-if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:714: \"$ac_try\") 1>&2; (eval $ac_try) 2>&2; }; } | egrep yes >/dev/null 2>&1; then
+if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:736: \"$ac_try\") 1>&2; (eval $ac_try) 2>&2; }; } | egrep yes >/dev/null 2>&1; then
   ac_cv_prog_gcc=yes
 else
   ac_cv_prog_gcc=no
@@ -729,7 +751,7 @@ ac_test_CFLAGS="${CFLAGS+set}"
 ac_save_CFLAGS="$CFLAGS"
 CFLAGS=
 echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&1
-echo "configure:733: checking whether ${CC-cc} accepts -g" >&2
+echo "configure:755: checking whether ${CC-cc} accepts -g" >&2
 if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -761,15 +783,16 @@ else
 fi
 
 
-# Check for a working mmap.
-MMAP=0
-
+# Check for a working mmap or semget when configuring for comm=shared
+if test "$with_comm" = "shared" ; then
+    MMAP=0
+    
 for ac_func in mmap
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:771: checking for $ac_func" >&2
+echo "configure:794: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 773 "configure"
+#line 796 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -790,7 +813,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:794: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:817: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -814,7 +837,7 @@ done
 
 # Check that MMAP works!
 echo $ac_n "checking that shared, anonymous mmap works with -1 filedes""... $ac_c" 1>&1
-echo "configure:818: checking that shared, anonymous mmap works with -1 filedes" >&2
+echo "configure:841: checking that shared, anonymous mmap works with -1 filedes" >&2
 
 
 if test "$cross_compiling" = 1 -a -z "$TESTCC" ; then
@@ -891,12 +914,12 @@ EOF
 
 fi
 
-# We need to check that semctl is ok.
-
+    # We need to check that semctl is ok.
+    
 # We need to check that semctl is ok.
 # Both of these need to go into aclocal.m4
 echo $ac_n "checking that semget works""... $ac_c" 1>&1
-echo "configure:900: checking that semget works" >&2
+echo "configure:923: checking that semget works" >&2
 ###
 ### Still need to check for SEMUN_UNDEFINED - see mpid/ch_p4/p4/configure.in
 ### 
@@ -995,15 +1018,16 @@ fi
 /bin/rm -f conftest*
 
 
-if test $MMAP = 0 -a "$SEMGET" = 0; then
-    print_error "Configure detected that both anonymous mmap and semget fail."
-    print_error "Configuring MPICH for shared memory may cause problems!"
+    if test $MMAP = 0 -a "$SEMGET" = 0; then
+        { echo "configure: error: Configure detected that both anonymous mmap and semget fail.
+Configuring MPICH for shared memory may cause problems! " 1>&2; exit 1; }
+    fi
 fi
 
 
 
 echo $ac_n "checking that signals work correctly""... $ac_c" 1>&1
-echo "configure:1007: checking that signals work correctly" >&2
+echo "configure:1031: checking that signals work correctly" >&2
 cat >conftest.c <<EOF
 #include <signal.h>
 static int rc = 0, irc = 1, maxcnt=5;
@@ -1057,17 +1081,17 @@ if test -n "$pac_cv_cross_compiling" ; then
     fi
 else
     echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
-echo "configure:1061: checking whether cross-compiling" >&2
+echo "configure:1085: checking whether cross-compiling" >&2
     # If we cannot run a trivial program, we must be cross compiling.
             if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1067 "configure"
+#line 1091 "configure"
 #include "confdefs.h"
 main(){exit(0);}
 EOF
-if { (eval echo configure:1071: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1095: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   pac_ok=1
 else
@@ -1084,11 +1108,11 @@ fi
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1088 "configure"
+#line 1112 "configure"
 #include "confdefs.h"
 main(){exit(1);}
 EOF
-if { (eval echo configure:1092: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1116: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   pac_ok=0 
 else
@@ -1116,7 +1140,7 @@ fi
 # Extract the first word of "$program", so it can be a program name with args.
 set dummy $program; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:1120: checking for $ac_word" >&2
+echo "configure:1144: checking for $ac_word" >&2
 if eval "test \"`echo '$''{'ac_cv_path_RSHCOMMAND'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1150,7 +1174,7 @@ fi
 
         if test -n "$RSHCOMMAND" ; then
 	    echo $ac_n "checking whether $RSHCOMMAND works""... $ac_c" 1>&1
-echo "configure:1154: checking whether $RSHCOMMAND works" >&2
+echo "configure:1178: checking whether $RSHCOMMAND works" >&2
             output=`$RSHCOMMAND $machine -n true 2>&1 </dev/null`
             if test -n "$output" ; then
 		echo "$ac_t""no" 1>&1
@@ -1173,7 +1197,7 @@ echo "configure:1154: checking whether $RSHCOMMAND works" >&2
     	# Extract the first word of "ssh", so it can be a program name with args.
 set dummy ssh; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:1177: checking for $ac_word" >&2
+echo "configure:1201: checking for $ac_word" >&2
 if eval "test \"`echo '$''{'ac_cv_path_RSHCOMMAND'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1207,7 +1231,7 @@ fi
 
     	if test -n "$RSHCOMMAND" ; then
     	    echo $ac_n "checking whether $RSHCOMMAND works""... $ac_c" 1>&1
-echo "configure:1211: checking whether $RSHCOMMAND works" >&2
+echo "configure:1235: checking whether $RSHCOMMAND works" >&2
     	    output=`$RSHCOMMAND -o "StrictHostKeyChecking no" \
     	      -o "BatchMode yes" $machine -n true 2>&1 </dev/null`
     	    if test $? -ne 0 ; then
@@ -1229,16 +1253,19 @@ if test -z "$RSHCOMMAND" ; then
     echo "configure: warning: You must use the secure server to start programs" 1>&2
 fi
 # Sizes of int and long (for sendid type)
+
+CROSS_SIZEOF_INT=${CROSS_SIZEOF_INT:-4}
+CROSS_SIZEOF_LONG=${CROSS_SIZEOF_LONG:-4}
 echo $ac_n "checking size of int""... $ac_c" 1>&1
-echo "configure:1234: checking size of int" >&2
+echo "configure:1261: checking size of int" >&2
 if eval "test \"`echo '$''{'ac_cv_sizeof_int'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
   if test "$cross_compiling" = yes; then
-  ac_cv_sizeof_int=0
+  ac_cv_sizeof_int=$CROSS_SIZEOF_INT
 else
   cat > conftest.$ac_ext <<EOF
-#line 1242 "configure"
+#line 1269 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1249,7 +1276,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1253: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1280: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_int=`cat conftestval`
 else
@@ -1269,15 +1296,15 @@ EOF
 
 
 echo $ac_n "checking size of long""... $ac_c" 1>&1
-echo "configure:1273: checking size of long" >&2
+echo "configure:1300: checking size of long" >&2
 if eval "test \"`echo '$''{'ac_cv_sizeof_long'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
   if test "$cross_compiling" = yes; then
-  ac_cv_sizeof_long=0
+  ac_cv_sizeof_long=$CROSS_SIZEOF_LONG
 else
   cat > conftest.$ac_ext <<EOF
-#line 1281 "configure"
+#line 1308 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1288,7 +1315,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1292: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1319: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_long=`cat conftestval`
 else
@@ -1311,9 +1338,9 @@ EOF
 for ac_func in gettimeofday BSDgettimeofday
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:1315: checking for $ac_func" >&2
+echo "configure:1342: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 1317 "configure"
+#line 1344 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -1334,7 +1361,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1338: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1365: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1356,6 +1383,62 @@ else
 fi
 done
 
+# These are needed for the process group
+for ac_func in setsid isatty
+do
+echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
+echo "configure:1391: checking for $ac_func" >&2
+cat > conftest.$ac_ext <<EOF
+#line 1393 "configure"
+#include "confdefs.h"
+#include <ctype.h> /* Arbitrary system header to define __stub macros. */
+#ifdef __cplusplus
+extern "C" { char $ac_func(); };
+#else
+char $ac_func();
+#endif
+int main() {
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+/* Override any gcc2 internal prototype to avoid an error.  */
+$ac_func();
+#endif
+
+; return 0; }
+EOF
+if { (eval echo configure:1414: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_func_$ac_func=yes"
+else
+  echo "configure: failed program was:" >&2
+  cat conftest.$ac_ext >&2
+  rm -rf conftest*
+  eval "ac_cv_func_$ac_func=no"
+fi
+rm -f conftest*
+if eval "test \"`echo '$ac_cv_func_'$ac_func`\" = yes"; then
+  echo "$ac_t""yes" 1>&1
+    ac_tr_func=HAVE_`echo $ac_func | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_func 1
+EOF
+ 
+else
+  echo "$ac_t""no" 1>&1
+fi
+done
+
+if test "$enable_processgroup" = "default" -o \
+        "$enable_processgroup" = "yes" ; then
+    cat >> confdefs.h <<\EOF
+#define SET_NEW_PGRP 
+EOF
+
+fi
 #
 # Generate a default machines file
 rootdir="../.."
@@ -1369,7 +1452,7 @@ if test ! -s ${rootdir}/util/machines/machines.$ARCH ; then
         # Extract the first word of "hostname", so it can be a program name with args.
 set dummy hostname; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
-echo "configure:1373: checking for $ac_word" >&2
+echo "configure:1456: checking for $ac_word" >&2
 ac_prog_where=""
 if test -n "$HOSTNAME_PGM"; then
   ac_pg_HOSTNAME_PGM="$HOSTNAME_PGM" # Let the user override the test.
diff --git a/mpid/ch_p4/p4/configure b/mpid/ch_p4/p4/configure
--- a/mpid/ch_p4/p4/configure
+++ b/mpid/ch_p4/p4/configure
@@ -9209,6 +9209,98 @@ fi
 rm -f conftest*
 done
 
+#
+# Check to see if we need to define sys_errlist.  We do this by defining it
+# badly, and then checking for an error.
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for whether sys_errlist needs do be defined""... $ac_c"
+else
+echo $ac_n "checking for whether sys_errlist needs do be defined""... $ac_c" 1>&1
+fi
+if test ! -f confdefs.h ; then
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"""!! SHELL ERROR !!""
+else
+echo "$ac_t"""!! SHELL ERROR !!"" 1>&1
+fi
+    echo "The file confdefs.h created by configure has been removed"
+    echo "This may be a problem with your shell; some versions of LINUX"
+    echo "have this problem.  See the Installation guide for more"
+    echo "information."
+    exit 1
+fi
+cat > conftest.c <<EOF
+#include "confdefs.h"
+#include <string.h>
+
+int main() { exit(0); }
+int t() { extern short sys_errlist; }
+EOF
+if eval $compile; then
+  if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""yes"
+else
+echo "$ac_t""yes" 1>&1
+fi
+  :
+else
+  expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+  eval echo "configure:$expandcompile" >> config.log
+  echo "configure: failed program was:" >>config.log
+  cat confdefs.h >> config.log
+  cat conftest.c >> config.log
+  if test -s conftest.out ; then cat conftest.out >> config.log 
+  else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+  fi
+  
+{
+test -n "$verbose" && \
+echo "	defining NEEDS_SYS_ERRLIST"
+echo "#define" NEEDS_SYS_ERRLIST 1 >> confdefs.h
+DEFS="$DEFS -DNEEDS_SYS_ERRLIST=1"
+}
+
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""no"
+else
+echo "$ac_t""no" 1>&1
+fi
+    expandcompile=`echo "$compile" | sed -e 's/>.*//'`
+    eval echo "configure:$expandcompile" >> config.log
+    echo "configure: failed program was:" >>config.log
+    cat confdefs.h >> config.log
+    cat conftest.c >> config.log
+    if test -s conftest.out ; then cat conftest.out >> config.log 
+    else
+      ${CC-cc} $CFLAGS conftest.c -o conftest $LDFLAGS $LIBS >> config.log 2>&1
+    fi
+
+fi
+rm -f conftest*
+
+#
 LIBS_save="${LIBS}"
 LIBS="${LIBS} -lcrypt"
 have_lib=""
diff --git a/util/mpiinstall.in b/util/mpiinstall.in
--- a/util/mpiinstall.in
+++ b/util/mpiinstall.in
@@ -612,7 +612,7 @@ else
     fi
     if [ -x src/fortran/src/mpif90 -a "@NO_F90@" = "0" ] ; then
         CopyFile src/fortran/src/mpif90 $bindir/mpif90 $XMODE
-	CopyFile src/fortran/src/mpif90.conf $sysconfdif
+	CopyFile src/fortran/src/mpif90.conf $sysconfdir
     fi
     if [ -s romio/include/mpio.h ] ; then
         CopyFile romio/include/mpio.h $includedir
@@ -748,6 +748,9 @@ done
 # shared library versioning.  This is the same as the step that installs 
 # the shared libraries
 # 
+# Problem: Installation sometimes builds libtvmpich.so and libtvmpich.so.1.0
+# as files, causing problems when installing.  
+# 
 for file in $libbuild_dir/libtvmpich.so* ; do
     # Also need to handle any links!
     if [ ! -h $file -a -f $file ] ; then 
@@ -766,6 +769,14 @@ for file in $libdir/libtvmpich.so* ; do
     while [ $filebase != $file ]; do
 	 if [ ! -h $filebase -a -s $file ] ; then 
 	     $Show ln -s $file $filebase
+	     # We need to debug this.  If there is an error, generate
+	     # some information on the failure
+             if [ $? != 0 ] ; then
+                  echo "Error in setting link.  Files in libdir are:"
+	          ls -l $libdir/libtvmpich.*
+		  echo "Files in source dir are"
+		  ls -l $libbuild_dir/libtvmpich.so*
+             fi
 	     echo "/bin/rm -f $libdir/$filebase" >>$UNINSTALLFILE
 	 fi
 	 file=$filebase
