1.1.2

diff --git a/util/makesharedlib b/util/makesharedlib
--- a/util/makesharedlib
+++ b/util/makesharedlib
@@ -3,66 +3,162 @@
 # Simple script to build shared libraries
 #
 kind=""
+nolink=0
+islocal=0
+created_shared=0
+Verbose=echo
+setecho=0
 for arg in "$@" ; do
     case $arg in
 	-lib=*) lib=`echo A$arg | sed -e 's/A-lib=//g'`
 	SHLIBS="$SHLIBS $lib"
 	;;
+	-obj=*) objs=`echo A$arg | sed -e 's/A-obj=//g'`
+	;;
 	-kind=*) kind=`echo A$arg | sed -e 's/A-kind=//g'`
 	;;
+	-suffix=*) slsuffix=`echo A$arg | sed -e 's/A-suffix=//g'`
+	;;
+	-echo) set -x ;;
+	-noecho) set +x ; setecho=0 ;;
+	-local) nolink=1 ; islocal=1 ;;
+	-link) nolink=0 ;;
+	-verbose) Verbose=echo ;;
+	-noverbose) Verbose=true ;;
 	*)
 	echo "Unrecognized option $arg"
 	exit 1
 	;;	
     esac
 done
-
+#
+# This allows us to turn echo on by default, but suppress EVERYTHING
+# with -noecho
+if [ "$SHELL_ECHO" = "on" -o $setecho = 1 ] ; then 
+    set -x 
+fi
 #
 # This is the default
-if test "$kind" = "ignore" ; then
+if [ "$kind" = "ignore" ] ; then
     exit 0
 fi
 
-if test -z "$slsuffix" ; then
+if [ -z "$slsuffix" ] ; then
     slsuffix=so.1.0
+    req_slsuffix=so
 fi
-if test -z "$AR" ; then
+if [ -z "$req_slsuffix" ] ; then
+    req_slsuffix=$slsuffix
+fi
+if [ -z "$AR" ] ; then
     AR=ar
 fi
-if test -z "$LD" ; then
+if [ -z "$LD" ] ; then
     LD=ld
 fi
-if test -z "$CLINKER" ; then
-    if test -n "$CC" ; then
+if [ -z "$CLINKER" ] ; then
+    if [ -n "$CC" ] ; then
         CLINKER=$CC
     else
 	echo "No C linker or C compiler specified!"
 	exit 1
     fi
 fi
-if test -z "$SHLIBS" ; then
+if [ -z "$SHLIBS" ] ; then
     echo "No libraries specified!"
     exit 1
+fi
+#
+# Check that there are libraries 
+foundlib=0
+for libname in $SHLIBS ; do
+   libnamelocal=`basename $libname`
+   if [ -s $libnamelocal ] ; then 
+       foundlib=1
+       break
+   fi
+done
+if [ -n "$objs" ] ; then
+    foundlib=1
+    for file in $objs ; do
+        if [ ! -s $file ] ; then
+	    foundlib=0
+	    break
+	fi
+    done
+fi
+if [ $foundlib = 0 ] ; then
+    if [ -n "$objs" ] ; then
+        echo "Could not find $objs"
+    else
+        echo "Could not find $SHLIBS"
+    fi
+    exit 1
+fi
+if [ ! -d shared ] ; then 
+    mkdir shared
+    created_shared=1
 fi
 case $kind in
     gcc)
     for libname in $SHLIBS ; do
+        $Verbose "Making a shared library of $libname"
+        rm -rf .tmp
         mkdir .tmp
-        cd .tmp
-        $AR x ../$libname
-        $CLINKER -shared -Wl,-soname,$libname.$slsuffix \
-		-o ../$libname.$slsuffix *.o
+
+	if [ -z "$objs" ] ; then
+            cd .tmp
+            $AR x ../$libname
+            #$CLINKER -shared -Wl,-soname,$libbase.$slsuffix \
+	    #	-o ../shared/$libbase.$slsuffix *.o
+	else
+	    cp $objs .tmp
+	    cd .tmp
+	fi
+        libbase=`basename $libname .a`
+        $CLINKER -shared -o ../shared/$libbase.$slsuffix *.o
         cd ..
+        # Make a link in the library directory to the shared library in the
+        # shared directory.
+	if [ $islocal = 1 ] ; then
+	    mv shared/$libbase.$slsuffix .
+  	    if [ $slsuffix != $req_slsuffix -a $nolink = 0 ] ; then
+	        ln -s $libbase.$slsuffix $libbase.$req_slsuffix
+	    fi
+	else
+  	    if [ $slsuffix != $req_slsuffix -a $nolink = 0 ] ; then
+	        (cd shared ; \
+                 ln -s ../$libbase.$slsuffix $libbase.$req_slsuffix )
+            fi
+	fi
         rm -rf .tmp
     done
     ;;
     solaris)
     for libname in $SHLIBS ; do
+        $Verbose "Making a shared library of $libname"
+        rm -rf .tmp
         mkdir .tmp
-        cd .tmp
-        $AR x ../$libname
-        $LD -G -h $libname.$slsuffix -o ../$libname.$slsuffix *.o
+	if [ -z "$objs" ] ; then
+            cd .tmp
+            $AR x ../$libname
+        else
+	    cp $objs .tmp
+	    cd .tmp
+	fi
+	libbase=`basename $libname .a`
+        $LD -G -h $libbase.$slsuffix -o ../shared/$libbase.$slsuffix *.o
         cd ..
+	if [ $islocal = 1 ] ; then
+	    mv shared/$libbase.$slsuffix .
+  	    if [ $slsuffix != $req_slsuffix  -a $nolink = 0 ] ; then
+	        ln -s $libbase.$slsuffix $libbase.$req_slsuffix
+            fi
+	else
+  	    if [ $slsuffix != $req_slsuffix  -a $nolink = 0 ] ; then
+	        ( cd shared ; ln -s $libbase.$slsuffix $libbase.$req_slsuffix )
+            fi
+        fi
         rm -rf .tmp
     done
     ;;
@@ -70,25 +166,43 @@ case $kind in
     rs6000|aix|aix-4)
     # Untested
     for libname in $SHLIBS ; do
+        $Verbose "Making a shared library of $libname"
+        rm -rf .tmp
         mkdir .tmp
-        cd .tmp
-        ar x ../$libname
+	if [ -z "$objs" ] ; then
+            cd .tmp
+            ar x ../$libname
+	else
+	    cp $objs .tmp
+	    cd .tmp
+	fi
+	libbase=`basename $libname .a`
         nm -g -p *.o | awk '{ if ($2 == "T") { print $1 ; }}' | \
-	    sed -e 's/^\.//g' >  $libname.exp
+	    sed -e 's/^\.//g' >  $libbase.exp
         # xlC doesn't work with this!
         # cc misses the iargc/getarg libraries
-        xlf -o ../$libname.so *.o -bE:$libname.exp -bM:SRE -bnoentry
+        xlf -o ../shared/$libbase.so *.o -bE:$libbase.exp -bM:SRE -bnoentry
         # create new shared file name
-        newfile=`basename $libname`
-        newfile="${newfile}shared.a"
+        newfile="${libbase}shared.a"
         /bin/rm -f $newfile
-        ar qv $newfile ../$libname.so
+        ar qv $newfile ../shared/$libbase.so
         /bin/rm -f *.o
         cd ..
         /bin/rm -rf .tmp
     done
-    *)
-    echo "Unknown shared library type $kind"
+    ;;
+    *)	
+    if [ -z "$kind" ] ; then
+        echo "Shared library type not specified"
+    else
+        echo "Unknown shared library type $kind"
+    fi 
     exit 1
     ;;
 esac
+# Remove the shared directory if local and we created it
+if [ $islocal = 1 -a $created_shared = 1 ] ; then
+   rm -rf shared
+fi
+
+
