1.2.2

diff --git a/mpe/contrib/test/Makefile.in b/mpe/contrib/test/Makefile.in
--- a/mpe/contrib/test/Makefile.in
+++ b/mpe/contrib/test/Makefile.in
@@ -19,6 +19,7 @@ PROF_LIBS     = -L$(MPE_LIBDIR) @PROF_LIBS@ $(MPI_LIBS)
 LOG_LIBS      = -L$(MPE_LIBDIR) @LOG_LIBS@ $(MPI_LIBS)
 TRACE_LIBS    = -L$(MPE_LIBDIR) @TRACE_LIBS@ $(MPI_LIBS)
 ANIM_LIBS     = -L$(MPE_LIBDIR) @ANIM_LIBS@ $(MPI_LIBS)
+XGRAPH_LIBS   = -L$(MPE_LIBDIR) @XGRAPH_LIBS@ $(MPI_LIBS)
 F2CMPI_LIBS   = @F2CMPI_LIBS@
 FLIB_PATH     = @FLIB_PATH_LEADER@$(MPE_LIBDIR) $(F2CMPI_LIBS) @LOG_LIBS@ \
                 $(MPI_LIBS)
@@ -70,6 +71,12 @@ fpilog: fpi.o
 srtest: srtest.o
 	$(MPI_CLINKER) $(CC_LDFLAGS)  -o $@ $? $(LOG_LIBS) $(DEBUG_LIBS) -lm 
 	
+cxgraphics: cxgraphics.o
+	$(MPI_CLINKER) $(CC_LDFLAGS)  -o $@ $? $(XGRAPH_LIBS) $(DEBUG_LIBS) -lm 
+
+fxgraphics: fxgraphics.o
+	$(MPI_FLINKER) $(FC_LDFLAGS) -o $@ $? $(XGRAPH_LIBS) $(DEBUG_LIBS) -lm
+
 linktest: linktest_C
 
 linktest_C: 
@@ -103,7 +110,17 @@ linktest_C:
 	        $(RM) -f cpi_anim ; \
 	    else \
 	        echo "** C application CANNOT be linked with animation library" ; \
-	    fi \
+	    fi ; \
+	    echo ; \
+	    echo "** Testing if C application can be linked with graphics library" ; \
+	    $(RM) -f cxgraphics ; \
+	    $(MAKE) cxgraphics ; \
+	    if test -x cxgraphics ; then \
+	        echo "** C application can be linked with graphics library" ; \
+	        $(RM) -f cxgraphics ; \
+	    else \
+	        echo "** C application CANNOT be linked with graphics library" ; \
+	    fi ; \
 	fi  
 	@-echo ; \
 	echo "** Testing if C application can use both automatic and manual logging together" ; \
@@ -114,26 +131,41 @@ linktest_C:
 	    $(RM) -f cpilog ; \
 	else \
 	    echo "** C application CANNOT use both automatic and manual logging together" ; \
-	fi 
+	fi ; \
+	echo
 	@-$(MAKE) clean
 
 linktest_f77: 
 	@-if [ $(NOF77) = 0 ] ; then \
-	      echo ; \
-	      echo "** Testing if Fortran77 application can be linked with logging library" ; \
-	      $(RM) -f fpilog ; \
-	      $(MAKE) fpilog ; \
-	      if test -x fpilog ; then \
-	          echo "** Fortran77 application can be linked with logging library" ; \
-	          $(RM) -f fpilog ; \
-	      else \
-	          echo "** Fortran77 application CANNOT be linked with logging library" ; \
-	      fi ; \
-	      $(MAKE) clean ; \
+	    echo ; \
+	    echo "** Testing if Fortran77 application can be linked with logging library" ; \
+	    $(RM) -f fpilog ; \
+	    $(MAKE) fpilog ; \
+	    if test -x fpilog ; then \
+	        echo "** Fortran77 application can be linked with logging library" ; \
+	        $(RM) -f fpilog ; \
+	    else \
+	        echo "** Fortran77 application CANNOT be linked with logging library" ; \
+	    fi ; \
+	    if [ $(NO_X) = 0 ] ; then \
+	        echo ; \
+	        echo "** Testing if Fortran77 application can be linked with graphics library" ; \
+	        $(RM) -f fxgraphics ; \
+	        $(MAKE) fxgraphics ; \
+	        if test -x fxgraphics ; then \
+	            echo "** Fortran77 application can be linked with graphics library" ; \
+	            $(RM) -f fxgraphics ; \
+	        else \
+	            echo "** Fortran77 application CANNOT be linked with graphics library" ; \
+	        fi ; \
+	    fi ; \
+	    echo ; \
+	    $(MAKE) clean ; \
 	  fi
 
 clean:
-	@-$(RM) -f *.o *~ PI* $(EXECS) cpilog cpi_anim cpi_trace cpi_log fpilog
+	@-$(RM) -f *.o *~ PI* $(EXECS) \
+	           cpilog cpi_anim cpi_trace cpi_log fpilog cxgraphics fxgraphics
 
 distclean: clean
 	@-$(RM) -f Makefile
diff --git a/mpe/viewers/configure b/mpe/viewers/configure
--- a/mpe/viewers/configure
+++ b/mpe/viewers/configure
@@ -12,13 +12,25 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
---enable-upshot                    - Build upshot which is the ALOG viewer if it exists.  The default is enable=yes."
+--enable-upshot                    - Build Upshot which is the ALOG viewer 
+                                     if it exists.  The default is enable=yes."
 ac_help="$ac_help
---enable-nupshot                   - Build nupshot which is the ALOG viewer if it exists.  The default is enable=yes."
+--enable-nupshot                   - Build Nupshot which is the ALOG viewer 
+                                     if it exists.  The default is enable=yes."
 ac_help="$ac_help
---enable-jumpshot2                 - Build jumpshot-2 which is the CLOG viewer if it exists.  The default is enable=yes."
+--enable-jumpshot2                 - Build Jumpshot-2 which is the CLOG 
+                                     viewer if it exists.  The default 
+                                     is enable=yes."
 ac_help="$ac_help
---enable-jumpshot3                 - Build jumpshot-3 which is the SLOG viewer if it exists.  The default is enable=yes."
+--enable-jumpshot3                 - Build Jumpshot-3 which is the SLOG 
+                                     viewer if it exists.  The default 
+                                     is enable=yes."
+ac_help="$ac_help
+--enable-jumpshots                 - Do not build Jumpshot-2 and Jumpshot-3.
+                                     The default is enable=yes."
+ac_help="$ac_help
+--without-java                     - Do not build any viewers that 
+                                     requires Java"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -531,7 +543,7 @@ if test "X$srcdir" != "X." -a -s $srcdir/bin/logviewer.in ; then
 else
     
 echo $ac_n "checking for current directory name""... $ac_c" 1>&6
-echo "configure:535: checking for current directory name" >&5
+echo "configure:547: checking for current directory name" >&5
 top_srcdir_abs=$PWD
 if test "${top_srcdir_abs}" != "" -a -d "${top_srcdir_abs}" ; then 
     if test -r ${top_srcdir_abs}/.foo$$ ; then
@@ -592,7 +604,7 @@ fi
 MAKE=${MAKE:-make}
 
 echo $ac_n "checking gnumake""... $ac_c" 1>&6
-echo "configure:596: checking gnumake" >&5
+echo "configure:608: checking gnumake" >&5
 /bin/rm -f conftest
 cat > conftest <<.
 SHELL=/bin/sh
@@ -618,7 +630,7 @@ str=""
 
 
 echo $ac_n "checking BSD 4.4 make""... $ac_c" 1>&6
-echo "configure:622: checking BSD 4.4 make" >&5
+echo "configure:634: checking BSD 4.4 make" >&5
 /bin/rm -f conftest
 cat > conftest <<.
 ALL:
@@ -642,7 +654,7 @@ str=""
 
 
 echo $ac_n "checking OSF V3 make""... $ac_c" 1>&6
-echo "configure:646: checking OSF V3 make" >&5
+echo "configure:658: checking OSF V3 make" >&5
 /bin/rm -f conftest
 cat > conftest <<.
 SHELL=/bin/sh
@@ -666,7 +678,7 @@ str=""
 
 
 echo $ac_n "checking for virtual path format""... $ac_c" 1>&6
-echo "configure:670: checking for virtual path format" >&5
+echo "configure:682: checking for virtual path format" >&5
 rm -rf conftest*
 mkdir conftestdir
 cat >conftestdir/a.c <<EOF
@@ -703,10 +715,9 @@ rm -rf conftest*
 
 # If we are relying on VPATH and no VPATH is set, then we must exit
 if test ! -s bin/logviewer.in -a -z "$VPATH" ; then
-    echo "No virtual MAKE path command found."
-    echo "You may need to set your make command"
-    echo "The GNU make (sometimes available as gnumake) can be used."
-    exit 1
+    { echo "configure: error: No virtual MAKE path command found.
+	You may need to set your make command
+	The GNU make (sometimes available as gnumake) can be used." 1>&2; exit 1; }
 fi
 
 CPRP=cp
@@ -758,6 +769,22 @@ else
 fi
 
 
+# Options to disselect more than 1 viewers
+# Check whether --enable-jumpshots or --disable-jumpshots was given.
+if test "${enable_jumpshots+set}" = set; then
+  enableval="$enable_jumpshots"
+  :
+else
+  enable_jumpshots=yes 
+fi
+
+# Check whether --with-java or --without-java was given.
+if test "${with_java+set}" = set; then
+  withval="$with_java"
+  :
+fi
+
+
 # The XXX in XXX_dirname below must match with AC_ARG_ENABLE( XXX, .. ) above
 upshot_dirname="upshot"
 nupshot_dirname="nupshot"
@@ -770,7 +797,11 @@ jumpshot3_dirname="jumpshot-3"
 
 
 
-trial_pkgs="upshot nupshot jumpshot2 jumpshot3"
+if test "$with_java" = "no" -o "$enable_jumpshots" = "no" ; then
+    trial_pkgs="upshot nupshot"
+else
+    trial_pkgs="upshot nupshot jumpshot2 jumpshot3"
+fi
 
 ac_configure_args="$ac_configure_args --enable-softerror"
 PKGS=""
diff --git a/mpe/viewers/upshot/configure b/mpe/viewers/upshot/configure
--- a/mpe/viewers/upshot/configure
+++ b/mpe/viewers/upshot/configure
@@ -599,10 +599,10 @@ fi
 if test ! -d "$top_srcdir_abs" ; then
     
 if test "$enable_softerror" = "yes" ; then
-    echo "configure: warning: *** $top_srcdir_abs is not a valid directory - cannot continue " 1>&2
+    echo "configure: warning:  *** $top_srcdir_abs is not a valid directory - cannot continue " 1>&2
     exit 0
 else
-    { echo "configure: error: *** $top_srcdir_abs is not a valid directory - cannot continue " 1>&2; exit 1; }
+    { echo "configure: error:  *** $top_srcdir_abs is not a valid directory - cannot continue " 1>&2; exit 1; }
 fi
 
 fi
@@ -793,10 +793,10 @@ fi
 if test -z "$wishloc" ; then
     
 if test "$enable_softerror" = "yes" ; then
-    echo "configure: warning: Could not find executable wish (needed for Upshot) " 1>&2
+    echo "configure: warning:  Could not find executable wish (needed for Upshot) " 1>&2
     exit 0
 else
-    { echo "configure: error: Could not find executable wish (needed for Upshot) " 1>&2; exit 1; }
+    { echo "configure: error:  Could not find executable wish (needed for Upshot) " 1>&2; exit 1; }
 fi
 
 fi
@@ -1018,10 +1018,10 @@ for script in "sbin/install-viewer"; do
     else
         
 if test "$enable_softerror" = "yes" ; then
-    echo "configure: warning: *** $script is not a valid file - Make sure you have configured with a valid Upshot source directory " 1>&2
+    echo "configure: warning:  *** $script is not a valid file - Make sure you have configured with a valid Upshot source directory " 1>&2
     exit 0
 else
-    { echo "configure: error: *** $script is not a valid file - Make sure you have configured with a valid Upshot source directory " 1>&2; exit 1; }
+    { echo "configure: error:  *** $script is not a valid file - Make sure you have configured with a valid Upshot source directory " 1>&2; exit 1; }
 fi
 
     fi
diff --git a/mpid/ch_p4/configure b/mpid/ch_p4/configure
--- a/mpid/ch_p4/configure
+++ b/mpid/ch_p4/configure
@@ -1047,7 +1047,7 @@ fi
 #
 if test -z "$RSHCOMMAND" ; then
     machine=`hostname`
-    for program in remsh rsh ssh ; do
+    for program in remsh rsh ; do
         # First, check to see if the program exists
         
 if test -n "$pac_cv_cross_compiling" ; then
@@ -1058,7 +1058,7 @@ else
     echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
 echo "configure:1060: checking whether cross-compiling" >&2
     # If we cannot run a trivial program, we must be cross compiling.
-    if test "$cross_compiling" = yes; then
+            if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
@@ -1079,7 +1079,7 @@ rm -fr conftest*
 fi
 
     if test $pac_ok = 1 ; then
-         if test "$cross_compiling" = yes; then
+        if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
@@ -1150,7 +1150,7 @@ fi
         if test -n "$RSHCOMMAND" ; then
 	    echo $ac_n "checking whether $RSHCOMMAND works""... $ac_c" 1>&1
 echo "configure:1153: checking whether $RSHCOMMAND works" >&2
-            output=`$RSHCOMMAND $machine -n true 2>&1`
+            output=`$RSHCOMMAND $machine -n true 2>&1 </dev/null`
             if test -n "$output" ; then
 		echo "$ac_t""no" 1>&1
 		echo "Errors while trying to run true on $machine with $program"
@@ -1166,13 +1166,70 @@ echo "configure:1153: checking whether $RSHCOMMAND works" >&2
 	    fi
         fi
     done
+    # Check ssh with special options to avoid user prompting which causes the
+    # configure script to "hang"
+    if test -z "$RSHCOMMAND" ; then
+    	# Extract the first word of "ssh", so it can be a program name with args.
+set dummy ssh; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
+echo "configure:1176: checking for $ac_word" >&2
+if eval "test \"`echo '$''{'ac_cv_path_RSHCOMMAND'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&1
+else
+  case "$RSHCOMMAND" in
+  /*)
+  ac_cv_path_RSHCOMMAND="$RSHCOMMAND" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_RSHCOMMAND="$RSHCOMMAND" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_RSHCOMMAND="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  ;;
+esac
+fi
+RSHCOMMAND="$ac_cv_path_RSHCOMMAND"
+if test -n "$RSHCOMMAND"; then
+  echo "$ac_t""$RSHCOMMAND" 1>&1
+else
+  echo "$ac_t""no" 1>&1
+fi
+
+    	if test -n "$RSHCOMMAND" ; then
+    	    echo $ac_n "checking whether $RSHCOMMAND works""... $ac_c" 1>&1
+echo "configure:1210: checking whether $RSHCOMMAND works" >&2
+    	    output=`$RSHCOMMAND -o "StrictHostKeyChecking no" \
+    	      -o "BatchMode yes" $machine -n true 2>&1 </dev/null`
+    	    if test $? -ne 0 ; then
+    		echo "$ac_t""no" 1>&1
+    		echo "Errors while trying to run true on $machine with ssh"
+    		echo "$output"
+    		RSHCOMMAND=""
+    		# HORRIBLE, TERRIBLE BUG in AUTOCONF!!!
+    		# It is determined to INCORRECTLY remember some results,
+    		# while forgetting others (like "cross-compiling")
+    		unset ac_cv_path_RSHCOMMAND
+    	    else
+    		echo "$ac_t""yes" 1>&1
+    	    fi
+    	fi
+    fi
 fi
 if test -z "$RSHCOMMAND" ; then
     echo "configure: warning: You must use the secure server to start programs" 1>&2
 fi
 # Sizes of int and long (for sendid type)
 echo $ac_n "checking size of int""... $ac_c" 1>&1
-echo "configure:1176: checking size of int" >&2
+echo "configure:1233: checking size of int" >&2
 if eval "test \"`echo '$''{'ac_cv_sizeof_int'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1180,7 +1237,7 @@ else
   ac_cv_sizeof_int=0
 else
   cat > conftest.$ac_ext <<EOF
-#line 1184 "configure"
+#line 1241 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1191,7 +1248,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1195: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1252: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_int=`cat conftestval`
 else
@@ -1211,7 +1268,7 @@ EOF
 
 
 echo $ac_n "checking size of long""... $ac_c" 1>&1
-echo "configure:1215: checking size of long" >&2
+echo "configure:1272: checking size of long" >&2
 if eval "test \"`echo '$''{'ac_cv_sizeof_long'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&1
 else
@@ -1219,7 +1276,7 @@ else
   ac_cv_sizeof_long=0
 else
   cat > conftest.$ac_ext <<EOF
-#line 1223 "configure"
+#line 1280 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1230,7 +1287,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1234: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1291: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_long=`cat conftestval`
 else
@@ -1253,9 +1310,9 @@ EOF
 for ac_func in gettimeofday BSDgettimeofday
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:1257: checking for $ac_func" >&2
+echo "configure:1314: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 1259 "configure"
+#line 1316 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -1276,7 +1333,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1280: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1337: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1298,6 +1355,87 @@ else
 fi
 done
 
+#
+# Generate a default machines file
+rootdir="../.."
+if test ! -s ${rootdir}/util/machines/machines.$ARCH ; then
+    if test ! -d ${rootdir}/util ; then mkdir ${rootdir}/util ; fi
+    if test ! -d ${rootdir}/util/machines ; then 
+        mkdir ${rootdir}/util/machines
+    fi
+    if test "$COMM" != "bproc" ; then
+        HOST=""
+        # Extract the first word of "hostname", so it can be a program name with args.
+set dummy hostname; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
+echo "configure:1372: checking for $ac_word" >&2
+ac_prog_where=""
+if test -n "$HOSTNAME_PGM"; then
+  ac_pg_HOSTNAME_PGM="$HOSTNAME_PGM" # Let the user override the test.
+else
+  ac_first_char=`expr "hostname" : "\(.\)"`
+  if test "$ac_first_char" = "/" -a -x "hostname" ; then
+       ac_pg_HOSTNAME_PGM=""
+       ac_prog_where=hostname
+  else
+      IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+      for ac_dir in $PATH; do
+        test -z "$ac_dir" && ac_dir=.
+        if test -f $ac_dir/$ac_word; then
+          ac_pg_HOSTNAME_PGM=""
+          ac_prog_where=$ac_dir/$ac_word
+          break
+        fi
+      done
+      IFS="$ac_save_ifs"
+  fi
+fi;HOSTNAME_PGM="$ac_pg_HOSTNAME_PGM"
+if test -n "$ac_prog_where" ; then
+  echo "$ac_t""found $ac_prog_where ($HOSTNAME_PGM)" 1>&1
+   hostname=$ac_prog_where  
+else
+  echo "$ac_t""no" 1>&1
+fi
+
+        if test -x "$hostname" ; then
+            HOST="`$hostname`"
+        fi
+        # Note that uname -n may not produce a usable hostname.  
+        # Any suggestions?
+        if test "$HOST" = "" ; then
+            HOST="`uname -n`"
+        fi
+	echo "Creating util/machines/machines.$ARCH"
+        cat > ${rootdir}/util/machines/machines.$ARCH <<EOF
+# Change this file to contain the machines that you want to use
+# to run MPI jobs on.  The format is one host name per line, with either
+#    hostname
+# or 
+#    hostname:n
+# where n is the number of processors in an SMP.  The hostname should
+# be the same as the result from the command "hostname"
+$HOST
+$HOST
+$HOST
+$HOST
+$HOST
+EOF
+    else
+        # bproc version from Rick Niles, slightly modified
+	# This gets all possible nodes in the current setup, but 
+        #  may include nodes that will never come up/ don't really exist)
+        CNT=`bpstat -n`   # Get maximum node count
+        INDEX=-1
+        while test "$INDEX" -le "$CNT" ; do
+	    # Using machines.bproc allows coexistance with other devices
+            echo $INDEX >> ${rootdir}/util/machines/machines.bproc
+	    # Use expr because some shells (e.g., Solaris's) choke with
+	    # ((...)) syntax
+            INDEX=`expr $INDEX + 1`
+        done
+    fi
+fi
+#
 trap '' 1 2 15
 
 trap 'rm -fr conftest* confdefs* core core.* *.core $ac_clean_files; exit 1' 1 2 15
diff --git a/mpid/ch_p4/configure.in b/mpid/ch_p4/configure.in
--- a/mpid/ch_p4/configure.in
+++ b/mpid/ch_p4/configure.in
@@ -32,12 +32,12 @@ PAC_SIGNALS_WORK
 #
 if test -z "$RSHCOMMAND" ; then
     machine=`hostname`
-    for program in remsh rsh ssh ; do
+    for program in remsh rsh ; do
         # First, check to see if the program exists
         AC_PATH_PROG(RSHCOMMAND,$program)
         if test -n "$RSHCOMMAND" ; then
 	    AC_MSG_CHECKING([whether $RSHCOMMAND works])
-            output=`$RSHCOMMAND $machine -n true 2>&1`
+            output=`$RSHCOMMAND $machine -n true 2>&1 </dev/null`
             if test -n "$output" ; then
 		AC_MSG_RESULT([no])
 		echo "Errors while trying to run true on $machine with $program"
@@ -53,6 +53,28 @@ if test -z "$RSHCOMMAND" ; then
 	    fi
         fi
     done
+    # Check ssh with special options to avoid user prompting which causes the
+    # configure script to "hang"
+    if test -z "$RSHCOMMAND" ; then
+    	AC_PATH_PROG(RSHCOMMAND, ssh)
+    	if test -n "$RSHCOMMAND" ; then
+    	    AC_MSG_CHECKING([whether $RSHCOMMAND works])
+    	    output=`$RSHCOMMAND -o "StrictHostKeyChecking no" \
+    	      -o "BatchMode yes" $machine -n true 2>&1 </dev/null`
+    	    if test $? -ne 0 ; then
+    		AC_MSG_RESULT([no])
+    		echo "Errors while trying to run true on $machine with ssh"
+    		echo "$output"
+    		RSHCOMMAND=""
+    		# HORRIBLE, TERRIBLE BUG in AUTOCONF!!!
+    		# It is determined to INCORRECTLY remember some results,
+    		# while forgetting others (like "cross-compiling")
+    		unset ac_cv_path_RSHCOMMAND
+    	    else
+    		AC_MSG_RESULT([yes])
+    	    fi
+    	fi
+    fi
 fi
 if test -z "$RSHCOMMAND" ; then
     AC_MSG_WARN([You must use the secure server to start programs])
@@ -62,4 +84,54 @@ AC_CHECK_SIZEOF(int,0)
 AC_CHECK_SIZEOF(long,0)
 
 AC_CHECK_FUNCS(gettimeofday BSDgettimeofday)
+#
+# Generate a default machines file
+rootdir="../.."
+if test ! -s ${rootdir}/util/machines/machines.$ARCH ; then
+    if test ! -d ${rootdir}/util ; then mkdir ${rootdir}/util ; fi
+    if test ! -d ${rootdir}/util/machines ; then 
+        mkdir ${rootdir}/util/machines
+    fi
+    if test "$COMM" != "bproc" ; then
+        HOST=""
+        PAC_PROGRAM_CHECK(HOSTNAME_PGM,hostname,,,hostname)
+        if test -x "$hostname" ; then
+            HOST="`$hostname`"
+        fi
+        # Note that uname -n may not produce a usable hostname.  
+        # Any suggestions?
+        if test "$HOST" = "" ; then
+            HOST="`uname -n`"
+        fi
+	echo "Creating util/machines/machines.$ARCH"
+        cat > ${rootdir}/util/machines/machines.$ARCH <<EOF
+# Change this file to contain the machines that you want to use
+# to run MPI jobs on.  The format is one host name per line, with either
+#    hostname
+# or 
+#    hostname:n
+# where n is the number of processors in an SMP.  The hostname should
+# be the same as the result from the command "hostname"
+$HOST
+$HOST
+$HOST
+$HOST
+$HOST
+EOF
+    else
+        # bproc version from Rick Niles, slightly modified
+	# This gets all possible nodes in the current setup, but 
+        #  may include nodes that will never come up/ don't really exist)
+        CNT=`bpstat -n`   # Get maximum node count
+        INDEX=-1
+        while test "$INDEX" -le "$CNT" ; do
+	    # Using machines.bproc allows coexistance with other devices
+            echo $INDEX >> ${rootdir}/util/machines/machines.bproc
+	    # Use expr because some shells (e.g., Solaris's) choke with
+	    # ((...)) syntax
+            INDEX=`expr $INDEX + 1`
+        done
+    fi
+fi
+#
 AC_OUTPUT(localdefs)
diff --git a/mpid/ch_p4/mpirun.ch_p4.in b/mpid/ch_p4/mpirun.ch_p4.in
--- a/mpid/ch_p4/mpirun.ch_p4.in
+++ b/mpid/ch_p4/mpirun.ch_p4.in
@@ -1,5 +1,8 @@
 #! /bin/sh
 exitstatus=1
+move_pgfile_to_master=no
+# We need to define the rcpcmd to allow for scp or Scyld bpcp
+rcpcmd=${RCPCOMMAND-rcp}
 #
 if [ -z "$argsset" ] ; then
    . $MPIRUN_HOME/mpirun.args
@@ -48,7 +51,7 @@ fi
 #
 # Construct the procgroup file.
 # If p4 was built with comm=shared, set MPI_MAX_CLUSTER_SIZE to 16 unless
-# it has already been set.
+# it has already been set. 
 if [ "$COMM" = "shared" ] ; then
     if [ -z "$MPI_MAX_CLUSTER_SIZE" ] ; then
         MPI_MAX_CLUSTER_SIZE=16
@@ -178,13 +181,22 @@ startpgm="$prognamemain $cmdLineArgs -p4pg $p4pgfile -p4wd $p4workdir"
 # startpgm="$startpgm < $stdinfile"
 #fi
 #
+# Having a p4p4file_master allows us to move the pg file to a location
+# where the master process can read it, even if the master does not
+# share a file system with the process that mpirun is executing on 
+p4pgfile_master=$p4pgfile
+if [ "$nolocal" = 1 -a "$move_pgfile_to_master" = "yes" ] ; then
+    # Should we use $TMPDIR  instead of /tmp here?
+    p4pgfile_master=/tmp/`basename $p4pgfile`
+fi
+#
 # Handle debuggers
 #
 if [ "$debugger" != "" ] ; then
     if [ -x "$MPIRUN_HOME/mpirun_dbg.$debugger" ] ; then
         $MPIRUN_HOME/mpirun_dbg.$debugger -progname $prognamemain -p4pg $p4pgfile -p4wd $p4workdir -cmdlineargs "$cmdLineArgs"
     else
-        echo "CANNOT RUN DEBUGGER - NO DEBUGGER SCRIPT" 
+        echo "Cannot run debugger - no debugger script." 
 	exit 1
     fi
 else
@@ -206,20 +218,31 @@ else
     #
     if [ $nolocal = 1 ] ; then
         if [ "$stdinfile" = "/dev/null" ] ; then
-            doitall="$doitall $rshcmd $machinehead"
-        else
             doitall="$doitall $rshcmd -n $machinehead"
+        else
+            doitall="$doitall $rshcmd $machinehead"
+        fi
+	if [ "$move_pgfile_to_master" = "yes" ] ; then
+	    $rcpcmd $p4pgfile $machinehead:$p4pgfile_master
         fi
     fi
-
-    $doitall $startpgm
-    exitstatus=$?
+    if [ -n "$stdinfile" ] ; then
+        $doitall $startpgm < $stdinfile
+        exitstatus=$?
+    else
+        $doitall $startpgm
+        exitstatus=$?
+    fi
 fi
 if [ $just_testing != 1 ] ; then
     if [ $leavePGFile = 1 ] ; then
         echo "P4 procgroup file is $p4pgfile."
     else
-        /bin/rm "$p4pgfile"
+        if [ $nolocal = 1 -a "$move_pgfile_to_master" = "yes" ] ; then
+	    $rshcmd -n $machinehead /bin/rm $p4pgfile_master
+        else
+            /bin/rm "$p4pgfile"
+        fi
     fi
     if [ "$MPIRUN_RANDOM" = "yes" ] ; then
         /bin/rm -f "$TEMPDIR/mpirand-$LOGNAME"*
diff --git a/mpid/ch_p4/setup_ch_p4 b/mpid/ch_p4/setup_ch_p4
--- a/mpid/ch_p4/setup_ch_p4
+++ b/mpid/ch_p4/setup_ch_p4
@@ -172,6 +172,16 @@ fi
 if test -n "$P4_OPTS" ; then
     otherargs="$otherargs $P4_OPTS"
 fi
+if test "$COMM" = "bproc" ; then
+    # Here would go bproc options, such as
+    #LIBS="$LIBS -lbproc -Wl,--undefined=beowulf_sched_shim,--undefined=get_beowulf_job_map  -lbeomap -lbeostat -ldl
+    # Note that we have to make sure that this is exported back up to the MPICH
+    # configure
+    # Do define the remote shell and copy commands
+    RSHCOMMAND="/usr/bin/bpsh"
+    # Note that RCPCOMMAND is not yet exported to mpirun.ch_p4.in
+    RCPCOMMAND="${RCPCOMMAND-/usr/bin/bpcp}"
+fi
 #
 # Run configure in the device directory
 # What is this here for?  It is:
@@ -182,8 +192,15 @@ RSHCOMMAND="${RSHCOMMAND-$rshcommand}"
 export CC ; export RSHCOMMAND 
 # Remove the configuration file if present
 rm -f $top_srcdir/mpid/ch_p4/mpich-mpid.h mpid/ch_p4/mpich-mpid.h
-(cd mpid/ch_p4 ; $top_srcdir/mpid/ch_p4/configure) # --srcdir=$srcdir)
+# Export ARCH so that the machines file will get made in the right place
+(cd mpid/ch_p4 ; export ARCH ; \
+$top_srcdir/mpid/ch_p4/configure) # --srcdir=$srcdir)
 # Variable assignments from configure are in localdefs
+if [ ! -f mpid/ch_p4/localdefs ] ; then
+    echo "Failed to build file of local definitions"
+    echo "configure in mpid/ch_p4 failed."
+    exit 1
+fi
 . mpid/ch_p4/localdefs
 #
 if test -n "$rshcommand" ; then
@@ -260,4 +277,5 @@ if test $? != 0 ; then
     print_error "used to speedup process startup."
     # No exit, because we want to be able to continue
 fi
+#
 echo "Finished configuring the p4 secure server"
diff --git a/mpid/ch_p4mpd/configure b/mpid/ch_p4mpd/configure
--- a/mpid/ch_p4mpd/configure
+++ b/mpid/ch_p4mpd/configure
@@ -465,7 +465,7 @@ echo > confdefs.h
 
 # A filename unique to this package, relative to the directory that
 # configure is in, which we can look for to find out if srcdir is correct.
-ac_unique_file=
+ac_unique_file=setup_ch_p4mpd
 
 # Find the source files, if location was not specified.
 if test -z "$srcdir"; then
@@ -816,7 +816,7 @@ fi
 #
 if test -z "$RSHCOMMAND" ; then
     machine=`hostname`
-    for program in remsh rsh ssh ; do
+    for program in remsh rsh ; do
         # First, check to see if the program exists
         
 if test -n "$pac_cv_cross_compiling" ; then
@@ -827,7 +827,7 @@ else
     echo $ac_n "checking whether cross-compiling""... $ac_c" 1>&1
 echo "configure:829: checking whether cross-compiling" >&2
     # If we cannot run a trivial program, we must be cross compiling.
-    if test "$cross_compiling" = yes; then
+            if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
@@ -848,7 +848,7 @@ rm -fr conftest*
 fi
 
     if test $pac_ok = 1 ; then
-         if test "$cross_compiling" = yes; then
+        if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
@@ -935,15 +935,71 @@ echo "configure:922: checking whether $RSHCOMMAND works" >&2
 	    fi
         fi
     done
+    # Check ssh with special options to avoid user prompting which causes the
+    # configure script to "hang"
+    if test -z "$RSHCOMMAND" ; then
+    	# Extract the first word of "ssh", so it can be a program name with args.
+set dummy ssh; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&1
+echo "configure:945: checking for $ac_word" >&2
+if eval "test \"`echo '$''{'ac_cv_path_RSHCOMMAND'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&1
+else
+  case "$RSHCOMMAND" in
+  /*)
+  ac_cv_path_RSHCOMMAND="$RSHCOMMAND" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_RSHCOMMAND="$RSHCOMMAND" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_RSHCOMMAND="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  ;;
+esac
+fi
+RSHCOMMAND="$ac_cv_path_RSHCOMMAND"
+if test -n "$RSHCOMMAND"; then
+  echo "$ac_t""$RSHCOMMAND" 1>&1
+else
+  echo "$ac_t""no" 1>&1
 fi
 
+    	if test -n "$RSHCOMMAND" ; then
+    	    echo $ac_n "checking whether $RSHCOMMAND works""... $ac_c" 1>&1
+echo "configure:979: checking whether $RSHCOMMAND works" >&2
+    	    output=`$RSHCOMMAND -o "StrictHostKeyChecking no" \
+    	      -o "BatchMode yes" $machine -n true 2>&1 </dev/null`
+    	    if test $? -ne 0 ; then
+    		echo "$ac_t""no" 1>&1
+    		echo "Errors while trying to run true on $machine with ssh"
+    		echo "$output"
+    		RSHCOMMAND=""
+    		# HORRIBLE, TERRIBLE BUG in AUTOCONF!!!
+    		# It is determined to INCORRECTLY remember some results,
+    		# while forgetting others (like "cross-compiling")
+    		unset ac_cv_path_RSHCOMMAND
+    	    else
+    		echo "$ac_t""yes" 1>&1
+    	    fi
+    	fi
+    fi
+fi
 
 for ac_func in gettimeofday BSDgettimeofday
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&1
-echo "configure:945: checking for $ac_func" >&2
+echo "configure:1001: checking for $ac_func" >&2
 cat > conftest.$ac_ext <<EOF
-#line 947 "configure"
+#line 1003 "configure"
 #include "confdefs.h"
 #include <ctype.h> /* Arbitrary system header to define __stub macros. */
 #ifdef __cplusplus
@@ -964,7 +1020,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:968: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1024: \"$ac_link\") 1>&2; (eval $ac_link) 2>&2; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
diff --git a/mpid/ch_p4mpd/configure.in b/mpid/ch_p4mpd/configure.in
--- a/mpid/ch_p4mpd/configure.in
+++ b/mpid/ch_p4mpd/configure.in
@@ -9,7 +9,7 @@ print_error() {
     echo "*# $*" 2>&1 ;
     }
 
-AC_INIT()
+AC_INIT(setup_ch_p4mpd)
 AC_CONFIG_HEADER(mpich-mpid.h)
 # Check for a working mmap.
 MMAP=0
@@ -26,7 +26,7 @@ PAC_SIGNALS_WORK
 #
 if test -z "$RSHCOMMAND" ; then
     machine=`hostname`
-    for program in remsh rsh ssh ; do
+    for program in remsh rsh ; do
         # First, check to see if the program exists
         AC_PATH_PROG(RSHCOMMAND,$program)
         if test -n "$RSHCOMMAND" ; then
@@ -47,8 +47,29 @@ if test -z "$RSHCOMMAND" ; then
 	    fi
         fi
     done
+    # Check ssh with special options to avoid user prompting which causes the
+    # configure script to "hang"
+    if test -z "$RSHCOMMAND" ; then
+    	AC_PATH_PROG(RSHCOMMAND, ssh)
+    	if test -n "$RSHCOMMAND" ; then
+    	    AC_MSG_CHECKING([whether $RSHCOMMAND works])
+    	    output=`$RSHCOMMAND -o "StrictHostKeyChecking no" \
+    	      -o "BatchMode yes" $machine -n true 2>&1 </dev/null`
+    	    if test $? -ne 0 ; then
+    		AC_MSG_RESULT([no])
+    		echo "Errors while trying to run true on $machine with ssh"
+    		echo "$output"
+    		RSHCOMMAND=""
+    		# HORRIBLE, TERRIBLE BUG in AUTOCONF!!!
+    		# It is determined to INCORRECTLY remember some results,
+    		# while forgetting others (like "cross-compiling")
+    		unset ac_cv_path_RSHCOMMAND
+    	    else
+    		AC_MSG_RESULT([yes])
+    	    fi
+    	fi
+    fi
 fi
-
 
 AC_CHECK_FUNCS(gettimeofday BSDgettimeofday)
 AC_OUTPUT(localdefs)
diff --git a/mpid/ch_p4mpd/install_ch_p4mpd b/mpid/ch_p4mpd/install_ch_p4mpd
--- a/mpid/ch_p4mpd/install_ch_p4mpd
+++ b/mpid/ch_p4mpd/install_ch_p4mpd
@@ -11,8 +11,31 @@ fi
 if [ -f mpid/mpd/Makefile ] ; then
     export XMODE
     (cd mpid/mpd ; $MAKE install UNINSTALLFILE=$UNINSTALLFILE )
+    rm -f ${bindir}/mpichboot
+    cat >${bindir}/mpichboot <<EOF
+#! /bin/sh
+if [ ! -s $HOME/.mpdpasswd -a ! -s $HOME/.mpd.conf ] ; then
+    echo "In mpichboot:"
+    echo "A .mpd.conf file is required before starting an mpd demon."
+    echo "See the documentation on mpd in the User Manual."
+    exit 1
+fi
+# Use the -b option to force mpd into the background, orphaned from the 
+# calling process.  
+${bindir}/mpd -b &
+EOF
+    chmod $XMODE ${bindir}/mpichboot
+    echo "rm -f ${bindir}/mpichboot" >>$UNINSTALLFILE
+    rm -f ${bindir}/mpichstop
+    cat >${bindir}/mpichstop <<EOF
+#! /bin/sh
+${bindir}/mpdallexit
+EOF
+    chmod $XMODE ${bindir}/mpichstop
+    echo "rm -f ${bindir}/mpichstop" >>$UNINSTALLFILE
 else
     echo "Could not find Makefile for mpid/mpd!"
     echo "Install not completed"
     exit 1
 fi
+#
diff --git a/mpid/ch_shmem/setup_ch_shmem b/mpid/ch_shmem/setup_ch_shmem
--- a/mpid/ch_shmem/setup_ch_shmem
+++ b/mpid/ch_shmem/setup_ch_shmem
@@ -38,7 +38,10 @@ DEFAULT_MACHINE="smp"
 rm -f ${top_srcdir}/mpid/ch_shmem/mpich-mpid.h
 ( cd mpid/ch_shmem ; export CC ; export usesysv ; \
     $top_srcdir/mpid/ch_shmem/configure )
-
+if [ $? != 0 ] ; then
+    echo "Aborting device setup because device configure failed"
+    exit 1
+fi
 # Variable assignments from configure are in localdefs
 . mpid/ch_shmem/localdefs
 LIB_LIST="$LIB_LIST $CHSHMEM_LIBS"
diff --git a/util/makesharedlib b/util/makesharedlib
--- a/util/makesharedlib
+++ b/util/makesharedlib
@@ -2,6 +2,12 @@
 #
 # Simple script to build shared libraries
 #
+#
+# Load the mpich configuration data
+if [ -s ../util/mpichlib.conf ] ; then 
+    . ../util/mpichlib.conf
+fi
+#
 kind=""
 nolink=0
 islocal=0
@@ -9,6 +15,9 @@ created_shared=0
 Verbose=echo
 setecho=0
 GetPathSpec="no"
+# OtherLibs contains any additional information, such as additional libraries,
+# that are needed to create a shared library.  Currently used only for gcc.
+OtherLibs=""
 for arg in "$@" ; do
     case $arg in
 	-lib=*) lib=`echo A$arg | sed -e 's/A-lib=//g'`
@@ -83,7 +92,7 @@ if [ -z "$AR" ] ; then
     AR=ar
 fi
 if [ -z "$LD" ] ; then
-    LD=ld
+    LD="ld"
 fi
 if [ -z "$CLINKER" ] ; then
     if [ -n "$CC" ] ; then
@@ -134,6 +143,10 @@ fi
 # they are ignored.
 case $kind in
     gcc)
+    # Include any other libraries needed to link with in case they are
+    # needed to resolve any symbols.  This is needed for Scyld and should
+    # be harmless in general.
+    OtherLibs="$BASE_LIB_LIST"
     for libname in $SHLIBS ; do
         $Verbose "Making a shared library of $libname"
         rm -rf .tmp
@@ -152,7 +165,9 @@ case $kind in
 	    cd .tmp
 	fi
         libbase=`basename $libname .a`
-        $CLINKER -shared -o ../shared/$libbase.$slsuffix *.o
+	# The -h name sets the name of the object; this is necessary to 
+	# ensure that the dynamic linker can find the proper shared library.
+        $CLINKER -shared -Wl,-h,$libbase.$slsuffix -o ../shared/$libbase.$slsuffix *.o $OtherLibs 
         cd ..
         # Make a link in the library directory to the shared library in the
         # shared directory.
@@ -172,7 +187,7 @@ case $kind in
         rm -rf .tmp
     done
     ;;
-    solaris)
+    solaris|solaris64)
     for libname in $SHLIBS ; do
         $Verbose "Making a shared library of $libname"
         rm -rf .tmp
@@ -187,8 +202,14 @@ case $kind in
 	    cp $objs .tmp
 	    cd .tmp
 	fi
+        # Note that we may need LD_LIBRARY_PATH_64 (!) for 64 bit builds
 	libbase=`basename $libname .a`
-        $LD -G -h $libbase.$slsuffix -o ../shared/$libbase.$slsuffix *.o
+        if $LD -G -h $libbase.$slsuffix -o ../shared/$libbase.$slsuffix *.o ; then
+	    :
+	else
+	    # Exit if we fail to build the library
+	    exit 1
+	fi
         cd ..
 	if [ $islocal = 1 ] ; then
 	    mv shared/$libbase.$slsuffix .
@@ -230,7 +251,11 @@ case $kind in
 	    sed -e 's/^\.//g' >  $libbase.exp
         # xlC doesn't work with this!
         # cc misses the iargc/getarg libraries
-        xlf -r -o ../shared/$libbase.so *.o -bE:$libbase.exp -bM:SRE -bnoentry
+        if xlf -r -o ../shared/$libbase.so *.o -bE:$libbase.exp -bM:SRE -bnoentry ; then
+	    :
+	else
+	    exit 1
+        fi
         # create new shared file name
         newfile="${libbase}shared.a"
         /bin/rm -f $newfile
@@ -257,8 +282,12 @@ case $kind in
 	    cd .tmp
 	fi
 	libbase=`basename $libname .a`
-        $CLINKER -elf -no_library_replacement -shared -rdata_shared -all \
-	    -o ../shared/$libbase.$slsuffix *.o
+        if $CLINKER -elf -no_library_replacement -shared -rdata_shared -all \
+	    -o ../shared/$libbase.$slsuffix *.o ; then
+	    :
+	else
+	    exit 1
+        fi
         cd ..
 	if [ $islocal = 1 ] ; then
 	    mv shared/$libbase.$slsuffix .
@@ -274,6 +303,14 @@ case $kind in
         fi
         rm -rf .tmp
     done
+    ;;
+
+    hpux*)
+    echo "HPUX is not supported"
+    # From libtools' ltconfig, we might try (except for hpux9)
+    # ld -b +h libmpich.so +b $installdir -o libmpich $objs ...
+    # Note that libtool notes that shared libraries need to have 
+    # permissions 555 (chmod 555 $lib)
     ;;
 
     *)	
